<div id="content_view_comment_<?php echo $this->comment['Data']['id_cmt']; ?>" class="content_view_comment_container">
	<div id="content_view_comment_<?php echo $this->comment['Data']['id_cmt']; ?>_username" class="content_view_comment_user">
		<?php
		if (isset($this->comment['Poster']['profile_image_thumb_usr']))
		{
		?>
			<img src="<?php echo $this->url(array('controller' => 'account', 'action' => 'profilethumb', 'id' => $this->comment['Poster']['id_usr']), 'lang_default', true); ?>" alt="User image" width="70" height="80"/>
		<?php
		}
		?>
		<br />
		<span class="content_view_comment_username"><?php echo $this->comment['Poster']['login_name_usr']; ?></span>
		<br />
		<span class="content_view_comment_posted"><?php echo date('d M Y', strtotime($this->comment['Data']['created_cmt'])); ?></span>
	</div>
	<div id="content_view_comment_<?php echo $this->comment['Data']['id_cmt']; ?>" class="content_view_comment">
		<div id="content_view_comment_<?php echo $this->comment['Data']['id_cmt']; ?>_title" class="content_view_comment_title">
			<?php //echo $comment['title_cmt']; ?>
		</div>
		<div id="content_view_comment_<?php echo $this->comment['Data']['id_cmt']; ?>_textbody" class="content_view_comment_textbody">
			<?php echo $this->comment['Data']['body_cmt']; ?>
		</div>
	</div>
	<div class="clear"></div>
</div>