
<?php /*
$form = $this->element;
?>
<div class="fetchPassword margin-top">
    <form id="<?php echo $this->escape($form->getName()); ?>" class="form-horizontal"
		<?php //name="echo $this->escape($form->getName()); "?>
          action="<?php echo $this->escape($form->getAction()); ?>"
          method="<?php echo $this->escape($form->getMethod()); ?>"
          enctype="<?php echo $this->escape($form->getAttrib('enctype')); ?>">

        <div class="control-group">
            <label class="control-label" for="email">
				<?php echo $this->translate('email');?>
            </label>
            <div class="controls">
				<?php echo $form->email;?>
            </div>
        </div>

        <div class="control-group">
	        <div class="controls">
				<?php echo $form->submit; ?>
            </div>
	    </div>
    </form>
</div> */
