<?php
	/** @var $this Zend_View */
	/** @var $form Default_Form_LoginForm */
	$form = $this->element;
?>

<div class="headerLogin">
    <form id="<?php echo $this->escape($form->getName()); ?>"
        <?php //name="echo $this->escape($form->getName()); "?>
          action="<?php echo $this->escape($form->getAction()); ?>"
          method="<?php echo $this->escape($form->getMethod()); ?>"
          enctype="<?php echo $this->escape($form->getAttrib('enctype')); ?>">

	    <?php echo $form->returnurl; ?>

        <div class="row">
            <div class="span2">
	            <?php echo $form->login_username; ?>
            </div>
            <div class="span2">
                <a class="signup" href="<?php echo $this->url(array(
                    'controller' => 'account',
                    'action'     => 'register',
	                'language'   => $form->getLanguage(),
                )); ?>">
                    <?php echo $this->translate('layout-signup'); ?>
                </a>
            </div>
        </div>

        <div class="row">
           <div class="span2">
	            <?php echo $form->login_password; ?>
	       </div>
           <div class="span2">
               <?php echo $form->login_submit; ?>
           </div>
        </div>
	    <div class="row">
		    <?php echo $form->login_returnurl; ?>
	    </div>
    </form>
</div>
