<?php
	/** @var $form Default_Form_LoginForm */
	$form = $this->element;
?>
<div class="loginSite margin-top">
    <form id="<?php echo $this->escape($form->getName()); ?>" class="form-horizontal"
        <?php //name="echo $this->escape($form->getName()); "?>
          action="<?php echo $this->escape($form->getAction()); ?>"
          method="<?php echo $this->escape($form->getMethod()); ?>"
          enctype="<?php echo $this->escape($form->getAttrib('enctype')); ?>">

	    <?php echo $form->returnurl; ?>
            <div class="control-group">
	            <label class="control-label" for="login_username">
					<?php echo $this->translate('email');?>
                </label>
                <div class="controls">
	                <?php echo $form->login_username; ?>
                </div>
            </div>

	        <div class="control-group">
		        <label class="control-label for="login_password">
					<?php echo $this->translate('password');?>
                </label>
                <div class="controls">
			        <?php echo $form->login_password; ?>
                </div>
	        </div>
            <div class="control-group">
                <div class="controls">
                    <a class="signup" href="<?php echo $this->url(array(
		                'controller' => 'account',
		                'action'     => 'register',
		                'language'   => $this->language,
	                ), 'lang_default', true); ?>">
		                <?php echo $this->translate('signup'); ?>
                    </a>
	                <?php echo $form->login_submit; ?>

                </div>
	            <div class="controls">
                    <a href="<?php echo $this->url(array('controller' => 'account',
				            'action' => 'fetchpassword',
				            'language' => $this->language),
			            'lang_default', true); ?>">
			            <?php echo $this->translate('forgotPassword'); ?>?
                    </a>
                </div>
	        </div>
     </form>
</div>
