<?php
	/** @var $form Default_Form_LoginForm */
	$form = $this->element;
?>
<div class="loginSite">
    <form id="<?php echo $this->escape($form->getName()); ?>" class="form-horizontal"
        <?php //name="echo $this->escape($form->getName()); "?>
          action="<?php echo $this->escape($form->getAction()); ?>"
          method="<?php echo $this->escape($form->getMethod()); ?>"
          enctype="<?php echo $this->escape($form->getAttrib('enctype')); ?>">

	    <?php echo $form->returnurl; ?>

        <div class="row">
            <div class="span2">
	            <?php echo $form->username; ?>
            </div>
            <div class="span2">
                <a class="signup" href="<?php echo $this->url(array(
                    'controller' => 'account',
                    'action'     => 'register',
                    'language'   => $this->language,
                ), 'lang_default', true); ?>">
                    <?php echo $this->translate('layout-signup'); ?>
                </a>
            </div>
        </div>

        <div class="row">
           <div class="span2">
	            <?php echo $form->password; ?>
	       </div>
           <div class="span2">
               <?php echo $form->submit; ?>
           </div>
        </div>
    </form>
</div>
