<?php
Zend_Layout::getMvcInstance()->setLayout('layout_new');

// some variable initiation
$url_sign_up = $this->url(array(
		'controller' => 'account',
        'action' => 'register',
        'language' => $this->language
	),
    'lang_default', true);
$url_more = $this->url(array(
		'controller' => 'search',
		'action' => 'result',
		'page' => '2',
		'language' => $this->language
	),
	'lang_default', true);
$url_getRecentContent = $this->url(array(
		'controller' => 'ajax',
		'action' => 'getrecentcontent',
		'type' => 'all',
		'language' => $this->language),
	'lang_default', true);
$url_checkRecentContent = $this->url(array(
		'controller' => 'ajax',
		'action' => 'checkrecentcontent',
		'language' => $this->language),
	'lang_default', true);
$url_tag_cloud = $this->url(array(
		'controller' => 'tag',
		'action' => 'index',
		'list_type' => 'index',
		'language' => $this->language),
	'lang_default', true);
?>

<script type="text/javascript">
	var CHECK_RECENT_CONTENT_URL = '<?php echo $url_checkRecentContent; ?>';
	var GET_RECENT_CONTENT_URL = '<?php echo $url_getRecentContent; ?>';
	var AJAX_LOADER_URL = '<?php echo $this->baseUrl('/images/ajax-loader-black.gif'); ?>';
</script>

<?php $this->headScript()->appendFile($this->baseUrl('/js/recentcontent.js')); ?>
    <h3 class="recent_posts"><?php echo $this->translate('index-recent-posts'); ?>
        <a href="<?php echo $this->url(array('controller' => 'rss',
                                             'action' => 'generate',
                                             'language' => $this->language),
                                             'lang_default', true); ?>">

        <img class="rsslogo" src="<?php echo $this->baseUrl('/images/icon_rss_28x28.png'); ?>" alt="RSS" width="18" height="18" style="padding-left: 5px; vertical-align: middle;" /></a>
        <a href="<?php echo $this->url(array('controller' => 'voice',
                                             'action' => 'generate',
                                             'language' => $this->language),
                                             'lang_default', true); ?>">

        <img class="rsslogo" src="<?php echo $this->baseUrl('/images/podcasts.png'); ?>" alt="RSS" width="18" height="18" style="padding-left: 4px; vertical-align: middle;" /></a>
	</h3>
<!-- Small hack to force a small space between the h2 and content... might help the Symbian -browsers a bit -->
<div style="height: 2px;"></div>

<div class="user_content_list" style="padding: 0px; margin: 0px; overflow:hidden;">
	<div id="recent_posts_ajax" style="width: 500px;"></div>
    	<div class="user_content_spacer"></div>

    <div id="recent_posts_ajax_link" style="margin-top: 10px; margin-left: 220px;">
        <h3>
            <a href="#" onclick="return false;"><?php echo $this->translate('index-view-more'); ?></a>
        </h3>
    </div>
</div>
</div>
<?php
/*
Assign the partial view to the layout :)
If there is nothing, the layout just prints nothing.
However, if you assign a file that does not exist, the site will
throw an application error instantly, so be careful!

Commented to fix temporary problem, will be researched further later
*/
//$this->layout()->right_side = $this->partial('partials/index.phtml');
?>

<div id="sidebar">
    <!-- For some mystical reason, paragraphs seem to need an empty style-attribute in order to extend a CSS -class -->
    <div class="box">
	    <h2>
	        <?php echo $this->translate('index-what-is'); ?>
	    </h2>
        <div class="box-content">
            <?php echo $this->translate('index-what-is-long'); ?>
            <?php // <span class="top_right_box_links"><a href="#"> echo $this->translate('index-learn-more'); </a></span> ?>
        </div>
    </div>
    <?php if(!$this->isLoggedIn): ?>
    <p id="sign_up_now" style="padding-bottom: 10px; text-align: center" class="top_right_box_links">
        <b>
            <a href="<?php echo $url_sign_up; ?>">
                <?php echo $this->translate('index-sigup')?>
            </a>
        </b>
    </p>
    <?php endif; ?>
    <!-- Campaigns -->
    <div id="campaigns">
            <?php $cmpurl = $this->url(array('controller' => 'campaign',
                                         'action' => 'index',
                                         'language' => $this->language),
                                   'lang_default', true); ?>
        <h2>Recent <a href="<?php echo $cmpurl;?>">campaigns</a></h2>
        <ul class="campaigns">
            <?php echo $this->partialLoop('partials/campaign_row_small.phtml', $this->campaigns); ?>
        </ul>
    </div>
    <!-- End of campaigns -->
    <!-- Groups -->
    <div id="groups">
        <?php $grpurl = $this->url(array('controller' => 'group',
                                         'action' => 'index',
                                         'language' => $this->language),
                                   'lang_default', true); ?>
        <h2>Recent <a href="<?php echo $grpurl;?>">groups</a></h2>
        <ul class="groups">
            <?php echo $this->partialLoop('partials/group_row_extra_small.phtml', $this->groups); ?>
        </ul>
    </div>
    <!-- End of groups -->
    <!-- Users -->
    <h2 id="most_active_users">
        <?php echo $this->translate('index-most-active')?>
        <a href="<?php echo $this->url(array('controller' => 'account',
                                             'action' => 'userlist',
        									 'order' => 'content',
        									 'list' => 'desc',
                                             'language' => $this->language),
                                             'lang_default', true); ?>">
            <?php echo "users"; ?></a>
    </h2>
    <div class="top_right_box_links_users">
    <ul class="users">
        <?php echo $this->partialLoop('partials/user_row.phtml', $this->activeusers); ?>
	</ul>
    </div>
    <!-- End of users -->
    <!-- Tags -->
    <h2>
        <?php echo $this->translate('index-most-popular')?>
        <a href="<?php echo $this->url(array('controller' => 'tag',
                                             'action' => 'index',
        									 'order' => 'popularity',
        									 'direction' => 'desc',
                                             'language' => $this->language),
                                             'lang_default', true); ?>">
            <?php echo $this->translate('index-tags')?>
        </a>
    </h2>
    <div class="tag_cloud">
        <ul class="tags">
        	<?php foreach($this->poptags as $tag): ?>
        	<li class="tags">
        		<?php echo $this->partial('partials/tag.phtml', $tag); ?>
        	</li>
        	<?php endforeach; ?>
			<div class="clear"></div>
        </ul>
     </div>
     <div class="clear"></div>
    <!-- End of tags -->
    <!--  Missing a feature? -->
	<h2>
		<?php echo $this->translate('content-list-missing-header'); ?>
	</h2>
	<p>
		<?php echo $this->translate('index-opensource'); ?>
	</p>
	<!--  End of Missing a feature? -->

