<?php
// some variable initiation    
$url_sign_up = $this->url(array('controller' => 'account',
                                'action' => 'register',
                                'language' => $this->language), 
                          		'lang_default', true);
    
$url_more = $this->url(array('controller' => 'search',
                             'action' => 'result',
                             'page' => '2',
                             'language' => $this->language), 
                        	 'lang_default', true);

$url_getRecentContent = $this->url(array('controller' => 'ajax',
							 'action' => 'getrecentcontent',
							 'type' => 'all',
							 'language' => $this->language), 
							 'lang_default', true);

$url_checkRecentContent = $this->url(array('controller' => 'ajax',
										   'action' => 'checkrecentcontent',
										   'language' => $this->language), 
										   'lang_default', true);

$url_tag_cloud = $this->url(array('controller' => 'tag',
                             	  'action' => 'index',
								  'list_type' => 'index',
                             	  'language' => $this->language),
                             	  'lang_default', true);
?>
<?php $this->headScript()->captureStart()?>

// Variables for ajax requests
var url_checkrecentcontent = '<?php echo $url_checkRecentContent; ?>';
var url_getrecentcontent = '<?php echo $url_getRecentContent; ?>';
var url_ajaxloader = '<?php echo $this->baseUrl('/images/ajax-loader-black.gif'); ?>';

<?php $this->headScript()->captureEnd()?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/recentcontent.js')); ?>
    <h3 class="recent_posts"><?php echo $this->translate('index-recent-posts'); ?>
        <a href="<?php echo $this->url(array('controller' => 'rss',
                                             'action' => 'generate',
                                             'language' => $this->language),
                                             'lang_default', true); ?>">
                                           
        <img class="rsslogo" src="<?php echo $this->baseUrl('/images/icon_rss_28x28.png'); ?>" alt="RSS" width="18" height="18" style="padding-left: 5px; vertical-align: middle;" />
        </a>
        <a href="<?php echo $this->url(array('controller' => 'voice',
                                             'action' => 'generate',
                                             'language' => $this->language),
                                             'lang_default', true); ?>">
                                           
        <img class="rsslogo" src="<?php echo $this->baseUrl('/images/podcasts.png'); ?>" alt="RSS" width="18" height="18" style="padding-left: 4px; vertical-align: middle;" />
        </a>
	</h3>
<!-- Small hack to force a small space between the h2 and content... might help the Symbian -browsers a bit -->
<div style="height: 2px;"></div>

<div class="user_content_list" style="padding: 0px; margin: 0px; overflow:hidden;">
	<div id="recent_posts_ajax" style="width: 500px;"></div>
    <div class="user_content_spacer">
        <img src="<?php echo $this->baseUrl('/images/gray_dot_line_500.png'); ?>" alt="Massidea.org" />
    </div>
    
    <div id="recent_posts_ajax_link" style="margin-top: 10px; margin-left: 220px;">
        <h3>
            <a href="#" onclick="return false;"><?php echo $this->translate('index-view-more'); ?></a>
        </h3>
    </div>
</div>

<?php 
/*
Assign the partial view to the layout :) 
If there is nothing, the layout just prints nothing. 
However, if you assign a file that does not exist, the site will 
throw an application error instantly, so be careful!

Commented to fix temporary problem, will be researched further later
*/
//$this->layout()->right_side = $this->partial('partials/index.phtml'); 
?>
<div class="right_side" style="padding: 0px; margin: 0px; margin-top: -52px;">
    <!-- For some mystical reason, paragraphs seem to need an empty style-attribute in order to extend a CSS -class -->
    <h4 style="margin-top: 8px; margin-bottom: 6px;">
        <?php echo $this->translate('index-what-is'); ?>
    </h4>
        <div class="top_right_box">
            <?php echo $this->translate('index-what-is-long'); ?>
            <?php // <span class="top_right_box_links"><a href="#"> echo $this->translate('index-learn-more'); </a></span> ?>
        </div>
        
    <?php if(!$this->isLoggedIn): ?>
    <p id="sign_up_now" style="padding-bottom: 10px;" class="top_right_box_links">
        <b>
            <a href="<?php echo $url_sign_up; ?>">
                <?php echo $this->translate('index-sigup')?>
            </a>
        </b>
    </p>
    <?php endif; ?>
    
    <h3 style="margin-top: 5px; margin-bottom: 0; padding: 0;">
        <?php echo $this->translate('index-most-popular')?>
        <a href="<?php echo $this->url(array('controller' => 'tag',
                                             'action' => 'index',
        									 'order' => 'popularity',
        									 'direction' => 'desc',
                                             'language' => $this->language),
                                             'lang_default', true); ?>">
            <?php echo $this->translate('index-tags')?>
        </a>
    </h3>
    
    <img src="<?php echo $this->baseUrl('/images/gray_dot_line_200.png'); ?>" alt="Massidea.org" />
    
    <div class="tag_cloud">
       
        <?php echo $this->partialLoop('partials/tag.phtml', $this->poptags); ?>
        
        <p id="show_all_tags" style="padding: 0px; margin-top: 10px;" class="top_right_box_links">
            <a href="<?php echo $this->url(array('controller' => 'tag',
                                             'language' => $this->language),
                                             'lang_default', true); ?>">
                <?php echo $this->translate('index-show-all')?>
            </a>
        </p>
    </div>
        
    <img src="<?php echo $this->baseUrl('/images/gray_dot_line_200.png'); ?>" alt="Massidea.org" />
    
    <p id="most_active_users" style="padding: 0px;" class="top_right_box_links">
        <?php echo $this->translate('index-most-active')?>
        <a href="<?php echo $this->url(array('controller' => 'account',
                                             'action' => 'userlist',
        									 'order' => 'content',
        									 'list' => 'desc',
                                             'language' => $this->language),
                                             'lang_default', true); ?>">
            <?php echo $this->translate('index-users')?>
        </a>
    </p>
    
    <img src="<?php echo $this->baseUrl('/images/gray_dot_line_200.png'); ?>" alt="Massidea.org" />
    
    <div class="top_right_box_links_users">
        <?php echo $this->partialLoop('partials/user_row.phtml', $this->activeusers); ?>
    </div>
    
    <div class="top_right_box_links_show_all_users">
        <a href="<?php echo $this->url(array('controller' => 'account',
                                             'action' => 'userlist',
                                             'language' => $this->language),
                                             'lang_default', true); ?>">
            <?php echo $this->translate('index-show-all')?>
            <?php echo $this->translate('index-users')?>
        </a>
    </div>
    
    <img src="<?php echo $this->baseUrl('/images/gray_dot_line_200.png'); ?>" alt="Massidea.org" />
    
    <div class="massidea_dev_info">
        <?php echo $this->translate('index-opensource')?>
    </div>

    <img src="<?php echo $this->baseUrl('/images/gray_dot_line_200.png'); ?>" alt="Massidea.org" />

    <div id="campaigns">
        <h3>Recent campaigns</h3>
        <ul>
            <?php echo $this->partialLoop('partials/campaign_row_small.phtml', $this->campaigns); ?>
        </ul>
    </div>
    <div style="text-align: center; margin-top: 20px; margin-bottom: 20px;">
        <?php $cmpurl = $this->url(array('controller' => 'campaign',
                                         'action' => 'index',
                                         'language' => $this->language),
                                   'lang_default', true); ?>
        <strong><a href="<?php echo $cmpurl; ?>">Show more</a></strong>
    </div>

    <div id="campaigns">
        <h3>Recent groups</h3>
        <ul>
            <?php echo $this->partialLoop('partials/group_row_extra_small.phtml', $this->groups); ?>
        </ul>
    </div>
    <div style="text-align: center; margin-top: 20px;">
        <?php $grpurl = $this->url(array('controller' => 'group',
                                         'action' => 'index',
                                         'language' => $this->language),
                                   'lang_default', true); ?>
        <strong><a href="<?php echo $grpurl; ?>">Show more</a></strong>
    </div>
</div>