<?php
// some variable initiation    
$url_sign_up = $this->url(array('controller' => 'account',
                                'action' => 'register',
                                'language' => $this->language), 
                          		'lang_default', true);
    
$url_more = $this->url(array('controller' => 'search',
                             'action' => 'result',
                             'page' => '2',
                             'language' => $this->language), 
                        	 'lang_default', true);

$url_getRecentContent = $this->url(array('controller' => 'ajax',
							 'action' => 'getrecentcontent',
							 'language' => $this->language), 
							 'lang_default', true);

$url_checkRecentContent = $this->url(array('controller' => 'ajax',
										   'action' => 'checkrecentcontent',
										   'language' => $this->language), 
										   'lang_default', true);
?>
<?php $this->headScript()->captureStart()?>

$(document).ready(function(){
	recentpostsdiv  = '#recent_posts_ajax';
	recentpostslink = '#recent_posts_ajax_link';
	recentpostslink_orig = $(recentpostslink).html();
	pagecount = 1;
	previousresult = "";

	$(recentpostslink+' a').live('click', function(){
		pagecount = pagecount + 1;
		ajaxLoad_getRecentPosts(recentpostsdiv, pagecount);
	});

	ajaxLoad_checkRecentPosts();
	//ajaxLoad_getRecentPosts(recentpostsdiv, pagecount);
	
});

	function ajaxLoad_getRecentPosts(obj, offset, prepend){
		$.ajax({
			beforeSend: function(){
				$(recentpostslink).html(
					'<h3 style="vertical-align: middle;"><img src="<?php echo $this->baseUrl('/images/ajax-loader-black.gif');?>" style="padding-right: 10px;" /> ' + 
					'Please wait...</h3>'
				);
			},
			complete: function(){
				$(recentpostslink).html(recentpostslink_orig);
			},
			url: "<?php echo $url_getRecentContent; ?>/offset/"+offset,
			success: function(result){
				if(prepend == 1) {
					$(obj).prepend(result);
				} else {
					$(obj).append(result);
				}
				$('.user_content_row_new').hide();
				removeDupes_recentPosts(recentpostsdiv);
				$('.user_content_row_new').removeClass('user_content_row_new');
				$('.user_content_row').fadeIn('slow');
			}
		});
	};
	
	function removeDupes_recentPosts(obj){
		$(recentpostsdiv + ' [id]').each(function(){
			var ids = $('[id='+this.id+']');
			if(ids.length > 1 && ids[0]!=this){
				console.warn('Multiple IDs #'+this.id);
				$(this).remove();
			}
		});
	}

	function ajaxLoad_checkRecentPosts(){
		$.ajax({
			url: "<?php echo $url_checkRecentContent; ?>/check/",
			success: function(result){
				//alert(result + " | " + previousresult);
				if(result != previousresult) {
					ajaxLoad_getRecentPosts(recentpostsdiv, 1, 1);
				}
				previousresult = result;
				setTimeout("ajaxLoad_checkRecentPosts()", 30000);
			}
		});
	}

<?php $this->headScript()->captureEnd()?>
<h3 class="recent_posts"><?php echo $this->translate('index-recent-posts'); ?></h3>
			
<!-- Small hack to force a small space between the h2 and content... might help the Symbian -browsers a bit -->
<div style="height: 2px;"></div>

<div class="user_content_list" style="padding: 0px; margin: 0px; overflow:hidden;">
	<div id="recent_posts_ajax" style="width: 500px;"></div>
    <div class="user_content_spacer">
        <img src="<?php echo $this->baseUrl('/images/gray_dot_line_500.png'); ?>" alt="Massidea.org" />
    </div>
    
    <div id="recent_posts_ajax_link" style="margin-top: 10px; margin-left: 220px;">
        <h3>
            <a href="#" onclick="return false;"><?php echo $this->translate('index-view-more'); ?></a>
        </h3>
    </div>
</div>

<?php 
/*
Assign the partial view to the layout :) 
If there is nothing, the layout just prints nothing. 
However, if you assign a file that does not exist, the site will 
throw an application error instantly, so be careful!

Commented to fix temporary problem, will be researched further later
*/
//$this->layout()->right_side = $this->partial('partials/index.phtml'); 
?>
<div class="right_side" style="padding: 0px; margin: 0px; margin-top: -52px;">
    <!-- For some mystical reason, paragraphs seem to need an empty style-attribute in order to extend a CSS -class -->
    <h4 style="margin-top: 8px; margin-bottom: 6px;">
        <?php echo $this->translate('index-what-is'); ?>
    </h4>
        <div class="top_right_box">
            <?php echo $this->translate('index-what-is-long'); ?>
            <?php // <span class="top_right_box_links"><a href="#"> echo $this->translate('index-learn-more'); </a></span> ?>
        </div>
        
    <?php if(!$this->isLoggedIn): ?>
    <p id="sign_up_now" style="padding-bottom: 10px;" class="top_right_box_links">
        <b>
            <a href="<?php echo $url_sign_up; ?>">
                <?php echo $this->translate('index-sigup')?>
            </a>
        </b>
    </p>
    <?php endif; ?>
    
    <h3 style="margin-top: 5px; margin-bottom: 0; padding: 0;">
        <?php echo $this->translate('index-most-popular')?>
        <a href="<?php echo $url_tag_cloud; ?>">
            <?php echo $this->translate('index-tags')?>
        </a>
    </h3>
    
    <img src="<?php echo $this->baseUrl('/images/gray_dot_line_200.png'); ?>" alt="Massidea.org" />
    
    <div class="tag_cloud">
       
        <?php echo $this->partialLoop('partials/tag.phtml', $this->poptags); ?>
        
        <p id="show_all_tags" style="padding: 0px; margin-top: 10px;" class="top_right_box_links">
            <a href="<?php echo $url_tag_cloud; ?>">
                <?php echo $this->translate('index-show-all')?>
            </a>
        </p>
    </div>
    
    <img src="<?php echo $this->baseUrl('/images/gray_dot_line_200.png'); ?>" alt="Massidea.org" />
    
    <p id="most_active_users" style="padding: 0px;" class="top_right_box_links">
        <?php echo $this->translate('index-most-active')?>
        <a href="<?php echo $this->url(array('controller' => 'account',
                                             'action' => 'userlist',
                                             'language' => $this->language),
                                             'lang_default', true); ?>">
            <?php echo $this->translate('index-users')?>
        </a>
    </p>
    
    <img src="<?php echo $this->baseUrl('/images/gray_dot_line_200.png'); ?>" alt="Massidea.org" />
    
    <div class="top_right_box_links_users">
        <?php echo $this->partialLoop('partials/user_row.phtml', $this->activeusers); ?>
    </div>
    
    <div class="top_right_box_links_show_all_users">
        <a href="<?php echo $this->url(array('controller' => 'account',
                                             'action' => 'userlist',
                                             'language' => $this->language),
                                             'lang_default', true); ?>">
            <?php echo $this->translate('index-show-all')?>
            <?php echo $this->translate('index-users')?>
        </a>
    </div>
    
    <img src="<?php echo $this->baseUrl('/images/gray_dot_line_200.png'); ?>" alt="Massidea.org" />
    
    <div class="massidea_dev_info">
        <?php echo $this->translate('index-opensource')?>
    </div>
</div>