<?php if($this->pageCount): ?>
<div class="paginationControl">
	<!-- First page link -->
	<?php if($this->current != $this->first): ?>
		<a href="<?php echo $this->url(array('page' => $this->first)); ?>"><img src="/images/paginator_first.png" alt="First page" /></a>
	<?php else: ?>
		<span class="disabled"><img src="/images/paginator_first.png" alt="First page" /></span>
	<?php endif; ?>

	<!-- Previous page link -->
	<?php if(isset($this->previous)): ?>
		<a href="<?php echo $this->url(array('page' => $this->previous)); ?>"><img src="/images/paginator_prev.png" alt="Previous page" /></a>
	<?php else: ?>
		<span class="disabled"><img src="/images/paginator_prev.png" alt="Previous page" /></span>
	<?php endif; ?>

	<!-- Numbered page links -->
	<?php foreach($this->pagesInRange as $page): ?>
		<?php if($page != $this->current): ?>
			<a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
		<?php else: ?>
			<span class="currentpage"><?php echo $page; ?></span>
		<?php endif; ?>
	<?php endforeach; ?>

	<!-- Next page link -->
	<?php if(isset($this->next)): ?>
		<a href="<?php echo $this->url(array('page' => $this->next)); ?>"><img src="/images/paginator_next.png" alt="Next page" /></a>
	<?php else: ?>
		<span class="disabled"><img src="/images/paginator_next.png" alt="Next page" /></span>
	<?php endif; ?>
	
	<!-- Last page link -->
	<?php if($this->current != $this->last): ?>
		<a href="<?php echo $this->url(array('page' => $this->last)); ?>"><img src="/images/paginator_last.png" alt="Last page" /></a>
	<?php else: ?>
		<span class="disabled"><img src="/images/paginator_last.png" alt="Last page" /></span>
	<?php endif; ?>
</div>
<?php endif; ?>