<?php if($this->pageCount): ?>
<div class="paginationControl">
	<!-- First page link -->
	<?php if($this->currentPage != 1): ?>
		<a href="<?php echo $this->url(array('page' => 1)); ?>">
            <img src="<?php echo $this->baseUrl(); ?>/images/paginator_first.png" alt="First page" />
        </a>
	<?php else: ?>
		<span class="disabled"><img src="<?php echo $this->baseUrl(); ?>/images/paginator_first.png" alt="First page" /></span>
	<?php endif; ?>

	<!-- Previous page link -->
	<?php if($this->currentPage > 1): ?>
		<a href="<?php echo $this->url(array('page' => $this->currentPage - 1)); ?>">
            <img src="<?php echo $this->baseUrl(); ?>/images/paginator_prev.png" alt="Previous page" />
        </a>
	<?php else: ?>
		<span class="disabled"><img src="<?php echo $this->baseUrl(); ?>/images/paginator_prev.png" alt="Previous page" /></span>
	<?php endif; ?>

	<!-- Numbered page links -->
    <?php
        if ($this->pagesInRange > $this->pageCount) {
            $this->pagesInRange = $this->pageCount;
        }
        
        $delta = ceil($this->pagesInRange / 2);
        
        if ($this->currentPage - $delta > $this->pageCount - $this->pagesInRange) {
            $lower = $this->pageCount - $this->pagesInRange + 1;
            $upper = $this->pageCount; 
        } else {
            if ($this->currentPage - $delta < 0) {
                $delta = $this->currentPage;
            }
            
            $offset     = $this->currentPage - $delta;
            $lower = $offset + 1; 
            $upper = $offset + $this->pagesInRange;
        }
    
    ?>
	<?php for($page = $lower; $page <= $upper; $page++): ?>
		<?php if($this->currentPage != $page): ?>
			<a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
		<?php else: ?>
			<span class="currentpage"><?php echo $page; ?></span>
		<?php endif; ?>
	<?php endfor; ?>

	<!-- Next page link -->
	<?php if($this->currentPage < $this->pageCount): ?>
		<a href="<?php echo $this->url(array('page' => $this->currentPage + 1)); ?>">
            <img src="<?php echo $this->baseUrl(); ?>/images/paginator_next.png" alt="Next page" /></a>
	<?php else: ?>
		<span class="disabled"><img src="<?php echo $this->baseUrl(); ?>/images/paginator_next.png" alt="Next page" /></span>
	<?php endif; ?>
	
	<!-- Last page link -->
	<?php if($this->currentPage != $this->pageCount): ?>
		<a href="<?php echo $this->url(array('page' => $this->pageCount)); ?>">
            <img src="<?php echo $this->baseUrl(); ?>/images/paginator_last.png" alt="Last page" />
        </a>
	<?php else: ?>
		<span class="disabled"><img src="<?php echo $this->baseUrl(); ?>/images/paginator_last.png" alt="Last page" /></span>
	<?php endif; ?>
</div>
<?php endif; ?>