		<?php
	        // user is giving an email
	        if (($this->action == '' || ($this->action == 'submit' && $this->submittedForm == 'fetchpassword')) && !isset($this->keyGiven)) {
	            echo '<h2 class="fetchpassword-no-error">' . $this->translate('account-fetchpassword-request') . '</h2>';
		        echo $this->form;
	            if (isset($this->error) && $this->error != '') {
	                echo '<h2 class="fetchpassword-error">' . $this->translate($this->error) . '</h2>';
	            }
	        }
	        // user is giving a new password
	        if (($this->action == '' && isset($this->keyGiven)) || ($this->action == 'submit' && $this->submittedForm == 'newpassword')) {
	            if (isset($this->error) && $this->error != '') {
	                echo '<h2 class="fetchpassword-error">' . $this->translate($this->error) . '</h2>';
	            }
	            else {
	               echo '<h2 class="fetchpassword-no-error">' . $this->translate('account-fetchpassword-newpassword') . '</h2>';
	               echo $this->form;
	            }
	        }
	        // sending an email failed
	        else if ($this->action == 'emailproblem') {
	            if (isset($this->error) && $this->error != '') {
	                echo '<h2 class="fetchpassword-error">' . $this->translate($this->error) . '</h2>';
	            }
	        }
	        // user has been sent an email
	        else if ($this->action == 'emailsent') {
	            echo '<h2 class="fetchpassword-no-error">' . $this->translate('account-fetchpassword-emailsent') . '</h2>';
	        }
	        // user has completed the process
	        else if ($this->action == 'complete') {
	            echo '<h2 class="fetchpassword-no-error">' . $this->translate('account-fetchpassword-complete') . '</h2>';
	        }
	    ?>