<div id="left_1">
</div> <!-- end of "left_1"  -->
<div id="right_1">
	<?php 
		if ($this->action == 'confirm')
		{
			// let the user know if the password was succesfully changed
			if ( count($this->errors) == 0)
			{
				echo '<p>'.$this->translate('Account-fetchpassword-confirmed') .' <strong>'.$this->username.'</strong>.</p>';
			}
			// if there were errors, show error message
			else
			{
				echo '<p>'.$this->translate('Account-fetchpassword-confirmationfailed') .'</p>';
			}
		}
		elseif ($this->action == 'complete')
		{
			echo '<p>'.$this->translate('Account-fetchpassword-complete') .'</p>';
		}
		else
		{
			echo '<p>'.$this->translate('Account-fetchpassword-request') .'</p>';
			echo '<form action="" method="post">
					<p>
					'.$this->translate('Username').'
					<input type="text" name="username" />
					<input type="submit" value="Ok" />
					</p>
				</form>';
		}
	?>
</div> <!-- end of "right_1" -->
<p style="clear: both"></p>
