<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<div>
</div>
<div class="left narrow">
    <?php
        // user is giving an email
        if (($this->action == '' || ($this->action == 'submit' && $this->submittedForm == 'fetchpassword')) && !isset($this->keyGiven)) {
            echo '<p class="fetchpassword-no-error">' . $this->translate('account-fetchpassword-request') . '</p>';
            echo $this->form;
            if (isset($this->error) && $this->error != '') {
            	echo '<p class="fetchpassword-error">' . $this->translate($this->error) . '</p>';
            }
        }
        // user is giving a new password
        if (($this->action == '' && isset($this->keyGiven)) || ($this->action == 'submit' && $this->submittedForm == 'newpassword')) {
        	if (isset($this->error) && $this->error != '') {
        		echo '<p class="fetchpassword-error">' . $this->translate($this->error) . '</p>';
        	}
        	else {
        	   echo '<p class="fetchpassword-no-error">' . $this->translate('account-fetchpassword-newpassword') . '</p>';
        	   echo $this->form;
        	}
        }
        // sending an email failed
        else if ($this->action == 'emailproblem') {
            if (isset($this->error) && $this->error != '') {
                echo '<p class="fetchpassword-error">' . $this->translate($this->error) . '</p>';
            }
        }
        // user has been sent an email
        else if ($this->action == 'emailsent') {
            echo '<p class="fetchpassword-no-error">' . $this->translate('account-fetchpassword-emailsent') . '</p>';
        }
        // user has completed the process
        else if ($this->action == 'complete') {
            echo '<p class="fetchpassword-no-error">' . $this->translate('account-fetchpassword-complete') . '</p>';
        }
    ?>
</div>
<div class="clear"></div>