<div>
	<?php echo $this->form; ?>
</div>
<div style="background-color: #FFF; margin: 10px; padding: 2px; font-size: 10pt; border: 1px solid #AAA; width: 150px;">
	<img src="/images/icon_openid_16x16.gif" alt="OpenID login" style="vertical-align: middle;" />
	<a href="<?php echo $this->url(array('controller' => 'account', 'action' => 'openid', 'language' => $this->language), 'lang_default', true); ?>">
		<?php echo $this->translate('account-login-via-openid'); ?>
	</a>
</div>
<div style="position:absolute; bottom: 30px; left: 10px; font-size: 8pt;">
	<a href="<?php echo $this->url(array('controller' => 'account', 'action' => 'fetchpassword', 'language' => $this->language), 'lang_default', true); ?>">
		<?php echo $this->translate('account-login-forgot_password'); ?>
	</a>
</div>
