<div id="login_form_container" style="background-color: #FFF; text-align: center;">

	<img src="/images/logo_openid_big.png" alt="OpenID logo" style="width: 75%; height: 75%;" />
	<h1><?php //echo $this->translate('account-openid-title'); ?></h1>
		<?php echo $this->translate('account-openid-text'); ?>

	<?php
    if(isset($this->errormsg))
    {
        echo "<h2>".$this->errormsg."</h2>";
    }
    ?>
    <div>
	<?php echo $this->form; ?>
	</div>

</div>