<?php 
	// Append the scripts needed by jCrop 
	$this->headLink()->appendStylesheet($this->baseUrl . '/css/jcrop/jquery.jcrop.css');
	$this->headScript()->prependFile($this->baseUrl . '/js/jquery.jcrop.min.js');
?>

<?php $this->headScript()->captureStart() ?>
$(function(){
	$('#cropbox').Jcrop({
		aspectRatio: 1,
		setSelect: [0,0,100,100],
		onSelect: updateCoords,
		boxWidth: 600,
		boxHeight: 600
	});
});

function updateCoords(c)
{
    // Coordinates are stored as variables and can be accessed here as
    // c.x, c.y, c.x2, c.y2, c.w, c.h
    
    $('#c_x').val(c.x);
    $('#c_y').val(c.y);
    $('#c_w').val(c.w);
    $('#c_h').val(c.h);
};
<?php $this->headScript()->captureEnd() ?>

<h1><?php echo $this->translate('account-processimage-title'); ?></h1>
<table>
	<tr>
		<td><img src="<?php echo $this->prethumb;?>" alt="cropbox" id="cropbox" /></td>
		<td><?php echo $this->form;?></td>
	</tr>
</table>
<br />