<?php $this->headScript()->appendFile($this->baseUrl . '/js/CheckContentForm.js'); ?>
<?php $this->headLink()->appendStylesheet('/css/style_additions_req.css'); ?>

<div style="width:500px; float:left;">
    <h2><?php echo $this->translate('account-registercomplete-header'); ?></h2>
    <p><?php echo $this->translate('account-registercomplete-p1'); ?></p>
    <p><?php echo $this->translate('account-registercomplete-p2'); ?></p>
    
    <?php
    /*
    <p style="font-size: 1.2em; font-weight: bold; padding:0; margin:0; color:#ccc;"><?php echo $this->translate('account-registercomplete-formtitle'); ?></p>
    <img src="/images/gray_dot_line_500.png" alt="Massidea.org" />
    <p style="font-size: 1em; font-weight: bold; padding:3px 0 0 0; margin:0; color:#ccc;"><?php echo $this->translate('account-registercomplete-formdesc'); ?></p>
    <div style="clear:both;"></div>
    

        if (isset($this->form)) {
            echo $this->form;
        } else {
            // PANIC!!
        }
        */
    ?>

</div>
    
    