<div id="form_registration">
	<h1><?php echo $this->translate('account-register-page_header'); ?></h1>
	
	<form method="post" id="register_form" action="<?php $this->url(array('controller' => 'account', 'action' => 'register', 'language' => $this->language), 'lang_default', true); ?>" enctype="multipart/form-data">			
			<p><?php echo $this->translate('account-register-first_paragraph'); ?></p>
			<p><?php echo $this->translate('account-register-second_paragraph'); ?></p>
			<p>	
				<label><?php echo $this->translate('account-register-username'); ?></label>	
				<input type="text" class="text" name="username" value="<?php // echo $this->fp->username ?>" /> *
			</p>
			<p class="error_message">		
				<?php // Show error messages for username
					/*
					if($this->errors)
					{
						if(array_key_exists('no_username', $this->errors)) echo $this->translate('No username');
						if(array_key_exists('username_exists', $this->errors)) echo $this->translate'Username exists');
						if(array_key_exists('username_invalid', $this->errors)) echo $this->translate('Username invalid');
					}
					*/
				?>
			</p>
		
			<p>
				<label><?php echo $this->translate('account-register-email'); ?></label>
					<input type="text" class="text" name="email" value="<?php //echo $this->fp->email ?>" /> *
			</p>
			<p class="error_message">
				<?php // Show error messages  for email
				/*
				if($this->errors)
				{
					if(array_key_exists('no_email', $this->errors)) echo $this->translate('No email');
					if(array_key_exists('email_not_valid', $this->errors)) echo $this->translate('Email invalid');
					if(array_key_exists('e-mail_too_long', $this->errors)) echo $this->translate('E-mail too long, max 99 characters');
				}
				*/
				?>
			</p>
			<p>
				<label><?php echo $this->translate('account-register-email_confirmation'); ?></label>
					<input type="text" class="text" name="email2" value="<?php // echo $this->fp->email2 ?>" /> *
			</p>
			<p class="error_message">
				<?php // Show error messages  email
				/*
				if ($this->errors)
				{
					if(array_key_exists('no_second_email', $this->errors)) echo $this->translate('No second email');
					if(array_key_exists('email_mismatch', $this->errors)) echo $this->translate('Email mismatch');
				}
				*/
				?>
			</p>
			
			<p>
				<label><?php echo $this->translate('account-register-verification'); ?></label>
				<img src="<?php echo Zend_Controller_Front::getInstance()->getBaseUrl(); ?>/captcha/png" alt="Verification image" id="captcha_image"/><br/>
				<label><?php echo $this->translate('account-register-enter_text'); ?></label>
				<input type="text" class="text" name="captcha" value="" /> *
			</p>
			<p class="error_message">
			<?php // Show error messages 
			/*
				if ($this->errors)
				{
					if(array_key_exists("captcha", $this->errors)) echo $this->translate('Captcha error');
				}
				*/
				?>
			</p>
		
		
			<p>
				<input type="checkbox" id="testinput_xml3" class="radio" name="terms" /> 
				<?php printf($this->translate('account-register-terms_and_privacy'), "#", "#"); //echo $this->translate('account-register-userterm'); ?> <a href="#">
				<?php //echo $this->translate('account-register-terms_link'); ?><!--</a><br/>-->
				<?php //echo $this->translate('account-register-and'); ?>
				<!--<a href="#"><?php //echo $this->translate('account-register-privacy_link'); ?></a>-->
			</p>
			
			<p class="error_message">
			<?php // Show error messages 
			/*
				if ($this->errors)
				{
					if(array_key_exists("terms", $this->errors)) echo $this->translate('Terms must be agreed to');
				}
				*/
				?>
			</p>
						
			<p>
				<input type="submit" value="<?php echo $this->translate('submit'); ?>" class="input_button"  />
			</p>
	</form>
</div>