<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<div class="row">
    <div class="span6">
        <h2><?php echo $this->translate('account-register-page_header'); ?></h2>
        <?php
        if (isset($this->form)) {
            echo $this->form;
        } else {
            // PANIC!!
        }
        ?>
    </div>
    <!-- TODO: Delete breaks - but don't know, where they come from :/ -->
    <div class="span6">
        <h2><?php echo $this->translate('registration-box-header'); ?></h2>
        <?php echo $this->translate('account-register'); ?>
    </div>
</div>
