<?php $this->headScript()->captureStart()?>
    // Definitions for input boxes ([0] = minimum, [1] = maximum, [2] = required (1 true/0 false)
	var inputDefinitions = {
		'biography':    [0,  4000, 0]
	};

    var date = new Date();
    var y = date.getFullYear();
    y = '1900:' + y;
    $(function() {
        $('#birthday').datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: y
        });
    });
<?php $this->headScript()->captureEnd()?>

<div id="edit-user-page" class="narrow">

	<h2>Edit your profile</h2>

    <span class="note">Information marked with *) are required</span>

    <div class="clear"></div>

	<?php
		echo $this->form;
	?>

</div>