<div id="left_1">
	<p>
		<img class="profile_image" src="<?php echo Zend_Controller_Front::getInstance()->getBaseUrl(); ?>/utility/profileimage?id=<?php echo $this->user->userid; ?>" alt="user_image" />
	</p>
	<p>
		<strong><?php echo $this->translate->_('Edit profile info', $this->language); ?></strong><br />
		<a href="?page=account"><strong><?php echo $this->translate->_('Account', $this->language); ?></strong></a><br />
		<a href="<?php echo Zend_Controller_Front::getInstance()->getBaseUrl(); ?>/account/index"><strong>Back</strong></a><br />
	</p>
</div> <!-- end of "left-1"  -->
	<div id="left_2">
		<h1><?php echo $this->translate->_('Account', $this->language); ?></h1>
		<form method="post" action="" id="profile_form">
			<fieldset>		
				<?php if ($this->page == 'account'): ?>
				<p>
					<label><?php echo $this->translate->_('Account-register-username', $this->language); ?></label>								
					<?php echo $this->user->username; ?>
				</p>
				<p class="error_message">
					<?php // Show error messages 
						if($this->errors)
						{
							if(array_key_exists('username_exists', $this->errors)) echo $this->translate->_('Username exists', $this->language);
							if(array_key_exists('username_invalid', $this->errors)) echo $this->translate->_('Username invalid', $this->language);
						}
					?>
				</p>
				<p>
					<label><?php echo $this->translate->_('Account-register-email', $this->language); ?></label>
					<input type="text" class="text"
					name="email" value="<?php echo $this->user->profile->email; ?>" />
				</p>
				<p class="error_message">
					<?php // Show error messages 
					if($this->errors)
					{
						if(array_key_exists('email_not_valid', $this->errors)) echo $this->translate->_('Email invalid', $this->language);
					}
					?>
				</p>
				<p>
				<p>
					<label><?php echo $this->translate->_('New password', $this->language); ?></label>
					<input type="password" class="text"
					name="newpass" value="" />
				</p>
				<p class="error_message">
					<?php // Show error messages 
					if ($this->errors)
					{
						if(array_key_exists('password_mismatch', $this->errors)) echo $this->translate->_('Password mismatch', $this->language);
					}
					?>
				</p>
				<p>
					<label><?php echo $this->translate->_('Re-type password', $this->language); ?></label>
					<input type="password" class="text"
					name="newpass2" value="" />
				</p>
				<p class="error_message">
					<?php // Show error messages 
					if ($this->errors)
					{
						if(array_key_exists('email_mismatch', $this->errors)) echo $this->translate->_('Email mismatch', $this->language);
					}
					?>
				</p>			
					<?php endif; ?>
					
				<div class="submit">
					<p>
						<input type="submit" value="<?php echo $this->translate->_('Modify', $this->language); ?>" class="login_button" />
					</p>
				</div>
			</fieldset>
		</form>
	</div> <!-- end of "left_2"  -->
	<p class="clear"></p>
</div><!-- end of "content"  -->						