<?php 
  
$url_getUserContents = $this->url(array('controller' => 'ajax',
							 'action' => 'getusercontents',
							 'language' => $this->language), 
							 'lang_default', true);

$url_contentView = $this->url(array('controller' => 'view',
							 'language' => $this->language), 
							 'lang_default', true);

$url_getUserStatistics = $this->url(array('controller' => 'ajax',
							 'action' => 'getuserstatistics',
							 'language' => $this->language), 
							 'lang_default', true);

$url_getUserListBase = $this->url(array('controller' => 'account',
							 'action' => 'userlist',
							 'language' => $this->language), 
							 'lang_default', true);

$url_iconPlus = $this->baseUrl('/images/icon_plus_tiny.png');
$url_iconMinus = $this->baseUrl('/images/icon_minus_tiny.png');
$url_arrowDown = $this->baseUrl('/images/arrow_down.png');
$url_arrowUp = $this->baseUrl('/images/arrow_up.png');
$url_arrowUpDown = $this->baseUrl('/images/arrow_UpDown.png');
$url_arrowUp_active = $this->baseUrl('/images/arrow_UpDownUpActive.png');
$url_arrowDown_active = $this->baseUrl('/images/arrow_UpDownDownActive.png');
$url_loader = $this->baseUrl('/images/ajax-loader-black.gif');
$url_thumbUp = $this->baseUrl('/images/icon_thumb_up.png'); 
$url_thumbDown = $this->baseUrl('/images/icon_thumb_down.png');

$this->headScript()->appendFile($this->baseUrl . '/js/jquery.autocomplete.js');
$this->headScript()->appendFile($this->baseUrl . '/js/jquery.gchart.min');
//$this->headLink()->prependStylesheet($this->baseUrl . '/css/css_reset.css');
$this->headScript()->captureStart();

?>

var thumbUp = "<?php echo $url_thumbUp; ?>";
var thumbDown = "<?php echo $url_thumbDown; ?>";
var loader = "<?php echo $url_loader; ?>";
var contentView = "<?php echo $url_contentView; ?>";
var userContents = "<?php echo $url_getUserContents ?>";
var userStatistics = "<?php echo $url_getUserStatistics ?>";
var loading = "<img src=\""+loader+"\" /><span> Please wait...</span>";
var userIds = jQuery.parseJSON('<?php echo json_encode($this->userList); ?>');
var userCities = jQuery.parseJSON('<?php echo $this->cities; ?>');
var topList = jQuery.parseJSON('<?php echo json_encode($this->topNames); ?>');
var arrowdown = "<?php echo $url_arrowDown; ?>";
var arrowup = "<?php echo $url_arrowUp; ?>";
var iconplus = "<?php echo $url_iconPlus; ?>";
var iconminus = "<?php echo $url_iconMinus; ?>";

<?php $this->headScript()->captureEnd(); ?>

<?php $this->headScript()->appendFile($this->baseUrl('/js/userlist.js')); ?>
 
<div id="user_list">

<span class="user_list_title">Users</span>
    <div id="user_list_top" class="clear">
	<div id="user_list_search_form">
		<span>Search users based on:</span>
		<?php echo $this->userSearch; ?>
	</div>
    <div id="user_list_search_instructions">
    	<?php echo $this->translate('account-userlist-search-instructions'); ?>
    </div>
    </div>
    <div style="border-bottom:1px dotted #DDDDDD; margin-bottom:5px; padding-top:2px"></div>
    
    <?php if($url_getUserListBase != $this->url()): ?>
    <div class="user_list_search_results"> 
    <div class="user_list_sort">
	<strong>Sort by: </strong>
	<?php foreach($this->order as $line => $description): ?>
	<?php 
		$url_desc = $this->url(array("order" => $line,"list" => "desc"));
		$url_asc = $this->url(array("order" => $line,"list" => "asc"));
		$sort_name = mb_convert_case($line, MB_CASE_TITLE);
		$style = "text-decoration: none;";
		$arrow = $url_arrowUpDown;
		$url = $url_desc;
		if($line == $this->lastOrder) { 
			$style .= "color:green; font-weight: bold;";
			if($this->list == "descending") { $arrow = $url_arrowDown_active; $url = $url_asc; }
			if($this->list == "ascending") { $arrow = $url_arrowUp_active; $url = $url_desc; }
		}

	?>
			<strong> |</strong>
			<a href="<?php echo $url; ?>" style="<?php echo $style; ?>">
			<?php echo $sort_name; ?> <img src="<?php echo $arrow; ?>" style="vertical-align: middle;"></img></a>
			
	<?php endforeach; ?>
	
	</div>
	<div style="margin-top: 5px;"><span style="font-weight: bold">Sort description: </span><span><?php echo $this->order[$this->lastOrder]; ?></span></div>
    <div style="border-bottom:1px dotted #DDDDDD; padding-bottom:5px;"></div>
    <?php if (!empty($this->userListData)):?>
            <?php if ($this->userCount > $this->count): ?>
            <div id="user_list_user_pagination_top">
                <?php echo $this->userPaginator->render('pagination/slidingPaginationControl.phtml'); ?>
            </div>
            <?php endif; ?>
        <div id="user_list_bottom">
                   
            <div id="account_user_list_container">

                <?php foreach ($this->userListData as $user): ?>
                    <div id="user_<?php echo $user['id_usr']; ?>" class="user_list_user_container clear">
                    	<div class="user_list_left_side"> 
	                        <div id="user_<?php echo $user['id_usr']; ?>_image" class="user_list_user_image">
	                                <img src="<?php echo $this->url(array('controller' => 'account', 
	                                                                      'action' => 'profilethumb', 
	                                                                      'thumb' => true, 
	                                                                      'id' => $user['id_usr'], 
	                                                                      'language' => $this->language), 
	                                                                'lang_default', true); ?>" alt="User image" class="profile_image_mediumsize" />
	                        </div>
	                        <div class="user_list_user_line">
	                        <a onClick="return false;" class="user_list_moreless" id="user_<?php echo $user['id_usr']; ?>_list_more" href="#" style="display:block;">More</a>
	                        <a onClick="return false;" class="user_list_moreless" id="user_<?php echo $user['id_usr']; ?>_list_less" href="#" style="display:none;">Less</a>
	                        </div>
                        </div>
                        <div class="user_list_right_side"> 
	                        <div id="user_<?php echo $user['id_usr']; ?>_info" class="user_list_user_info">
		                        <div class="user_list_user_line">
			                        <a class="user_list_username" href="<?php echo $this->url(array('controller' => 'account',
			                                                                     'action' => 'view',
			                                                                     'user' => $user['login_name_usr'],
			                                                                     'language' =>  $this->language),
			                                                               'lang_default', true); ?>">
			                                    <?php echo $user['login_name_usr']; ?>(<?php echo $user['contentCount']; ?>)
			                         ,</a>
			                        <?php if($user['city']): ?>
			                        <a href="<?php echo $this->url(array('city' => $user['city'])); ?>" class="user_list_city"><?php echo $user['city']; ?>, </a>
			                        <?php endif; if($user['country']): ?>
			                        <a href="<?php echo $this->url(array('country' => $user['countryIso'])); ?>" class="user_list_country"><?php echo substr($user['country'],0,20); ?>, </a>
			                        <?php endif; if($user['ratingAmount']): ?>
									<span class="user_list_rating"><span class="user_list_positive_icon"><?php echo $user['ratingRatioPositive']; ?>% </span><img src="<?php echo $this->baseUrl('/images/icon_thumb_up.png'); ?>" alt="" /><img src="<?php echo $this->baseUrl('/images/icon_thumb_down.png'); ?>" alt="" /><span class="user_list_negative_icon"><?php echo $user['ratingRatioNegative']; ?>%</span></span>
									<span class="user_list_rating_amount">(<?php echo $user['ratingAmount']; ?> Ratings) </span>
			                        <?php else: ?>
			                        <span class="user_list_rating">No rated contents.</span>
			                        <?php endif; ?>
			                        <span class="user_list_last_login" style="display: block">Last login: <?php echo date("d M Y, H:i",strtotime($user['last_login_usr'])); ?></span>
		                        </div>
		                        <div class="user_list_statistics" id="user_list_user_<?php echo $user['id_usr']; ?>_statistics" style="display:none;">
			                        <div class="user_list_user_line"><span class="user_list_statistics_title">Statistics</span>
			                         | <a id="user_list_user_<?php echo $user['id_usr']; ?>_statistics_load_graphs" href="#" onClick="return false;">Show graphs</a>
			                         <div style="display:inline"><div id="user_list_<?php echo $user['id_usr']; ?>_show_graphs_loading" style="display: none"></div></div>
			                        </div>
			                        <div class="user_list_user_line"><span class="user_list_statistics_line">> Joined: <?php echo date("d M Y",strtotime($user['created_usr'])); ?></span></div>
			                        <?php 
			                        //This is not in use for now...
			                        /* if($user['ratingAmount']): ?>
			                        <div class="user_list_user_line">
				                        <span class="user_list_statistics_line">> Contents rating ratio: 
				                        	<span class="user_list_positive_icon"><?php echo $user['ratingRatioPositive']; ?>% </span><img src="<?php echo $this->baseUrl('/images/icon_thumb_up.png'); ?>" alt="" /><img src="<?php echo $this->baseUrl('/images/icon_thumb_down.png'); ?>" alt="" /><span class="user_list_negative_icon"><?php echo $user['ratingRatioNegative']; ?>%</span>
				                        </span>
			                        </div>
			                        <div class="user_list_user_line">
				                        <span class="user_list_statistics_line">> Contents rating average: 
				                        	<span class="user_list_positive_icon"><?php echo $user['ratingAveragePositive']; ?>% </span><img src="<?php echo $this->baseUrl('/images/icon_thumb_up.png'); ?>" alt="" /><img src="<?php echo $this->baseUrl('/images/icon_thumb_down.png'); ?>" alt="" /><span class="user_list_negative_icon"><?php echo $user['ratingAverageNegative']; ?>%</span>
				                        </span>
			                        </div>

			                        <?php endif; */ ?>
			                        <div class="user_list_charts" id="user_<?php echo $user['id_usr']; ?>_charts" style="display:none">
			                        	<div class="user_list_user_line"><div id="user_<?php echo $user['id_usr']; ?>_typechart" class="contentTypeChart"></div></div>
		                        	</div>
		                        </div>
		                        
		                        <?php if (sizeof($this->userContents[$user['id_usr']]) > 0): ?>
		                        <div class="user_list_user_recent_contents">
		                        <div class="user_list_user_line" style="height: 15px">
			                        <span class="user_list_recet_contents_title">Recent posts </span>
			                        |
			                        <a id="user_list_<?php echo $user['id_usr']; ?>_show_more" href="#" onClick="return false;" style="display: inline">Show 3 more </a>
			                        <div style="display:inline"><div id="user_list_<?php echo $user['id_usr']; ?>_show_more_loading" style="display: none"></div></div>
			                        |
			                        <a id="user_list_<?php echo $user['id_usr']; ?>_hide_new" href="#" onClick="return false;" style="block">Hide</a>
		                        </div>
		                        
		                        <div class="user_list_statistics" id="user_list_user_<?php echo $user['id_usr']; ?>_search" style="display:none;">
			                        <div class="user_list_user_line">
				                        <div class="user_list_content_search">
	                       					<form action="#" id="user_<?php echo $user['id_usr']; ?>_content_link"><span id="user_<?php echo $user['id_usr']; ?>_content_search_text">Content search: </span><input id="user_<?php echo $user['id_usr']; ?>_content"></input><input type="submit" value="Go"></input></form>
	                       				</div>
		                       		</div>
	                       		</div>
		                       		<div class="user_list_user_recent_contents_list" id="user_<?php echo $user['id_usr']; ?>_list_user_recent_contents_list">
			                        <?php
			                        
			                        foreach($this->userContents[$user['id_usr']] as $content) :?>
			                        	<div class="user_list_user_line"><span class="user_list_content_type_<?php echo $content['key_cty']; ?>">> </span><a class="user_list_content_title" href="<?php
			                        					 echo $this->url(array('controller' => 'view',
	                                                                     'action' => $content['id_cnt'],
	                                                                     'language' =>  $this->language),
	                                                               'lang_default', true); ?>"><?php 
			                        					 if(mb_strlen($content['title_cnt']) > 70)
			                        					 	echo substr($content['title_cnt'],0,70)."...";
			                        					 else echo $content['title_cnt']; 
			                        					 
			                        					 ?></a></div>
			                  		
			                        <?php endforeach; ?>
			                        
			                        </div>
		                        </div>
		                        <?php else: ?>
		                        	<div class="user_list_user_line"><span class="user_list_no_content">User has no added contents</span></div>
		                        
		                        <?php endif; ?>
		                                        
                        	</div>
                        </div>
                    </div>
                <?php endforeach; ?>
                
            </div>
            
            <?php if ($this->userCount > $this->count): ?>
        	<div id="user_list_user_pagination_bottom">
                <?php echo $this->userPaginator->render('pagination/slidingPaginationControl.phtml'); ?>
        	</div>
            <?php endif; ?>
            
        </div>
<?php else: ?>
	<div>
		<?php echo $this->translate('search-nothing-found'); ?>
	</div>
<?php endif; ?>
</div>
<?php else: ?>

<div class="user_list_top_list">
<div class="user_list_top_list_title">
<span>Top users list </span>
<a id="user_list_top_list_expand_all" href="#" onClick="return false;"><img src="<?php echo $this->baseUrl('/images/icon_plus_tiny.png'); ?>" /></a>
</div>
	<div class="user_list_top_line">
<?php $i = 0;
	foreach($this->top as $key => $top) { 
		if($i % 3 == 0 && $i != 0) { ?>
			</div> 
			<div class="user_list_top_line">
			<?php 
				 echo $this->partial("partials/account_userlist_toplist_box.phtml", $top); 
		} else { 
			echo $this->partial("partials/account_userlist_toplist_box.phtml", $top); 
		}
		$i++;
	}
	
?>
	</div>
</div>
<?php endif; ?>
 </div>