<?php 

$url_getUserLocations = $this->url(array('controller' => 'ajax',
							 'action' => 'getuserlocations',
							 'language' => $this->language), 
							 'lang_default', true);

$url_getUserContents = $this->url(array('controller' => 'ajax',
							 'action' => 'getusercontents',
							 'language' => $this->language), 
							 'lang_default', true);

$url_contentView = $this->url(array('controller' => 'view',
							 'language' => $this->language), 
							 'lang_default', true);

$this->headScript()->appendFile($this->baseUrl . '/js/jquery.autocomplete');
//$this->headLink()->appendStylesheet($this->baseUrl . '/css/style_additions_req.css');
$this->headScript()->captureStart();

?>

$(document).ready(function(){
	jsonSearchLocations("cities");
	var json_users = '<?php echo json_encode($this->userList); ?>';
	var obj = jQuery.parseJSON(json_users);
	$.each(obj, function() {
		jsonSearchContents(this);
		$("input#user_"+this+"_content").focus(function() {
			$(this).click();
		});
	});
	
});

function jsonSearchContents(user_id){
	$.getJSON("<?php echo $url_getUserContents ?>/search/"+user_id, function(data) {
	  complete_user_content_search(user_id,data);	  
	});
};

function complete_user_content_search(user_id,result){

		var green = "smallsize_idea_border";
		var red = "smallsize_problem_border";
		var yellow = "smallsize_finfo_border";
		
		$("#user_"+user_id+"_content").autocomplete(result, {
		minChars: 0,
		width:347,
		delay:400,
		scrollHeight:200,
		matchContains: true,
		autoFill: false,
		selectFirst:true,
		max:result.length,
		formatItem: function(row, i, max) {
			if (row.id_cty_cnt == 1) var type = red;
			if (row.id_cty_cnt == 2) var type = green;
			if (row.id_cty_cnt == 3) var type = yellow;
			return "<span class=\""+type+"\"><span style=\"padding-left:2px;\"><a href=\"<?php echo $url_contentView ?>/"+row.id_cnt+"\" OnClick=\"window.location=\'<?php echo $url_contentView ?>/"+row.id_cnt+"'\;\">" + row.title_cnt + "</a></span><br /><span style=\"margin-left:0.5em;padding-left:2px;\">"+row.lead_cnt+"</span><span style=\"float:right\"> [" + row.created_cnt + "]</span></span>";
		},
		formatMatch: function(row, i, max) {
			return row.title_cnt;
		},
		formatResult: function(row) {
			return row.title_cnt;
		}
	});

};

function jsonSearchLocations(method){
	$.getJSON("<?php echo $url_getUserLocations ?>/search/"+method, function(data) {
	  if (method == "cities") complete_city(data);
	  else return;
	});
};

function complete_city(result){
	
		$("#city").autocomplete(result, {
		minChars: 1,
		width:247,
		delay:400,
		scrollHeight:200,
		matchContains: true,
		autoFill: false,
		selectFirst:false,
		formatItem: function(row, i, max) {
			return row.name + "<span style=\"float:right\"> [" + row.amount + "]</span>";
		},
		formatMatch: function(row, i, max) {
			return row.name;
		},
		formatResult: function(row) {
			return row.name;
		}
	});
	
};
<?php $this->headScript()->captureEnd(); ?>

<div id="user_list">

    <div id="user_list_top" class="clear">

	<div id="user_list_search_form">
		<?php echo $this->userSearch; ?>
	</div>
	
	    <div id="user_list_search_instructions">
    	<?php echo $this->translate('account-userlist-search-instructions'); ?>
    </div>
    </div>

    <?php if (!empty($this->userListData)):?>
            <?php if ($this->userCount > $this->count): ?>
            <div id="user_list_user_pagination_top">
                <?php echo $this->userPaginator->render('pagination/slidingPaginationControl.phtml'); ?>
            </div>
            <?php endif; ?>
        <div id="user_list_bottom">
                   
            <div id="account_user_list_container">

                <?php foreach ($this->userListData as $user): ?>
                    <div id="user_<?php echo $user['id_usr']; ?>" class="user_list_user_container clear">
                    
                        <div id="user_<?php echo $user['id_usr']; ?>_image" class="user_list_user_image">
                                <img src="<?php echo $this->url(array('controller' => 'account', 
                                                                      'action' => 'profilethumb', 
                                                                      'thumb' => true, 
                                                                      'id' => $user['id_usr'], 
                                                                      'language' => $this->language), 
                                                                'lang_default', true); ?>" alt="User image" class="profile_image_mediumsize" />
                        </div>
                        
                        <div id="user_<?php echo $user['id_usr']; ?>_info" class="user_list_user_info">
                            <div id="user_<?php echo $user['id_usr']; ?>_info_header">
                                <a href="<?php echo $this->url(array('controller' => 'account',
                                                                     'action' => 'view',
                                                                     'user' => $user['login_name_usr'],
                                                                     'language' =>  $this->language),
                                                               'lang_default', true); ?>">
                                    <?php echo $user['login_name_usr']; ?>
                                </a>
                            </div>
                            
                            <div id="user_<?php echo $user['id_usr']; ?>_info_created" class="user_list_user_info_data">
                                <?php echo $this->translate('account-userlist-user-joined').date('d M Y', strtotime($user['created_usr'])); ?>
                            </div>
                            
                            <div id="user_<?php echo $user['id_usr']; ?>_info_content" class="user_list_user_info_data">
                                <?php echo $this->translate(('account-userlist-user-content-added'), $user['contentCount']); ?>
                            </div>
                        </div>
                        <div class="user_list_user_info_second">
                        <div class="user_list_content_search">
                        Content search:
                        <input id="user_<?php echo $user['id_usr']; ?>_content"></input>
                        </div>
                        </div>
                        
                    </div>
                <?php endforeach; ?>
                
            </div>
            
            <?php if ($this->userCount > $this->count): ?>
        	<div id="user_list_user_pagination_bottom">
                <?php echo $this->userPaginator->render('pagination/slidingPaginationControl.phtml'); ?>
        	</div>
            <?php endif; ?>
            
        </div>
<?php else: ?>
	<div>
		<?php echo $this->translate('search-nothing-found'); ?>
	</div>
<?php endif; ?>   
 </div>