<?php $this->headScript()->captureStart() ?>

function publishconfirmation(url) {
    var answer = confirm("Publish content?");
    if (answer) {
        alert("Content published");
        window.location = url;
    } else {
        //alert("");
    }
}
function deleteconfirmation(url) {
    var answer = confirm("Delete content?");
    if (answer) {
        alert("Content deleted");
        window.location = url;
    } else {
        //alert("");
    }
}

// Bio: show 750; max 4000
var biographyBody = new Array();

$(document).ready(function() {
    // Bio
    var previewChars = 750;
	$(".biographyrow").each(function(key, value){
		biographyBody[key] = $(value).children().html();
		var biographylength = $(value).children().html().length;
		if(biographylength >= previewChars) {
			var biographyshort = biographyBody[key].substring(0,previewChars);
			var expandLink = '<a href="#" onclick="javascript:expandText('+key+');return false;">... more</a>';
			$(value).children().html(biographyshort + expandLink);
		};
	});
		
	$('#checkallrows').click(function(){
		$("INPUT[type='checkbox']").attr('checked', $('#checkallrows').is(':checked'));
	});
    // Endof Bio

	$("#activity > .left > #content_type > ul > li, \
	   #activity > .right > #content_type > ul > li, \
	   #activity > .wide > #content_type > ul > li").each(function () {
		$(this).css('cursor', 'pointer');
	});
	
	$("#activity > .left > #content_type, \
	   #activity > .right > #content_type, \
	   #activity > .wide > #content_type").each(function () {
		var selected = "";
		$(this).children("ul").children("li").each(function () {
			if ($(this).hasClass('selected')) {
				$(this).removeClass('selected');
				selected = $(this).attr('class');
				$(this).addClass('selected');
				return;
			}
		});
		var box = $(this).parent().attr('id');
		filterList(selected, box);
	});
	
	$("#activity > .left > #content_type > ul > li, \
	   #activity > .right > #content_type > ul > li, \
	   #activity > .wide > #content_type > ul > li").click(function (event) {		
		if ($(this).hasClass('selected')) return;

		$(this).siblings().removeClass('selected');
		var selected = $(this).attr('class'); 
		$(this).addClass('selected');
		var box = $(this).parent().parent().parent().attr('id');
		filterList(selected, box);
	}); // Endof a.click
	

	$("#user_profile_toplist_title").click(function(){
		if($(".user_profile_toplist_rank").is(":visible")) {
			$("#user_profile_toplist_title").html("Points");
			$(".user_profile_toplist_rank").slideUp(function(){$(".user_profile_toplist_points").slideDown();});
		}
		else {
			$("#user_profile_toplist_title").html("Rank");
			$(".user_profile_toplist_points").slideUp(function(){$(".user_profile_toplist_rank").slideDown();});
		}
	});
	
	$('#picker').farbtastic('#customfontcolor');
	
	$('#custombgcolorpicker').farbtastic('#custombgcolor');
	
	$("#advancedsettings-modal").dialog({
		autoOpen: false,
		title: 'Advanced Layout Customization',
		height: 800,
		width: 600,
		resizable: false,
		modal: true
	});
	
	$('#advencedsettingsbutton').click(function() {
		$("#advancedsettings-modal").dialog('open');
		$("#advancedsettings-modal").parent().css({'background-color' : 'black',
										  		   'opacity' : '0.7'});
	});
	
	$('#cancel_css_button').click(function() {
		$("#advancedsettings-modal").dialog('close');
	});
	
	$('#restore_css_button').click(function() {
		var original_css = $("#original_css").val();
		$("#css_textarea").val(original_css);
	});
	
	$('#default_css_button').click(function() {
		var default_css = $("#default_css").val();
		$("#css_textarea").val(default_css);
	});	

}); // Endof document ready

function filterList(selected, box) {
	$("#" + box + " > .scroll-box > ul > li").each(function() {
		curClass =$(this).attr('class');
		if( !$(this).hasClass(selected) && !$(this).hasClass('popup')) {
			$(this).hide();
		} else if ($(this).hasClass(selected) && !$(this).hasClass('popup')) {
			$(this).show();
			$(this).scrollTop();
		}
	}); // endof li.each
}

function expandText(key)
{
	$(".biographyrow:eq("+key+")").html("<span>"+ biographyBody +"</span>");
}


<?php $this->headScript()->captureEnd(); ?>

<?php
Zend_Layout::getMvcInstance()->setLayout('layout_new');
//$this->headLink()->appendStylesheet($this->baseUrl('/css/style_additions_req.css'));?>
<?php
    $admin = false;
    if(in_array("admin", $this->logged_user_roles)):
        $admin = true;
?>
<div id="admin_tools">
    <a href="<?php echo $this->url(array('controller' => 'admin',
                                         'action' => 'editroles',
                                         'user' => $this->user['login_name_usr'],
                                         'language' => $this->language),
                                   'lang_default', true); ?>">
        Edit roles of this user
    </a>
</div>
<?php endif; ?>

<div id="user-page" class="wide">
    <div id="profile-meta">
        <img src="<?php echo $this->url(array('controller' => 'account',
                                              'action' => 'profilethumb',
                                              'id' => $this->user['id_usr'],
        									  'thumb' => 'true',
                                              'language' => $this->language),
											  'lang_default', true); ?>" alt="User Image" class="avatar" width="200" />
        <ul>
            <li><strong>Joined:</strong> <?php echo date("d.m.Y H:i", strtotime($this->user['created_usr'])); ?></li>
            <li><strong>Last login:</strong> <?php echo $this->user['last_login_usr'] != null ?
                                date("d.m.Y H:i", strtotime($this->user['last_login_usr'])) :
                                'Never logged in'; ?></li>
            <!-- <li><strong>Page views:</strong> 1,200</li> -->
            
            <li>
            	<ul class="user_profile_toplist">
	            <li class="clear"><strong style="float: left">User ranking in:</strong><a href="#" onClick="return false;" style="float:right;" id="user_profile_toplist_title">Rank</a></li>
	            	<?php 
	            	foreach($this->topList as $key => $value) :
	            	 $rank = $value['addedUsers'][0]['rank']+1; 
	            	 if($rank != 0) $points = $value['addedUsers'][0]['value'];
	            	 if($rank == 0) { $rank = "Not ranked"; $points = "Not ranked"; } ?>
	            		<li class="clear"><strong style="float:left"><?php echo $value['title']; ?>: </strong><span class="user_profile_toplist_rank"><?php echo $rank; ?></span><span class="user_profile_toplist_points"><?php echo $points; ?></span></li>
	            	<?php endforeach; ?>
	            </ul>
            </li>
        </ul>
    </div>
    <div id="profile-info">
        <div id="user-info">
            <div id="connect" class="right">
                <?php if($this->user_edit): ?>
                <div>
                    <a href="<?php echo $this->url(array('controller' => 'account',
                                                         'action' => 'settings',
                                                         'language' => $this->language),
                                                   'lang_default', true); ?>">
                        Edit profile
                    </a>
                </div>
                <div>
                    <a href="<?php echo $this->url(array('controller' => 'account',
                                                         'action' => 'images',
                                                         'language' => $this->language),
                                                   'lang_default', true); ?>">
                        Change profile image
                        </a>
                </div>
                <div>
                    <a href="<?php echo $this->url(array('controller' => 'privmsg',
                                                         'action' => 'index',
                                                         'language' => $this->language),
                                                   'lang_default', true); ?>">
                        Private messages
                        <?php
                        if($this->unread_privmsgs > 0) {
                            echo "(".$this->unread_privmsgs.")";
                        }
                        ?>
                    </a>
                </div>
                <?php else:
                    if($this->authenticated): ?>
                <?php $privatemessage = $this->url(array('controller' => 'privmsg',
                                                     'action' => 'send',
                                                     'language' => $this->language),
                                               'lang_default', true)."/".$this->user['login_name_usr'];
                ?>
                <input type="button" value="Send a message" id="send-message" class="submit-button" name="send-message" alt="Send a message" onClick="location.href='<?php echo $privatemessage; ?>'">
                <?php endif; endif; ?>
            </div>
            <h2><?php echo $this->user['login_name_usr']; ?></h2>

            <?php //echo '<pre>'; var_dump($this->userprofile); ?>

            <ul>
                <?php if((isset($this->userprofile['firstname']) && $this->userprofile['firstname'] !== "") &&
                         (isset($this->userprofile['surname']) && $this->userprofile['surname'] !== "")) : ?>
                <li>
                    <strong>Full name:</strong>
                    <?php
                    echo $this->userprofile['firstname']." ".$this->userprofile['surname'];
                    ?>
                </li>
                <?php elseif (isset($this->userprofile['firstname']) && $this->userprofile['firstname'] !== "") : ?>
                <li>
                    <strong>First name:</strong>
                    <?php
                    echo $this->userprofile['firstname'];
                    ?>
                </li>
                <?php elseif (isset($this->userprofile['surname']) && $this->userprofile['surname'] !== "") : ?>
                <li>
                    <strong>Last name:</strong>
                    <?php
                    echo $this->userprofile['surname'];
                    ?>
                </li>
                <?php endif; ?>
                <?php
                if (isset($this->userprofile['gender']) && $this->userprofile['gender'] != NULL) :
                ?>
                <li><strong>Gender:</strong> <?php echo $this->userprofile['gender']; ?></li>
                <?php endif; ?>
                <?php 
                if (isset($this->userprofile['country']) && $this->userprofile['country'] != NULL) :
                ?>
                <li><strong>Country:</strong> <a href="<?php echo $this->url(array('controller' => 'account',
                                                             'action' => 'userlist',
                											 'order' => 'username',
                											 'list' => 'asc',
                											 'country' => $this->userprofile['countryIso'],
                                                             'language' => $this->language,
                                                             ),
                                                       'lang_default', true); ?>"><?php echo $this->userprofile['country']; ?></a></li>
                <?php endif; ?>
                <?php 
                if (isset($this->userprofile['city']) && $this->userprofile['city'] != NULL):
                ?>
                <li><strong>Homecity:</strong> <a href="<?php echo $this->url(array('controller' => 'account',
                                                             'action' => 'userlist',
                											 'order' => 'username',
                											 'list' => 'asc',
                											 'city' => $this->userprofile['city'],
                                                             'language' => $this->language,
                                                             ),
                                                       'lang_default', true); ?>"><?php echo $this->userprofile['city']; ?></a></li>
                <?php endif; ?>
                <?php
                if (isset($this->userprofile['address']) && $this->userprofile['address'] != NULL):
                ?>
                <li><strong>Address:</strong> <?php echo $this->userprofile['address']; ?></li>
                <?php endif; ?>
                <?php
                if (isset($this->userprofile['usertimezone']) && $this->userprofile['usertimezone'] != NULL):
                ?>
                <li><strong>Timezone:</strong> <?php echo $this->userprofile['usertimezone']; ?></li>
                <?php endif; ?>
                <?php
                if (isset($this->userprofile['birthday']) && $this->userprofile['birthday'] != NULL):
                ?>
                <?php
				// date_parse_from_format() is not supported in php 5.2.0,
				// date_parse() function seems to work ok as a workaround with older versions.
                $date = date_parse($this->userprofile['birthday']);
                //$date = date_parse_from_format("n/j/Y", $this->userprofile['birthday']);
                if ($date['day'] < 10)
                    $date['day'] = '0'.$date['day'];
                if ($date['month'] < 10)
                    $date['month'] = '0'.$date['month'];
                $birthday = $date['year'].'-'.$date['month'].'-'.$date['day'];
                $birthday = new Zend_Date($birthday, Zend_Date::ISO_8601);
                $birthday = $birthday->toString('dd MMM, yyyy');
                ?>
                <li><strong>Birthday:</strong> <?php echo $birthday; ?></li>
                <?php endif; ?>
                <?php
                if (isset($this->userprofile['phone']) && $this->userprofile['phone'] != NULL):
                ?>
                <li><strong>Phone:</strong> <?php echo $this->userprofile['phone']; ?></li>
                <?php endif; ?>
                <?php
                if (isset($this->userprofile['company']) && $this->userprofile['company'] != NULL):
                ?>
                <li><strong>Employer / Organization:</strong> <?php echo $this->userprofile['company']; ?></li>
                <?php endif; ?>
                <?php
                if (isset($this->userprofile['employment']) && $this->userprofile['employment'] != NULL):
                ?>
                <li><strong>I am:</strong> <?php echo $this->userprofile['employment']; ?></li>
                <?php endif; ?>
            </ul>
        </div>
        <?php if (isset($this->userprofile['biography']) && $this->userprofile['biography'] != NULL && $this->userprofile['biography'] != "") : ?>
        <div id="user-bio">
            <h5>Bio:</h5>
            <p class="biographyrow"><span><?php echo $this->userprofile['biography']; ?></span></p>
            <!--<p><a href="#">(read more)</a></p>-->

            <!--<p class="my-links"><strong>My links:</strong> <a href="#">Facebook</a>, <a href="#">LinkedIN</a>, <a href="#">Blogger</a>, <a href="#">Youtube</a>, <a href="#">Myspace</a></p>-->
        </div>
        <?php endif; ?>
        <?php if (isset($this->userprofile['userWeblinks']) && $this->userprofile['userWeblinks'] != NULL) : ?>
        <div id="user-links">
            <p class="my-links">My links:
                <?php
                $count = count($this->userprofile['userWeblinks']);
                $i = 1;
                foreach ($this->userprofile['userWeblinks'] as $weblink) {
                ?>
                <a href="<?php echo $weblink['url_uwl']; ?>"><?php
                    echo $weblink['name_uwl'];
                ?></a><?php
                if ($i != $count)
                    echo ',';
                $i++;
                }
                ?>
            </p>
        </div>
        <?php endif; ?>
    </div>
    <div class="clear"></div>
    <div id="activity">
    	<?php foreach($this->boxes as $this->box): ?>
			<?php echo $this->partial("partials/account_view_user_box.phtml", $this); ?>
		<?php endforeach; ?>

            <!--
            <div id="comments">
                <h4>Comments</h4>
                <p><strong><a href="#">Login</a> or <a href="#">Sign Up</a> to post a comment</strong></p>

                <div class="comment">
                    <div class="comment-head">
                        <div class="left"><a href="#"><strong>Username</strong></a> | <a href="#"><strong>City</strong></a> (12 Jun 2009)</div>
                        <div class="right"><a href="#">Flag</a> | <a href="#"><strong>Reply</strong></a></div>
                        <div class="clear"></div>
                    </div>
                    <div class="comment-context">
                        <p>In the future many services workes cloud be displaced by artificial intelligence.</p>
                    </div>
                </div>

                <div class="comment">
                    <div class="comment-head">
                        <div class="left"><a href="#"><strong>Username</strong></a> | <a href="#"><strong>City</strong></a> (12 Jun 2009)</div>
                        <div class="right"><a href="#">Flag</a> | <a href="#"><strong>Reply</strong></a></div>
                        <div class="clear"></div>
                    </div>
                    <div class="comment-context">
                        <p>In the future many services workes cloud be displaced by artificial intelligence.</p>
                    </div>
                </div>

                <div class="comment">
                    <div class="comment-head">
                        <div class="left"><a href="#"><strong>Username</strong></a> | <a href="#"><strong>City</strong></a> (12 Jun 2009)</div>
                        <div class="right"><a href="#">Flag</a> | <a href="#"><strong>Reply</strong></a></div>
                        <div class="clear"></div>
                    </div>
                    <div class="comment-context">
                        <p>In the future many services workes cloud be displaced by artificial intelligence.</p>
                    </div>
                </div>

                <div class="comment reply">
                    <div class="comment-head">
                        <div class="left"><a href="#"><strong>Username</strong></a> | <a href="#"><strong>City</strong></a> (12 Jun 2009)</div>
                        <div class="right"><a href="#">Flag</a> | <a href="#"><strong>Reply</strong></a></div>
                        <div class="clear"></div>
                    </div>
                    <div class="comment-context">
                        <p>In the future many services workes cloud be displaced by artificial intelligence.</p>
                    </div>
                </div>

                <div class="comment reply">
                    <div class="comment-head">
                        <div class="left"><a href="#"><strong>Username</strong></a> | <a href="#"><strong>City</strong></a> (12 Jun 2009)</div>
                        <div class="right"><a href="#">Flag</a> | <a href="#"><strong>Reply</strong></a></div>
                        <div class="clear"></div>
                    </div>
                    <div class="comment-context">
                        <p>In the future many services workes cloud be displaced by artificial intelligence.</p>
                    </div>
                </div>

                <div class="comment">
                    <div class="comment-head">
                        <div class="left"><a href="#"><strong>Username</strong></a> | <a href="#"><strong>City</strong></a> (12 Jun 2009)</div>
                        <div class="right"><a href="#">Flag</a> | <a href="#"><strong>Reply</strong></a></div>
                        <div class="clear"></div>
                    </div>
                    <div class="comment-context">
                        <p>In the future many services workes cloud be displaced by artificial intelligence.</p>
                    </div>
                </div>

                <div id="add-comment">
                    <h4>Would you like to comment? <a href="#">Login</a> or <a href="#">Sign Up</a></h4>
                </div>
            </div>
            -->
        <div class="clear"></div>
    </div>

    <div id="advancedsettings-modal">
		<?php echo $this->customLayoutAdvancedForm; ?>
	</div>
</div>