<?php
// User page has new layout but still WIP because edit profile form is not ready.
// Todo:
//      My groups
//      Delete and publish confirm
//      Country and city links ??
//      PartialLoops for contents and order
?>

<?php $this->headScript()->captureStart() ?>
function publishconfirmation(url) {
    var answer = confirm("Publish content?");
    if (answer) {
        alert("Content published");
        window.location = url;
    } else {
        //alert("");
    }
}
function deleteconfirmation(url) {
    var answer = confirm("Delete content?");
    if (answer) {
        alert("Content deleted");
        window.location = url;
    } else {
        //alert("");
    }
}
<?php $this->headScript()->captureEnd(); ?>

<?php
Zend_Layout::getMvcInstance()->setLayout('layout_new');
//$this->headLink()->appendStylesheet($this->baseUrl('/css/style_additions_req.css')); ?>
<?php
    $admin = false;
    if(in_array("admin", $this->logged_user_roles)):
        $admin = true;
?>
<div id="admin_tools">
    <a href="<?php echo $this->url(array('controller' => 'admin',
                                         'action' => 'editroles',
                                         'user' => $this->user['login_name_usr'],
                                         'language' => $this->language),
                                   'lang_default', true); ?>">
        Edit roles of this user
    </a>
</div>
<?php endif; ?>

<div id="user-page" class="wide">
    <div id="profile-meta">
        <img src="<?php echo $this->url(array('controller' => 'account',
                                              'action' => 'profilethumb',
                                              'id' => $this->user['id_usr'],
        									  'thumb' => 'true',
                                              'language' => $this->language),
											  'lang_default', true); ?>" alt="User Image" class="avatar" width="200" />
        <ul>
            <li><strong>Joined:</strong> <?php echo date("d.m.Y H:i", strtotime($this->user['created_usr'])); ?></li>
            <li><strong>Last login:</strong> <?php echo $this->user['last_login_usr'] != null ?
                                date("d.m.Y H:i", strtotime($this->user['last_login_usr'])) :
                                'Never logged in'; ?></li>
            <!-- <li><strong>Page views:</strong> 1,200</li> -->
        </ul>
    </div>
    <div id="profile-info">
        <div id="user-info">
            <div id="connect" class="right">
                <?php if($this->user_edit): ?>
                <div>
                    <a href="<?php echo $this->url(array('controller' => 'account',
                                                         'action' => 'settings',
                                                         'language' => $this->language),
                                                   'lang_default', true); ?>">
                        Edit profile
                    </a>
                </div>
                <div>
                    <a href="<?php echo $this->url(array('controller' => 'account',
                                                         'action' => 'images',
                                                         'language' => $this->language),
                                                   'lang_default', true); ?>">
                        Change profile image
                        </a>
                </div>
                <div>
                    <a href="<?php echo $this->url(array('controller' => 'privmsg',
                                                         'action' => 'index',
                                                         'language' => $this->language),
                                                   'lang_default', true); ?>">
                        Private messages
                        <?php
                        if($this->unread_privmsgs > 0) {
                            echo "(".$this->unread_privmsgs.")";
                        }
                        ?>
                    </a>
                </div>
                <?php else:
                    if($this->authenticated): ?>
                <?php $privatemessage = $this->url(array('controller' => 'privmsg',
                                                     'action' => 'send',
                                                     'language' => $this->language),
                                               'lang_default', true)."/".$this->user['login_name_usr'];
                ?>
                <form><input type="button" value="Send a message" id="send-message" class="submit-button" name="send-message" alt="Send a message" onClick="location.href='<?php echo $privatemessage; ?>'"></form>
                <!--<input type="submit" value="Send a message" id="send-message" class="submit-button" name="send-message" alt="Send a message" />-->
                <?php endif; endif; ?>
            </div>
            <h2><?php echo $this->user['login_name_usr']; ?></h2>
            <ul>
                <?php if((isset($this->userprofile['firstname']) && $this->userprofile['firstname'] !== "") ||
                         (isset($this->userprofile['surname']) && $this->userprofile['surname'] !== "")) : ?>
                <li>
                    <strong>Full name:</strong>
                    <?php
                    // This is always set, so here is needed to check if it is empty
                    if(isset($this->userprofile['firstname']) && $this->userprofile['firstname'] !== "")
                        echo $this->userprofile['firstname']." ";
                    // This is always set, so here is needed to check if it is empty
                    if(isset($this->userprofile['surname']) && $this->userprofile['surname'] !== "")
                              echo $this->userprofile['surname'];
                    ?>
                </li>
                <?php endif; ?>
                <?php //display country TODO: link
                if (isset($this->userprofile['country']) && $this->userprofile['country'] != NULL) :
                ?>
                <li><strong>Country:</strong> <a href="#"><?php echo $this->userprofile['country']; ?></a></li>
                <?php endif; ?>
                <?php //display city TODO: link
                if (isset($this->userprofile['city']) && $this->userprofile['city'] != NULL):
                ?>
                <li><strong>Homecity:</strong> <a href="#"><?php echo $this->userprofile['city']; ?></a></li>
                <?php endif; ?>
                <?php
                if (isset($this->userprofile['birthday']) && $this->userprofile['birthday'] != NULL):
                ?>
                <li><strong>Birthday:</strong> <?php echo $this->userprofile['birthday']; ?></li>
                <?php endif; ?>
                <?php
                if (isset($this->userprofile['phone']) && $this->userprofile['phone'] != NULL):
                ?>
                <li><strong>Phone:</strong> <?php echo $this->userprofile['phone']; ?></li>
                <?php endif; ?>
                <?php
                if (isset($this->userprofile['profession']) && $this->userprofile['profession'] != NULL):
                ?>
                <li><strong>Profession:</strong> <?php echo $this->userprofile['profession']; ?></li>
                <?php endif; ?>
                <?php
                if (isset($this->userprofile['company']) && $this->userprofile['company'] != NULL):
                ?>
                <li><strong>Company:</strong> <?php echo $this->userprofile['company']; ?></li>
                <?php endif; ?>
                <!-- <li><strong>I am:</strong> <a href="#">Working in a private sector</a></li> -->
            </ul>
        </div>
        <?php if (isset($this->userprofile['biography']) && $this->userprofile['biography'] != NULL && $this->userprofile['biography'] != "") : ?>
        <div id="user-bio">
            <h5>Bio:</h5>
            <p><?php echo $this->userprofile['biography'];?></p>
            <!--<p><a href="#">(read more)</a></p>-->

            <!--<p class="my-links"><strong>My links:</strong> <a href="#">Facebook</a>, <a href="#">LinkedIN</a>, <a href="#">Blogger</a>, <a href="#">Youtube</a>, <a href="#">Myspace</a></p>-->
        </div>
        <?php endif; ?>
    </div>
    <div class="clear"></div>
    <div id="activity">
        <div id="my-posts" class="left">
            <h3>My posts</h3>
            <div id="content_type">
                <ul>
                    <li class="all<?php if ($this->type === 0) echo " selected"; ?>">
                        <a href="<?php echo $this->url(array('controller' => 'account',
                                                             'action' => 'view',
                                                             'language' => $this->language,
                                                             'user' => $this->user['login_name_usr']),
                                                       'lang_default', true); ?>">
                            <strong>All</strong>
                            (<?php echo $this->userprofile['contentCounts']['totalCount']; ?>)
                        </a>
                    </li>
                    <li class="challenges<?php if ($this->type === "problem") echo " selected"; ?>">
                        <a href="<?php echo $this->url(array('controller' => 'account',
                                                             'action' => 'view',
                                                             'language' => $this->language,
                                                             'user' => $this->user['login_name_usr'],
                                                             'type' => 'problem'),
                                                       'lang_default', true); ?>">
                            <strong>Challenges</strong>
                            (<?php echo $this->userprofile['contentCounts']['problem']; ?>)
                        </a>
                    </li>
                    <li class="ideas<?php if ($this->type === "idea") echo " selected"; ?>">
                        <a href="<?php echo $this->url(array('controller' => 'account',
                                                             'action' => 'view',
                                                             'language' => $this->language,
                                                             'user' => $this->user['login_name_usr'],
                                                             'type' => 'idea'),
                                                       'lang_default', true); ?>">
                            <strong>Ideas</strong>
                            (<?php echo $this->userprofile['contentCounts']['idea']; ?>)
                        </a>
                    </li>
                    <li class="visions<?php if ($this->type === "finfo") echo " selected"; ?>">
                        <a href="<?php echo $this->url(array('controller' => 'account',
                                                             'action' => 'view',
                                                             'language' => $this->language,
                                                             'user' => $this->user['login_name_usr'],
                                                             'type' => 'finfo'),
                                                       'lang_default', true); ?>">
                            <strong>Visions</strong>
                            (<?php echo $this->userprofile['contentCounts']['finfo']; ?>)
                        </a>
                    </li>
                    <?php if($this->user_edit) : ?>
                    <!-- saved is not in style_new.css so we use all -->
                    <li class="all<?php if ($this->type === "saved") echo " selected"; ?>">
                        <a href="<?php echo $this->url(array('controller' => 'account',
                                                             'action' => 'view',
                                                             'language' => $this->language,
                                                             'user' => $this->user['login_name_usr'],
                                                             'type' => 'saved'),
                                                       'lang_default', true); ?>">
                            <strong>Saved</strong>
                            (<?php echo $this->userprofile['contentCounts']['savedCount']; ?>)
                        </a>
                    </li>
                    <?php endif; ?>
                </ul>
            </div>
            <div class="clear"></div>
            <div class="scroll-box">
                <?php if (!empty($this->authorContents )): ?>
                <ul>
                    <?php foreach($this->authorContents as $content): ?>
                    <?php if($this->type === "saved" && $this->user_edit) {
                              if($content['published_cnt'] != 0)
                                  { continue; }
                          } else {
                              if($this->type !== 0 && $content['key_cty'] !== $this->type)
                                  { continue; }
                          }
                    ?>
                    <?php

                    $contentclass = '';
                    if ($content['key_cty'] === "idea") {
                        $contentclass = "ideas";
                    } elseif ($content['key_cty'] === "problem") {
                        $contentclass = "challenges";
                    } elseif ($content['key_cty'] === "finfo") {
                        $contentclass = "visions";
                    }
                    ?>
                    <li class="<?php echo $contentclass; ?>">
                        <div>
                            <p>
                                <a href="<?php echo $this->url(array('content_id' => $content['id_cnt'],
                                                                     'language' => $this->language),
                                                               'content_shortview', true); ?>">
                                    <?php echo $content['title_cnt']; ?>
                                </a>
                            </p>
                            <p>
                                <?php echo $content['lead_cnt']; ?>
                            </p>
                            <p><strong>Posted</strong>
                               <?php echo date("d.m.Y", strtotime($content['created_cnt'])); ?>
                                <!-- |  <strong>Rating</strong> -->
                               | <strong>Views</strong> <?php echo $content['views']; ?>
                            </p>
                            <?php if ($this->user_edit == true): ?>
                            <p>
                                <b>
                                    <a href="<?php echo $this->url(array('content_id' => $content['id_cnt'],
                                                                         'language' => $this->language),
                                                                   'content_edit', true); ?>">
                                        Edit
                                    </a>
                                </b>
                                <?php if ($this->user_edit == true && $content['published_cnt'] == 0): ?>
                                | <b>
                                    <a href="#" onclick="publishconfirmation('<?php
                                                    echo $this->url(array('language' => $this->language,
                                                                          'content_id' => $content['id_cnt']),
                                                                    'content_publish', true); ?>')">
                                        Publish
                                    </a>
                                </b> |
                                <?php endif; ?>
                                | <b>
                                    <a href="#" onclick="deleteconfirmation('<?php
                                                    echo $this->url(array('language' => $this->language,
                                                                          'content_id' => $content['id_cnt']),
                                                                    'content_remove', true); ?>')">
                                        Delete
                                    </a>
                                </b>
                                <?php if ($content['cntHasCntCountParent'] > 0 || $content['cntHasCntCountChild'] > 0): ?>
                                | <b>
                                    <a href="<?php echo $this->url(array('relatestoid' => $content['id_cnt'],
                                                                         'language' => $this->language),
                                                                   'unlinkcontent', true); ?>">
                                        Edit content links (<?php echo ($content['cntHasCntCountParent'] + $content['cntHasCntCountChild']); ?>)
                                    </a>
                                </b>
                                <?php endif; ?>
                                <?php if ($content['cmpHasCntCount'] > 0): ?>
                                | <b>
                                    <a href="<?php echo $this->url(array('relatestoid' => $content['id_cnt'],
                                                                 'language' => $this->language),
                                                                 'unlinkcampaign', true); ?>">
                                        Edit campaign links (<?php echo $content['cmpHasCntCount']; ?>)
                                    </a>
                                </b>
                                <?php endif; ?>
                            </p>
                            <?php endif; ?>
                        </div>
                    </li>
                    <li id="popup_publish_content_<?php echo $content['id_cnt']; ?>"
                            class="popup" style="display:none;">
                        <!-- Tämä pitää tehdä vielä paremmin -->
                            <?php echo $this->translate('content-publish-confirm'); ?>

                            <br />
                            <br />

                            <a href="<?php echo $this->url(array('language' => $this->language,
                                                                 'content_id' => $content['id_cnt']),
                                                           'content_publish', true); ?>" class="button">
                                <?php echo $this->translate('content-publish'); ?>
                            </a>

                            <a href="#" style="text-decoration: none;" class="button"
                                onclick="popup_close()">
                                <?php echo $this->translate('content-cancel'); ?>
                            </a>
                    </li>
                    <li id="popup_delete_content_<?php echo $content['id_cnt']; ?>"
                            class="popup" style="display:none;">
                            <?php echo $this->translate('content-delete-confirm'); ?>

                            <br />
                            <br />

                            <a href="<?php echo $this->url(array('language' => $this->language,
                                                                 'content_id' => $content['id_cnt']),
                                                           'content_remove', true); ?>" class="button">
                                <?php echo $this->translate('content-delete'); ?>
                            </a>
                            <a href="#" style="text-decoration: none;" class="button"
                                onclick="popup_close()">
                                <?php echo $this->translate('content-cancel'); ?>
                            </a>
                        <!-- Loppuu tähän -->

                    </li>
                    <?php endforeach; ?>
                </ul>
                <?php endif; ?>
            </div>
            <!--
            <div id="comments">
                <h4>Comments</h4>
                <p><strong><a href="#">Login</a> or <a href="#">Sign Up</a> to post a comment</strong></p>

                <div class="comment">
                    <div class="comment-head">
                        <div class="left"><a href="#"><strong>Username</strong></a> | <a href="#"><strong>City</strong></a> (12 Jun 2009)</div>
                        <div class="right"><a href="#">Flag</a> | <a href="#"><strong>Reply</strong></a></div>
                        <div class="clear"></div>
                    </div>
                    <div class="comment-context">
                        <p>In the future many services workes cloud be displaced by artificial intelligence.</p>
                    </div>
                </div>

                <div class="comment">
                    <div class="comment-head">
                        <div class="left"><a href="#"><strong>Username</strong></a> | <a href="#"><strong>City</strong></a> (12 Jun 2009)</div>
                        <div class="right"><a href="#">Flag</a> | <a href="#"><strong>Reply</strong></a></div>
                        <div class="clear"></div>
                    </div>
                    <div class="comment-context">
                        <p>In the future many services workes cloud be displaced by artificial intelligence.</p>
                    </div>
                </div>

                <div class="comment">
                    <div class="comment-head">
                        <div class="left"><a href="#"><strong>Username</strong></a> | <a href="#"><strong>City</strong></a> (12 Jun 2009)</div>
                        <div class="right"><a href="#">Flag</a> | <a href="#"><strong>Reply</strong></a></div>
                        <div class="clear"></div>
                    </div>
                    <div class="comment-context">
                        <p>In the future many services workes cloud be displaced by artificial intelligence.</p>
                    </div>
                </div>

                <div class="comment reply">
                    <div class="comment-head">
                        <div class="left"><a href="#"><strong>Username</strong></a> | <a href="#"><strong>City</strong></a> (12 Jun 2009)</div>
                        <div class="right"><a href="#">Flag</a> | <a href="#"><strong>Reply</strong></a></div>
                        <div class="clear"></div>
                    </div>
                    <div class="comment-context">
                        <p>In the future many services workes cloud be displaced by artificial intelligence.</p>
                    </div>
                </div>

                <div class="comment reply">
                    <div class="comment-head">
                        <div class="left"><a href="#"><strong>Username</strong></a> | <a href="#"><strong>City</strong></a> (12 Jun 2009)</div>
                        <div class="right"><a href="#">Flag</a> | <a href="#"><strong>Reply</strong></a></div>
                        <div class="clear"></div>
                    </div>
                    <div class="comment-context">
                        <p>In the future many services workes cloud be displaced by artificial intelligence.</p>
                    </div>
                </div>

                <div class="comment">
                    <div class="comment-head">
                        <div class="left"><a href="#"><strong>Username</strong></a> | <a href="#"><strong>City</strong></a> (12 Jun 2009)</div>
                        <div class="right"><a href="#">Flag</a> | <a href="#"><strong>Reply</strong></a></div>
                        <div class="clear"></div>
                    </div>
                    <div class="comment-context">
                        <p>In the future many services workes cloud be displaced by artificial intelligence.</p>
                    </div>
                </div>

                <div id="add-comment">
                    <h4>Would you like to comment? <a href="#">Login</a> or <a href="#">Sign Up</a></h4>
                </div>
            </div>
            -->
        </div>
        <div class="right">
            <?php
            /*
            <div id="my_groups">
                <h3>My groups</h3>
                <strong>All</strong> | <strong><a href="#">Member</a></strong> | <strong><a href="#">Admin</a></strong>
                <div class="scroll-box">
                    <ul>
                        <?php foreach($this->usergroups as $usergroup): ?>
                        <?php $groupurl = $this->url(array('groupid' => $usergroup["id_grp"],
                                                           'language' => $this->language),
                                                     'group_shortview', true); ?>
                        <li><a href="<?php echo $groupurl; ?>"><?php echo $usergroup['group_name_grp']; ?></a> <br />
                        <!--154 views--></li>
                        <?php endforeach; ?>
                    </ul>
                    <!--<p><strong><a href="#">See all 23</a></strong></p>-->
                </div>
            </div>
            */
            ?>
        </div>
    </div>
</div>