<?php $this->headScript()->appendFile($this->baseUrl('/js/ContentForm.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/xregexp-min.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/xregexp-unicode-base.js')); ?>

<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>

<?php $previewUrl = $this->url(array('controller' => 'content',
									 'action' => 'preview',
									 'language' => $this->language),
									 'lang_default', true);?>

<?php $this->headScript()->captureStart()?>
// Set javascript variables for accessible in external .js files
var language = '<?php echo $this->language;?>';
var previewUrl = '<?php echo $previewUrl; ?>';
<?php $this->headScript()->captureEnd()?>

<div id="add-content-page" class="narrow left">
	
	<div id="form_content_realcontent" style="display: block">
        <h2>
            <?php echo $this->translate('content-add-'
                                . $this->short_contenttype
                                . '-page-header'
                ); ?>
        </h2>
        <p>
            <?php echo $this->translate('content-add-' 
                                . $this->short_contenttype 
                                . '-p1'
                ); ?>
        </p>
        
        <?php if($this->short_contenttype != "idea"): ?>
        <p>
        <?php echo $this->translate('content-add-' 
                            . $this->short_contenttype 
                            . '-p2'
            ); ?>
        </p>
        <?php endif; ?>
            
        <?php if($this->relatesToId != 0): ?>
            <div id="linked">
                <div class="link-target"><strong>
                    <?php echo $this->translate('content-is-linked-to'); ?>
                </strong></div>
                <?php 
                if($this->relatesToType == "problem") { 
                    $color = "red";
                }
                elseif($this->relatesToType == "finfo") {
                    $color = "yellow";
                }
                elseif($this->relatesToType == "idea") {
                    $color = "green";
                }
                ?>
                
                <div class="linked-<?php echo $this->relatesToType; ?>">
                 
                <!-- 
                <img class="linkedtoimage" src="/images/<?php echo $color; ?>_vertical_line_small.png" alt="<?php echo $color; ?>" />
                -->
                 
                    <a href="<?php echo $this->url(array('content_id' => $this->relatesToId, 
                                                     'language' => $this->language), 
                                                     'content_shortview', true); ?>">
                        <?php
                            if(strlen($this->relatesToHeader) > 68) {
                                $this->relatesToHeader = substr($this->relatesToHeader, 0, 68) . "...";
                            }
                            echo $this->relatesToHeader;
                        ?>
                    </a>
                </div>
                <div class="clear"></div>
            </div>
        <?php endif; ?>
        
        <?php echo $this->form; ?>
        
    </div>
    
    <div id="form_content_previewcontent" style="display: none"></div>
</div>
</div>
<div id="sidebar">

    <?php $contentType = $this->short_contenttype; ?>
    
    
    <div class="box">
	    <h2 class="right_side_title_small">
	        <?php echo $this->translate('content-add-'.$contentType.'-right-box-header'); ?>
	    </h2>
        <div class="box-content">
            <?php // What is this? 
            if($contentType == "problem") {
                ?>
                
                <p>
                    <b><?php echo $this->translate('content-add-problem-right-box-t1'); ?></b><br />
                    <?php echo $this->translate('content-add-problem-right-box-p1'); ?>
                </p>
                <p>
                    <b><?php echo $this->translate('content-add-problem-right-box-t2'); ?></b><br />
                    <?php echo $this->translate('content-add-problem-right-box-p2'); ?>
                </p>
                <p><?php echo $this->translate('content-add-problem-right-box-p3'); ?></p>
                <p><?php echo $this->translate('content-add-problem-right-box-p4'); ?></p>
                <p><?php echo $this->translate('content-add-problem-right-box-p5'); ?></p>
                <p><?php echo $this->translate('content-add-problem-right-box-p6'); ?></p>
                <p>
                    <b><?php echo $this->translate('content-add-problem-right-box-t3'); ?></b><br />
                    <?php echo $this->translate('content-add-problem-right-box-p7'); ?>
                </p>
                <p><?php echo $this->translate('content-add-problem-right-box-p8'); ?></p>
                
                <?php
            }
            elseif($contentType == "finfo") {
                ?>
                
                <p>
                    <b><?php echo $this->translate('content-add-finfo-right-box-t1'); ?></b><br />
                    <?php echo $this->translate('content-add-finfo-right-box-p1'); ?>
                </p>
                <p>
                    <b><?php echo $this->translate('content-add-finfo-right-box-t2'); ?></b><br />
                    <?php echo $this->translate('content-add-finfo-right-box-p2'); ?>
                </p>
                <p><?php echo $this->translate('content-add-finfo-right-box-p3'); ?></p>
                <p><?php echo $this->translate('content-add-finfo-right-box-p4'); ?></p>
                <p>
                    <b><?php echo $this->translate('content-add-finfo-right-box-t3'); ?></b><br />
                    <?php echo $this->translate('content-add-finfo-right-box-p5'); ?>
                </p>
                <p><?php echo $this->translate('content-add-finfo-right-box-p6'); ?></p>
                <p>
                    <b><?php echo $this->translate('content-add-finfo-right-box-t4'); ?></b><br />
                    <?php echo $this->translate('content-add-finfo-right-box-p7'); ?>
                </p>
                <p><?php echo $this->translate('content-add-finfo-right-box-p8'); ?></p>
                
                <?php
            }
            elseif($contentType == "idea") {
                ?>
                
                <p>
                    <b><?php echo $this->translate('content-add-idea-right-box-t1'); ?></b><br />
                    <?php echo $this->translate('content-add-idea-right-box-p1'); ?>
                </p>
                <p>
                    <b><?php echo $this->translate('content-add-idea-right-box-t2'); ?></b><br />
                    <?php echo $this->translate('content-add-idea-right-box-p2'); ?>
                </p>
                <p><?php echo $this->translate('content-add-idea-right-box-p3'); ?></p>
                <p><?php echo $this->translate('content-add-idea-right-box-p4'); ?></p>
                <p><?php echo $this->translate('content-add-idea-right-box-p5'); ?></p>
                <p>
                    <b><?php echo $this->translate('content-add-idea-right-box-t3'); ?></b><br />
                    <?php echo $this->translate('content-add-idea-right-box-p6'); ?>
                </p>
                <p>
                    <b><?php echo $this->translate('content-add-idea-right-box-t4'); ?></b><br />
                    <?php echo $this->translate('content-add-idea-right-box-p7'); ?>
                </p>
                <p><?php echo $this->translate('content-add-idea-right-box-p8'); ?></p>
                
                <?php
            }
            ?>
        </div>
    </div>
