<?php $this->headScript()->appendFile($this->baseUrl . '/js/CheckContentForm.js'); ?>

<?php $this->headScript()->captureStart()?>
function previewRoll(action) {
	if(action == 'open') {
		$("#form_content_realcontent").fadeOut(function(){
			$("#form_preview_content").fadeIn();
		});
	} else if(action == 'close') {
		$("#form_preview_content").fadeOut(function(){
			$("#form_content_realcontent").fadeIn();
		});
	}
}

setTimeout("preCheck('<?php echo $this->language; ?>')", 30);

<?php $this->headScript()->captureEnd()?>
<?php $this->headLink()->appendStylesheet('/css/style_additions_req.css'); ?>

<?php 
if($this->short_contenttype == "problem") {
?>
    <?php $this->headScript()->captureStart() ?>
    setTimeout("changeBack('#d21034')", 300);
    <?php $this->headScript()->captureEnd() ?>
<?php
} else if($this->short_contenttype == "idea") {
?>
    <?php $this->headScript()->captureStart() ?>
    setTimeout("changeBack('#4b9b07')", 300);
    <?php $this->headScript()->captureEnd() ?>
<?php
} else if ($this->short_contenttype == "finfo") {;
?>
   <?php $this->headScript()->captureStart() ?>
   setTimeout("changeBack('#ffc726')", 300);
    <?php $this->headScript()->captureEnd() ?>
<?php
} ?>

<div id="form_content_add_container" style="float: left;">

	<div id="form_preview_content">

            <div style="float: right; margin-right: 60px;">
                <div>
                    <a href="#" onclick="previewRoll('close');">
                        <img src="<?php echo $this->baseUrl('/images/icon_close.png'); ?>"
                            alt="" style="position: absolute;" />
                    </a>
                </div>
                <div>
                    <a href="#" onclick="previewRoll('close');"
                       style="position: absolute; margin-top: 50px; margin-left: -15px;">
                        <?php echo $this->translate('content-add-preview-close'); ?>
                    </a>
                </div>
            </div>

            <h3 style="padding-top: 10px;"><?php echo $this->translate('content-add-preview-header'); ?></h3>

            <div style="clear:both; padding-top: 30px;">

                <div id="content_view_left_p">

                    <div id="content_view_content_p">

                        <div id="content_view_content_container_p" style="padding-top: 10px;">
                            <div class="content_view_texttitle_finfo_p">
                                <h3 style="margin: 0px; padding: 0px; font-weight: bold;" id="preview_header">
                                    Header goes here
                                </h3>
                                <p style="margin: 0px; padding: 0px; font-style: italic;" id="content_view_textlead_item_p">
                                    Textlead goes here
                                </p>
                            </div>

                            <div id="content_view_tags_p" style="padding-top: 7px;">
                                <span class="content_view_bold_p" style="float: left;">
                                    <a href="#">Tags: </a>
                                </span>

                                <div id="content_view_tags_items_p">
                                    <a href="#">Tag</a>
                                </div>
                            </div>

                            <div id="content_view_textbody_p">
                                <p>Textbody goes here</p>
                            </div>
                        </div>

                        <div class="user_content_spacer">
                            <img alt="Massidea.org" src="<?php echo $this->baseUrl('/images/gray_dot_line_500.png'); ?>"/>
                        </div>

                        <div class="content_view_industries_p" id="content_view_industries_p">
                            <h3>Industry classification</h3>
                            <p id="content_view_industries_item_p">Industry goes here</p>
                            <p id="content_view_division_item_p">Division goes here</p>
                            <p id="content_view_group_item_p">Group goes here</p>
                            <p id="content_view_class_item_p">Class goes here</p>
                        </div>

                    </div>

                </div>

                <div class="clear_p"></div>

            </div>
        
	</div>
	
	<div id="form_content_realcontent">
        <h2>
            <?php echo $this->translate('content-add-'
                                . $this->short_contenttype
                                . '-page-header'
                ); ?>
        </h2>
        <p>
            <?php echo $this->translate('content-add-' 
                                . $this->short_contenttype 
                                . '-p1'
                ); ?>
        </p>
        
        <?php if($this->short_contenttype != "idea"): ?>
        <p>
        <?php echo $this->translate('content-add-' 
                            . $this->short_contenttype 
                            . '-p2'
            ); ?>
        </p>
        <?php endif; ?>
            
        <?php
        if($this->relatesToId != 0) {
        ?>
            <div id="linkedto" class="linkedto">
                <p class="linkedtotext">
                    <?php echo $this->translate('content-is-linked-to'); ?>
                </p>
                <?php 
                if($this->relatesToType == "problem") { 
                    $color = "red";
                }
                elseif($this->relatesToType == "finfo") {
                    $color = "yellow";
                }
                elseif($this->relatesToType == "idea") {
                    $color = "green";
                }
                ?>
                
                <div class="<?php echo $this->relatesToType; ?>Line"></div>
                 
                <!-- 
                <img class="linkedtoimage" src="/images/<?php echo $color; ?>_vertical_line_small.png" alt="<?php echo $color; ?>" />
                -->
                 
                <p style="padding-top: 9px;">
                    <a href="<?php echo $this->url(array('content_id' => $this->relatesToId, 
                                                     'language' => $this->language), 
                                                     'content_shortview', true); ?>">
                        <?php
                            if(strlen($this->relatesToHeader) > 68) {
                                $this->relatesToHeader = substr($this->relatesToHeader, 0, 68) . "...";
                            }
                            echo $this->relatesToHeader;
                        ?>
                    </a>
                </p>
            </div>
        <?php
        }
        ?>
        
        <?php echo $this->form; ?>
        
    </div>
    
    <div class="IAmABufferHearMeRoar" style="clear:both; height:100px;"></div>
    
</div>

<div class="right_side" style="padding: 0px; margin-right: 5px; margin-top: 0px;">

    <?php $contentType = $this->short_contenttype; ?>
    
    <p class="right_side_title_small" style="padding-top: 0px; padding-bottom:3px; color:#c0c0c0;">
        <?php echo $this->translate('content-add-'.$contentType.'-right-box-header'); ?>
    </p>
    
    <div class="top_right_box" style="margin-bottom:10px; background: #EEEEEE; width:100%; margin-left:3px; padding:3px;">
        <div>
            <?php // What is this? 
            if($contentType == "problem") {
                ?>
                
                <p>
                    <b><?php echo $this->translate('content-add-problem-right-box-t1'); ?></b><br />
                    <?php echo $this->translate('content-add-problem-right-box-p1'); ?>
                </p>
                <p>
                    <b><?php echo $this->translate('content-add-problem-right-box-t2'); ?></b><br />
                    <?php echo $this->translate('content-add-problem-right-box-p2'); ?>
                </p>
                <p><?php echo $this->translate('content-add-problem-right-box-p3'); ?></p>
                <p><?php echo $this->translate('content-add-problem-right-box-p4'); ?></p>
                <p><?php echo $this->translate('content-add-problem-right-box-p5'); ?></p>
                <p><?php echo $this->translate('content-add-problem-right-box-p6'); ?></p>
                <p>
                    <b><?php echo $this->translate('content-add-problem-right-box-t3'); ?></b><br />
                    <?php echo $this->translate('content-add-problem-right-box-p7'); ?>
                </p>
                <p><?php echo $this->translate('content-add-problem-right-box-p8'); ?></p>
                
                <?php
            }
            elseif($contentType == "finfo") {
                ?>
                
                <p>
                    <b><?php echo $this->translate('content-add-finfo-right-box-t1'); ?></b><br />
                    <?php echo $this->translate('content-add-finfo-right-box-p1'); ?>
                </p>
                <p>
                    <b><?php echo $this->translate('content-add-finfo-right-box-t2'); ?></b><br />
                    <?php echo $this->translate('content-add-finfo-right-box-p2'); ?>
                </p>
                <p><?php echo $this->translate('content-add-finfo-right-box-p3'); ?></p>
                <p><?php echo $this->translate('content-add-finfo-right-box-p4'); ?></p>
                <p>
                    <b><?php echo $this->translate('content-add-finfo-right-box-t3'); ?></b><br />
                    <?php echo $this->translate('content-add-finfo-right-box-p5'); ?>
                </p>
                <p><?php echo $this->translate('content-add-finfo-right-box-p6'); ?></p>
                <p>
                    <b><?php echo $this->translate('content-add-finfo-right-box-t4'); ?></b><br />
                    <?php echo $this->translate('content-add-finfo-right-box-p7'); ?>
                </p>
                <p><?php echo $this->translate('content-add-finfo-right-box-p8'); ?></p>
                
                <?php
            }
            elseif($contentType == "idea") {
                ?>
                
                <p>
                    <b><?php echo $this->translate('content-add-idea-right-box-t1'); ?></b><br />
                    <?php echo $this->translate('content-add-idea-right-box-p1'); ?>
                </p>
                <p>
                    <b><?php echo $this->translate('content-add-idea-right-box-t2'); ?></b><br />
                    <?php echo $this->translate('content-add-idea-right-box-p2'); ?>
                </p>
                <p><?php echo $this->translate('content-add-idea-right-box-p3'); ?></p>
                <p><?php echo $this->translate('content-add-idea-right-box-p4'); ?></p>
                <p><?php echo $this->translate('content-add-idea-right-box-p5'); ?></p>
                <p>
                    <b><?php echo $this->translate('content-add-idea-right-box-t3'); ?></b><br />
                    <?php echo $this->translate('content-add-idea-right-box-p6'); ?>
                </p>
                <p>
                    <b><?php echo $this->translate('content-add-idea-right-box-t4'); ?></b><br />
                    <?php echo $this->translate('content-add-idea-right-box-p7'); ?>
                </p>
                <p><?php echo $this->translate('content-add-idea-right-box-p8'); ?></p>
                
                <?php
            }
            ?>
        </div>
    </div>
</div>