<?php $this->headScript()->appendFile($this->baseUrl . '/js/CheckContentForm.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl . '/js/ContentPreview.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl . '/js/xregexp-min.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl . '/js/xregexp-unicode-base.js'); ?>

<?php $previewUrl = $this->url(array('controller' => 'content',
									 'action' => 'preview',
									 'language' => $this->language),
									 'lang_default', true);?>

<?php $this->headScript()->captureStart()?>
// Set javascript variables for accessible in external .js files
var language = '<?php echo $this->language;?>';
var previewUrl = '<?php echo $previewUrl; ?>';
<?php $this->headScript()->captureEnd()?>

<?php $this->headLink()->appendStylesheet('/css/style_additions_req.css'); ?>

<?php 
    // change background color
    if (isset($this->short_contenttype)) {
	    $this->headScript()->captureStart(); 
	    ?> changeBack('<?php echo $this->short_contenttype; ?>'); <?php
	    $this->headScript()->captureEnd(); 
    }
?>

<div id="form_content_add_container" style="float: left;">
	
	<div id="form_content_realcontent" style="display: block">
        <h2>
            <?php echo $this->translate('content-add-'
                                . $this->short_contenttype
                                . '-page-header'
                ); ?>
        </h2>
        <p>
            <?php echo $this->translate('content-add-' 
                                . $this->short_contenttype 
                                . '-p1'
                ); ?>
        </p>
        
        <?php if($this->short_contenttype != "idea"): ?>
        <p>
        <?php echo $this->translate('content-add-' 
                            . $this->short_contenttype 
                            . '-p2'
            ); ?>
        </p>
        <?php endif; ?>
            
        <?php
        if($this->relatesToId != 0) {
        ?>
            <div id="linkedto" class="linkedto">
                <p class="linkedtotext">
                    <?php echo $this->translate('content-is-linked-to'); ?>
                </p>
                <?php 
                if($this->relatesToType == "problem") { 
                    $color = "red";
                }
                elseif($this->relatesToType == "finfo") {
                    $color = "yellow";
                }
                elseif($this->relatesToType == "idea") {
                    $color = "green";
                }
                ?>
                
                <div class="<?php echo $this->relatesToType; ?>Line"></div>
                 
                <!-- 
                <img class="linkedtoimage" src="/images/<?php echo $color; ?>_vertical_line_small.png" alt="<?php echo $color; ?>" />
                -->
                 
                <p style="padding-top: 9px;">
                    <a href="<?php echo $this->url(array('content_id' => $this->relatesToId, 
                                                     'language' => $this->language), 
                                                     'content_shortview', true); ?>">
                        <?php
                            if(strlen($this->relatesToHeader) > 68) {
                                $this->relatesToHeader = substr($this->relatesToHeader, 0, 68) . "...";
                            }
                            echo $this->relatesToHeader;
                        ?>
                    </a>
                </p>
            </div>
        <?php
        }
        ?>
        
        <?php echo $this->form; ?>
        
    </div>
    
    <div id="form_content_previewcontent" style="display: none"></div>
    
    <div class="IAmABufferHearMeRoar" style="clear:both; height:100px;"></div>
    
</div>

<div class="right_side" style="padding: 0px; margin-right: 5px; margin-top: 0px;">

    <?php $contentType = $this->short_contenttype; ?>
    
    <p class="right_side_title_small" style="padding-top: 0px; padding-bottom:3px; color:#c0c0c0;">
        <?php echo $this->translate('content-add-'.$contentType.'-right-box-header'); ?>
    </p>
    
    <div class="top_right_box" style="margin-bottom:10px; background: #EEEEEE; width:100%; margin-left:3px; padding:3px;">
        <div>
            <?php // What is this? 
            if($contentType == "problem") {
                ?>
                
                <p>
                    <b><?php echo $this->translate('content-add-problem-right-box-t1'); ?></b><br />
                    <?php echo $this->translate('content-add-problem-right-box-p1'); ?>
                </p>
                <p>
                    <b><?php echo $this->translate('content-add-problem-right-box-t2'); ?></b><br />
                    <?php echo $this->translate('content-add-problem-right-box-p2'); ?>
                </p>
                <p><?php echo $this->translate('content-add-problem-right-box-p3'); ?></p>
                <p><?php echo $this->translate('content-add-problem-right-box-p4'); ?></p>
                <p><?php echo $this->translate('content-add-problem-right-box-p5'); ?></p>
                <p><?php echo $this->translate('content-add-problem-right-box-p6'); ?></p>
                <p>
                    <b><?php echo $this->translate('content-add-problem-right-box-t3'); ?></b><br />
                    <?php echo $this->translate('content-add-problem-right-box-p7'); ?>
                </p>
                <p><?php echo $this->translate('content-add-problem-right-box-p8'); ?></p>
                
                <?php
            }
            elseif($contentType == "finfo") {
                ?>
                
                <p>
                    <b><?php echo $this->translate('content-add-finfo-right-box-t1'); ?></b><br />
                    <?php echo $this->translate('content-add-finfo-right-box-p1'); ?>
                </p>
                <p>
                    <b><?php echo $this->translate('content-add-finfo-right-box-t2'); ?></b><br />
                    <?php echo $this->translate('content-add-finfo-right-box-p2'); ?>
                </p>
                <p><?php echo $this->translate('content-add-finfo-right-box-p3'); ?></p>
                <p><?php echo $this->translate('content-add-finfo-right-box-p4'); ?></p>
                <p>
                    <b><?php echo $this->translate('content-add-finfo-right-box-t3'); ?></b><br />
                    <?php echo $this->translate('content-add-finfo-right-box-p5'); ?>
                </p>
                <p><?php echo $this->translate('content-add-finfo-right-box-p6'); ?></p>
                <p>
                    <b><?php echo $this->translate('content-add-finfo-right-box-t4'); ?></b><br />
                    <?php echo $this->translate('content-add-finfo-right-box-p7'); ?>
                </p>
                <p><?php echo $this->translate('content-add-finfo-right-box-p8'); ?></p>
                
                <?php
            }
            elseif($contentType == "idea") {
                ?>
                
                <p>
                    <b><?php echo $this->translate('content-add-idea-right-box-t1'); ?></b><br />
                    <?php echo $this->translate('content-add-idea-right-box-p1'); ?>
                </p>
                <p>
                    <b><?php echo $this->translate('content-add-idea-right-box-t2'); ?></b><br />
                    <?php echo $this->translate('content-add-idea-right-box-p2'); ?>
                </p>
                <p><?php echo $this->translate('content-add-idea-right-box-p3'); ?></p>
                <p><?php echo $this->translate('content-add-idea-right-box-p4'); ?></p>
                <p><?php echo $this->translate('content-add-idea-right-box-p5'); ?></p>
                <p>
                    <b><?php echo $this->translate('content-add-idea-right-box-t3'); ?></b><br />
                    <?php echo $this->translate('content-add-idea-right-box-p6'); ?>
                </p>
                <p>
                    <b><?php echo $this->translate('content-add-idea-right-box-t4'); ?></b><br />
                    <?php echo $this->translate('content-add-idea-right-box-p7'); ?>
                </p>
                <p><?php echo $this->translate('content-add-idea-right-box-p8'); ?></p>
                
                <?php
            }
            ?>
        </div>
    </div>
</div>