<?php $this->headScript()->appendFile($this->baseUrl . '/js/CheckContentForm.js'); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/style_additions_req.css')); ?>

<?php 
    // change background color
    $color = array( 'problem' => '#d21034',
    				'idea' => '#4b9b07',
    				'finfo' => '#ffc726');
    
    if (isset($color[$this->short_contenttype])) {
	    $this->headScript()->captureStart(); 
	    ?> changeBack('<?php echo $color[$this->short_contenttype]; ?>'); <?php
	    $this->headScript()->captureEnd(); 
    }
?>

<div id="form_content_add_container" style="float: left;">	
	<div id="form_content_realcontent">
        <h2>Editing <?php echo $this->short_contenttype . " " . $this->contentHeader; ?></h2>
        <?php echo $this->form; ?>
	</div>
</div>
