<div id="form_content_add_container">
<?php

echo $this->form;

?>
</div>

<div id="popup_preview" class="popup_preview" style="display:none;">
    <div class="popup_text">
        <div class="popup_close">
            <div style="float:right;">
                <a href="#" onclick="popup('popup_preview')"><img src="/images/icon_close.png" alt="" /></a>
            </div>
        </div>
        <div style="clear:both; padding-top: 10px;">
            <div id="content_view_left_p">
                <div id="content_view_content_p">
                    <div id="content_view_content_created_p">
                        <span class="right">Viewed 10 times</span>
                        Added: 2009-07-03 11:49:26
                    </div>
                    <div id="content_view_content_info_container_p">
                        <div id="content_view_content_rating_p">
                            <!-- try changing to class="right"> -->
                            <span>                                         Rating                    0                    </span>
                        </div>		
                        <div id="content_view_content_vote_p">
                            <img src="/images/icon_thumb_up.png" alt="Vote up" />
                            <img src="/images/icon_thumb_down.png" alt="Vote down" />
                        </div>
                    </div>
                    <div id="content_view_content_container_p">
                        <div class="content_view_texttitle_finfo_p">
                            <h1 id="preview_header">header</h1>
                        </div>
                        <div class="content_view_industries_p" id="content_view_industries_p">
                            <p id="content_view_industries_item_p">Industry: Agriculture, foresty and fishing</p>
                            <p id="content_view_division_item_p">Division: Forestry and logging</p>
                        </div>
                    </div>
                    <div id="content_view_textlead_p">
                        <h2 id="content_view_textlead_item_p">Textlead hear</h2>
                    </div>
                    <div id="content_view_textbody_p">
                        Textbody hear
                    </div>
                    <div id="content_view_tags_p">
                        <span class="content_view_bold_p">Tags: </span>
                        <div id="content_view_tags_items_p">
                            <a href="#">Tag</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clear_p"></div>
        </div>
    </div>
</div>