<li class="vision">
    <div class="headline">Headline of the Content</div>
    <div class="author">by Tobias Curth</div>
    <div class="desc">Here are two or three lines of textbox to have a short
        introduction of it‘s content. So maybe you are
        interested in this and go to the post.
    </div>
</li>
<li class="idea">
    <div class="headline">Headline of the Content</div>
    <div class="author">by Tobias Curth</div>
    <div class="desc">Here are two or three lines of textbox to have a short
        introduction of it‘s content. So maybe you are
        interested in this and go to the post.
    </div>
</li>
<li class="challenge">
    <div class="headline">Headline of the Content</div>
    <div class="author">by Tobias Curth</div>
    <div class="desc">Here are two or three lines of textbox to have a short
        introduction of it‘s content. So maybe you are
        interested in this and go to the post.
    </div>
</li>
<li class="idea">
    <div class="headline">Headline of the Content</div>
    <div class="author">by Tobias Curth</div>
    <div class="desc">Here are two or three lines of textbox to have a short
        introduction of it‘s content. So maybe you are
        interested in this and go to the post.
    </div>
</li>
