<select id="content_group" name="content_group" 
    onChange="getItems('<?php echo $this->url(array('controller' => 'content',
                                                    'action' => 'class',
                                                    'language' => $this->language),
                                              'lang_default', true); ?>/group/'+this.value, 
        'content_class_div', this.value)"
    >
    
    <option value="0">
        <?php echo $this->translate("content-add-select-group"); ?>
    </option>
    
    <?php foreach($this->groups as $group): ?>
    <option value="<?php echo $group['id_ind']; ?>">
        <?php echo $group['name_ind']; ?>
    </option>
    <?php endforeach; ?>
    
</select>