<?php if($this->authenticated):?>
        
		<div style="float: left; width: 400px; padding-top: 30px;">
            <?php echo $this->translate('content-index-authenticated-text', $this->language); ?>
        </div>
        
        <div style="float: left; padding: 30px 0px 0px 5px;">
            <img 
                src="<?php echo $this->baseUrl(); ?>/images/<?php echo $this->language; ?>/Add_content_picture.png" 
                alt="<?php echo $this->translate('content-index-image-add',
                                                 $this->language); ?>"
                title="<?php echo $this->translate('content-index-image-add',
                                                   $this->language); ?>"
                usemap="#addcontent"
            />
            <map id="addcontent" name="addcontent">
                <area 
                    shape="rect"
                    coords="9,64,112,143"
                    href="<?php echo $this->url(array(/*'controller' => 'content',
                                                      'action' => 'add',*/
                                                      'language' => $this->language,
                                                      'contenttype' => 'problem'),
                                                'addcnttype', true); ?>"
                    alt="<?php echo $this->translate('content-index-image-add-problem',
                                                     $this->language); ?>"
                    title="<?php echo $this->translate('content-index-image-add-problem',
                                                       $this->language); ?>"
                />
                <area 
                    shape="rect"
                    coords="9,228,112,308"
                    href="<?php echo $this->url(array(/*'controller' => 'content',
                                                      'action' => 'add',*/
                                                      'language' => $this->language,
                                                      'contenttype' => 'finfo'),
                                                'addcnttype', true); ?>"
                    alt="<?php echo $this->translate('content-index-image-add-finfo',
                                                     $this->language); ?>"
                    title="<?php echo $this->translate('content-index-image-add-finfo',
                                                       $this->language); ?>"
                />
            </map>
        </div>
        
<?php else: ?>
        
        <div style="float: left; width: 475px; padding-top: 30px;">
            <?php
            printf($this->translate('content-index-non-authenticated-text',
                          $this->language),
                          $this->url(array('controller' => 'account',
                                           'action' => 'register',
                                           'language' => $this->language),
                                     'lang_default', true),
                          $this->url(array('controller' => 'account',
                                           'action' => 'login',
                                           'language' => $this->language),
                                     'lang_default', true)
            );
            ?>
        </div>
        
        <div style="float: left; padding: 30px 0px 0px 5px;">
            <img 
                src="<?php echo $this->baseUrl(); ?>/images/<?php echo $this->language; ?>/User_steps_vertical.png" 
                alt="<?php echo $this->translate('content-index-image-steps',
                                                 $this->language); ?>"
                title="<?php echo $this->translate('content-index-image-steps',
                                                   $this->language); ?>"
            />
        </div>
		<?php endif; ?>