<?php

if($this->linkingContentType == "problem") {
    $title = $this->translate('content-link-challenge-to');
    $linkedColor = "red";
}
elseif($this->linkingContentType == "finfo") {
    $title = $this->translate('content-link-vision-to');
    $linkedColor = "yellow";
}
elseif($this->linkingContentType == "idea") {
    $title = $this->translate('content-link-idea-to');
    $linkedColor = "green";
}

if($this->relatesToContentContentTypeId == "problem") {
    $title2 = $this->translate('content-link-challenge');
}
elseif($this->relatesToContentContentTypeId == "finfo") {
    $title2 = $this->translate('content-link-vision');
}
elseif($this->relatesToContentContentTypeId == "idea") {
    $title2 = $this->translate('content-link-idea');
}
?>
<div class="linking_content">
<?php
echo "<h3 class=\"recent_posts\">".$title." ".$title2."</h3>";

if($this->relatesToId != 0 && $this->hasUserContents == true) {
?>
    <div id="linkedto" class="linkedto" style="margin-bottom: 10px;">
        <p class="linkedtotext">
            <?php echo $this->translate('content-link-target', 
                                                    $this->language);
            ?>
        </p>
        <?php 
        if($this->relatesToContentContentTypeId == "problem") { 
            $color = "red";
        }
        elseif($this->relatesToContentContentTypeId == "finfo") {
            $color = "yellow";
        }
        elseif($this->relatesToContentContentTypeId == "idea") {
            $color = "green";
        }
        ?>
        <img class="linkedtoimage" src="<?php echo $this->baseUrl."/images/".$color; ?>_vertical_line_small.png" alt="<?php echo $color; ?>" />
        
        <p style="padding-top: 9px;">
            <a href="<?php echo $this->url(array('content_id' => $this->relatesToId, 
                                                     'language' => $this->language), 
                                                     'content_shortview', true); ?>">
                <?php
                    if(strlen($this->relatesToContentTitle) > 68) {
                        $this->relatesToContentTitle = substr($this->relatesToContentTitle, 0, 68) . "...";
                    }
                    echo $this->relatesToContentTitle;
                ?>
            </a>
        </p>
    </div>

    <p style="color: #808080; margin: 10px 0 8px 15px;"><?php echo $this->translate('content-link-helptext'); ?></p>
    <?php
    if($this->contents) {
        foreach($this->contents as $content) {
            if($content['published_cnt'] != 0) {
                ?>
                <div class="form_helptext_line"></div>
                <div style="height: 20px;">
                    <div style="float: left; width: 450px;">
                        <img class="linkedtoimage" src="<?php echo $this->baseUrl."/images/".$linkedColor; ?>_vertical_line_small.png" alt="<?php echo $linkedColor; ?>" height="15" width="4"/>
                        <?php
                        echo "<a href=\"".$this->baseUrl."/".$this->language."/view/".$content['id_cnt']."\">";
                        echo $content['title_cnt'];
                        echo "</a> ";
                        ?>
                        <p style="margin: 4px 0 4px 20px;"><?php echo $content['lead_cnt']; ?></p>
                    </div>
                    <div style="margin-top: 4px;">
                        <?php
                        echo "<a href=\"".$this->baseUrl."/".$this->language."/content/makelinks/"
                        .$this->linkingContentType."/".$this->relatesToId
                        ."/to/".$content['id_cnt']."\">".
                        $this->translate('content-link')."</a>";?>
                    </div>
                </div>
                <div style="clear: both;"></div>
                <?php
            }
        }
    }
} else {
    ?>
    <p><?php echo $this->translate('content-link-not-content-this-type'); ?></p>
    <?php
}
?>
</div>
<div class="right_side" style="padding: 0px; margin-right: 5px; margin-top: 0px;">
    What is content linking?
</div>