<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<?php
if($this->linkingContentType == "problem") {
    $title = $this->translate('content-link-challenge-to');
}
elseif($this->linkingContentType == "finfo") {
    $title = $this->translate('content-link-vision-to');
}
elseif($this->linkingContentType == "idea") {
    $title = $this->translate('content-link-idea-to');
}

if($this->relatesToContentContentType == "problem") {
    $title2 = $this->translate('content-link-challenge');
}
elseif($this->relatesToContentContentType == "finfo") {
    $title2 = $this->translate('content-link-vision');
}
elseif($this->relatesToContentContentType == "idea") {
    $title2 = $this->translate('content-link-idea');
}
?>
<div class="linking">
<h3 class="linking_header"><?php echo $title." ".$title2; ?></h3>
<?php
if($this->relatesToId != 0 && $this->hasUserContents == true) {
?>
    <div id="linked_to">
        <div id="linked_to_where">
            <p class="linking_paragraph"><?php echo $this->translate('content-link-target',
                                                                     $this->language);
            ?></p>
        </div>
        <div class="linked_to_where_<?php echo $this->relatesToContentContentType; ?>">
            <p class="linking_paragraph"><a href="<?php echo $this->url(array('content_id' => $this->relatesToId,
                                                                              'language' => $this->language),
                                                                        'content_shortview', true); ?>">
                    <?php
                        if(strlen($this->relatesToContentTitle) > 68) {
                            $this->relatesToContentTitle = substr($this->relatesToContentTitle, 0, 68) . "...";
                        }
                        echo $this->relatesToContentTitle;
                    ?>
                </a>
            </p>
        </div>
    </div>
    <?php
    if($this->contents) {
        ?> <p class="linking_help_text"><?php echo $this->translate('content-link-helptext'); ?></p> <?php
        foreach($this->contents as $content) {
            if($content['published_cnt'] != 0) {
                ?>
                <div class="linking_dot_line"></div>
                <div class="linking_from">
                    <div class="linking_from_name">
                        <?php
                        $linkurl = $this->url(array('content_id' => $content['id_cnt'],
                                                    'language' => $this->language),
                                              'content_shortview', true);
                        ?>
                        <div class="linking_from_<?php echo $content['key_cty']; ?>">
                            <strong><a href="<?php echo $linkurl; ?>"><?php echo $content['title_cnt']; ?></a></strong>
                            <p class="linking_from_text"><?php echo $content['lead_cnt']; ?></p>
                        </div>
                    </div>
                    <div class="linking_from_link">
                        <?php
                        $linkurl = $this->url(array('contenttype' => $this->linkingContentType,
                                                    'parentid'    => $this->relatesToId,
                                                    'childid'     => $content['id_cnt'],
                                                    'language' => $this->language),
                                              'makecontentlinks', true);
                        ?>
                        <a href="<?php echo $linkurl; ?>"><?php echo $this->translate('content-link'); ?></a>
                    </div>
                </div>
                <div class="clear"></div>
                <?php
            }
        }
        ?> <div class="linking_dot_line"></div> <?php
    } else {
        ?> <p>No contents</p> <?php
    }
} else {
    ?>
    <p><?php echo $this->translate('content-link-not-content-this-type'); ?></p>
    <?php
}
?>
</div>

<div id="sidebar" style="margin-left:20px; margin-right:0;">
    <div class="box">
        <h4>What is content unlinking?</h4>
        <div class="box-content">
            <p><strong></strong><br />
            </p>

            <p><strong></strong><br />
            </p>

            <div class="clear"></div>
        </div>
    </div>
</div>