<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<?php
if($this->linkingContentType == "problem") {
    $title = $this->translate('content-link-challenge-to');
}
elseif($this->linkingContentType == "finfo") {
    $title = $this->translate('content-link-vision-to');
}
elseif($this->linkingContentType == "idea") {
    $title = $this->translate('content-link-idea-to');
}

if($this->relatesToContentContentType == "problem") {
    $title2 = $this->translate('content-link-challenge');
}
elseif($this->relatesToContentContentType == "finfo") {
    $title2 = $this->translate('content-link-vision');
}
elseif($this->relatesToContentContentType == "idea") {
    $title2 = $this->translate('content-link-idea');
}
?>
<div id="content-page-additional-functions" class="narrow">
<h2 class="linking_header"><?php echo $title." ".$title2; ?></h2>
<?php if($this->relatesToId != 0 && $this->hasUserContents == true): ?>
    <div id="linked">
        <div class="link-target">
            <strong><?php echo $this->translate('content-link-target', $this->language); ?></strong>
        </div>
        <div class="linked-<?php echo $this->relatesToContentContentType; ?>">
            <strong><a href="<?php echo $this->url(array('content_id' => $this->relatesToId,
                                                                              'language' => $this->language),
                                                                        'content_shortview', true); ?>">
                    <?php
                        if(strlen($this->relatesToContentTitle) > 68) {
                            $this->relatesToContentTitle = substr($this->relatesToContentTitle, 0, 68) . "...";
                        }
                        echo $this->relatesToContentTitle;
                    ?>
                </a></strong>
        </div>
            <div class="clear"></div>
    </div>
    <?php if($this->contents): ?> 
    	<p class="linking_help_text"><?php echo $this->translate('content-link-helptext'); ?></p>
    	<div id="linking-contents">
    		<ul>
    		<?php foreach($this->contents as $content): ?>
	            <?php if($content['published_cnt'] != 0): ?>
	            <li>
	            	<span class="linked-<?php echo $content['key_cty'];?>">
						<?php
	                        $linkurl = $this->url(array('content_id' => $content['id_cnt'],
	                                                    'language' => $this->language),
	                                              'content_shortview', true);
	                    ?>
	                    <a href="<?php echo $linkurl; ?>"><?php echo $content['title_cnt']; ?></a>
	                    <?php
	                        $linkurl = $this->url(array('contenttype' => $this->linkingContentType,
	                                                    'parentid'    => $this->relatesToId,
	                                                    'childid'     => $content['id_cnt'],
	                                                    'language' => $this->language),
	                                              'makecontentlinks', true);
	                    ?>
	                    <strong><a href="<?php echo $linkurl; ?>"><?php echo $this->translate('content-link'); ?></a></strong>
	                    <div class="clear"></div>
                	</span>
                </li>
                <?php endif ?>
        	<?php endforeach; ?>
        	</ul>
    	</div> 
	<?php else: ?>
        <p>No contents</p>
    <?php endif; ?>
<?php else: ?>
    <p><?php echo $this->translate('content-link-not-content-this-type'); ?></p>
<?php endif; ?>
</div>
</div>
<div id="sidebar" class="left">
    <div class="box">
        <h4>What is content linking?</h4>
        <div class="box-content">
            <p>Combining different contents together boost creativity 
            and increase the likelihood of unexpected findings.</p>

			<p>By linking you can create logical relationships between different contents.</p> 

			<p>You can link your own published content to other users or to your own contents.</p> 

			<p>One content can be linked to multiple contents.</p> 

			<p>If you want, you can remove links later on from your profile page.</p>
            <div class="clear"></div>
        </div>
    </div>