<div class="btn-group pull-right">
	<button class="btn dropdown-toggle" data-toggle="dropdown">
		Category: All
		<span class="caret"></span>
	</button>
	<ul id="filter-category" class="dropdown-menu">
		<?php foreach ($this->categories as $category): ?>
		<li>
			<a rel="<?php echo $category['id_ctg']; ?>" href="#"><?php echo $this->translate($category['title_ctg']); ?></a>
		</li>
		<?php endforeach; ?>
	</ul>
</div>

<h1><?php echo $this->translate('index-challenge')?></h1>
<div><?php echo $this->translate('challenge-list-description')?></div>
<div class="image challenge"></div>

<div id="content-list" class="row push-left"></div>
<a id="load-more">more</a>

<script type="text/javascript"> $(function () { Content.init(); }); </script>
