<?php

$title = '';

if($this->linkingContentType == "problem") {
    $title = $this->translate('content-unlink-from-challenge');
    $linkedColor = "red";
}
elseif($this->linkingContentType == "finfo") {
    $title = $this->translate('content-unlink-from-vision');
    $linkedColor = "yellow";
}
elseif($this->linkingContentType == "idea") {
    $title = $this->translate('content-unlink-from-idea');
    $linkedColor = "green";
}
?>
<div class="linking_content">
<?php
echo "<h3 class=\"recent_posts\">".$title."</h3>";

if($this->contentexists) {
?>
    <div id="linkedto" class="linkedto" style="margin-bottom: 10px;">
        <p class="linkedtotext">
            <?php echo $this->translate('content-unlink-target',
                                                    $this->language);
            ?>
        </p>
        <img class="linkedtoimage" src="<?php echo $this->baseUrl."/images/".$linkedColor; ?>_vertical_line_small.png" alt="<?php echo $linkedColor; ?>" />
        
        <p style="padding-top: 9px;">
            <a href="<?php echo $this->url(array('content_id' => $this->relatesToId, 
                                                     'language' => $this->language), 
                                                     'content_shortview', true); ?>">
                <?php
                    if(strlen($this->relatesToContentTitle) > 68) {
                        $this->relatesToContentTitle = substr($this->relatesToContentTitle, 0, 68) . "...";
                    }
                    echo $this->relatesToContentTitle;
                ?>
            </a>
        </p>
    </div>

    <p style="color: #808080; margin: 10px 0 8px 15px;"><?php echo $this->translate('content-unlink-helptext'); ?></p>
    <?php
    if($this->contents) {
        foreach($this->contents as $key => $contents) {
            foreach ($contents as $content) {
                if($content['published_cnt'] != 0) {
                    ?>
                    <div class="form_helptext_line"></div>
                    <div style="height: 20px;">
                        <div style="float: left; width: 420px;">
                            <?php
                            if($content['key_cty'] == "problem") {
                                $color = "red";
                            }
                            elseif($content['key_cty'] == "finfo") {
                                $color = "yellow";
                            }
                            elseif($content['key_cty'] == "idea") {
                                $color = "green";
                            }
                            ?>
                            <img class="linkedtoimage" src="<?php echo $this->baseUrl."/images/".$color; ?>_vertical_line_small.png" alt="<?php echo $color; ?>" height="15" width="4"/>
                            <?php
                            $linkusr = $this->url(array('controller' => 'account',
                                                        'action' => 'view',
                                                        'user' => $content['username'],
                                                        'language' => $this->language),
                                                  'lang_default', true);
                            $linkurl = $this->url(array('content_id' => $content['id_usr'],
                                                        'language' => $this->language),
                                                  'content_shortview', true);
                            ?>
                            <a href="<?php echo $linkusr; ?>"><?php echo $content['username']; ?></a> : 
                            <a href="<?php echo $linkurl; ?>"><?php echo $content['title_cnt']; ?></a>
                            <p style="margin: 4px 0 4px 20px;"><?php echo $content['lead_cnt']; ?></p>
                        </div>
                        <div style="margin-top: 4px;">
                            <?php
                            if ($key === "parents") {
                                $linkurl = $this->url(array('contenttype' => $this->linkingContentType,
                                                        'childid'     => $content['id_cnt'],
                                                        'parentid'    => $this->relatesToId,
                                                        'language' => $this->language),
                                                  'removecontentlinks', true);
                            } elseif ($key === "childs") {
                                $linkurl = $this->url(array('contenttype' => $this->linkingContentType,
                                                        'childid'     => $this->relatesToId,
                                                        'parentid'    => $content['id_cnt'],
                                                        'language' => $this->language),
                                                  'removecontentlinks', true);
                            }
                            ?>
                            <a href="<?php echo $linkurl; ?>"><?php echo $this->translate('content-unlink'); ?></a>
                        </div>
                    </div>
                    <div style="clear: both;"></div>
                    <?php
                }
            }
        }
    }
} else {
    ?>
    <p><?php echo $this->translate('content-unlink-invalid-relatestoid'); ?></p>
    <?php
}
?>
</div>
<div class="right_side" style="padding: 0px; margin-right: 5px; margin-top: 0px;">
    What is content linking?
</div>