<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<div class="linking">
<h3 class="linking_header"><?php echo $this->translate('content-unlink-title', $this->language); ?></h3>
<?php
if($this->contentexists) {
?>
    <div id="linked_to">
        <div id="linked_to_where">
            <p class="linking_paragraph"><?php echo $this->translate('content-unlink-target',
                                                                     $this->language);
            ?></p>
        </div>
        <div class="linked_to_where_<?php echo $this->linkingContentType; ?>">
            <p class="linking_paragraph"><a href="<?php echo $this->url(array('content_id' => $this->relatesToId,
                                                                              'language' => $this->language),
                                                                        'content_shortview', true); ?>">
                    <?php
                        if(strlen($this->relatesToContentTitle) > 68) {
                            $this->relatesToContentTitle = substr($this->relatesToContentTitle, 0, 68) . "...";
                        }
                        echo $this->relatesToContentTitle;
                    ?>
                </a>
            </p>
        </div>
    </div>
    <?php
    if($this->contents) {
        ?> <p class="linking_help_text"><?php echo $this->translate('content-unlink-helptext'); ?></p> <?php
        foreach($this->contents as $key => $contents) {
            foreach ($contents as $content) {
                if($content['published_cnt'] != 0) {
                    ?>
                    <div class="linking_dot_line"></div>
                    <div class="linking_from">
                        <div class="linking_from_name">
                            <?php
                            $linkusr = $this->url(array('controller' => 'account',
                                                        'action' => 'view',
                                                        'user' => $content['login_name_usr'],
                                                        'language' => $this->language),
                                                  'lang_default', true);
                            $linkurl = $this->url(array('content_id' => $content['id_cnt'],
                                                        'language' => $this->language),
                                                  'content_shortview', true);
                            ?>
                            <div class="linking_from_<?php echo $content['key_cty']; ?>">
                                <a href="<?php echo $linkusr; ?>"><?php echo $content['login_name_usr']; ?></a> :
                                <strong><a href="<?php echo $linkurl; ?>"><?php echo $content['title_cnt']; ?></a></strong>
                                <p class="linking_from_text"><?php echo $content['lead_cnt']; ?></p>
                            </div>
                        </div>
                        <div class="linking_from_link">
                            <?php
                            if ($key === "parents") {
                                $linkurl = $this->url(array('contenttype' => $this->linkingContentType,
                                                        'childid'     => $content['id_cnt'],
                                                        'parentid'    => $this->relatesToId,
                                                        'language' => $this->language),
                                                  'removecontentlinks', true);
                            } elseif ($key === "childs") {
                                $linkurl = $this->url(array('contenttype' => $this->linkingContentType,
                                                        'childid'     => $this->relatesToId,
                                                        'parentid'    => $content['id_cnt'],
                                                        'language' => $this->language),
                                                  'removecontentlinks', true);
                            }
                            ?>
                            <a href="<?php echo $linkurl; ?>"><?php echo $this->translate('content-unlink'); ?></a>
                        </div>
                    </div>
                    <div class="clear"></div>
                    <?php
                }
            }
        }
        ?> <div class="linking_dot_line"></div> <?php
    } else {
        ?> <p>No linked contents</p> <?php
    }
} else {
    ?>
    <p><?php echo $this->translate('content-unlink-invalid-relatestoid'); ?></p>
    <?php
}
?>
</div>

<div id="sidebar" style="margin-left:20px; margin-right:0;">
    <div class="box">
        <h4>What is content unlinking?</h4>
        <div class="box-content">
            <p><strong></strong><br />
            </p>

            <p><strong></strong><br />
            </p>

            <div class="clear"></div>
        </div>
    </div>
</div>