<div class="row content-detail-page">
    <div class="span12">
        <div class="row">
            <div class="span12">
                <h1>Contenttitle</h1>
                <span class="meta-header">by Tobias Curth &sdot; Nov, 12 2012</span>
            </div>
        </div>
        <div class="row">
            <div class="span3">
                <div class="row">
                    <div class="span12">
                        <img src="..." class="img-polaroid">
                    </div>
                </div>
                <div class="row">
                    <div class="span12 meta-information">
                        <span class="meta-information-title">Documents (2)</span>
                        <ul>
                            <li><img src="" alt=""> Introduction.pdf</li>
                            <li><img src="" alt=""> Introduction.pdf</li>
                        </ul>

                        <span class="meta-information-title">Referenzes (1)</span>
                        <ul>
                            <li><img src="" alt=""> Massidea.org</li>
                            <li><img src="" alt=""> Introduction.pdf</li>
                        </ul>

                        <span class="meta-information-title">Category</span>
                        <ul>
                            <li>Environment</li>
                        </ul>

                        <span class="meta-information-title">Tags (1)</span>
                        <ul>
                            <li>Austria</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="span9 content">
                <h2></h2>
                Lorem ipsum dolor le content.
            </div>
        </div>
        <div class="row comments">
            <div class="span12">
                <div class="row">
                    <div class="span6 content-header">Comments (1)</div>
                    <div class="span6">
                        <button class="btn">Write a comment</button>
                    </div>
                </div>

                <div class="row comment">
                    <div class="span3">
                        <img src="..." class="img-polaroid">

                        <div class="meta">
                            <span class="name">Tobias Curth</span>
                            <span class="date">Nov. 12, 2012</span>
                        </div>
                    </div>
                    <div class="span9">Comment lorem ipsum dolor.
                        <span class="reply"><a href="">Reply</a></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>