<div class="row content-detail-page">
    <div class="span12">
        <div class="row margin-bottom">
            <div class="span12">
                <h2><?php echo $this->content['title_cnt']; ?></h2>
                <div class="meta-header">by <?php echo $this->content['login_name_usr']; ?> &sdot; <?php echo $this->content['created_cnt']; ?></div>
            </div>
        </div>
        <div class="row margin-bottom">
            <div class="span2">
                <div class="row ">
                    <div class="span12 margin-bottom">
                        <img src="http://placehold.it/136x104" width="136" height="104" class="img-polaroid">
                    </div>
                </div>
                <div class="row">
                    <div class="span12 meta-information">
                        <span class="meta-information-title">Documents (<?php echo count($this->files); ?>)</span>
                        <ul>
                        <?php foreach($this->files as $file) { ?>
                            <li><a href="#"><img src="/img/icons/pdf.png" alt=""><?php echo $file; ?></a></li>
                        <?php } ?>
                        </ul>

                        <span class="meta-information-title">Category</span>
                        <ul>
                            <li>Environment</li>
                        </ul>

                        <span class="meta-information-title">Tags (1)</span>
                        <ul>
                            <li>Austria</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="span10 content">
                <div class="content-headline"><?php echo $this->content['lead_cnt']; ?></div>
                <?php echo $this->content['body_cnt']; ?>
            </div>
        </div>
        <div class="row comments">
            <div class="span12">
                <div class="row">
                    <div class="span6 comment-header">Comments (<?php echo count($this->comments); ?>)</div>
                    <div class="span6">
                        <button class="btn pull-right">Write a comment</button>
                    </div>
                </div>

                <?php foreach ($this->comments as $comment) { ?>
                    <div class="row comment">
                        <div class="span2 meta">
                            <img src="http://placehold.it/105x80" width="105" height="80" class="img-polaroid">

                            <div class="meta-box">
                                <div class="name"><?php echo $comment['login_name_usr']; ?></div>
                                <div class="date"><?php echo $comment['created_cmt']; ?></div>
                            </div>
                        </div>
                        <div class="span10 comment-content"><?php echo $comment['body_cmt']; ?></div>
                    </div>
                <?php } ?>

                <div class="row reply">
                    <div class="span12">
                        <span><a href="">Reply</a></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>