<div class="row content-detail-page">
    <div class="span12">
        <div class="row margin-bottom">
            <div class="span12">
                <h2>Contenttitle</h2>
                <div class="meta-header">by Tobias Curth &sdot; Nov, 12 2012</div>
            </div>
        </div>
        <div class="row margin-bottom">
            <div class="span2">
                <div class="row ">
                    <div class="span12 margin-bottom">
                        <img src="http://placehold.it/136x104" width="136" height="104" class="img-polaroid">
                    </div>
                </div>
                <div class="row">
                    <div class="span12 meta-information">
                        <span class="meta-information-title">Documents (2)</span>
                        <ul>
                            <li><a href="#"><img src="/img/icons/pdf.png" alt=""> Introduction.pdf</a></li>
                            <li><a href="#"><img src="/img/icons/pdf.png" alt=""> Abstract.pdf</a></li>
                        </ul>

                        <span class="meta-information-title">Referenzes (1)</span>
                        <ul>
                            <li><a href="#"><img src="/img/icons/link.png" alt=""> Massidea.org</a></li>
                        </ul>

                        <span class="meta-information-title">Category</span>
                        <ul>
                            <li>Environment</li>
                        </ul>

                        <span class="meta-information-title">Tags (1)</span>
                        <ul>
                            <li>Austria</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="span10 content">
                <div class="content-headline">Short description.</div>
                Lorem ipsum dolor le content.
            </div>
        </div>
        <div class="row comments">
            <div class="span12">
                <div class="row">
                    <div class="span6 comment-header">Comments (1)</div>
                    <div class="span6">
                        <button class="btn pull-right">Write a comment</button>
                    </div>
                </div>

                <div class="row comment">
                    <div class="span2 meta">
                        <img src="http://placehold.it/105x80" width="105" height="80" class="img-polaroid">

                        <div class="meta-box">
                            <div class="name">Tobias Curth</div>
                            <div class="date">Nov. 12, 2012</div>
                        </div>
                    </div>
                    <div class="span10 comment-content">Comment lorem ipsum dolor.

                    </div>
                </div>
                <div class="row reply">
                    <div class="span12">
                        <span><a href="">Reply</a></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>