<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<div class="row imprint">
    <div class="span6">
        <p>REGISTER DESCRIPTION <br>
            Personal Data Act (523/99) 10 § <br>
            Created: 08.09.2009
        </p>


        <h3><?php echo $this->translate('imprint-register-keeper'); ?></h3>

        <p>
            Laurea University of Applied Sciences <br>
            Vanha maantie 9 <br>
            02650 Espoo, Finland
        </p>

        <h3><?php echo $this->translate('imprint-contact-person'); ?></h3>

        <p>
            Sari Jääskeläinen <br>
            Laurea University of Applied Sciences <br>
            Leppävaara <br>
            Vanha maantie 9, 02650 Espoo, Finland
        </p>

        <h3><?php echo $this->translate('imprint-register-name'); ?></h3>

        <p>
            Massidea.org
        </p>

        <h3><?php echo $this->translate('imprint-purpose-and-use-of-the-register'); ?></h3>

        <p>
           Massidea.org user register and service specific maintenance records
        </p>

        <h3><?php echo $this->translate('imprint-register-content'); ?></h3>

        <p>
        <ul>
            <li><?php echo $this->translate('imprint-customer-data-content'); ?>:</li>
            <li><?php echo $this->translate('imprint-required-information'); ?>(<?php echo $this->translate('imprint-these-must-be-given-in-order-to-register'); ?>):</li>
            <li><?php echo $this->translate('imprint-user-name'); ?></li>
            <li><?php echo $this->translate('imprint-password'); ?></li>
            <li><?php echo $this->translate('imprint-email'); ?></li>
            <li><?php echo $this->translate('imprint-hometown'); ?></li>
        </ul>
        <ul>
            <li><?php echo $this->translate('imprint-status'); ?>:</li>
            <li><?php echo $this->translate('imprint-working-in-private-sector'); ?></li>
            <li><?php echo $this->translate('imprint-working-in-public-sector'); ?></li>
            <li><?php echo $this->translate('imprint-student'); ?></li>
            <li><?php echo $this->translate('imprint-senior-citizen'); ?></li>
            <li><?php echo $this->translate('imprint-other'); ?></li>
        </ul>
        <ul>
            <li><?php echo $this->translate('imprint-in-addition-the-user-may-voluntarily-provide-other-information-such-as'); ?>:</li>
            <li><?php echo $this->translate('imprint-first-name'); ?></li>
            <li><?php echo $this->translate('imprint-last-name'); ?></li>
            <li><?php echo $this->translate('imprint-gender'); ?></li>
            <li><?php echo $this->translate('imprint-date-of-birth'); ?></li>
            <li><?php echo $this->translate('imprint-country-of-residence'); ?></li>
            <li><?php echo $this->translate('imprint-user-interface-language'); ?></li>
            <li><?php echo $this->translate('imprint-biography'); ?></li>
            <li><?php echo $this->translate('imprint-web-links'); ?></li>
            <li><?php echo $this->translate('imprint-position-title'); ?></li>
            <li><?php echo $this->translate('imprint-employer-organization'); ?></li>
            <li><?php echo $this->translate('imprint-time-zone'); ?></li>
            <li><?php echo $this->translate('imprint-openid'); ?></li>
        </ul>
        </p>

        <h3><?php echo $this->translate('imprint-regular-data-sources'); ?></h3>

        <p>
            <?php echo $this->translate('imprint-customer-given-information'); ?>
        </p>

        <p>
            <?php echo $this->translate('imprint-regular-data-transfer-and-disclosure-to-the-eu-and-or-outside-eu'); ?>
        </p>

        <h3><?php echo $this->translate('imprint-data-protection-principles'); ?></h3>

        <p>
            <?php echo $this->translate('imprint-private-customer-information-will-not-be-disclosed-to-a-third-party'); ?>. <br>
            <?php echo $this->translate('imprint-private-information-is-password-protected-and-accessed-only-by-defined-persons'); ?>.
        </p>


        <h3><?php echo $this->translate('imprint-images-and-photos'); ?></h3>

        <p>
            <?php echo $this->translate('imprint-startpage'); ?>: <br>
            <a target="new" href="http://www.softicons.com">http://www.softicons.com</a><br>
            <a target="new" href="http://www.sxc.hu/">http://www.sxc.hu/</a>
        </p>

    </div>
</div>







