<?php if(!empty($this->contentData)): ?>
<div id="contentpagecontainer">
	<div id="content_view_right">
		<div id="content_view_userinfo_container" class="clear">
			<div id="content_view_userinfo_header">
				<?php echo $this->translate('content-view-userheader'); ?>
			</div>
			<div id="content_view_userinfo" class="clear">
			<?php if ($this->user_has_image): ?>
				<div id="content_view_userinfo_image">
					<img src="<?php echo $this->url(array('controller' => 'account', 'action' => 'profilethumb', 'id' => $this->userData['id_usr'], 'language' => $this->language, 'thumb' => 'true'), 'lang_default', true); ?>" alt="User image" width="80" height="80" />
				</div>
			<?php endif; ?>
			<?php //foreach($this->userData as $poster):   Content can be owner by a single user or a single group consisting of many users ?>
            <?php //print_r($this->userData); die; ?>
				<div id="content_view_userinfo_data">
					<div class="user_info_row">
						<span class="content_view_user_info_left">
							<?php echo $this->translate('content-view-author'); ?>
						</span>
						<span class="content_view_user_info_right">
							<a href="<?php echo $this->url(array('controller' => 'account', 'action' => 'view', 
								'user' => $this->userData['login_name_usr'], 'language' => $this->language), 'lang_default', true);?>">
							<span class="bold"><?php echo $this->userData['login_name_usr']; ?></span></a>
						</span>
					</div>
					<div class="user_info_row">
						<span class="content_view_user_info_left">
							<?php echo $this->translate('content-view-joined'); ?>
						</span>
						<span class="content_view_user_info_right">
							<?php 
                                $joinDate = date('d M Y', strtotime($this->content['Content']['Data']['created_cnt']));
                                if ($joinDate != "01 Jan 1970") {
                                    echo date('d M Y', strtotime($this->content['Content']['Data']['created_cnt'])); 
                                } else {
                                    echo $this->translate('content-view-joined-longtime');
                                }
                            ?>
						</span>
					</div>
				</div>
			<?php // endforeach; ?>
			</div>
		</div>
		<div id="content_view_user_related_container" class="clear">
			<div id="content_view_user_related_header">
                <div class="right">
                    <a id="box_more_link" href="#" onclick="cycleMoreBox('content_view_user_related', 'box_more_link');"><img src="/images/icon_plus_tiny.png" alt="" /></a>
                </div>
				<?php echo $this->translate('content-view-user-related'); ?>
			</div>
			<div id="content_view_user_related" style="display:none;">
				<?php foreach($this->moreFromUser as $user_cnt): ?>

                <div id="content_view_user_related_entry_<?php echo $user_cnt['id_cnt']; ?>" class="content_view_user_related_entry_<?php echo $user_cnt['key_cty'];?>">
						<p><a href="<?php echo $this->url(array('content_id' => $user_cnt['id_cnt'], 'language' => $this->language), 'content_shortview', true); ?>"><?php echo stripslashes($user_cnt['title_cnt']); ?></a></p>
						<p><?php echo $this->translate('content-view-user-related-views'); echo $user_cnt['views']; ?></p>
					</div>

                <?php endforeach; ?>
			</div>
		</div>
	</div>
	<div id="content_view_left">
		<div id="content_view_content">
			<div id="content_view_content_created">
				<span class="right"><?php printf($this->translate('content-view-view_times'), $this->views); ?></span>
				<?php echo $this->translate('content-view-added') . $this->contentData['created_cnt']; ?>
			</div>
			<div id="content_view_content_info_container">
				<div id="content_view_content_rating">
					<span>
                    <?php if (isset($this->savedRating)) { echo $this->translate('rating-succesful'); } ?>
                    <?php echo " " . $this->translate('content-rating'); ?>
                    <?php print_r($this->rating); ?>
                    </span>
				</div>		
                <?php if($this->user_can_comment): // if can comment, can also rate ?>
				<div id="content_view_content_vote">
					<a href="?rate=1"><img src="<?php echo Zend_Controller_Front::getInstance()->getBaseUrl(); ?>/images/icon_thumb_up.png" alt="Vote up" /></a>
					<a href="?rate=-1"><img src="<?php echo Zend_Controller_Front::getInstance()->getBaseUrl(); ?>/images/icon_thumb_down.png" alt="Vote down" /></a>
				</div>
                <?php endif; ?>
			</div>				
			<div id="content_view_content_container">
				<div class="content_view_texttitle_<?php echo $this->contentType; ?>">
					<h1><?php echo stripslashes($this->contentData['title_cnt']); ?></h1>
				</div>
                <div class="content_view_industries">
                    <?php if (!empty($this->industries[0])) : ?>
                    <?php echo "<p>"; ?>
                    <?php echo $this->translate('content-add-industry') . ": " . $this->industries[0]; ?> 
                    <?php echo "</p>"; ?>
                    <?php endif; ?>
                    <?php if (!empty($this->industries[1])) : ?>
                    <?php echo "<p>"; ?>
                    <?php echo $this->translate('content-add-division') . ": " . $this->industries[1]; ?>
                    <?php echo "</p>"; ?>
                    <?php endif; ?>
                    <?php if (!empty($this->industries[2])) : ?>
                    <?php echo "<p>"; ?>
                    <?php echo $this->translate('content-add-group') . ": " . $this->industries[2]; ?>
                    <?php echo "</p>"; ?>
                    <?php endif; ?>
                    <?php if (!empty($this->industries[3])) : ?>
                    <?php echo "<p>"; ?>
                    <?php echo $this->translate('content-add-class') . ": " . $this->industries[3]; ?>
                    <?php echo "</p>"; ?>
                    <?php endif; ?> 
                </div>
				<div id="content_view_textlead">
					<h2><?php echo stripslashes($this->contentData['lead_cnt']); ?></h2>
				</div>
					
				<div id="content_view_textbody">
					<?php echo stripslashes(nl2br($this->contentData['body_cnt'])); ?>
				</div>
				<div id="content_view_tags">
					<span class="content_view_bold"><?php echo $this->translate('content-view-tags'); ?></span>
					<?php 
						$i = count($this->tags) - 1;
						foreach($this->tags as $tag):
					?>
						<a href="<?php echo $this->url(array('controller' => 'tag', 'action' => 'view', 
											'id' => $tag['id_tag']), 'lang_default', true); ?>">
							<?php echo stripslashes($tag['name_tag']); ?></a><?php echo $i-- > 0 ? ', ' : '';?>
					<?php endforeach; ?>	
				</div>
                    <?php 
                        if (isset($this->children[0])) :
                            echo '<div class="success">';
                            echo "<h3>" . $this->translate('content-view-solutions-for') . "</h3>";
                            echo "<ul>";
                            foreach ($this->children as $child) : 
                    ?>
                            <li><a href="<?php echo $this->url(array('content_id' => $child['id_cnt'], 'language' => $this->language), 'content_shortview', true); ?>"><?php echo $child['title_cnt']; ?></a><br /></li>
                    <?php 
                            endforeach; 
                            echo "</ul>";
                            echo '</div>';
                        endif;
                    ?>
                    <?php   
                        if (isset($this->parents[0])) :
                            echo '<div class="success">';
                            echo "<h3>".$this->translate('content-view-solution-to')."</h3>";
                            echo "<ul>";
                            foreach ($this->parents as $parent): 
                    ?>
                            <li><a href="<?php echo $this->url(array('content_id' => $parent['id_cnt'], 'language' => $this->language), 'content_shortview', true); ?>"><?php echo $parent['title_cnt']; ?></a><br /></li>
                    <?php 
                            endforeach;
                            echo "</ul>";
                            echo '</div>';
                        endif;
                    ?>
                <div class="message">
                    <?php if($this->user_can_comment): ?>
                    <h3><?php echo $this->translate('content-box-add-header'); ?></h3>
                    <ul>
                        <li><a href="http://oibs2.projects.tamk.fi/en/content/add/idea?relatestoid=<?php echo $this->contentData['id_cnt']; ?>"> <?php echo $this->translate('content-box-add-idea'); ?> </a> </li>
                        <li><a href="http://oibs2.projects.tamk.fi/en/content/add/problem"> <?php echo $this->translate('content-box-add-problem'); ?> </a> </li>
                        <li><a href="http://oibs2.projects.tamk.fi/en/content/add/finfo"> <?php echo $this->translate('content-box-add-futureinfo'); ?> </a> </li>
                    </ul>
                    <?php endif; ?>
                    <?php if(!$this->user_can_comment): ?>
                    <h3><?php echo $this->translate('content-box-join-header'); ?></h3>

                    <p><?php echo $this->translate('content-box-join-message'); ?></p>
                    <?php endif; ?>
                </div>
                <?php
            // not implemented yet.
			//	<div id="content_view_links">
			//		<span class="content_view_bold">?php echo $this->translate('content-view-links'); ?</span>
			//		?php  foreach($this->links as $link): ?
			//			<a href="?php echo $link['url_lnk'] ?">?php echo $link['url_lnk'] ?</a>
			//		?php endforeach; ?
			//	</div>
                ?>
			</div>
		</div>
        <div class="clear"></div>
		<div id="content_view_comments">
			<div id="content_view_comments_header">
			<?php if (count($this->comments) == 1): ?>
				<h1><?php printf($this->translate('content-view-comment'), count($this->comments)); ?></h1>
			<?php elseif (count($this->comments) > 1): ?>
				<h1><?php printf($this->translate('content-view-comments'), count($this->comments)); ?></h1>
			<?php endif; ?>
			</div>
			<?php
				foreach($this->commentPaginator as $comment):
			?>		
            <div class="clear"></div>
			<div id="content_view_comment_<?php echo $comment['id_cmt']; ?>_container" class="content_view_comment_container">
				<div id="content_view_comment_<?php echo $comment['id_cmt']; ?>_username" class="content_view_comment_user">
					<?php //if (isset($userinfo['profile_image_thumb_usr'])): NOT IMPLEMENTED YET
					//	<img src=" echo $this->url(array('controller' => 'account', 'action' => 'profilethumb', 'id' => $userinfo['id_usr']), 'lang_default', true); " alt="User image" width="70" height="80"/>
					// endif; 
                    ?>
					<p class="content_view_comment_username content_view_bold"><?php echo $comment['login_name_usr']; ?></p>
					<p class="content_view_comment_posted content_view_small"><?php echo date('d M Y H:i:s', strtotime($comment['created_cmt'])); ?></p>
				</div>
				<div id="content_view_comment_<?php echo $comment['id_cmt']; ?>" class="content_view_comment">
					<div id="content_view_comment_<?php echo $comment['id_cmt']; ?>_title" class="content_view_comment_title content_view_bold">
						<?php echo $comment['title_cmt']; ?>
					</div>
					<div id="content_view_comment_<?php echo $comment['id_cmt']; ?>_textbody" class="content_view_comment_textbody">
						<?php echo $comment['body_cmt']; ?>
					</div>
				</div>
			</div>
			<?php endforeach; ?>
			<div id="content_view_comment_pagination">
				<?php
                    if (count($this->comments) >> 10) {
                        echo $this->paginationControl($this->commentPaginator, 'Sliding', 'pagination/paginationControl.phtml'); 
                    }
                ?>
			</div>
		</div>        
		<?php if($this->user_can_comment): ?>
		<div id="content_view_comment_form_container">
			<h3><?php echo $this->translate('content-view-comment-add'); ?></h3>
			<?php echo $this->comment_form; ?>
		</div>
		<?php endif; ?>
	</div>
	<div class="clear"></div>
</div>
<?php endif;