<?php // Part of the ajax funtionalities? ?>
<?php $flagCommentUrl = $this->url(array('controller' => 'comment',
										'action' => 'flag',
										'language' => $this->language),
										'lang_default', true); 
?>
<?php $flagContentUrl = $this->url(array('controller' => 'content',
										'action' => 'flag',
										'language' => $this->language),
										'lang_default', true); 
?>
<?php $contentRatingUrl = $this->url(array('controller' => 'ajax',
										   'action' => 'contentrating',
										   'id' => $this->contentData['id_usr'],
										   'language' => $this->language),
										   'lang_default', true);
?>
<?php $moreFromUserUrl = $this->url(array('controller' => 'ajax',
										  'action' => 'morefromuser',
										  'user_id' => $this->contentData['id_usr'],
										  'cnt_id' => $this->contentData['id_cnt'],
										  'language' => $this->language),
										  'lang_default', true); 
?>
<?php $relatedContentUrl = $this->url(array('controller' => 'ajax',
											'action' => 'relatedcontent',
											'id' => $this->contentData['id_cnt'],
											'language' => $this->language),
											'lang_default', true); 
?>

<?php $this->headScript()->captureStart() ?>
function expandCollapse(type) {
	target = "#content_view_"+type+"_related";
	expandButton = ".expand_"+type+"_related";
	if ($(target).is(':hidden')){
		$(expandButton).attr("src", "<?php echo $this->baseUrl('/images/icon_minus_tiny.png');?>");
	} else {
		$(expandButton).attr("src", "<?php echo $this->baseUrl('/images/icon_plus_tiny.png');?>");
	}
	$(target).slideToggle('normal');
}
	
function ajaxLoad_moreRelated(type, url){
	expandButton = ".expand_"+type+"_related";
	target =  "#content_view_"+type+"_related";
	$(expandButton).bind('click', function () { expandCollapse(type); });
	$.ajax({
		async: false,
		beforeSend: function(){
			$(expandButton).attr("src", "<?php echo $this->baseUrl('/images/ajax-loader-black.gif');?>");
		},
		complete: function(){
			$(expandButton).attr("src", "<?php echo $this->baseUrl('/images/icon_minus_tiny.png');?>");
		},
		url: url,
		success: function(result){
			$(target).append(result);
			//$(target).slideToggle('normal');
		}
	});
};
	
$(document).ready(function(){
		ajaxLoad_moreRelated("user", "<?php echo $moreFromUserUrl; ?>");
		ajaxLoad_moreRelated("content", "<?php echo $relatedContentUrl; ?>");
	
		$("#content_view_content_info_container").load("<?php echo $contentRatingUrl; ?>");
		//$("#content_view_favourite").load("?page=add_favourite&format=html");
});

/*
function ajaxLoad_favourite(method){
	$.ajax({
		type: "POST",
		beforeSend: function(){
			if (method == "add") $("#favouriteadd").attr("src", "<?php echo $this->baseUrl('/images/ajax-loader-black.gif');?>");
			if (method == "remove") $("#favouriteremove").attr("src", "<?php echo $this->baseUrl('/images/ajax-loader-black.gif');?>");
		},
		url: "?favourite="+method,
		success: function(result){
			$("#content_view_favourite").html(result);
			$("#current_favourites").animate({backgroundColor: "red"}, 1).animate({backgroundColor: "#ffffff"}, 1400);
		}
	});
};
*/

function ajaxLoad_vote(score){
	$.ajax({
		type: "POST",
		beforeSend: function(){
			if (score == "1") $("#voteup").attr("src", "<?php echo $this->baseUrl('/images/ajax-loader-black.gif');?>");
			if (score == "-1") $("#votedown").attr("src", "<?php echo $this->baseUrl('/images/ajax-loader-black.gif');?>");
		},
		url: "<?php echo $contentRatingUrl; ?>/rate/"+score,
		success: function(result){
			$("#content_view_content_info_container").html(result);
			$("#current_rating").animate({backgroundColor: "green"}, 1).animate({backgroundColor: "#ffffff"}, 1400);
		}
	});
};

/**
*   replyTo
*   
*   Basic function for comment replying
*/
replyTo = function (replyId, username)
{
    // Quote is not necessary
    // var source = $('#unmodified_' + replyId/* + '_textbody'*/).html();
    //var text = '@' + username + ':\n\n'; //'[quote=' + username + ']' + trimmer(source) + '[/quote]\n';
    
    // Apply values
    //$('textarea#comment_message').val(text);
    $('#comment_parent').val(replyId);
    $('#parent_username').val(username);
    $('p#replying_to').html('<?php echo $this->translate('content-view-comment-replying-to'); ?> <b>' + username + '</b>');
    
    // Show "Replying to..." text and "Cancel reply" -link
    $('p#replying_to').show();
    $('a#cancel_reply_link').show();
    
    return false;
}

trimmer = function (str) 
{
    var	str = str.replace(/^\s\s*/, ''),
        ws = /\s/,
        i = str.length;
    while (ws.test(str.charAt(--i)));
    
    return str.slice(0, i + 1);

}

/**
*   cancelReply
*   
*   Basic function for canceling replying
*/
cancelReply = function ()
{
    // Apply values
    $('#comment_parent').val(0);
    $('#parent_username').val('');
    
    // Hide "Replying to..." text and "Cancel reply" -link
    $('p#replying_to').hide();
    $('a#cancel_reply_link').hide();
    
    return false;
}

/**
*   flagAsSpam
*   
*   Basic function for flagging comments as spam
*/
function flagAsSpam(commentId)
{
	var replaceCommentText;
	$.ajax({
		type: "POST",
		url: "<?php echo $flagCommentUrl;?>",
		data: "flaggedid=" + commentId,
		success: function(msg){
			if(msg == '1') { replaceCommentText = '<?php echo $this->translate('content-view-comment-flagged'); ?>'; }
			if(msg == '0') { replaceCommentText = '<?php echo $this->translate('content-view-comment-alreadyflagged'); ?>'; }
			$('#flagSpamLink_'+commentId).replaceWith(replaceCommentText);
		}
	});
}

/**
*   flagContent
*   
*   Basic function for flagging content inappropriate
*/
function flagContent()
{
	var replaceContentText;
	$.ajax({
		type: "POST",
		url: "<?php echo $flagContentUrl;?>",
		data: "flaggedid=<?php echo $this->id;?>",
		success: function(msg){
			if(msg == '1') { replaceContentText = '<?php echo $this->translate('content-view-content-flagged') ?>'; }
			if(msg == '0') { replaceContentText = '<?php echo $this->translate('content-view-content-alreadyflagged') ?>'; }
			$('#flagContentLink').replaceWith(replaceContentText);
		}
	});
}
<?php $this->headScript()->captureEnd(); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/style_additions_req.css')); ?>

<?php 
    // change background color
    if (isset($this->contentType)) {
	    $this->headScript()->captureStart(); 
	    ?> changeBack('<?php echo $this->contentType; ?>'); <?php
	    $this->headScript()->captureEnd(); 
    }
?>

<div style="clear:both;"></div>
        <?php if ($this->contentData['published_cnt'] == 0): ?>
            <h1><?php echo $this->translate('content-view-unpublished'); ?></h1>
        <?php endif; ?>
		<?php echo $this->partial('partials/content_view.phtml', $this);?>

<div class="right_side" style="float: right; padding: 0px; margin: 0px; margin-top: 0px;">
    <p class="right_side_title_small" style="padding: 11px 0px 3px 10px; font-weight: bold;"><?php echo $this->translate('content-view-author'); ?></p>
    <div class="top_right_box" style="margin-bottom:10px;">
            <img src="<?php echo $this->url(array('controller' => 'account',
                                                  'action' => 'profilethumb',
                                                  'id' => $this->userData['id_usr'],
                                                  'language' => $this->language,
                                                  'thumb' => 'true'),
                                            'lang_default', true); ?>" 
                alt="User image" class="profile_image_smallsize" />
		<div style="float: right;">
            <a href="<?php echo $this->url(array('controller' => 'account',
                                                 'action' => 'view', 
                                                 'user' => $this->userData['login_name_usr'],
                                                 'language' => $this->language),
                                                 'lang_default', true);?>">
            <?php echo $this->userData['login_name_usr']; ?></a><br />
            <?php echo $this->translate('content-view-joined'); ?> <?php echo date('d M Y', strtotime($this->userData['created_usr'])); ?>
		</div>
            <br /><br />
            <a href="<?php echo $this->url(array('controller' => 'privmsg',
                                     'action' => 'send',
                                     'language' => $this->language),
                               'lang_default', true); ?>/<?php echo $this->userData['login_name_usr']; ?>">
            <img src="<?php echo $this->baseUrl('/images/button_send_message_' . $this->language); ?>.png" alt="<?php echo $this->translate('account-profile-send-private-message'); ?>" title="<?php echo $this->translate('account-profile-send-private-message'); ?>" />
            </a>

    </div>
    
    <div id="content_view_user_related_header">
        <div class="pointerCursor" style="float: left;">
            <img class="expand_user_related" src="<?php echo $this->baseUrl('/images/icon_plus_tiny.png');?>" alt="" />
            <img class="expand_user_related" src="<?php echo $this->baseUrl('/images/icon_minus_tiny.png');?>" alt="" style="display: none" />
        </div>
        <span style="padding-left: 10px;color: #0089CF; float: left;"><?php echo $this->translate('content-view-user-related'); ?></span>
    </div>
    <div id="content_view_user_related">
    </div>
    <div id="content_view_related_content_header">
        <div class="pointerCursor" style="float: left;">
            <img class="expand_content_related" src="<?php echo $this->baseUrl('/images/icon_plus_tiny.png');?>" alt="" />
            <img class="expand_content_related" src="<?php echo $this->baseUrl('/images/icon_minus_tiny.png');?>" alt="" style="display: none" />
        </div>
        <span style="padding-left: 10px;color: #0089CF; float: left;"><?php echo $this->translate('content-view-related'); ?></span>
    </div>
    <div id="content_view_content_related" style="padding-top: 10px;">
    </div>
</div>
<div style="clear:both;"></div>