<?php // Part of the ajax funtionalities ?>
<?php $flagContentUrl = $this->url(array('controller' => 'content',
										'action' => 'flag',
										'language' => $this->language),
										'lang_default', true); 
?>
<?php $contentRatingUrl = $this->url(array('controller' => 'ajax',
										   'action' => 'contentrating',
										   'id_cnt' => $this->contentData['id_cnt'],
										   'language' => $this->language),
										   'lang_default', true);
?>
<?php $moreFromUserUrl = $this->url(array('controller' => 'ajax',
										  'action' => 'morefromuser',
										  'id_usr' => $this->contentData['id_usr'],
										  'id_cnt' => $this->contentData['id_cnt'],
										  'language' => $this->language),
										  'lang_default', true); 
?>
<?php $relatedContentUrl = $this->url(array('controller' => 'ajax',
											'action' => 'relatedcontent',
											'id_cnt' => $this->contentData['id_cnt'],
											'language' => $this->language),
											'lang_default', true); 
?>

<?php $this->headScript()->captureStart() ?>
more = false;

function expandCollapse(type) {
	var target = "#content_view_"+type+"_related";
	var expandButton = ".expand_"+type+"_related";
	if ($(target).is(':hidden')){
		$(expandButton).attr("src", "<?php echo $this->baseUrl('/images/icon_minus_tiny.png');?>");
	} else {
		$(expandButton).attr("src", "<?php echo $this->baseUrl('/images/icon_plus_tiny.png');?>");
	}
	$(target).slideToggle('normal');
}
	
function ajaxLoad_moreRelated(type, more){
	var expandButton = ".expand_"+type+"_related";
	var targetDiv =  "#content_view_"+type+"_related";
	var url = "";
	if (type == 'user') {
		url = "<?php echo $moreFromUserUrl; ?>";
	} else {
		url = "<?php echo $relatedContentUrl; ?>";
	}
	var data = new Array();
	if (more) { 
		data = { 'more': '1' };
	} else { 
		$(expandButton).bind('click', function () { expandCollapse(type); }); 
	}
	
	$.ajax({
		//async: false,
		beforeSend: function(){
			$(expandButton).attr("src", "<?php echo $this->baseUrl('/images/ajax-loader-black.gif');?>");
		},
		complete: function(){
			$(expandButton).attr("src", "<?php echo $this->baseUrl('/images/icon_minus_tiny.png');?>");
		},
		url: url,
		data: data,
		success: function(result){
			$(targetDiv).html(result);
			$("a[id*='show_more_']").click(function(obj) {
				var more=true;
				obj.preventDefault();
				var type = $(this).attr('id').replace("show_more_", "");
				ajaxLoad_moreRelated(type, more);
			});
		}
	});
};

$(document).ready(function(){
		ajaxLoad_moreRelated("user", false);
		ajaxLoad_moreRelated("content", false);
		$("#content_view_content_info_container").load("<?php echo $contentRatingUrl; ?>");
		//$("#content_view_favourite").load("?page=add_favourite&format=html");
});




/*
function ajaxLoad_favourite(method){
	$.ajax({
		type: "POST",
		beforeSend: function(){
			if (method == "add") $("#favouriteadd").attr("src", "<?php echo $this->baseUrl('/images/ajax-loader-black.gif');?>");
			if (method == "remove") $("#favouriteremove").attr("src", "<?php echo $this->baseUrl('/images/ajax-loader-black.gif');?>");
		},
		url: "?favourite="+method,
		success: function(result){
			$("#content_view_favourite").html(result);
			$("#current_favourites").animate({backgroundColor: "red"}, 1).animate({backgroundColor: "#ffffff"}, 1400);
		}
	});
};
*/

function ajaxLoad_vote(score){
	$.ajax({
		type: "POST",
		beforeSend: function(){
			if (score == "1") $("#voteup").attr("src", "<?php echo $this->baseUrl('/images/ajax-loader-black.gif');?>");
			if (score == "-1") $("#votedown").attr("src", "<?php echo $this->baseUrl('/images/ajax-loader-black.gif');?>");
		},
		url: "<?php echo $contentRatingUrl; ?>/rate/"+score,
		success: function(result){
			$("#content_view_content_info_container").html(result);
			$("#current_rating").animate({backgroundColor: "green"}, 1).animate({backgroundColor: "#ffffff"}, 1400);
		}
	});
};

/**
*   flagContent
*   
*   Basic function for flagging content inappropriate
*/
function flagContent()
{
	var replaceContentText;
	$.ajax({
		type: "POST",
		url: "<?php echo $flagContentUrl;?>",
		data: "flaggedid=<?php echo $this->id;?>",
		success: function(msg){
			if(msg == '1') { replaceContentText = '<?php echo $this->translate('content-view-content-flagged') ?>'; }
			if(msg == '0') { replaceContentText = '<?php echo $this->translate('content-view-content-alreadyflagged') ?>'; }
			$('#flagContentLink').replaceWith(replaceContentText);
		}
	});
}
<?php $this->headScript()->captureEnd(); ?>

<?php $this->headScript()->prependFile($this->baseUrl('/js/comments.js')); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/style_additions_req.css')); ?>

<?php 
    // change background color
    if (isset($this->contentType)) {
	    $this->headScript()->captureStart(); 
	    ?> changeBack('<?php echo $this->contentType; ?>'); <?php
	    $this->headScript()->captureEnd(); 
    }
?>

<div style="clear:both;"></div>
        <?php if ($this->contentData['published_cnt'] == 0): ?>
            <h1><?php echo $this->translate('content-view-unpublished'); ?></h1>
        <?php endif; ?>
		<?php echo $this->partial('partials/content_view.phtml', $this);?>

<div class="right_side" style="float: right; padding: 0px; margin: 0px; margin-top: 0px;">
    <p class="right_side_title_small" style="padding: 11px 0px 3px 10px; font-weight: bold;"><?php echo $this->translate('content-view-author'); ?></p>
    <div class="top_right_box" style="margin-bottom:10px;">
            <img src="<?php echo $this->url(array('controller' => 'account',
                                                  'action' => 'profilethumb',
                                                  'id' => $this->userData['id_usr'],
                                                  'language' => $this->language,
                                                  'thumb' => 'true'),
                                            'lang_default', true); ?>" 
                alt="User image" class="profile_image_smallsize" />
		<div style="float: right;">
            <a href="<?php echo $this->url(array('controller' => 'account',
                                                 'action' => 'view', 
                                                 'user' => $this->userData['login_name_usr'],
                                                 'language' => $this->language),
                                                 'lang_default', true);?>">
            <?php echo $this->userData['login_name_usr']; ?></a><br />
            <?php echo $this->translate('content-view-joined'); ?> <?php echo date('d M Y', strtotime($this->userData['created_usr'])); ?>
		</div>
            <br /><br />
            <a href="<?php echo $this->url(array('controller' => 'privmsg',
                                     'action' => 'send',
                                     'language' => $this->language),
                               'lang_default', true); ?>/<?php echo $this->userData['login_name_usr']; ?>">
            <img src="<?php echo $this->baseUrl('/images/button_send_message_' . $this->language); ?>.png" alt="<?php echo $this->translate('account-profile-send-private-message'); ?>" title="<?php echo $this->translate('account-profile-send-private-message'); ?>" />
            </a>

    </div>
    
    <div id="content_view_user_related_header">
        <div class="pointerCursor" style="float: left;">
            <img class="expand_user_related" src="<?php echo $this->baseUrl('/images/icon_plus_tiny.png');?>" alt="" />
            <img class="expand_user_related" src="<?php echo $this->baseUrl('/images/icon_minus_tiny.png');?>" alt="" style="display: none" />
        </div>
        <span style="padding-left: 10px;color: #0089CF; float: left;"><?php echo $this->translate('content-view-user-related'); ?></span>
    </div>
    <div id="content_view_user_related">
    </div>
    <div id="content_view_related_content_header">
        <div class="pointerCursor" style="float: left;">
            <img class="expand_content_related" src="<?php echo $this->baseUrl('/images/icon_plus_tiny.png');?>" alt="" />
            <img class="expand_content_related" src="<?php echo $this->baseUrl('/images/icon_minus_tiny.png');?>" alt="" style="display: none" />
        </div>
        <span style="padding-left: 10px;color: #0089CF; float: left;"><?php echo $this->translate('content-view-related'); ?></span>
    </div>
    <div id="content_view_content_related" style="padding-top: 10px;">
    </div>
</div>
<div style="clear:both;"></div>