<?php 
	$loginLink = $this->url(array('controller' => 'account',
								'action' => 'login',
								'language' => $this->language),
								'lang_default', true);
	$signupLink = $this->url(array('controller' => 'account',
								'action' => 'register',
								'language' => $this->language),
								'lang_default', true);
?>

<div id="content_view_content_rating">
	<span id="current_rating">
		<div class="content_rating_positive">
			<?php echo $this->rating['positive_percentage'] . '%'; ?>
		</div>
		
		<div class="content_view_content_vote">
	        <?php if($this->hasIdentity): ?>
				<img id="voteup" onclick="ajaxLoad_vote('1');" src="<?php echo $this->baseUrl('/images/icon_thumb_up.png'); ?>" alt="Vote up" />
				<img id="votedown" onclick="ajaxLoad_vote('-1');" src="<?php echo $this->baseUrl('/images/icon_thumb_down.png'); ?>" alt="Vote down" />
			<?php else: ?>
				<img src="<?php echo $this->baseUrl('/images/icon_thumb_up.png'); ?>" alt="Vote up" />
				<img src="<?php echo $this->baseUrl('/images/icon_thumb_down.png'); ?>" alt="Vote down" />
			<?php endif; ?>
		</div>
		
		<div class="content_rating_negative">
			<?php echo $this->rating['negative_percentage'] . '%'; ?>
		</div>
		<div id="content_view_content_rating_total">
			<?php echo '(' . $this->rating['total'] . ' ' . $this->translate('content-rating') . ')'; ?>
		</div>
		
		<?php if(!$this->hasIdentity): ?>
		<div class="content_view_content_vote">
			<span>
				<a href="<?php echo $loginLink;?>">
					<?php echo $this->translate("content-login"); ?>
				</a>
				<?php echo $this->translate("content-or"); ?>
				<a href="<?php echo $signupLink;?>">
					<?php echo $this->translate("content-signup"); ?>
				</a>
				<?php echo $this->translate("content-torate"); ?>
			</span>
		</div>
		<?php endif; ?>
        </span>
</div>