<?php 
	$loginLink = $this->url(array('controller' => 'account',
								'action' => 'login',
								'language' => $this->language),
								'lang_default', true);
	$signupLink = $this->url(array('controller' => 'account',
								'action' => 'register',
								'language' => $this->language),
								'lang_default', true);
?>


		<div class="content_rating_positive left">
			<?php echo $this->rating['positive_percentage'] . '%'; ?>
		</div>
		
		<div class="content_view_content_vote left">
	        <?php if($this->hasIdentity && !$this->userIsOwner): ?>
				<img id="voteup" class="left vote" onclick="ajaxLoad_vote('1');" src="<?php echo $this->baseUrl('/images/icon_thumb_up.png'); ?>" alt="Vote up" />
				<img id="votedown" class="left vote" onclick="ajaxLoad_vote('-1');" src="<?php echo $this->baseUrl('/images/icon_thumb_down.png'); ?>" alt="Vote down" />
			<?php else: ?>
				<img class="left" src="<?php echo $this->baseUrl('/images/icon_thumb_up.png'); ?>" alt="Vote up" />
				<img class="left" src="<?php echo $this->baseUrl('/images/icon_thumb_down.png'); ?>" alt="Vote down" />
			<?php endif; ?>
		</div>
		
		<div class="content_rating_negative left">
			<?php echo $this->rating['negative_percentage'] . '%'; ?>
		</div>
		<div id="content_view_content_rating_total" class="left">
			<?php echo '(' . $this->rating['total'] . ' ' . $this->translate('content-rating') . ')'; ?></div>
		
		<?php if(!$this->hasIdentity): ?>
		<div class="content_view_content_vote left">
				<a id="login_link" href="#">
					<?php echo $this->translate("content-login"); ?>
				</a>
				<?php echo $this->translate("content-or"); ?>
				<a href="<?php echo $signupLink;?>">
					<?php echo $this->translate("content-signup"); ?>
				</a>
				<?php echo $this->translate("content-torate"); ?>
		</div>
		<?php endif; ?>
