<?php if($this->userid != 0): ?>
	<div id="content_view_content_add_favourite" style="padding: 2px;text-align: top;" class="left">
		<?php if(!$this->favourite['is_favourite']):?>
			<div onclick="ajaxLoad_favourite('add');">
				<img id="favouriteadd" style="vertical-align: top;" src="<?php echo $this->baseUrl('/images/icon_fav_on.png'); ?>" alt="Add to favourites" />
				<a href="#" onClick="return false;">
					<?php echo " " . $this->translate('content-favourite-add'); ?>
					to favourites
				</a>
			</div>
		<?php elseif($this->favourite['is_favourite']):?>
			<div onclick="ajaxLoad_favourite('remove');">
				<img id="favouriteremove" style="vertical-align: top;" src="<?php echo $this->baseUrl('/images/icon_fav_off.png'); ?>" alt="Remove from favourites"/>
				<a href="#" onClick="return false;">
					<?php echo " " . $this->translate('content-favourite-remove'); ?>
					from favourites
				</a>
			</div>
		<?php endif; ?>
	</div>
<?php endif;  /* ?>
<span id="content_view_content_favourite" class="left">
	This content has been
		<?php echo $this->translate('content-favourites'); ?>
		<?php echo $this->favourite['total_favourites']; ?>
		times
</span>	
*/