<?php if (isset($this->comments)): ?>
<?php $comments = array(); ?>
	<?php foreach ($this->comments as $comment): ?>
		<?php 	
			$c['parent'] = $comment['id_parent_cmt'];
			$c['id'] = $comment['id_cmt'];
			$c['commentDiv'] = $this->partial('partials/comment_row.phtml', $comment);
			$comments[] = $c; 
		?>
	<?php endforeach;?>
	<?php echo json_encode($comments); ?>
<?php else: ?>
0
<?php endif; ?>