<?php if(count($this->contents)):?>
	<?php foreach($this->contents as $user_cnt): ?>
		<div id="content_view_user_related_entry_<?php echo $user_cnt['id_cnt']; ?>" class="hover-link content_view_user_related_entry_<?php echo $user_cnt['key_cty'];?>" onclick="makeLink(this);">
			<span><a href="<?php echo $this->url(array('content_id' => $user_cnt['id_cnt'], 'language' => $this->language), 'content_shortview', true); ?>"><?php echo stripslashes($user_cnt['title_cnt']); ?></a></span><br />
			<span><?php echo $this->translate('content-view-user-related-views'); echo $user_cnt['views']; ?></span>
		</div>
	<?php endforeach; ?>
	<?php if(count($this->contents) >= 5 && !$this->more): ?>
		<a id="show_more_user" href="">Show more</a>
	<?php endif;?>
<?php else:?>
<?php echo $this->translate('content-view-user-related-nothing'); ?>
<?php endif;?>