<?php $loopround = 0; ?>
<?php foreach($this->relatedContents as $cnt) : ?>
	<div id="content_view_content_related_entry_<?php echo $cnt['id_cnt']; ?>" class="content_view_content_related_entry_<?php echo $cnt['contentType'];?>">
		<span><a href="<?php echo $this->url(array('content_id' => $cnt['id_cnt'], 'language' => $this->language), 'content_shortview', true); ?>"><?php echo stripslashes($cnt['title_cnt']); ?></a></span><br />
		<span><?php echo $this->translate('content-view-user-related-views'); echo $cnt['viewCount']; ?></span>
	</div>
	
	<?php
	$loopround++;
	if ($loopround == 10) // limit view to 10 items
		break;
	?>
<?php endforeach;?>