<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<?php 
$loginLink = $this->url(array('controller' => 'account',
								'action' => 'login',
								'language' => $this->language),
								'lang_default', true);
$signupLink = $this->url(array('controller' => 'account',
								'action' => 'register',
								'language' => $this->language),
								'lang_default', true);
?>
<div id="content-guidlines-page" class="narrow left">    
        <?php if (!$this->authenticated) { ?>
            <h3><a id="login_link" href="#"><?php echo $this->translate("help-login"); ?></a> <?php echo $this->translate("help-or"); ?> <a href="<?php echo $signupLink;?>"><?php echo $this->translate("help-sign-up"); ?></a> <?php echo $this->translate("help-to-add-new-content"); ?>
            </h3>

            <p>
            <?php echo $this->translate("help-guidelines-top1"); ?>

            <a id="login_link" href="#"><?php echo $this->translate("help-login"); ?></a> <?php echo $this->translate("help-or"); ?> <a href="<?php echo $signupLink;?>"><?php echo $this->translate("help-sign-up"); ?></a> <?php echo $this->translate("help-to-add-new-content"); ?>
            </p>

            <p><?php echo $this->translate("help-guidelines-top2"); ?></p>
            
            <div class="user_content_spacer"><img src="<?php echo $this->baseUrl('/images/gray_dot_line_500.png'); ?>" alt="Massidea.org" /></div>

        <?php } ?>

        <h2><?php echo $this->translate('help-guidelines-header'); ?></h2>
        <div class="left">
            <img class="left" style="padding:15px;" src="<?php echo $this->baseUrl('/images/guidelines.png'); ?>" alt="Guidelines" />
            <div class="left" style="width:300px"><?php echo $this->translate('help-guidelines-paragraph1'); ?></div>
        </div>
        <div class="clear"></div>
            <div id="guidline-challenge" class="left">
            	<div class="guidline">
	                <h3><?php echo $this->translate('help-guidelines-header-problem'); ?></h3>
	                <?php echo $this->translate('help-guidelines-paragraph2'); ?>
	                <div class="examples">
	                	<p><a href="#">Read examples</a></p>
	                </div>
                </div>
            </div>
            <div id="guidline-idea" class="left">
            	<div class="guidline">
	                <h3><?php echo $this->translate('help-guidelines-header-idea'); ?></h3>
	                <?php echo $this->translate('help-guidelines-paragraph3'); ?>
	                <div class="examples">
	                	<p><a href="#">Read examples</a></p>
	                </div>
                </div>
            </div>
            <div id="guidline-vision" class="left">
				<div class="guidline">
	                <h3><?php echo $this->translate('help-guidelines-header-finfo'); ?></h3>
	                <?php echo $this->translate('help-guidelines-paragraph4'); ?>
	                <div class="examples">
	                	<p><a href="#">Read examples</a></p>
	                </div>
                </div>
            </div>
        <div class="clear"></div>
        <div>
            <?php echo $this->translate('help-guidelines-paragraph5'); ?>
        </div>
        <div>
            <?php echo $this->translate('help-guidelines-paragraph6'); ?>
        </div>
    </div>
	<div id="sidebar" class="left">
		<div class="box">
	    	<h3><?php echo $this->translate('help-guidelines-right-header'); ?></h3>
	    	<div class="box-content">
	            <?php echo $this->translate('help-guidelines-right-text'); ?>
	        </div>
	   	</div>
	</div>