<div id="help_sidebar">
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'help',
                                                 'action' => 'about',
                                                 'language' => $this->language),
                                           'lang_default', true); ?>"> 
                <?php echo $this->translate('About us'); ?>
            </a>                                    
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'help',
                                                 'action' => 'idea',
                                                 'language' => $this->language),
                                           'lang_default', true); ?>"> 
                <?php echo $this->translate('Where did the idea for massidea.org come from?'); ?>
            </a>                                    
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'help',
                                                 'action' => 'working',
                                                 'language' => $this->language),
                                           'lang_default', true); ?>"> 
                <?php echo $this->translate('How massidea.org is working'); ?>
            </a>                                    
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'help',
                                                 'action' => 'benefits',
                                                 'language' => $this->language),
                                           'lang_default', true); ?>"> 
                <?php echo $this->translate('What are the Benefits for the users'); ?>
            </a>                                    
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'help',
                                                 'action' => 'built',
                                                 'language' => $this->language),
                                           'lang_default', true); ?>"> 
                <?php echo $this->translate('How is Massidea built?'); ?>
            </a>                                    
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'help',
                                                 'action' => 'contact',
                                                 'language' => $this->language),
                                           'lang_default', true); ?>"> 
                <?php echo $this->translate('Contact us'); ?>
            </a>                                    
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'help',
                                                 'action' => 'banner',
                                                 'language' => $this->language),
                                           'lang_default', true); ?>"> 
                <?php echo $this->translate('Download our banner'); ?>
            </a>                                    
        </li>
    </ul>
</div>