<div id="sidebar" class="left">
    <p><a href="<?php echo $this->url(array('controller' => 'help',
                                                 'action' => 'about',
                                                 'language' => $this->language),
                                           'lang_default', true); ?>"> 
                <?php echo $this->translate('About us'); ?>
            </a></p>                                    
    <p><a href="<?php echo $this->url(array('controller' => 'help',
                                                 'action' => 'idea',
                                                 'language' => $this->language),
                                           'lang_default', true); ?>"> 
                <?php echo $this->translate('Where did the idea for massidea.org come from?'); ?>
            </a></p>                                    
   <p><a href="<?php echo $this->url(array('controller' => 'help',
                                                 'action' => 'working',
                                                 'language' => $this->language),
                                           'lang_default', true); ?>"> 
                <?php echo $this->translate('How massidea.org is working'); ?>
            </a></p>                                    
            <p><a href="<?php echo $this->url(array('controller' => 'help',
                                                 'action' => 'benefits',
                                                 'language' => $this->language),
                                           'lang_default', true); ?>"> 
                <?php echo $this->translate('What are the Benefits for the users'); ?>
            </a></p>                                    
            <p><a href="<?php echo $this->url(array('controller' => 'help',
                                                 'action' => 'built',
                                                 'language' => $this->language),
                                           'lang_default', true); ?>"> 
                <?php echo $this->translate('How is Massidea built?'); ?>
            </a></p>
            <p><a href="<?php echo $this->url(array('controller' => 'help',
                                                 'action' => 'contact',
                                                 'language' => $this->language),
                                           'lang_default', true); ?>"> 
                <?php echo $this->translate('Contact us'); ?>
            </a></p>                                    
            <p><a href="<?php echo $this->url(array('controller' => 'help',
                                                 'action' => 'banner',
                                                 'language' => $this->language),
                                           'lang_default', true); ?>"> 
                <?php echo $this->translate('Download our banner'); ?>
            </a></p>                                    
</div>