<script type="text/javascript">

$("document").ready(function () {
	bindEvents();
	setSelectSize();
	$('#cancel-button').click(function() {
		 window.location.href = "<?php echo $this->linkback;?>"; 
	});
	
});

function submitFeeds() {
	$('#feed-form-list > #feed-rows > .feed-row').each(function () {
		url = $(this).html();
		$("#feeds").append($("<option></option>").val(url).html(url));
	});
	$("#feeds > option").attr("selected", "selected"); 
	$('#feed-form').submit();
}

function addFeed(url) {
	var exists = false;
	$('#feed-form-list > #feed-rows > .feed-row').each(function () {
		if ($(this).html() == url) 
				exists = true;
	});
	if (exists) {
		alert("Feed already exists!");
		$('#rss-input-feed-url').val("");
		return true;
	}
	if ($('#feed-form-list').is(':hidden')) $("#feed-form-list").toggle();
	$('#feed-rows').append($('<div class="feed-row"></div>').val(url).html(url));
	bindEvents();
	setSelectSize();
	$('#rss-input-feed-url').val('');
}

function bindEvents() {
	$('#feed-form-list > #feed-rows > .feed-row').each(function() {
		$(this).dblclick(function() {
			removeFeed($(this));					
		});
		$(this).hover(function() { $(this).addClass("feed-row-selected");}, 
					  function() { $(this).removeClass("feed-row-selected"); }
		  );
	});
}

function setSelectSize() {
	var options = $("#feed-form-list > #feed-rows > .feed-row").length;
	if ( options == 0) { 
		$("#feed-form-list").toggle();
	}
}

function removeFeed(obj) {
	$(obj).remove();
	setSelectSize();
}

function validateFeed() {
	var url = $('#rss-input-feed-url').val();
	jsmeta = jQuery.parseJSON($("#jsmetabox").text());
	var isValid = false;
	$.ajax({
		type: "POST",
		async: true,
		url: jsmeta.baseUrl + "/en/ajax/validaterss", //urls.commentUrls[0].postCommentUrl,
		data: { 'url': url },
		success: function(msg) {
			if (msg == '1') {
				addFeed(url)
			} else {
				alert("Feed does not validate!");
				$('#rss-input-feed-url').val("");
			}
		}
	});
}
</script>
<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<?php if(!$this->admin): ?>
	<h2>You are not an admin of selected page</h2>
<?php else:?>
<h2>Feeds for '<?php echo $this->pageTitle; ?>'</h2>
<div id="rss-editfeeds">
	<div id="rss-input-feed">Enter feed URL<br />
	<input id="rss-input-feed-url" type="text" name="feed"/><input id="rss-input-feed-add" class="submit-button" onclick="validateFeed()" type="button" value="Add"/></div><br />
	<div id="rss-list-feeds">
	<form id="feed-form" method="post">
		<div id="feed-form-list">
		<select id="feeds" name="feeds[]" multiple="true" style="display: none">
		</select>
		<div id="feed-rows">
			<?php foreach ($this->urls as $url): ?>
				<div class="feed-row" ondblclick="removeFeed(this);"><?php echo $url['url_rss'];?></div>
			<?php endforeach; ?>
		</div>
		<p>*Double click to remove feed</p>
		</div>
		<input id="submit-feeds" class="submit-button" type="button" value="Save" onclick="submitFeeds();"/>
		<input type="button" id="cancel-button" class="submit-button" value="Cancel"/>
	</form>
	</div>

</div>
<?php endif;?>