<?php
	$cache = $this->cache;
	//Zend_Debug::dump($cache);

	if(!$result = $cache->load($this->cacheIdentifier))
	{
		// Get baseurl
		$baseUrl = $this->absoluteBaseUrl . "/";
		
		// Create a new DOM Document object
		$pDom = new DOMDocument();
		// Set encoding to UTF-8
		$pDom->encoding = ('UTF-8');
		// Enable output to be formatted nicely
		$pDom->formatOutput = true;
		// Create root element 'RSS'
		$pRSS = $pDom->createElement('rss');
		// And set it's 'version' attribute
		$pRSS->setAttribute('version', 0.91);
		// Apply given settings to root element
		$pDom->appendChild($pRSS);
		// Create new element 'channel' inside root element
		$pChannel = $pDom->createElement('channel');
		// Apply
		$pRSS->appendChild($pChannel);
		
		// Create more elements
		$pTitle = $pDom->createElement('title', 'Massidea.org');
		$pLink  = $pDom->createElement('link', $baseUrl);
		$pDesc  = $pDom->createElement('description', $this->translate('rss-generate-description'));
		$pLang  = $pDom->createElement('language', $this->language);
		// And make 'em true
		$pChannel->appendChild($pTitle);
		$pChannel->appendChild($pLink);
		$pChannel->appendChild($pDesc);
		$pChannel->appendChild($pLang);

		// Loop every content item (from the controller)
		foreach($this->contentData as $content) {
			// Create item elements
		    $pItem  = $pDom->createElement('item');
		    $pTitle = $pDom->createElement('title', $content['title_cnt']);
		    $link = $baseUrl . $this->language . "/view/" . $content['id_cnt'];
		    $pLink  = $pDom->createElement('link', $link);
		    $pDesc  = $pDom->createElement('description', $content['lead_cnt']);
	
		    // format date to use RCF-822 standard date syntax
			$formattedDate = date("r", strtotime($content['created_cnt']));
		    $pPubDate = $pDom->createElement('pubDate', $formattedDate);
		    
		    // Apply item elements
		    $pItem->appendChild($pTitle);
		    $pItem->appendChild($pLink);
		    $pItem->appendChild($pDesc);
		    $pItem->appendChild($pPubDate);
		    
		    // Apply items to element 'channel'
		    $pChannel->appendChild($pItem);

		}
		
		$result = $pDom->saveXML();
		$cache->save($result, $this->cacheIdentifier);
	}
	else
	{
		$result = $cache->load($this->cacheIdentifier);
	}
	
	// Set browser header
	header('Content-type: application/rss+xml');
	echo $result;
?> 