<?php
    // param handling
    $tag_list = $this->tag_list;
    $order = $this->order;
    $direction = $this->direction;
    $ctype = $this->ctype;
    $where = $this->where;
    $baseUrl = $this->baseUrl;
    $divider = " | ";
    $list_type = $this->list_type;
?>

<div id="tag_cloud_container">
    <div class="tag_list_type_row">
        <?php
			$cloud = '<a href="' . $this->url(array('list_type' => 'cloud')) . '">' . $this->translate('tag-cloud').'</a>';
			$index = '<a href="' . $this->url(array('list_type' => 'index')) . '">' . $this->translate('tag-index').'</a>';
            if ($list_type == 'cloud') $cloud = $this->translate('tag-cloud');
            if ($list_type == 'index') $index = $this->translate('tag-index');
            
            echo '<h3 style="padding: 0px; margin: 0px;">' . $cloud . $divider . $index . '</h3>';
            ?>
    </div>
    <img src="<?php echo $this->baseUrl('/images/gray_dot_line_720.png');?>" alt="Massidea.org" />
    <div class="tag_alphanum_row" style="padding-top:5px;">
    <?php
    // ignoring case, LIKE() is case insensitive
    $chars = array('All','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','Å','Ä','Ö','#');
    
    foreach ($chars as $char) {
        if ($where != $char && $char != "#" && $char != 'all' && $char != 'All') {
            echo '<a href="' . $this->url(array('where' => $char)) . '">' . $char.'</a>';
            
        } else if ($char == "#" && $where != 'other') {
            echo '<a href="' . $this->url(array('where' => 'other')) . '">#</a>';
        } else if ($where == 'other') {
            echo '<font style="font-weight:bold;">#</font>';
        } else if ($char == 'All' && $where == 'All') {
            echo '<font style="font-weight:bold;">'.$this->translate('tag-all').'</font>';
        } else if ($char == 'All' && $where != 'All') {
        	echo '<a href="' . $this->url(array('where' => $char)) . '">' . $this->translate('tag-all') .'</a>';
        } else {
        	echo '<font style="font-weight:bold;">'.$char.'</font>';
        }
        if ($char != '#') echo $divider;
    }
    
    ?>
    </div>
    <img src="<?php echo $this->baseUrl('/images/gray_dot_line_720.png');?>" alt="Massidea.org" />
    <div class="tag_filters_row" style="padding-top:5px;">
        <div class="tag_filters_left" style="float:left;">
            <?php
            $pre = $this->translate('tag-show')." ";
			$all = '<a href="' . $this->url(array('ctype' => 'all')) . '">' . $this->translate('tag-all').'</a>';
            $problem = '<a href="' . $this->url(array('ctype' => 'problem')) . '">' . $this->translate('tag-problem').'</a>';
            $futureinfo = '<a href="' . $this->url(array('ctype' => 'futureinfo')) . '">' . $this->translate('tag-futureinfo').'</a>';
            $idea = '<a href="' . $this->url(array('ctype' => 'idea')) . '">' . $this->translate('tag-idea').'</a>';
            
            switch ($ctype) {
                case 'problem':
                case 'problems':
                    $problem = '<font style="font-weight:bold;">'.$this->translate('tag-problem').'</font>';
                    break;
                case 'idea':
                case 'ideas':
                    $idea =  '<font style="font-weight:bold;">'.$this->translate('tag-idea').'</font>';
                    break;
                case 'finfo':
                case 'futureinfo':
                case 'future':
                    $futureinfo = '<font style="font-weight:bold;">'.$this->translate('tag-futureinfo').'</font>';
                    break;
                case 'all':
                case 'All':
                default:
                    $all = '<font style="font-weight:bold;">'.$this->translate('tag-all').'</font>';
                    break;
             }
            echo $pre . $all . $divider . $problem . $divider . $futureinfo . $divider . $idea;
            ?>
        </div> <div class="tag_filters_right" style="float: right;">
            <?php
            $pre = $this->translate('tag-sort').": ";
            $name = '<a href="' . $this->url(array('order' => 'name', 'direction' => 'desc')) . '">' . $this->translate('tag-name').'</a> 
                     <a href="' . $this->url(array('order' => 'name', 'direction' => 'desc')) . '"><img src="'.$baseUrl.'/images/icon_desc_enabled.png" title="desc" alt="desc"></a>
                     <a href="' . $this->url(array('order' => 'name', 'direction' => 'asc')) . '"><img src="'.$baseUrl.'/images/icon_asc_enabled.png" title="asc" alt="asc"></a>'; 
            $popularity = '<a href="' . $this->url(array('order' => 'popularity', 'direction' => 'desc')) . '">' . $this->translate('tag-popularity').'</a> 
                           <a href="' . $this->url(array('order' => 'popularity', 'direction' => 'desc')) . '"><img src="'.$baseUrl.'/images/icon_desc_enabled.png" title="desc" alt="desc"></a>
                           <a href="' . $this->url(array('order' => 'popularity', 'direction' => 'asc')) . '"><img src="'.$baseUrl.'/images/icon_asc_enabled.png" title="asc" alt="asc"></a>'; 
            $publication = '<a href="' . $this->url(array('order' => 'creation', 'direction' => 'desc')) . '">' . $this->translate('tag-publication').'</a> 
                            <a href="' . $this->url(array('order' => 'creation', 'direction' => 'desc')) . '"><img src="'.$baseUrl.'/images/icon_desc_enabled.png" title="desc" alt="desc"></a>
                            <a href="' . $this->url(array('order' => 'creation', 'direction' => 'asc')) . '"><img src="'.$baseUrl.'/images/icon_asc_enabled.png" title="asc" alt="asc"></a>';
            
                
            switch ($order) {
                case "name":
                    if ($direction == 'desc') {
                        $name = '<font style="font-weight:bold;">'.$this->translate('tag-name').'</font> <img src="'.$baseUrl.'/images/icon_desc_disabled.png" title="desc" alt="desc"><a href="' . $this->url(array('order' => 'name', 'direction' => 'asc')) . '"><img src="'.$baseUrl.'/images/icon_asc_enabled.png" title="asc" alt="asc"></a>';
                    } else {
                        $name = '<font style="font-weight:bold;">'.$this->translate('tag-name').'</font> <a href="' . $this->url(array('order' => 'name', 'direction' => 'desc')) . '"><img src="'.$baseUrl.'/images/icon_desc_enabled.png" title="desc" alt="desc"></a><img src="'.$baseUrl.'/images/icon_asc_disabled.png" title="desc" alt="desc">';
                    }
                    break;
                case "popularity":
                    if ($direction == 'desc') {
                        $popularity = '<font style="font-weight:bold;">'.$this->translate('tag-popularity').'</font> <img src="'.$baseUrl.'/images/icon_desc_disabled.png" title="desc" alt="desc"><a href="' . $this->url(array('order' => 'popularity', 'direction' => 'asc')) . '"><img src="'.$baseUrl.'/images/icon_asc_enabled.png" title="asc" alt="asc"></a>';
                    } else {
                        $popularity = '<font style="font-weight:bold;">'.$this->translate('tag-popularity').'</font> <a href="' . $this->url(array('order' => 'popularity', 'direction' => 'desc')) . '"><img src="'.$baseUrl.'/images/icon_desc_enabled.png" title="desc" alt="desc"></a><img src="'.$baseUrl.'/images/icon_asc_disabled.png" title="desc" alt="desc">';
                    }
                    break;
                case "creation":
                    if ($direction == 'desc') {
                        $publication = '<font style="font-weight:bold;">'.$this->translate('tag-publication').'</font> <img src="'.$baseUrl.'/images/icon_desc_disabled.png" title="desc" alt="desc"><a href="' . $this->url(array('order' => 'creation', 'direction' => 'asc')) . '"><img src="'.$baseUrl.'/images/icon_asc_enabled.png" title="asc" alt="asc"></a>';
                    } else {
                        $publication = '<font style="font-weight:bold;">'.$this->translate('tag-publication').'</font> <a href="' . $this->url(array('order' => 'creation', 'direction' => 'desc')) . '"><img src="'.$baseUrl.'/images/icon_desc_enabled.png" title="desc" alt="desc"></a><img src="'.$baseUrl.'/images/icon_asc_disabled.png" title="desc" alt="desc">';
                    }
                    break;
            }

            echo $pre . $name . $divider . $popularity . $divider . $publication;
            ?>
        </div>
    </div>
    <img src="<?php echo $this->baseUrl('/images/gray_dot_line_720.png');?>" alt="Massidea.org" />
    <div style="clear:both;"> </div>
	<div id="tag_cloud_container_tags" style="width:720px;">
    <h3><?php if ($where == 'All') { echo $this->translate('tag-all'); } else { echo $where; }?></h3>
    <?php if ($list_type == 'index') echo'<div class="tag_index_col_0" style="text-align: left; width:150px; float: left;">' ?>
    <?php
        $i = 0;                     // keeps track of tag render round
        $j = count($tag_list);      // how many tags are there?
        $limiter = round($j/3, 0);  // let's limit the amount of tags per column (3 cols) so that cols are even(ish) length
        $col = 0;                   // keeps track of which column is current
        
        foreach($tag_list as $tag) {
            $url = $this->url(array('controller' => 'tag',
                            'action' => 'view',
                            'id' => $tag['id_tag'],
                            'language' => $this->language),
                            'lang_default', true);
                            
            if ($list_type == 'cloud') {
                $size = $tag['tag_size'];
                echo ' <a href="'.$url.'" style="font-size:'.$size.'%">'.stripslashes($tag['name_tag']).'</a>';
            } else if ($list_type == 'index') {
                if ($i == $limiter && $col <= 1) {              // max 3 cols!
                    echo '</div>';                              // this div is full, move to next
                    echo '<div class="tag_index_col_'.$i.'" style="text-align: left; width: 225px; float:left; margin-left: 22px;">';  // move to next column
                    $i = 0;
                    $col++;
                }
                $i++;
                echo ' <a href="'.$url.'">'.stripslashes($tag['name_tag']).' (' . $tag['count'] . ')</a><br />';
            }
        }
    ?>
    <?php if ($list_type == 'index') echo'</div>'; ?>
    <div style="clear:both; font-weight: bold; padding-top:20px;">
        <?php 
        if ($where != 'all' && $where != 'All') {
                echo '<a href="' . $this->url(array('where' => 'all')) . '">' . $this->translate('tag-show-all').'</a>'; 
        }
        ?></div>
	</div>
    <img src="<?php echo $this->baseUrl('/images/gray_dot_line_720.png');?>" alt="Massidea.org" />
</div>