<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>

<div id="search_results">
	    <h2 style="width: 450px"> <?php echo $this->translate('tag-view-header'); ?>
	        "<?php echo $this->escape($this->tagName); ?>"
		</h2>
		<div id="selector">
	        <a href="<?php echo $this->url(array('controller' => 'tag',
	        									 'list_type' => 'cloud',
	                                             'language' => $this->language), 
	                                       'lang_default', true); ?>">
	            <?php echo $this->translate('tag-view-cloudmsg'); ?>
	        </a>
	         | 
	        <a href="<?php echo $this->url(array('controller' => 'tag',
	        									'list_type' => 'index',
	                                             'language' => $this->language), 
	                                       'lang_default', true); ?>">
	            <?php echo $this->translate('tag-view-indexmsg'); ?>
	        </a>
	        <?php /* ?>
	         |
	        <a href="<?php echo $this->url(array('controller' => 'tag',
	                                             'language' => $this->language), 
	                                       'lang_default', true); ?>">
	            <?php echo $this->translate('tag-view-companymsg'); ?>
	        </a>
	         <?php */ ?>
        </div>
    
    <div class="clear"></div>

    <div class="column">
    	<div class="search_info">
    		<!-- <img class="left" src="<?php echo $this->baseUrl('/images/no_profile_img_placeholder.gif'); ?>" width=45 height=45/>  -->
			<h2><?php echo $this->translate('tag-view-contents');?> </h2>
    		<p><?php echo $this->translate('tag-view-contents-intro');?></p>
		</div>
	    <ul id="contents">
	    <?php foreach($this->content as $content): ?>
	    	<?php if($content['id_cnt'] != null): ?>
		     	<li class="<?php echo $content['key_cty']; ?>">
		                <span><a href="<?php echo $this->url(array('content_id' => $content['id_cnt'], 
		                                                     'language' => $this->language), 
		                                                	 'content_shortview', true); ?>">
		                    <?php echo $this->escape($content['title_cnt']); ?>
		                </a><br />
		                    <?php echo $this->escape($content['lead_cnt']); ?>
		                </span>
		        </li>
	        <?php endif; ?>
	    <?php endforeach; ?>
	    </ul>
	</div>

    <div class="column">
		<?php /* ?>
    	<div class="search_info">
    		<!-- <img class="left" src="<?php echo $this->baseUrl('/images/no_profile_img_placeholder.gif'); ?>" width=45 height=45/>  -->
    		<h2><?php echo $this->translate('tag-view-campaigns-groups');?> </h2>
	   		<p><?php echo $this->translate('tag-view-campaigns-groups-intro');?></p>
		</div>
	    <ul id="contents">
	    </ul>
		<?php */ ?>
	</div>

    <div class="column">
    	<?php /* ?>
    	<div class="search_info">
    		<!-- <img class="left" src="<?php echo $this->baseUrl('/images/no_profile_img_placeholder.gif'); ?>" width=45 height=45/>  -->
			<h2><?php echo $this->translate('tag-view-users');?> </h2>
    		<p><?php echo $this->translate('tag-view-users-intro');?></p>
		</div>
	    <ul id="contents">
	    </ul>
	    <?php */ ?>
	</div>
    <div class="clear"></div>
</div>