<aside id="page-sidebar">
	<div class="matchMaking">
        <div class="input-prepend input-append ">
            <input class="span2" id="searchbar" placeholder="Search..." type="text">
            <span class="icon search "></span>
        </div>

    <div>
    <div class="accordion" id="accordion2">
        <div class="accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                   Collapsible Group Item #1
                </a>
            </div>
            <div id="collapseOne" class="accordion-body collapse in">
                <a class="accordion-inner" href="#">
                    <div class="right-arrow">
                        <div class="image idea pull-left"></div>
                        <div class="content-search pull-right">fjldskjflkdsjfksdklfjsdl kjf kdsjfksdjkl jdsklf jkdsjfkldsjfkjds f
                            sfkldsj flskdjflkjdsflkjds kdsjdsfjkdsjfj  kdsfjksdfjjdsfjdslkf dslkjdsfsdj fl</div>
                        <div class="clearfix"></div>
                    </div>

                </a>
            </div>
        </div>
        <div class="accordion-group">
            <div class="accordion-heading">

                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                    Collapsible Group Item #2
                </a>
            </div>
            <div id="collapseTwo" class="accordion-body collapse">
                <a class="accordion-inner" href="#">
                   <div class="right-arrow">
                       <div class="image idea pull-left"></div>
                        <div class="content-search pull-right">fjldskjflkdsjfksdklfjsdl kjf kdsjfksdjkl jdsklf jkdsjfkldsjfkjds f
                         sfkldsj flskdjflkjdsflkjds kdsjdsfjkdsjfj  kdsfjksdfjjdsfjdslkf dslkjdsfsdj fl</div>
                    <div class="clearfix"></div>
                   </div>

                </a>
                <a class="accordion-inner" href="#">
                <div class="right-arrow">
                    <div class="image idea pull-left"></div>
                    <div class="content-search pull-right">fjldskjflkdsjfksdklfjsdl kjf kdsjfksdjkl jdsklf jkdsjfkldsjfkjds f
                        sfkldsj flskdjflkjdsflkjds kdsjdsfjkdsjfj  kdsfjksdfjjdsfjdslkf dslkjdsfsdj fl</div>
                    <div class="clearfix"></div>
                </div>

                </a>
            </div>
        </div>
    </div>
        </div>
    </div>
</aside>
