<h1><?php echo $this->translate('privmsg-messages'); ?></h1>
<br />
<?php $this->headScript()->captureStart() ?>
$(document).ready(function() {
	$("input[type=button][value=Reply]").click(function() {
		url = "<?php echo $this->baseUrl("/".$this->language."/privmsg/send/")?>" + $(this).attr('id').replace(/replyto-/, "");
		location.href = url;
	});
});
<?php $this->headScript()->captureEnd() ?>
<?php
if($this->privmsgs):
?>

<!-- A form for deleting the selected messages -->
<form name="delete_privmsgs" id="delete_privmsgs" action="#" method="post">
	<input type="hidden" name="delete_action" value="1" />
	<input type="hidden" name="delete_first" value="<?php echo $this->privmsgs[0]['id_pmg']; ?>" />
	<input type="hidden" name="delete_last" value="<?php echo $this->privmsgs[count($this->privmsgs)-1]['id_pmg']; ?>" />
	<div style="padding: 0px 0px 5px 0px;">
		<input type="checkbox" name="select_all" id="select_all" onclick="selectAllPrivmsgs(); return true;" />
		<a href="javascript: void(0)" onclick="document.delete_privmsgs.submit(); return false;">
			<?php echo $this->translate('privmsg-delete-selected'); ?>
		</a>
	</div>
	
<?php
	foreach($this->privmsgs as $privmsg):
		$sent = strtotime($privmsg['created_pmg']);
		$elapsed = time() - $sent;
		
		// calculate how long ago was the message sent
		if($elapsed < 3600) {
			$minutes = round($elapsed / 60);
			
			$sent = "(" . $minutes . " " . $this->translate('minutes-ago') . ")";
		} elseif($elapsed < 86400) {
			$hours = round($elapsed / 3600);
			
			$sent = "(" . $hours . " " . $this->translate('hours-ago') . ")";
		} elseif($elapsed < 604800) {
			$days = round($elapsed / 86400);
			
			$sent = "(" . $days . " " . $this->translate('days-ago') . ")";
		} elseif($elapsed < 31449600) {
			$weeks = round($elapsed / 604800);
			
			$sent = "(" . $weeks . " " . $this->translate('weeks-ago') . ")";
		} else {
			$years = round($elapsed / 31449600);
			
			$sent = "(" . $years . " " . $this->translate('years-ago') . ")";
		}
        ?>
		
		<div class="privmsg">
			<div class="privmsg_userinfo">
				
				<!-- Checkbox and Delete-button for every message -->
				<div style="padding: 0px 0px 3px 0px;">
					<input type="checkbox" name="select_<?php echo $privmsg['id_pmg']; ?>" id="select_<?php echo $privmsg['id_pmg']; ?>" />
					<a href="javascript: void(0)" onclick="selectOnlyThisMsg(<?php echo $privmsg['id_pmg']; ?>); document.delete_privmsgs.submit(); return false">
						<?php echo $this->translate('privmsg-delete'); ?>
					</a>
				</div>
					
                    <center>
                    <?php 
                    if($privmsg['username_pmg'] != 'privmsg-message-sender-system') 
                    {
                    ?>
	                    <a href="<?php echo $this->url(array('controller' => 'account',
	                                                         'action' => 'view',
	                                                         'user' => $privmsg['username_pmg'],
	                                                         'language' => $this->language),
	                                                   		 'lang_default', true); ?>">
	                    <?php 
                    }
                    ?>
                        <?php if($privmsg['user_has_image']): ?>
                        
                            <img src="<?php echo $this->url(array('controller' => 'account', 
                                                                  'action' => 'profilethumb', 
                                                                  'id' => $privmsg['id_sender_pmg'], 
                                                                  'language' => $this->language, 
                                                                  'thumb' => 'true'), 
                                                            'lang_default', true); ?>" 
                                alt="User image" width="80" height="80" />
                    </a>
                    </center>
                    
                    <br />
                    
                    <?php $this->translate('privmsg-message-from'); ?>
                    <a href="<?php echo $this->url(array('controller' => 'account',
                                                         'action' => 'view',
                                                         'user' => $privmsg['username_pmg'],
                                                         'language' => $this->language),
                                                   'lang_default', true); ?>">
                        <?php echo $privmsg['username_pmg']; ?>
                    </a>
                <?php else: ?>
                    <img src="<?php echo $this->baseUrl('/images/system.png'); ?>" 
                        alt="System" />
                    </a>
                    </center>
                    
                    <br />
                    
                    <?php echo $this->translate('privmsg-message-from'); ?>
                    <b>
                        <?php echo $this->translate($privmsg['username_pmg']); ?>
                    </b>
                <?php endif; ?>
                
				<br />
				<?php echo $sent; ?>
			</div><!-- end of privmsg_userinfo -->
			<div class="privmsg_content">
                <?php if($privmsg['read_pmg'] == 0): ?>
                    <span style="color: red;">
                        <b>NEW!</b>
                    </span>
                <?php endif; ?>
                
                <p>
                    <?php echo stripslashes($privmsg['header_pmg']); ?>
                </p>
                <p>
                    <?php echo stripslashes($privmsg['message_body_pmg']); ?>
                </p>
                <?php if($privmsg['username_pmg'] != "privmsg-message-sender-system"): ?> <!-- Reply button if sender is not system -->
					<input type="button" class="reply" id="replyto-<?php echo $privmsg['username_pmg']; ?>" value="Reply"/>
				<?php endif; ?>
			</div><!-- end of privmsg_content -->
		</div><!-- end of privmsg -->
    <?php endforeach; ?>
<?php endif; ?>
</form> <!-- end of 'Delete selected'-form -->

