<?php $this->headScript()->captureStart() ?>
$(document).ready(function() {
	$("input[type=button][value=Reply]").click(function() {
		url = "<?php echo $this->baseUrl("/".$this->language."/privmsg/send/")?>" + $(this).attr('id').replace(/replyto-/, "");
		location.href = url;
	});
});
<?php $this->headScript()->captureEnd() ?>

<div id="privmsg-page">
<h2><?php echo $this->translate('privmsg-messages'); ?></h2>

<?php if($this->privmsgs): ?>
<!-- A form for deleting the selected messages -->
<form name="delete_privmsgs" id="delete_privmsgs" action="#" method="post">
	<input type="hidden" name="delete_first" value="<?php echo $this->privmsgs[0]['id_pmg']; ?>" />
	<input type="hidden" name="delete_last" value="<?php echo $this->privmsgs[count($this->privmsgs)-1]['id_pmg']; ?>" />
	<div id="privmsg-options-all">
		<input type="checkbox" name="select_all" id="select_all" onclick="selectAllPrivmsgs(); return true;" />
		<input type="submit" name="delete_selected" value="<?php echo $this->translate('privmsg-delete-selected'); ?>" onclick="document.delete_privmsgs.submit(); return false;" />
	</div>
	<div id="message-list" class="clear">
	<?php foreach($this->privmsgs as $privmsg):
		$sent = strtotime($privmsg['created_pmg']);
		$elapsed = time() - $sent;
		
		// calculate how long ago was the message sent
		if($elapsed < 3600) {
			$minutes = round($elapsed / 60);
			
			$sent = "(" . $minutes . " " . $this->translate('minutes-ago') . ")";
		} elseif($elapsed < 86400) {
			$hours = round($elapsed / 3600);
			
			$sent = "(" . $hours . " " . $this->translate('hours-ago') . ")";
		} elseif($elapsed < 604800) {
			$days = round($elapsed / 86400);
			
			$sent = "(" . $days . " " . $this->translate('days-ago') . ")";
		} elseif($elapsed < 31449600) {
			$weeks = round($elapsed / 604800);
			
			$sent = "(" . $weeks . " " . $this->translate('weeks-ago') . ")";
		} else {
			$years = round($elapsed / 31449600);
			
			$sent = "(" . $years . " " . $this->translate('years-ago') . ")";
		}
        ?>
		
		<div class="privmsg">
			<div class="privmsg_userinfo left">
				
				<!-- Checkbox and Delete-button for every message -->
				<div class="privmsg_buttons">
					<input type="checkbox" name="select_<?php echo $privmsg['id_pmg']; ?>" id="select_<?php echo $privmsg['id_pmg']; ?>" />
					<a href="javascript: void(0)" onclick="selectOnlyThisMsg(<?php echo $privmsg['id_pmg']; ?>); document.delete_privmsgs.submit(); return false">
						<?php echo $this->translate('privmsg-delete'); ?>
					</a>
				</div>
					
                <div class="">
                    <?php if($privmsg['username_pmg'] != 'privmsg-message-sender-system'): ?>
	                    <a href="<?php echo $this->url(array('controller' => 'account',
	                                                         'action' => 'view',
	                                                         'user' => $privmsg['username_pmg'],
	                                                         'language' => $this->language),
	                                                   		 'lang_default', true); ?>">
							<img src="<?php echo $this->url(array('controller' => 'account', 
	                                                                  'action' => 'profilethumb', 
	                                                                  'id' => $privmsg['id_sender_pmg'], 
	                                                                  'language' => $this->language, 
	                                                                  'thumb' => 'true'), 
	                                                            'lang_default', true); ?>" 
	                                alt="User image" width="80" height="80" />
                    	</a>
               </div>
                    <?php $this->translate('privmsg-message-from'); ?>
                    <strong>
	                    <a href="<?php echo $this->url(array('controller' => 'account',
	                                                         'action' => 'view',
	                                                         'user' => $privmsg['username_pmg'],
	                                                         'language' => $this->language),
	                                                   'lang_default', true); ?>">
	                        <?php echo $privmsg['username_pmg']; ?></a>
                    </strong>
                <?php else: //if message from system ?> 
                    <img src="<?php echo $this->baseUrl('/images/system.png'); ?>" 
                        alt="System" />
                    </div>

                    <?php echo $this->translate('privmsg-message-from'); ?>
                    <strong>
                        <?php echo $this->translate($privmsg['username_pmg']); ?>
                    </strong>
                <?php endif; ?>
				<div class="privmsg-time-sent"><?php echo $sent; ?></div>
			</div><!-- end of privmsg_userinfo -->
			<div class="privmsg_content left">
                <div class="privmsg-header">
	                <h4 class="left"><?php echo stripslashes($privmsg['header_pmg']); ?></h4>
	                <div class="privmsg-header-new left">
	                <?php if($privmsg['read_pmg'] == 0): ?>
                        <strong><small>* NEW!</small></strong>
                	<?php endif; ?>
                	</div>
	                
	                <?php if($privmsg['username_pmg'] != "privmsg-message-sender-system" && $privmsg['username_pmg'] != $this->user): ?> <!-- Reply button if sender is not system -->
						<div class="reply right"><input type="button" id="replyto-<?php echo $privmsg['username_pmg']; ?>" value="Reply"/></div>						
					<?php endif; ?>
					<div class="clear"></div>
				</div>				
                <p>
                    <?php echo stripslashes($privmsg['message_body_pmg']); ?>
                </p>
			</div><!-- end of privmsg_content -->
			<div class="clear"></div>
			
		</div><!-- end of privmsg -->
    <?php endforeach; ?>
<?php endif; ?>
</form> <!-- end of 'Delete selected'-form -->
</div>
