<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<div id="privmsg_title">
    <h2>
        <?php echo $this->translate('privmsg-send-title'); ?>
    </h2>
    
    <p>
        <?php echo $this->translate('info-text'); ?>
    </p>
    
    <br />
    
    <div class="form_privmsg_row">
        <label>
            <?php echo $this->translate('privmsg-message-to'); ?>
        </label>
        <?php echo $this->receiver; ?>
    </div>
    
    <div class="form_privmsg_row">
        <label>
            <?php echo $this->translate('privmsg-message-from'); ?>
        </label>
        <?php echo $this->sender; ?>
    </div>
    
    <?php echo $this->form; ?>
</div>