<script type="text/javascript">
$(document).ready(function() {
	$("textarea[id=privmsg_message]").bind("keydown keyup change",function(){
		var limit = 1000;
		var newLines = $(this).val().split("\n").length - 1;
		var length = $(this).val().length + newLines;
		if(limit < length)
			$("#privmsg-charcount-cut").show();
		else $("#privmsg-charcount-cut").hide();

		$('#privmsg-charcount').html("Character limit: " + length+"/"+limit);
	});
});
</script>
<div id="privmsg_title">
    <h2>
        <?php echo $this->translate('privmsg-send-title'); ?>
    </h2>
    
    <p>
        <?php echo $this->translate('info-text'); ?>
    </p>
    
    <br />
    
    <div class="form_privmsg_row">
        <label>
            <?php echo $this->translate('privmsg-message-to'); ?>
        </label>
        <?php echo $this->receiver; ?>
    </div>
    
    <div class="form_privmsg_row">
        <label>
            <?php echo $this->translate('privmsg-message-from'); ?>
        </label>
        <?php echo $this->sender; ?>
    </div>
    
    <?php echo $this->form; ?>
</div>