<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<div id="gaccampaignlist">
    <h3>Recent campaigns</h3>
    <div class="campaign-list">
        <ul>
            <?php echo $this->partialLoop('partials/campaign-row.phtml', $this->campaigns); ?>
        </ul>
    </div>
    <div style="text-align: center; margin-top: 10px;">
        <?php $morecmpsurl = $this->url(array('controller' => 'campaign',
                                              'action'     => 'list',
                                              'language'   => $this->language),
                                          'lang_default', true); ?>
        <strong><a href="<?php echo $morecmpsurl; ?>">Show more</a></strong>
    </div>
</div>

<div id="gacsidebar">
    <div class="box">
        <h2>What are groups and campaigns?</h2>
        <div class="box-content">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed viverra nibh non diam cursus a aliquet dui tempus. Phasellus pellentesque mattis elit. Aenean sagittis ultrices lacus, pharetra congue turpis semper sit amet. Vivamus quam diam, elementum viverra dignissim vitae, elementum at dolor. Aliquam sit amet volutpat.
        </div>
    </div>

    <div id="groups">
        <h3>Recent groups</h3>
        <ul>
            <?php echo $this->partialLoop('partials/group_row_small.phtml', $this->groups); ?>
        </ul>
    </div>

    <div style="text-align: center; margin-top: 20px;">
        <?php $moregrpsurl = $this->url(array('controller' => 'group',
                                              'action'     => 'list',
                                              'language'   => $this->language),
                                          'lang_default', true); ?>
        <strong><a href="<?php echo $moregrpsurl; ?>">Show more</a></strong>
    </div>
</div>