<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<div id="gaccampaignlist">
    <h3 style="float:left;">Recent campaigns</h3>

    <?php
    $addgrpurl = $this->url(
        array(
            'controller' => 'group',
            'action'     => 'create',
            'language'   => $this->language
        ), 'lang_default', true);
    ?>

    <h3 style="float:right; margin-right:20px;"><a href="<?php echo $addgrpurl; ?>">&gt; Create new group</a></h3>
    <div class="clear"></div>
    <div class="campaign-list">
        <ul>
            <?php echo $this->partialLoop('partials/campaign-row.phtml', $this->campaigns); ?>
        </ul>
    </div>
    <div style="text-align: center; margin-top: 10px;">
        <?php $morecmpsurl = $this->url(array('controller' => 'campaign',
                                              'action'     => 'list',
                                              'language'   => $this->language),
                                          'lang_default', true); ?>
        <strong><a href="<?php echo $morecmpsurl; ?>">Show more</a></strong>
    </div>
</div>

<div id="gacsidebar">
    <div class="box">
        <h2>What are groups and campaigns?</h2>
        <div class="box-content">
            <strong><a href="<?php echo $addgrpurl; ?>">Create a group</a></strong><br />
            Groups help like-minded people to join their forces.
            You can create as many groups as you want.

            <p>Once you have created a group you can launch group campaigns.</p>

            <strong>Launch a campaign</strong><br />
            To collect others' opinions, launch a campaign that combines
            individual contents as an easy-to-navigate unit.
        </div>
    </div>

    <div id="groups">
        <h3>Recent groups</h3>
        <ul>
            <?php echo $this->partialLoop('partials/group_row_small.phtml', $this->groups); ?>
        </ul>
    </div>

    <div style="text-align: center; margin-top: 20px;">
        <?php $moregrpsurl = $this->url(array('controller' => 'group',
                                              'action'     => 'list',
                                              'language'   => $this->language),
                                          'lang_default', true); ?>
        <strong><a href="<?php echo $moregrpsurl; ?>">Show more</a></strong>
    </div>
</div>