<!DOCTYPE HTML>

<html>
<head>
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8"/>
	<title><?php echo $this->translate($this->title); ?></title>

	<link rel="stylesheet/less" type="text/css" href="/css/massidea.less" media="all" />
	<script type="text/javascript"> var less = { env : 'development' }; </script>
	<script type="text/javascript" src="/js/less-1.3.0.min.js"></script>

	<script type="text/javascript" src="/js/jquery-1.7.2.min.js"></script>
	<?php
	$this->headScript()->appendFile($this->baseUrl('/js/bootstrap.min.js'));
	$this->headScript()->appendFile($this->baseUrl('/js/massidea.js'));
	$this->headScript()->appendFile($this->baseUrl('/js/massidea-popover.js'));
	$this->headScript()->appendFile($this->baseUrl('/js/massidea-content.js'));

	echo $this->headLink();
	echo $this->headMeta();
	?>
	<script type="text/javascript"> $(function () { MassIdea.init("<?php echo $this->language;?>"); }); </script>
</head>
<body>
	<div id="footerBackground">
		<div class="container">
			<div class="row header">
				<div class="span8">
					<a id="massidea-logo" href="/"><img src="/img/massideaLogo.png"/></a>
					<img id="massidea-signet" src="/img/signet.png"/>
				</div>
				<div class="span4 login">
					<div class="usermenu" data-toggle="dropdown">
						<span class="username pull-right">
							<span><?php echo $this->identity->username;?></span>
							<span class="caret"></span>
						</span>

						<span class="userImage pull-right">
							<img  src="<?php echo $this->profile_image; ?>" alt="User Image" />
						</span>
					</div>

					<ul id="user-dropdown" class="dropdown-menu pull-right">
						<li><a href="<?php echo $this->url(array(
							'controller' => 'account',
							'action' => 'view',
							'user' => $this->username,
							'language' => $this->language,
						), 'lang_default', true); ?>"><?php echo $this->translate('account-view-user-profile'); ?></a></li>
						<li><a href="<?php echo $this->url(array(
							'controller' => 'account',
							'action' => 'settings',
							'language' => $this->language,
						), 'lang_default', true); ?>"><?php echo $this->translate('account-view-user-settings'); ?></a></li>
						<li><a href="<?php echo $this->url(array(
							'controller' => 'account',
							'action' => 'logout',
							'language' => $this->language,
						), 'lang_default', true); ?>"><?php echo $this->translate('account-view-user-logout'); ?></a></li>
					</ul>
				</div>
			</div>

			<div class="row">
				<div class="span2">
					<?php include("partial-navigation.phtml"); ?>
				</div>

				<div class="span7">
					<section id="page-content">
						<?php foreach ($this->messages as $message) : ?>
						<div class="alert alert-success">
							<button type="button" class="close" data-dismiss="alert">×</button>
							<?php echo $message; ?>
						</div>
						<?php endforeach; ?>

						<?php echo $this->layout()->content; ?>
					</section>
				</div>

				<div class="span3">
					<?php echo $this->sidebar('sidebar.phtml'); ?>
				</div>
			</div>

			<div class="row footer">
				<div class="span4">
					<ul>
						<li><a href="#"><?php echo $this->translate('layout-about-Massidea'); ?></a></li>
						<li><a href="#"><?php echo $this->translate('layout-terms'); ?></a></li>
						<li><a href="#"><?php echo $this->translate('layout-privacy'); ?></a></li>
						<li><a href="<?php echo $this->url(array(
							'controller' => 'imprint',
							'action' => 'view',
							'language' => $this->language,
						), 'lang_default', true); ?>"><?php echo $this->translate('layout-imprint'); ?></a></li>
					</ul>
				</div>
				<div class="span4">
					<ul>
						<li><a href="<?php echo $this->url(array(
								'controller' => 'account',
								'action' => 'login',
								'language' => $this->language),
							'lang_default', true);?>">
							<?php echo $this->translate('layout-join-our-community-footer'); ?></a></li>
						<li><a href="<?php echo $this->url(array(
								'controller' => 'account',
								'action' => 'register',
								'language' => $this->language),
							'lang_default', true);?>">
							<?php echo $this->translate('layout-sign-up'); ?></a></li>
						<li><a href="<?php echo $this->url(array(
								'controller' => 'content',
								'action' => 'add',
								'language' => $this->language),
							'lang_default', true);?>">
							<?php echo $this->translate('layout-create-a-post'); ?></a></li>
					</ul>
				</div>
				<div class="span4">
					<?php echo $this->translate('layout-select-your-platform-language'); ?>:
					<select id="languageMenu">
						<option><?php echo $this->translate('layout-language'); ?></option>
						<?php foreach($this->activeLanguages as $language) {?>
						<option value="<?php echo $language['id']; ?>"><?php echo $this->translate($language['name']); ?></option>
						<?php } ?>
					</select>
				</div>
			</div>
		</div>
	</div>
	<?php
	echo $this->headScript();
	?>
</body>
</html>


