<!DOCTYPE HTML>

<html>
<head>
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8"/>
    <title><?php echo $this->translate($this->title); ?></title>

    <link rel="stylesheet/less" type="text/css" href="/css/massidea.less" media="all" />
    <script type="text/javascript"> var less = { env : 'development' }; </script>
    <script type="text/javascript" src="/js/less-1.3.0.min.js"></script>

    <?php
        $this->headScript()->appendFile($this->baseUrl('/js/jquery-1.7.2.min.js'));
        $this->headScript()->appendFile($this->baseUrl('/js/bootstrap.min.js'));
        $this->headScript()->appendFile($this->baseUrl('/js/massidea.js'));


        echo $this->headLink();
        echo $this->headMeta();
    ?>
</head>
<body>
<div id="footerBackground">
    <div class="container">
        <div class="row header">
            <div class="span8">
                <a id="massidea-logo" href="<?php echo $this->url(array('language' => $this->language),
                    'lang_default', true); ?>/"><img src="/img/massideaLogo.png"/></a>
                <img id="massidea-signet" src="/img/signet.png"/>
            </div>
            <div class="span4 login">
                <?php
                if (!$this->authenticated) :
                    echo $this->loginform; else :
                    echo $this->username;
                    ?>
                    <span class="grey"> |</span>
                    <a href="<?php echo $this->url(array(
                        'controller' => 'account',
                        'action' => 'logout',
                        'language' => $this->language,
                    ), 'lang_default', true); ?>">
                        <?php echo $this->translate('layout-logout'); ?>
                    </a>
                    <?php endif; ?>
            </div>
        </div>

        <section id="row content">
            <?php echo $this->layout()->content; ?>
        </section>
        <div class="row footer">
            <div class="span4">
                <ul>
                    <li><a href="#"><?php echo $this->translate('layout-about-Massidea'); ?></a></li>
                    <li><a href="#"><?php echo $this->translate('layout-terms'); ?></a></li>
                    <li><a href="#"><?php echo $this->translate('layout-privacy'); ?></a></li>
                    <li><a href="#"><?php echo $this->translate('layout-imprint'); ?></a></li>
                </ul>
            </div>
            <div class="span4">
                <ul>
                <li><a href="#"><?php echo $this->translate('layout-join-our-community-footer'); ?></a></li>
                <li><a href="#"><?php echo $this->translate('layout-sign-up'); ?></a></li>
                <li><a href="#"><?php echo $this->translate('layout-create-a-post'); ?></a></li>
                </ul>
            </div>
            <div class="span4">
                <?php echo $this->translate('layout-select-your-platform-language'); ?>:
                <select id="languageMenu">
                    <option><?php echo $this->translate('layout-language'); ?></option>
                    <?php foreach($this->activeLanguages as $language) {?>
                        <option value="<?php echo $language['id']; ?>"><?php echo $this->translate($language['name']); ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
    </div>
</div>
<?php
echo $this->headScript();
?>
</body>
</html>


