<?php 
$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();

echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fi">
<head>
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
    <link rel="icon" type="image/png" href="<?php echo $baseUrl; ?>/images/favicon.png"/>
    <title><?php echo $this->escape($this->translate($this->title)); ?></title>
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $baseUrl; ?>/css/new_public.css" />
    <script type="text/javascript" src="<?php echo $baseUrl; ?>/js/functions.js"></script>
    <script type="text/javascript" src="<?php echo $baseUrl; ?>/js/OibsUtils.js"></script>
    <?php
    if($this->action == "register")
    {
        echo '<script type="text/javascript" src="'.$baseUrl.'/js/checkRF.js"></script>';
    }
    elseif($this->controller == "content")
    {
        if($this->action == "add" || $this->action == "edit")
        {
            echo '<script type="text/javascript" src="'.$baseUrl.'/js/CheckContentForm.js"></script>';
        }
    }
    ?>
    
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="header_topbar_left">
                <div class="logo_picture">
                    <a href="<?php echo $this->url(array('controller' => 'index', 'language' => $this->language), 'lang_default', true); ?>">
                        <img src="<?php echo $baseUrl; ?>/images/logo_small_triangle_2.png" alt="" style="" /></a>
                </div><!-- End of logo_picture -->
                <div class="logo_text">
                    <span><a href="#" onclick="popup('popup_naming_competition')"><?php echo $this->translate('index-name-missing'); ?></a></span>
                    <br />
                </div><!-- End of logo_text -->
            </div><!--  End of topbar_left -->
            
            <div class="header_topbar_right">
                <div class="header_topbar_right_top">
                    <?php if($this->authenticated):?>
                        <?php echo $this->translate('index-logged_in'); ?>                    
                        <a href=" <?php echo $this->url(array('controller' => 'account', 'action' => 'view', 'user' => $this->username, 'language' => $this->language), 'lang_default', true); ?>">
                            <?php echo $this->username; ?></a>
                        <?php
                        if($this->unread_privmsgs > 0)
                        {
                            if($this->controller == "privmsg" && $this->action == "index")
                            {
                                $models_privmsg = New Models_PrivateMessages();
                                $models_privmsg->markUnreadMessagesAsRead($this->userid);
                            }
                            else
                            {
                                ?> 
                                <a href="<?php echo $this->url(array('controller' => 'privmsg', 'action' => 'index', 'language' => $this->language), 'lang_default', true); ?>">
                                    (<?php echo $this->unread_privmsgs; ?>)</a>
                                <?php
                            }
                        } ?>
                        |
                        <a href="<?php echo $this->url(array('controller' => 'account', 
                                                        'action' => 'logout', 'language' => $this->language), 
                                                        'lang_default', true); ?>">
                            <?php echo $this->translate('index-logout'); ?></a>
                    <?php else: ?>
                        <a href="<?php echo $this->url(array('controller' => 'account', 
                                                        'action' => 'login', 'language' => $this->language), 
                                                        'lang_default', true); ?>">
                            <?php echo $this->translate('index-login'); ?></a>
						 <?php echo $this->translate('index-or'); ?>
                        <a href="<?php echo $this->url(array('controller' => 'account', 
                                                        'action' => 'register', 'language' => $this->language), 
                                                        'lang_default', true); ?>">
                            <?php echo $this->translate('index-signup'); ?></a>
						
                    <?php endif; ?>
					|
						<a href="<?php echo $this->url(array('controller' => 'help', 
                                                        'action' => 'index', 'language' => $this->language), 
                                                        'lang_default', true); ?>">
                            <?php echo $this->translate('index-help'); ?></a>
                     &nbsp;
                     <select id="languages" onchange="changeLang(document.getElementById('languages').value, '<?php echo $_SERVER['HTTP_HOST'].$baseUrl; ?>')">
                    <?php // Echo the translations set available
                         foreach($this->languages as $language)
                        {
                            echo '<option value="'.$language.'" ';
                            if    ($language == $this->language)
                            {
                                echo 'selected="selected"';
                            }
                            echo '>'.$this->translate('lang-'.$language).'</option>';
                        }
                    ?>
                </select> 
                </div><!--  End of header_topbar_right_top -->
                <div class="header_topbar_right_btm">
                    <div class="header_topbar_right_btm_adspace">
                        <img src="<?php echo $baseUrl; ?>/images/placeholder_advertise_top.png" width="468" height="60" alt="ADVERTISEMENT" style="position:relative; top: 8px;" />
                    </div>
                    <div class="header_topbar_right_btm_textspace">
                    <div class="box_developers">
                        <div class="box_developers_top">
                            <i><?php echo $this->translate('index-involve'); ?></i>
                        </div>
                        <div class="box_developers_mid">
                            <?php echo $this->translate('index-become-developer'); ?>
                        </div>
                        <div class="box_developers_btm">
                            <a href="http://www.oibs.fi/wiki/" class="u">Wiki</a> | <a href="http://www.oibs.fi/forum/" class="u">Forum</a>
                        </div>
                    </div>
                    </div>
                </div><!--  End of header_topbar_right_btm -->
            </div><!--  End of topbar_right -->
        
            <div class="header_mainbar">
                <div class="header_mainbar_mainlinks">
                    <ul id="header_mainbar_navigation">
                        <li>
                            <a href="<?php echo $this->url(array('controller' => 'content', 
                                                                 'action' => 'list', 
                                                                 'type' => 'problem', 
                                                                 'language' => $this->language), 
                                                           'lang_default', true); ?>">
                                <img src="<?php echo $baseUrl; ?>/images/icon_ball_red.png" width="15" height="15" alt="*" />
                                <?php echo $this->translate('index-problems');?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('controller' => 'content', 
                                                                 'action' => 'list', 
                                                                 'type' => 'finfo', 
                                                                 'language' => $this->language), 
                                                           'lang_default', true); ?>">
                                <img src="<?php echo $baseUrl; ?>/images/icon_ball_orange.png" width="15" height="15" alt="*" />
                                <?php echo $this->translate('index-futureinfo');?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('controller' => 'content', 
                                                                 'action' => 'list', 
                                                                 'type' => 'idea', 
                                                                 'language' => $this->language), 
                                                           'lang_default', true); ?>">
                                <img src="<?php echo $baseUrl; ?>/images/icon_ball_green.png" width="15" height="15" alt="*" />
                                <?php echo $this->translate('index-ideas');?>
                            </a>
                        </li>
                    </ul>
                </div><!--  End of header_mainbar_mainlinks -->
                <div class="header_mainbar_right">
                    <a href=" <?php echo $this->url(array('controller' => 'account', 
                                                          'action' => 'userlist', 
                                                          'language' => $this->language), 
                                                    'lang_default', true); ?>">
                        <?php echo $this->translate('index-users'); ?>
                    </a> |
                    <a href=" <?php echo $this->url(array('controller' => 'content', 
                                                          'action' => 'index', 
                                                          'language' => $this->language), 
                                                    'lang_default', true); ?>">
                        <?php echo $this->translate('index-add_content'); ?>
                    </a>
                </div><!--  End of header_mainbar_right -->
            </div> <!--  End of mainbar -->
            <?php 
            //if($this->controller != "search")
            //{ 
            $searchparam = "";
            
            if ((isset($_GET["search"])) && ($_GET["search"] != "")){
                $searchparam = $_GET["search"];
            }
            
            $tab = "all";
            
            if(isset($this->tab))
            {
                $tab = $this->tab;
            }
            ?>
            <div class="header_searchbar">
                <div class="header_searchbar_form">
                <?php 
                /*
                    <form action="<?php echo $this->url(array('controller' => 'search', 'action' => 'result', 'language' => $this->language), 'lang_default', true); ?>" method="get">
                        <ins>
                            <input name="search" type="text" size="65" value="<?php echo $searchparam ?>" />
                        </ins>
                        <?php
                        /*
                        <ins>
                            <input name="tab" type="hidden" value="<?php echo $tab; ?>" />
                        </ins>
                        
                        ?>
                        <ins>
                            <input type="submit" value="<?php echo $this->translate('index-search'); ?>"/>
                        </ins>
                    </form>
                    */
                    echo $this->searchForm;
                    ?>
                </div> <!--  End of header_searchbar_form -->
            </div> <!--  End of header_searchbar -->
            <?php 
            //} // end of if this controller is search
            ?>
        </div> <!--  End of header -->
        
        <div class="content_container">

            <div class="content">
                <?php echo $this->layout()->content; ?>
            </div> <!-- End of content -->

            <div class="adbar">
                <img src="<?php echo $baseUrl; ?>/images/logo_leverage.png" alt="Leverage from the EU" width="103" height="49" />
                <img src="<?php echo $baseUrl; ?>/images/placeholder_advertise_right.png" alt="Advertisement placeholder" width="121" height="600" style="margin-left:5px;" />
                <img src="<?php echo $baseUrl; ?>/images/logo_esf.png" alt="This project is funded by the European Social Fund" width="120" height="120" />
            </div> <!-- End of adbar -->
        </div>
        <div class="footer">
            <span class="text_0_7"><a href="#"><?php echo $this->translate('index-terms-of-use'); ?></a> | <a href="#"><?php echo $this->translate('index-privacy-policy'); ?></a>&nbsp;&nbsp;&nbsp; &copy; 2009 OIBS</span>
        </div> <!-- End of footer -->
    </div> <!-- End of container -->
    
    <div id="popup_naming_competition" class="popup" style="display:none;">
        <div class="popup_text" style="color:#fff;">
            <div class="popup_close" style="float:left;">
                <div style="float:right;">
                    <a href="#" onclick="popup('popup_naming_competition')"><img src="<?php echo $baseUrl; ?>/images/icon_close.png" alt="" /></a>
                </div>
            </div>
            <div style="clear:both; padding-top: 10px;">
                <a href="http://www.oibs.fi/forum/viewforum.php?id=12" onclick="popup('popup_naming_competition')"><?php echo $this->translate('Help us choose a name for the project website'); ?></a>
            </div>
        </div>
    </div>
    
    <div id="backdrop" onclick="closePopups()" style="display:none;"></div>  <!-- this is the pseudo-div used for the bakcdrop of all css-popups -->
    <?php //echo "<p>this->messages as seen by layout.phtml:" . $this->messages . "</p>";?>
</body>
</html>