<?php
//$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();

// Set some variables for dynamic RSS linking for each page
$headlink_rsstype = isset($this->rsstype) ? $this->rsstype : 'all';

$headlink_rsslink = $this->url(array('controller' => 'rss',
                            'action' => 'generate',
							'type' => $headlink_rsstype,
							'language' => $this->language),
                        'lang_default', true);
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
    <title><?php echo $this->translate($this->title); ?></title>
    
    <?php
	$this->headLink()->appendStylesheet($this->baseUrl('/css/style.css'));
	$this->headLink()->appendStylesheet($this->baseUrl('/css/style_additions_req.css'));
	$this->headLink()->appendStylesheet($this->baseUrl('/css/ie8_fix.css'), 'screen', 'IE 8');
	$this->headLink()->appendStylesheet($this->baseUrl('/css/ie7_fix.css'), 'screen', 'IE 7');
	$this->headLink()->appendStylesheet($this->baseUrl('/css/ie6_fix.css'), 'screen', 'IE 6');
    //$this->headLink()->appendStylesheet($this->baseUrl('/css/ui-lightness/jquery-ui-1.7.2.custom.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('/css/custom-theme/jquery-ui-1.8.2.custom.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('/css/farbtastic.css'));		// Used for farbtastic custom color picker
	
    $this->headlink()->headLink(array(
        'rel' => 'shortcut icon',
        'href' => $this->baseUrl('/images/favicon.png'),
        'type' => 'image/x-icon'),
        'PREPEND'
    );
                                        
    $this->headLink()->headLink(array(
        'rel' => 'alternate',
        'type' => 'application/rss+xml',
        'title' => 'RSS',
        'href' => $headlink_rsslink),
        'PREPEND'
    );

    $this->headScript()->prependFile($this->baseUrl('/js/jquery.qtip-1.0.0-rc3.js'));
    $this->headScript()->prependFile($this->baseUrl('/js/jquery-ui-1.7.2.custom.min.js'));
    $this->headScript()->prependFile($this->baseUrl('/js/auto_translate.js'));                                    
    $this->headScript()->prependFile($this->baseUrl('/js/functions.js'));
    $this->headScript()->prependFile($this->baseUrl('/js/OibsUtils.js'));
    $this->headScript()->prependFile($this->baseUrl('/js/scripts.js'));
    $this->headScript()->prependFile($this->baseUrl('/js/jquery.js'));
    $this->headScript()->prependFile($this->baseUrl('/js/farbtastic.js'));
    $this->headScript()->prependFile('http://maps.google.com/jsapi');

    echo $this->headLink();
    echo $this->headMeta();
    echo $this->headScript();
    ?>
    
</head>
<body>
	<!-- This is the top banner -->
	<div class="top_row">
		<div class="top_row_center">
			<div class="top_row_center_left">
                <a href="<?php echo $this->url(array('language' => $this->language),
                                               'lang_default', true); ?>/">
                    <img src="<?php echo $this->baseUrl('/images/massidea_logo.png'); ?>" alt="Massidea.org" />
                </a>
            </div>

			<div class="top_row_center_right">
				<div class="top_row_center_right_login">
				
					<div class="top_row_center_right_login_links" style="width: 350px; text-align: left; padding: 0px; margin: 0px;">
					
						<?php if($this->authenticated) : ?>
                        <div style="float: left; width: 14px;">&nbsp;</div>
						<div style="text-align: right; float: left; width: 50px;">
                                <div style="width: 337px;">
							            <?php //$auth = Zend_Auth::getInstance(); ?>
								        <?php if (in_array("admin", $this->logged_user_roles)): ?>
											<a href="<?php echo $this->url(array('controller' => 'admin',
																				 'action' => 'index',
																				 'language' => $this->language),
																				 'lang_default', true); ?>">
												<?php echo $this->translate('index-admin-tools');?>
											</a> | 
							            <?php endif; ?>

                                    <?php echo $this->translate('index-logged_in'); ?>
                                    <a href="<?php echo $this->url(array('controller' => 'account',
                                                                         'action' => 'view',
                                                                         'user' => $this->username,
                                                                         'language' => $this->language),
                                                                   'lang_default', true); ?>">
                                        <?php echo $this->username; ?></a>
                                    <?php
                                    if($this->unread_privmsgs > 0) {
                                        if($this->controller == "privmsg" && $this->action == "index") {
                                            $Default_Model_privmsg = New Default_Model_PrivateMessages();
                                            $Default_Model_privmsg->markUnreadMessagesAsRead($this->userid);
                                        } else {
                                            ?> 
                                            <a href="<?php echo $this->url(array('controller' => 'privmsg',
                                                                                 'action' => 'index',
                                                                                 'language' => $this->language),
                                                                           'lang_default', true); ?>">
                                                (<?php echo $this->unread_privmsgs; ?>)</a>
                                            <?php
                                        }
                                    } ?>
                                    |
                                    <a href="<?php echo $this->url(array('controller' => 'account', 
                                                                         'action' => 'logout',
                                                                         'language' => $this->language), 
                                                                   'lang_default', true); ?>">
                                        <?php echo $this->translate('index-logout'); ?>
                                    </a>
                                </div>
                        <?php else: ?>
                            <?php 
                            $url_sign_up = $this->url(array('controller' => 'account',
                                                            'action' => 'register',
                                                            'language' => $this->language), 
                                                      'lang_default', true);
                            ?>
							<div style="float: left; width: 156px;">&nbsp;</div>
                            
                            <div style="padding-left: 100px; float: left; width: 50px;">
                            
                                <div style="width: 237px;">
                                    <a id="login_link" href="#">
                                        <?php echo $this->translate('index-login'); ?></a> 
                                    | 
                                    <a href="<?php echo $url_sign_up; ?>">
                                        <?php echo $this->translate('index-signup'); ?>
                                    </a>
                                </div>
                                
                                <div id="login_box">
                                    <form action="<?php echo $this->url(array(
                                                'controller' => 'account', 
                                                'action' => 'login',
                                                'language' => $this->language),
                                            'lang_default', true);?>" method="post">                               
                                        <div>
                                            <?php echo $this->translate("account-register-username"); ?>
                                        </div>
                                        <div>
                                            <input type="text" name="username"/>
                                        </div>
                                        <div>
                                            <?php echo $this->translate("account-register-password"); ?>
                                        </div>
                                        <div>
                                            <input type="password" name="password"/>
                                        </div>
                                        <div>
                                            <input type="hidden" name="returnurl" value="<?php echo $this->url(); ?>" />
                                        </div>
                                        <div style="margin-top: 10px;">
                                            <input style="margin-right: 6px; width: 70px;" type="submit" 
                                                value="<?php echo $this->translate('account-login-submit'); ?>" /> 
                                            <span class="top_right_box_links" style="font-size: 12px;">
                                                <a href="<?php echo $this->url(array('controller' => 'account', 
                                                                                     'action' => 'fetchpassword', 
                                                                                     'language' => $this->language), 
                                                                                     'lang_default', true); ?>">
                                                    <?php echo $this->translate('account-login-problems'); ?>
                                                </a>
                                            </span>
                                        </div>
                                    </form>
                                    
                                    <div style="margin-top: 0px;">
                                        <div class="top_right_box_links" style="float:left; font-size: 12px; margin-left: 4px;">
                                            <p>
                                                <?php echo $this->translate('account-login-via-openid-loginbox'); ?> 
                                                <a id="login_link_openid" href="#">
                                                    <?php echo $this->translate('account-login-via-openid-loginbox-link'); ?>
                                                </a>
                                            </p>
                                        </div>
                                        
                                        <div style="margin-top: -6px; float:left; margin-left: 12px;">
                                            <p>
                                                <img src="<?php echo $this->baseUrl("/images/openid.png");?>" alt="OpenID" />
                                            </p>
                                        </div>
                                        
                                        <div style="clear: both;"></div>
                                    </div>
                                </div>
                                
                                <div id="login_box_openid">
                                    <form action="<?php echo $this->url(array(
                                                'controller' => 'account',
                                                'action' => 'openid',
                                                'language' => $this->language),
                                            'lang_default', true);?>" method="post">
                                        <div>Your OpenID</div>
                                        <div>
                                            <input style="margin-bottom: 12px; width: 212px; padding-left: 20px; background: #fff url('<?php echo $this->baseUrl('/images/openid-16x16.png'); ?>') 2px no-repeat;" name="openid_identifier" type="text" />
                                        </div>
                                        <div>
                                            <input style="margin-right: 6px;" type="submit" name="openid_action" value="Login" /> 
                                            <span class="top_right_box_links" style="font-size: 12px;">
                                                <a id="login_link_in_box" href="#">
                                                    Back to Massidea Login
                                                </a>
                                            </span>
                                        </div>
                                    </form>
                                </div>
                    <?php endif; ?>
                        
                            </div>
                            
                            <div style="clear: both;"></div>
					
                        </div>	
                    
					<div style="clear: both;"></div>
                    
				</div>

				<?php

                $searchparam = "";
                 if ((isset($_GET["search"])) && ($_GET["search"] != "")) {
                    $searchparam = $_GET["search"];
                 }
                 
                 $tab = "all";
                 
                 if(isset($this->tab)) {
                    $tab = $this->tab;
                 }
                ?>

				
				<div class="top_row_center_right_search">
					<div style="width: 450px;" class="top_row_center_right_search_field">
                    
                        <form style="margin: 0px; padding: 0px;" method="post" 
                            action="<?php echo $this->url(array(
                                    'controller' => 'search',
                                    'action' => 'result',
                                    'language' => $this->language),
                                'lang_default', true); ?>">
                            <div>
                                <input type="text" id="q" name="q" class="top_search_field" />
                                <input style="position: relative; left: 20px; top: 2px;" 
                                    type="image" src="<?php echo $this->baseUrl('/images/search_en.png'); ?>" 
                                    id="submitsearch" name="submitsearch" alt="Search" />
                            </div>
                        </form>
                        
                    </div>
                    
					<div style="clear: both;"></div>
				</div>
                
                <!-- Layout selector -->
				<div class="top_row_center_right_layout">
					<div class="top_row_center_right_selection_text">Layout: </div>
					<?php //echo $layoutForm = new Default_Form_AccountCustomLayout(); ?>
				</div>
				
                <!-- Language selector -->
				<div class="top_row_center_right_language">

		            <?php
		            $languages = new Default_Model_Languages();
		            $allLanguages = $languages->getAllNamesAndCodes();
		            echo $translationForm = new Default_Form_ChangeTranslationLanguageForm($allLanguages);
		            ?>
				</div>
				
			</div>
			
			<!-- Resets the floating row -->
			<div style="clear: both;"></div>
		</div>
	</div>
    
	<!-- This is the white area where the content is -->
	<div class="middle_row">

		<!-- Supra-Hax to prevent XHTML's mystical gap after top banner, which seems only to happen in Firefox. -->
		<div style="font-size: 1px;"><br /></div>

		<div class="sub_menu">
			<!-- LEFT SIDE OF THE MENU -->
			<div class="sub_menu_left">&nbsp;</div>
			
			<div id="home_latest" 
                onmouseout="blurMenu(this.id, 'deepblue', '<?php echo $this->baseUrl();?>')" 
                onmouseover="focusMenu(this.id, 'deepblue', '<?php echo $this->baseUrl();?>');" 
                class="sub_menu_item_deepblue"
            >
                <a href="<?php echo $this->url(array('language' => $this->language),
                                               'lang_default', true); ?>/">
                	<?php echo $this->translate('index-latest');?>
                </a>
            </div>
			
			<div class="sub_menu_left_space">&nbsp;</div>
            
			<div id="todays_challenges" 
                onmouseout="blurMenu(this.id, 'red', '<?php echo $this->baseUrl();?>')" 
                onmouseover="focusMenu(this.id, 'red', '<?php echo $this->baseUrl();?>');" 
                class="sub_menu_item_red"
            >
                <a href="<?php echo $this->url(array('type' => 'problem', 
                                                     'language' => $this->language),
                                               		'content_list', true); ?>">
                    <?php echo $this->translate('index-problems');?>
                </a>
            </div>
            
			<div class="sub_menu_left_space">&nbsp;</div>
            
			<div id="new_ideas" 
                onmouseout="blurMenu(this.id, 'green', '<?php echo $this->baseUrl();?>')" 
                onmouseover="focusMenu(this.id, 'green', '<?php echo $this->baseUrl();?>');" 
                class="sub_menu_item_green"
            >
                <a href="<?php echo $this->url(array('type' => 'idea', 
                                                     'language' => $this->language), 
                                               'content_list', true); ?>">
                    <?php echo $this->translate('index-ideas');?>
                </a>
            </div>
            
			<div class="sub_menu_left_space">&nbsp;</div>
            
            <div id="visions_of_the_future" 
                onmouseout="blurMenu(this.id, 'yellow', '<?php echo $this->baseUrl();?>')" 
                onmouseover="focusMenu(this.id, 'yellow', '<?php echo $this->baseUrl();?>');" 
                class="sub_menu_item_yellow"
            >
                <a href="<?php echo $this->url(array('type' => 'finfo', 
                                                     'language' => $this->language), 
                                               'content_list', true); ?>">
                    <?php echo $this->translate('index-futureinfo');?>
                </a>
            </div>

            <div class="sub_menu_left_space">&nbsp;</div>
            
            <div id="groups_campaigns" 
                onmouseout="blurMenu(this.id, 'blue', '<?php echo $this->baseUrl();?>')" 
                onmouseover="focusMenu(this.id, 'blue', '<?php echo $this->baseUrl();?>');" 
                class="sub_menu_item_blue"
            >
                <a href="<?php echo $this->url(array('language'   => $this->language,
                                                     'controller' => 'groupsandcampaigns',
                                                     'action'     => 'index',
                                               ), 'lang_default', true); ?>">
                    <?php echo $this->translate('index-groups-campaigns');?>
                </a>
            </div>
            
            <div class="sub_menu_left_space">&nbsp;</div>
            
            <div id="users" 
                onmouseout="blurMenu(this.id, 'blue', '<?php echo $this->baseUrl();?>')" 
                onmouseover="focusMenu(this.id, 'blue', '<?php echo $this->baseUrl();?>');" 
                class="sub_menu_item_blue"
            >
                <a href="<?php echo $this->url(array('controller' => 'account',
                                                     'action' => 'userlist',
                                                     'language' => $this->language),
                                                'lang_default', true); ?>">
                    <?php echo $this->translate('index-users');?>
                </a>
            </div>
            <div class="sub_menu_left_space">&nbsp;</div>
			<div id="blog" 
                onmouseout="blurMenu(this.id, 'deepblue', '<?php echo $this->baseUrl();?>')" 
                onmouseover="focusMenu(this.id, 'deepblue', '<?php echo $this->baseUrl();?>');" 
                class="sub_menu_item_deepblue"
            >
                <a href="/blog/">Blog</a>
            </div>            
            <div class="sub_menu_left_space">&nbsp;</div>
			
			<!-- RIGHT SIDE OF THE MENU, note that the placement order is reversed -->
			<div class="sub_menu_right">&nbsp;</div>
            
			<div class="sub_menu_right">
				<a href="#">
                    <img id="add_content_button" 
                        src="<?php echo $this->baseUrl('/images/add_new_content_en.png'); ?>" 
                        alt="Add content" />
                </a>
				
                <?php
                $url_add_i = $url_add_c = $url_add_v = 
                        $this->url(array('controller' => 'content',
                                         'action' => 'index',
                                         'language' => $this->language),
                                   'lang_default', true);
                                   
                if ($this->authenticated) {     
                	/*   Quite confusing for not having a link to adding ideas... */
                        // Idea can now be, without a link to the problem or finfo
                    $url_add_i = $this->url(array('contenttype' => 'idea',
                                                  'language' => $this->language),
                                                  'addcnttype', true);    
					    
                    $url_add_c = $this->url(array('contenttype' => 'problem',
                                                  'language' => $this->language),
                                                  'addcnttype', true);
                    
                    $url_add_v = $this->url(array('contenttype' => 'finfo',
                                                  'language' => $this->language),
                                                  'addcnttype', true);
                }
                ?>                
                
				<!-- This menu is hidden, and activated by using jQuery on demand. Check the JS -file for the function -->
				<div id="add_content_menu">
					<div id="add_content_menu_challenge">
						<a class="add_content_button" href="<?php echo $url_add_c; ?>">
							<span> 
								<div class="hidden_menu_red"></div>
								<div class="hidden_menu_row">
		                                <?php echo $this->translate('index-addcontent-challenge'); ?>
		                        </div>
							</span>		
                        </a>
						<div style="clear: both;"></div>
					</div>
                    
					<div id="add_content_menu_idea">
						<a class="add_content_button" href="<?php echo $url_add_i; ?>">
							<span>
								<div class="hidden_menu_green"></div>
								<div class="hidden_menu_row">
		                                <?php echo $this->translate('index-addcontent-idea'); ?>
		                        </div>
		                    </span>	
	                    </a>
						<div style="clear: both;"></div>
					</div>
                    
					<div id="add_content_menu_vision">
                        <a class="add_content_button" href="<?php echo $url_add_v; ?>">
	                        <span>
								<div class="hidden_menu_yellow"></div>
								<div class="hidden_menu_row">
			    	          		<?php echo $this->translate('index-addcontent-vision'); ?>
		                        </div>
								<div style="clear: both;"></div>
							</span>
						</a>
					</div>
				</div>		
			</div>
			
			<div class="sub_menu_right_space" style="width: 0px;">&nbsp;</div>
			<!-- Resets the floating row -->
			<div style="clear: both;"></div>
		</div>
		
		<!-- Content area -->
		<div id="content" class="content">
			<?php echo $this->layout()->content; ?>
			
            <?php
			/* So here it is, we just echo the layout -variable, right_side in 
            this -case, and we can throw stuff into this variable from any view.
			For example, in a view: 
            $this->layout()->right_side = $this->partial('partials/index.phtml');
            
			It should work just like that. Please note, I created the partials 
            folder in the views -folder. All partials (right -side alternatives)
			should be stored right there. Cheerio. - Tuomas -->
            
			
            if(isset($this->layout()->right_side)){
				echo '<div class="right_side" style="padding: 0px; margin: 0px; margin-top: -52px;">';
				echo $this->layout()->right_side;
				echo '</div>';
			} 
            */
            ?>
			
			
			<div class="before_footer" style="clear: both;"></div>
           
            <!-- Resets the floating row -->
            <div style="clear: both;"></div>
	
            <div id="footer">
                <!-- And the footer... -->
                <div class="footer_links">
                    <span class="link_text">&copy; 2009 <a href="http://massidea.org">Massidea.org</a></span>
                    
                    <span class="link_text">
                        <a href="http://www.massidea.org/blog/?page_id=40">
                            <?php echo $this->translate('index-about'); ?></a>
                    </span>
                    
                    <a href="http://www.massidea.org/blog/?page_id=71">
                    <?php echo $this->translate('index-contact'); ?></a> 
                    
                    <a href="http://www.massidea.org/blog/?page_id=74">
                    	<?php echo $this->translate('index-development'); ?></a> 
                    
                    <a href="#" onclick="popup('popup_terms_'); return false;">
                        <?php echo $this->translate('index-service-agreement'); ?></a> 
                    
                    <a href="#" onclick="popup('popup_privacy_'); return false;">
                        <?php echo $this->translate('index-register-description'); ?></a>
                </div>
                
                <img src="<?php echo $this->baseUrl('/images/gray_dot_line_720.png'); ?>" 
                    class="image_line" alt="Massidea.org"
                />
                
                <div id="footer_left" class="footer_left">
                    <div id="footer_funded" class="footer_funded">
                        <?php echo $this->translate('index-funded'); ?>
                    </div>
                    
                    <a href="http://www.rakennerahastot.fi/rakennerahastot/<?php echo $this->language; ?>/index.jsp">
                        <img src="<?php echo $this->baseUrl('/images/footer1.png'); ?>" alt="Footer" />
                    </a>
                </div>
                
                <div id="footer_right" class="footer_right">
                    <div id="footer_coordinator" class="footer_coordinator">
                        <?php echo $this->translate('index-coordinator'); ?>
                    </div>
                    <?php
                    // This entire block should be done somewhere else than here
                    $uniUrl['cop'] = 'http://www.cop.fi/';
                    $uniUrl['hamk'] = 'http://www.hamk.fi/';
                    $uniUrl['tkk'] = 'http://www.tkk.fi/';
                    $uniUrl['humak'] = 'http://www.humak.fi/';
                    $uniUrl['tokem'] = 'http://www.tokem.fi/';
                    $uniUrl['kyamk'] = 'http://www.kyamk.fi/';
                    $uniUrl['laurea'] = 'http://www.laurea.fi/';
                    $uniUrl['piramk'] = 'http://www.tamk.fi/';
                    $uniUrl['ramk'] = 'http://www.ramk.fi/';
                    $uniUrl['samk'] = 'http://www.samk.fi/';
                    $uniUrl['tamk'] = 'http://www.tamk.fi/';
                    $uniUrl['tse'] = 'http://www.tse.fi/';
                    
                    if ($this->language = 'en') {
                        $uniUrl['laurea'] = 'http://www.laurea.fi/internet/en/index.jsp';
                    }
                    ?>
                    <a href="<?php echo $uniUrl['laurea']; ?>">
                        <img src="<?php echo $this->baseUrl('/images/laurea.png'); ?>" alt="Laurea" />
                    </a>
                    
                    <div id="footer_group" class="footer_group">
                        <?php echo $this->translate('index-group'); ?>
                    </div>
                    
                    <select id="project_groups">
                        <option value="0">Select partner university</option>
                        <option value="<?php echo $uniUrl['cop']; ?>">
                            Central Ostrobothnia University of Applied Sciences
                        </option>
                        <option value="<?php echo $uniUrl['hamk']; ?>">
                            HAMK University of Applied Sciences
                        </option>
                        <option value="<?php echo $uniUrl['tkk']; ?>">
                            Helsinki University of Technology
                        </option>
                        <option value="<?php echo $uniUrl['humak']; ?>">
                            HUMAK University of Applied Sciences
                        </option>
                        <option value="<?php echo $uniUrl['tokem']; ?>">
                            Kemi-Tornio University of Applied Sciences
                        </option>
                        <option value="<?php echo $uniUrl['kyamk']; ?>">
                            Kymenlaakso University of Applied Sciences
                        </option>
                        <option value="<?php echo $uniUrl['laurea']; ?>">
                            Laurea University of Applied Sciences
                        </option>
                        <option value="<?php echo $uniUrl['piramk']; ?>">
                            PIRAMK University of Applied Sciences
                        </option>
                        <option value="<?php echo $uniUrl['ramk']; ?>">
                            Rovaniemi University of Applied Sciences
                        </option>
                        <option value="<?php echo $uniUrl['samk']; ?>">
                            Satakunta University of Applied Sciences
                        </option>
                        <option value="<?php echo $uniUrl['tamk']; ?>">
                            TAMK University of Applied Sciences
                        </option>
                        <option value="<?php echo $uniUrl['tse']; ?>">
                            Finland Future Research Center
                        </option>
                    </select>
                </div>
                
                <img src="<?php echo $this->baseUrl('/images/gray_dot_line_720.png'); ?>" 
                    class="image_line" alt="Massidea.org"
                />
            </div>
            
            <!-- Resets the floating row and adds a small margin for the bottom -->
            <div style="height: 10px; clear: both;"></div>
        </div>
    </div>
    
    <!-- this is the pseudo-div used for the bakcdrop of all css-popups -->
    <div id="backdrop" onclick="popup_close(); popup_terms_close()"></div>  
    
    <!-- globally accessible pop-ups -->
    <div id="popup_terms_" class="popup_terms" style="display:none;">
        <div class="popup_close" style="">  
            <div style="float:right;">
                <a href="#" onclick="popup_terms_close('')">
                    <img src="<?php echo $this->baseUrl('/images/icon_close.png') ?>" alt="Close" />
                </a>
            </div>       
        </div>
        
        <div class="privacy">
            <?php echo $this->translate('network-service-agreement'); ?>
        </div>      
    </div>

    <div id="popup_privacy_" class="popup_terms" style="display:none;">
        <div class="popup_close">
            <div style="float:right;">
                <a href="#" onclick="popup_terms_close('')">
                    <img src="<?php echo $this->baseUrl('/images/icon_close.png'); ?>" alt="Close" />
                </a>
            </div>
        </div>
        
        <div class="privacy">
            <?php echo $this->translate('register-description'); ?>
        </div>
    </div>
    
    <div id="jsmetabox" style="display:none;">
    	<?php echo $this->jsmetabox->output(); ?>
    </div>
</body>
</html>
