<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<?php $this->headScript()->appendFile($this->baseUrl . '/js/CheckGacForm.js'); ?>

<?php $this->headScript()->captureStart()?>
// Definitions for input boxes ([0] = minimum, [1] = maximum, [2] = required (1 true/0 false)
var inputDefinitions = {
    'groupname': [1,  140, 1],
    'groupdesc': [1,  320, 1],
    'groupbody': [1,  4000, 1]
};
<?php $this->headScript()->captureEnd()?>

<div id="add-content-page" style="float:left; width:500px;">
    <h2><?php echo $this->translate('groups-create_new_group'); ?></h2>

    <p>Group collects together individual users who share mutual interest such as studies,
        hobbies, association activities, job or place of residence.</p>

    <p>All logged in users can create as many groups as they want and linked their own
        groups to other groups.</p>

    <div id="add_content_form">
        <?php echo $this->form; ?>
    </div>
</div>

<div id="sidebar" style="margin-left:20px; margin-right:0;">
    <div class="box">
        <h2>How to create a group?</h2>
        <div class="box-content">
            <p><strong>Name</strong><br />
                Name capture the essence of group’s interest and goals. It can
                also be name of your organization, asso-ciation, studying course, etc.</p>

            <p><strong>Type</strong><br />
                Open group: All users are accepted as group members without admin approaval.</p>

            <p>Closed group: Becoming a member requires group admin’s approval. Regardless
                of type, all group related contents are visible for all users. However,
                only group members can link content to group’s campaigns.</p>

            <p><strong>Short description</strong><br />
                Shortly explain the purpose of the group by answering to what, who and whom
                questions. This information is shown on the group listing pages and therefore
                is important tool to attract users.</p>

            <p><strong>Full description</strong><br />
                Is elaborating in more detail the group and it’s purpose by answer following questions:</p>

            <p>1) What is the group.</p>

            <p>2) Who is running the group and whom should be interested to join in.</p>

            <p>3) Why the group is important and valuable.</p>

            <p>4) Where group is operating (can be geographical location or circumstances)</p>

            <p>5) When (temporal dimension) the group is operating. Is this a permanent group
                for long-term collabora-tion or temporary and operating only limited time.</p>
        </div>
    </div>
</div>