<?php $this->headScript()->appendFile($this->baseUrl . '/js/CheckGacForm.js'); ?>

<?php $this->headScript()->captureStart()?>
// Definitions for input boxes ([0] = minimum, [1] = maximum, [2] = required (1 true/0 false)
var inputDefinitions = {
    'groupname': [1,  140, 1],
    'groupdesc': [1,  320, 1],
    'groupbody': [1,  4000, 1]
};
<?php $this->headScript()->captureEnd()?>
<h2><?php echo $this->translate('create-group-title'); ?></h2>
   <?php echo $this->form; ?>