<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<?php $this->headScript()->appendFile($this->baseUrl . '/js/CheckGacForm.js'); ?>

<?php $this->headScript()->captureStart()?>
// Definitions for input boxes ([0] = minimum, [1] = maximum, [2] = required (1 true/0 false)
var inputDefinitions = {
    'groupname': [1,  140, 1],
    'groupdesc': [1,  320, 1],
    'groupbody': [1,  4000, 1]
};
<?php $this->headScript()->captureEnd()?>

<div id="add-content-page" style="float:left; width:500px;">
    <h2>Edit group <?php echo $this->grpName; ?></h2>

    <p>Groups help like-minded people to join their forces. You can create as many groups as you want.
    Once you have created a group you can create group campaigns.</p>

    <p>All fields are mandatory.</p>

    <div id="add-content-form">
        <?php echo $this->form; ?>
    </div>
</div>

<div id="sidebar" style="margin-left:20px; margin-right:0;">
    <div class="box">
        <h2>How to create a group?</h2>
        <div class="box-content">
            <p><strong>Name</strong><br />
            A good name grabs the reader's attention and summarizes the meaning
            of the group.</p>

            <p><strong>Lead paragraph</strong><br />
            Lead paragraph sums up the whole meaning of your group.</p>

            <p><strong>Body</strong><br />
            The further body content is elaborating the headline and lead paragraph,
            and justifies in more detail, why you should join the group.</p>
        </div>
    </div>
</div>