<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<div id="group-page">
    <?php echo $this->partial('partials/group_header.phtml', $this->grpData); ?>
    <?php echo $this->partial('partials/group_menu.phtml', $this->menuData); ?>
    <div id="activity" class="right">
        <div class="left group-feeds">
            <?php if($this->isAdmin): ?>
            <p id="group-feeds-edit"><a href="<?php echo $this->editFeedsLink; ?>">&gt; Edit feeds</a></p>
            <?php endif;?>
            <?php
            if ($this->hasFeeds) {
                foreach($this->feeds['titles'] as $feedHead) {
                    ?>
                    <h3><?php echo $feedHead; ?></h3>
                    <ul>
                    <?php
                    foreach($this->feeds['items'] as $feed) {
                        if ($feed['cTitle'] === $feedHead) {
                            ?>
                            <li><a href="<?php echo $feed['link']; ?>"><?php echo $feed['title']; ?></a></li>
                            <?php
                        }
                    }
                    ?>
                    </ul>
                    <?php
                }
            } else {
                ?>
                <p>This group does not have feeds. Only the group admin can add them.</p>
                <?php
            }
            ?>
            <h3></h3>
        </div>
    </div>
</div>