<h2><?php echo $this->translate('groups-title'); ?></h2>

<h4><?php echo $this->translate('groups-all_groups') . ":"; ?></h4>
<table cellpadding="2" cellspacing="0" style="padding-bottom: 20px;">
    <tr>
        <td style="font-style: italic; border-bottom: 1px solid black; padding-right: 10px;"><?php echo $this->translate('groups-name'); ?></td>
        <td style="font-style: italic; border-bottom: 1px solid black; padding-left: 10px;"><?php echo $this->translate('groups-description'); ?></td>
    </tr>
<?php foreach ($this->groupdata as $group): ?>
    <tr>
        <td style="border-right: 1px solid black; padding-right: 10px;">
            <?php
                $groupUrl = $this->url(
                    array(
                        'groupid' => $group["id_grp"],
                        'language' => $this->language),
                    'group_shortview',
                    true);
            ?>
            <a href="<?php echo $groupUrl; ?>">
                <?php echo $this->escape($group["group_name_grp"]); ?>
            </a>
        </td>
        <td style="padding-left: 10px;"><?php echo $this->escape($group["description_grp"]); ?></td>
    </tr>
<?php endforeach; ?>
</table>

<?php
    $addgrpurl = $this->url(
        array(
            'controller' => 'group',
            'action'     => 'create',
            'language'   => $this->language
        ), 'lang_default', true);
?>
<p><a href="<?php echo $addgrpurl; ?>">Create new group</a></p>