<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>

<?php
// some variable initiation
$url_getRecentGroups = $this->url(array('controller' => 'ajax',
							 'action' => 'getrecentgroups',
							 'language' => $this->language),
							 'lang_default', true);
?>
<?php $this->headScript()->captureStart()?>

// Variables for ajax requests
var url_getrecentgroups = '<?php echo $url_getRecentGroups; ?>';
var url_ajaxloader = '<?php echo $this->baseUrl('/images/ajax-loader-black.gif'); ?>';

<?php $this->headScript()->captureEnd()?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/recentgroups.js')); ?>

<div id="gaccampaignlist">
    <h3 style="float:left;">Recent groups</h3>

    <?php
    $addgrpurl = $this->url(
        array(
            'controller' => 'group',
            'action'     => 'create',
            'language'   => $this->language
        ),  'lang_default', true);
    ?>

    <?php if ($this->logged_in): ?>
	<h3 style="float:right; margin-right:20px;"><a href="<?php echo $addgrpurl; ?>">&gt; Create new group</a></h3>
    <?php endif; ?>
    
    <div class="clear"></div>
    <div id="group-list" class="group-list"></div>
    <div id="recent_group_ajax_link" style="text-align: center; margin-top: 10px;">
        <h3>
            <a href="#" onclick="return false;">Show more</a>
        </h3>
    </div>
</div>

<?php
$cmpUrl = $this->url(
    array(
        'controller' => 'campaign',
        'action'     => 'index',
        'language'   => $this->language
    ),  'lang_default', true);
?>

<div id="gacsidebar">
    <div class="box">
        <h2>What are groups?</h2>
        <div class="box-content">
            <p>Group collects together individual users who share mutual interest
            such as studies, hobbies, association activities, job or place of residence.</p>

            <p>Groups include <a href="<?php echo $cmpUrl; ?>">campaign</a> functionality
            which help to join forces to achieve a common set of goals. Only group members
            can link content to campaigns.</p>

            <p>All logged in users can create as many groups as they want.</p>

            <p>There are two kind of groups:</p>

            <p>1) Open groups where all users are accepted without admin approaval.</p>

            <p>2) Closed groups where participation requires group admin’s approval.</p>

            <p>All group contents are visible for everybody regardless of group type.</p>

            <p>Group can also add external RSS feeds to their home and campaign pages.</p>
        </div>
    </div>

    <?php /*
    <div id="groups">
        <h3>Recent groups</h3>
        <ul>
            <?php echo $this->partialLoop('partials/group_row_small.phtml', $this->groups); ?>
        </ul>
    </div>

    <div style="text-align: center; margin-top: 20px;">
        <?php $moregrpsurl = $this->url(array('controller' => 'group',
                                              'action'     => 'list',
                                              'language'   => $this->language),
                                          'lang_default', true); ?>
        <strong><a href="<?php echo $moregrpsurl; ?>">Show more</a></strong>
    </div>
    */ ?>
</div>
