<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<div id="group-page">
    <?php echo $this->partial('partials/group_header.phtml', $this->grpData); ?>
    <?php echo $this->partial('partials/group_menu.phtml', $this->menuData); ?>
    <div id="activity" class="right">
        <div class="left">
            <div id="group-description" class="group-text">
                <?php echo $this->grpData['description_grp']; ?>
            </div>
            <div id="group-body" class="group-text">
                <?php echo $this->grpData['body_grp']; ?><?php //Zend_Debug::dump($this->grpData); ?>
            </div>
            <div id="group-admin" class="group-text">
                <?php $grpAdminsCount = count($this->grpData['grp_admins']); ?>
                <p>Group admin:
                    <?php $adminUrl = $this->url(array('controller' => 'account',
                                                       'action' => 'view',
                                                       'user' => $this->grpData['grp_admins'][0]['login_name_usr'],
                                                       'language' =>  $this->language),
                                                 'lang_default', true); ?>
                    <a href="<?php echo $adminUrl; ?>"><?php echo $this->grpData['grp_admins'][0]['login_name_usr']; ?>
                        (<?php echo $this->grpData['grp_admins'][0]['count']; ?>)</a>
                </p>
            </div>
            <?php if (isset($this->grpData['groupWeblinks']) && $this->grpData['groupWeblinks'] != NULL) : ?>
            <?php if(!empty($this->files)) : ?>
            <div id="group-files" class="group-text">
                <p>Added files:
                    <?php $filecount = count($this->files);
                    $file_i = 0;
                    foreach ($this->files as $id_fil => $filename):
                        $file_i++; ?>
                        <a href="<?php echo $this->baseUrl('/en/file/view/'.$id_fil); ?>">
                        <?php echo $filename; ?></a><?php if($file_i < $filecount) echo ', ';
                    endforeach;?>
                </p>
            </div>
            <?php endif; ?>
            <div id="group-links" class="group-text">
                <p class="group-links">Group web links:
                    <?php
                    $count = count($this->grpData['groupWeblinks']);
                    $i = 1;
                    foreach ($this->grpData['groupWeblinks'] as $weblink) {
                    ?>
                    <a href="<?php echo $weblink['url_gwl']; ?>"><?php
                        echo $weblink['name_gwl'];
                    ?></a><?php
                    if ($i != $count)
                        echo ',';
                    $i++;
                    }
                    ?>
                </p>
            </div>
            <?php endif ?>
        </div>
    </div>
</div>