<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<div class="linking">
<h3 class="linking_header">Link to group</h3>
<?php
if($this->grpid != 0 && $this->hasUserGroups == true) {
?>
    <div id="linked_to">
        <div id="linked_to_where">
            <p class="linking_paragraph">Group</p>
        </div>
        <div class="linked_to_where_group">
            <p class="linking_paragraph"><a href="<?php echo $this->url(array('groupid'  => $this->grpid,
                                                                              'language' => $this->language),
                                                                        'group_shortview', true); ?>">
                <?php
                    if(strlen($this->grp['group_name_grp']) > 68) {
                        $this->grp['group_name_grp'] = substr($this->grp['group_name_grp'], 0, 68) . "...";
                    }
                    echo $this->grp['group_name_grp'];
                ?>
            </a></p>
        </div>
    </div>
    <p class="linking_help_text">Groups available for linking</p>
    <?php
    if($this->usrgrp) {
        foreach($this->usrgrp as $group) {
            ?>
            <div class="linking_dot_line"></div>
            <div class="linking_from">
                <div class="linking_from_name">
                    <?php
                    $grpurl = $this->url(array('groupid'    => $group['id_grp'],
                                               'language'   => $this->language),
                                         'group_shortview', true);
                    ?>
                    <div class="linking_from_group">
                        <strong><a href="<?php echo $grpurl; ?>"><?php echo $group['group_name_grp']; ?></a></strong>
                        <p class="linking_from_text"><?php echo $group['description_grp']; ?></p>
                    </div>
                </div>
                <div class="linking_from_link">
                    <?php
                    $linkurl = $this->url(array('controller'  => 'group',
                                                'action'      => 'makegrouplink',
                                                'parentgrpid' => $this->grpid,
                                                'childgrpid'  => $group['id_grp'],
                                                'language'    => $this->language),
                                          'lang_default', true);
                    ?>
                    <a href="<?php echo $linkurl; ?>">Add link</a>
                </div>
            </div>
            <div class="clear"></div>
            <?php
        }
        ?> <div class="linking_dot_line"></div> <?php
    }
} else {
    ?>
    <p>You don't have any groups to link.</p>
    <?php
}
?>
</div>

<div id="sidebar" style="margin-left:20px; margin-right:0;">
    <div class="box">
        <h4>What is group linking?</h4>
        <div class="box-content">
			<p>Combining different groups together boost creativity and helps similar groups to join forces.</p>
			<p>By linking you can create logical relationships between different groups.</p>
			<p>As a group admin you can link your group to other users or to your own groups.</p> 
			<p>One group can be linked to multiple groups.</p> 
			<p>If you want, you can remove links later on by clicking edit groups links in the group’s home page.</p>
            <div class="clear"></div>
        </div>
    </div>
</div>