<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<h2>Groups</h2>

<div id="gaccampaignlist">
    <div class="campaign-list">
        <ul>
            <?php echo $this->partialLoop('partials/group_row.phtml', $this->groups); ?>
        </ul>
    </div>
</div>

<?php
    $addgrpurl = $this->url(
        array(
            'controller' => 'group',
            'action'     => 'create',
            'language'   => $this->language
        ), 'lang_default', true);
?>
<p><a href="<?php echo $addgrpurl; ?>">Create new group</a></p>