<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<div id="group-page">
    <?php echo $this->partial('partials/group_header.phtml', $this->grpData); ?>
    <?php echo $this->partial('partials/group_menu.phtml', $this->menuData); ?>
    <div id="activity" class="right">
        <div class="left">
            <p><?php Zend_Debug::dump($this->grpUsers); ?></p>
        </div>
    </div>
</div>