<?php $this->headScript()->captureStart(); ?>
function deleteconfirmation(url) {
    var answer = confirm("Delete group? This will also delete all of the group's campaigns.");
    if (answer) {
        alert("Group deleted");
        window.location = url;
    } else {
        //alert("");
    }
}
<?php $this->headScript()->captureEnd(); ?>
<?php $this->headScript()->prependFile($this->baseUrl('/js/comments.js')); ?>
<?php
Zend_Layout::getMvcInstance()->setLayout('layout_new');
$date_founded = new Zend_Date($this->grpData['created_grp'], Zend_Date::ISO_8601);
?>
<div id="group-page">
    <h2><?php echo $this->grpData["group_name_grp"]; ?></h2>

    <div id="profile-meta">
        <?php //TODO: tähän tulostetaan ryhmän kuva, ei tätä kiinteää kuvaa ?>
        <!-- <img class="avatar" alt="Group profile picture" src="/en/account/profilethumb/id/1/thumb/true" /> -->

        <p><?php echo $this->grpData["description_grp"]; ?></p>
        <?php //TODO:muutä tätä järkevämmäksi? ?>
        <!--
        <p><strong><a href="<?php echo $this->url(array('controller' => 'tag',
                                                        'action' => 'index',
                                                        'language' => $this->language),
                                                        'lang_default', true); ?>">
                  <?php echo $this->translate('content-view-tags'); ?>
                  </a>
            </strong><?php // tägit tähän väliin ?></p>
        -->
        <p><strong><?php echo $this->translate('group-founded') . ': '; ?></strong><?php echo $date_founded->toString('dd MMM, yyyy'); ?></p>
        <strong><?php echo $this->translate('group-admins') . ':'; ?></strong>
		<ul>
        <?php echo $this->partialLoop('partials/user_row.phtml', $this->grpAdmins); ?>
        </ul>
        <h4><?php echo $this->translate('group-members'); ?></h4>
        <!--<span class="more"><strong><a href="">Show all</a></strong></span>-->
        <div class="clear"></div>
        <ul>
           <?php echo $this->partialLoop('partials/user_row.phtml', $this->grpUsers); ?>
        </ul>
        <!--<span class="more"><strong><a href="">Show all</a></strong></span>-->
        <div class="clear dot-line-200"></div>
        <div>
            <p>
                <strong>Linked groups: </strong>
                <br />
                <ul>
                    <?php //var_dump($this->linkedgroups); ?>
                    <?php
                    foreach($this->linkedgroups as $group) {
                        $grpurl = $this->url(array('groupid'    => $group['id_grp'],
                                                   'language'   => $this->language),
                                             'group_shortview', true);
                        ?>
                        <li class="linked_groups">
                            <div class="linked_groups">
                                <strong><a href="<?php echo $grpurl; ?>"><?php echo $group['group_name_grp']; ?></a></strong>
                            </div>
                        </li>
                        <?php
                    }
                    ?>
                </ul>
            </p>
            <?php
            $addgroups = $this->url(
                                array(
                                    'controller' => 'group',
                                    'action'     => 'linkgroup',
                                    'language'   => $this->language,
                                    'grpid'      => $this->grpData["id_grp"]
                                 ), 'lang_default', true
                            );
            $editgrouplinks = $this->url(
                                array(
                                    'controller' => 'group',
                                    'action'     => 'unlinkgroup',
                                    'language'   => $this->language,
                                    'grpid'      => $this->grpData["id_grp"]
                                 ), 'lang_default', true
                            );
            ?>
            <p><a href="<?php echo $addgroups; ?>">Add groups</a></p>
            <?php if ($this->userIsGroupAdmin): ?>
                <p><a href="<?php echo $editgrouplinks; ?>">Edit group links</a></p>
            <?php endif; ?>
        </div>
    </div>
    <div id="activity" class="right">
        <div class="left">
            <div id="group-info">
                <?php if ($this->userIsGroupAdmin):
                    $editlink = $this->url(
                        array(
                            'controller' => 'group',
                            'action'     => 'edit',
                            'language'   => $this->language,
                            'id'         => $this->grpData["id_grp"]
                        ), 'lang_default', true
                    );
                    $dellink = $this->url(
                        array(
                            'controller' => 'group',
                            'action'     => 'remove',
                            'language'   => $this->language,
                            'id'         => $this->grpData["id_grp"]
                         ), 'lang_default', true
                    );
                    $waitinglist = $this->url(
                        array(
                            'controller' => 'group',
                            'action'     => 'waitinglist',
                            'language'   => $this->language,
                            'grpid'      => $this->grpData["id_grp"]
                        ), 'lang_default', true
                    );
                ?>
                <div id="edit-group-etc">
                    <p class="join">
                        <a href="<?php echo $editlink; ?>">Edit group</a> |
                        <!--<a href="#">Edit group links</a> |-->
                        <a href="#" onclick="deleteconfirmation('<?php echo $dellink; ?>')">Delete group</a> |
                        <a href="<?php echo $waitinglist; ?>">Waiting&nbsp;list (<?php echo $this->usrWaitingCount; ?>)</a>
                    </p>
                </div>
                <?php endif; ?>

                <p><?php echo $this->grpData['body_grp']; ?></p>

                <?php if (isset($this->grpData['groupWeblinks']) && $this->grpData['groupWeblinks'] != NULL) : ?>
                <div id="group-links">
                    <p class="group-links">Group links:
                        <?php
                        $count = count($this->grpData['groupWeblinks']);
                        $i = 1;
                        foreach ($this->grpData['groupWeblinks'] as $weblink) {
                        ?>
                        <a href="<?php echo $weblink['url_gwl']; ?>"><?php
                            echo $weblink['name_gwl'];
                        ?></a><?php
                        if ($i != $count)
                            echo ',';
                        $i++;
                        }
                        ?>
                    </p>
                </div>
                <?php endif; ?>
            </div>
            <div class="clear"></div>
            <div id="group-campaigns">
                <h3>Campaigns</h3>
                <p>Group's call of contents</p>
            </div>
            <?php if ($this->identity == true) : ?>
            <div id="join-group">
                <?php
                if ($this->userIsGroupAdmin):
                     $cmplink = $this->url(
                         array(
                            'controller' => 'campaign',
                            'action'     => 'create',
                            'language'   => $this->language,
                            'grpid'      => $this->grpData["id_grp"]
                         ), 'lang_default', true
                );
                ?>
                <p class="join">
                    <a href="<?php echo $cmplink; ?>">&gt;&nbsp;Create a campaign</a>
                </p>
                <?php else : ?>
                    <?php if ($this->isClosed && !$this->userHasGroup->userHasGroup($this->grpId, $this->userid)) : ?>
                        <?php if (!$this->userHasGroupWaiting->userWaitingGroup($this->grpId, $this->userid)):
                            $joinwaitingurl = $this->url(
                                array(
                                    'controller' => 'group',
                                    'action' => 'join',
                                    'groupid' => $this->grpId,
                                    'language' => $this->language
                                ), 'lang_default', true
                            );
                        ?>
                        <p class="join">
                            <a href="<?php echo $joinwaitingurl; ?>">&gt; <?php echo $this->translate('group-join-waiting_group'); ?></a>
                        </p>
                        <?php else:
                            $leavewaitingurl = $this->url(
                                array(
                                    'controller' => 'group',
                                    'action' => 'leavewaiting',
                                    'groupid' => $this->grpId,
                                    'language' => $this->language
                                ), 'lang_default', true);
                        ?>
                        <p class="join">
                            <a href="<?php echo $leavewaitingurl; ?>">&gt; <?php echo $this->translate('group-leave-waiting_group'); ?></a>
                        </p>
                        <?php endif; ?>
                    <?php else : ?>
                        <?php if (!$this->userHasGroup->userHasGroup($this->grpId, $this->userid)):
                            $joinurl = $this->url(
                                array(
                                    'controller' => 'group',
                                    'action' => 'join',
                                    'groupid' => $this->grpId,
                                    'language' => $this->language
                                ), 'lang_default', true
                            );
                        ?>

                        <p class="join">
                            <a href="<?php echo $joinurl; ?>">&gt; <?php echo $this->translate('group-join_group'); ?></a>
                        </p>
                        <?php else:
                            $leaveurl = $this->url(
                                array(
                                    'controller' => 'group',
                                    'action' => 'leave',
                                    'confirm' => 0,
                                    'groupid' => $this->grpId,
                                    'language' => $this->language
                                ), 'lang_default', true);
                        ?>
                        <p class="join">
                            <a href="<?php echo $leaveurl; ?>">&gt; <?php echo $this->translate('group-leave_group'); ?></a>
                        </p>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <p>Only by joining you can add contents to campaigns</p>
            </div>
            <?php endif; ?>
            <div class="clear"></div>
            <div class="scroll-box">
                <ul>
                    <?php //echo $this->partialLoop('partials/campaign-row.phtml', $this->campaigns); ?>
                    <?php if (count($this->openCampaigns) != 0) : ?>
                    <li style="border: none;"><h4 style="margin-bottom: 0;">Open:</h4></li>
                    <?php echo $this->partialLoop('partials/campaign-row.phtml', $this->openCampaigns); ?>
                    <?php endif;
                    if (count($this->notstartedCampaigns) != 0) : ?>
                    <li style="border: none;"><h4 style="margin-bottom: 0;">Not started:</h4></li>
                    <?php echo $this->partialLoop('partials/campaign-row.phtml', $this->notstartedCampaigns); ?>
                    <?php endif;
                    if (count($this->endedCampaigns) != 0) : ?>
                    <li style="border: none;"><h4 style="margin-bottom: 0;">Ended:</h4></li>
                    <?php echo $this->partialLoop('partials/campaign-row.phtml', $this->endedCampaigns); ?>
                    <?php endif; ?>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
         		<?php echo $this->partial('partials/comments.phtml', array('comments' => $this->comments)); ?>
        
    </div>
</div>
