<div class="linking_content">
<h3 class="recent_posts"><?php echo $this->translate('campaign-unlink-content-from-campaign'); ?></h3>
<?php
if($this->campaignexists) {
?>
    <div id="linkedto" class="linkedto" style="margin-bottom: 10px;">
        <p class="linkedtotext">Campaign</p>
        <img class="linkedtoimage" src="/images/blue_vertical_line_small.png" alt="<?php echo $linkedColor; ?>" />

        <p style="padding-top: 9px;">
            <a href="<?php echo $this->url(array('cmpid' => $this->relatesToId,
                                                     'language' => $this->language),
                                                     'campaign_view', true); ?>">
                <?php
                    if(strlen($this->relatesToCampaignName) > 68) {
                        $this->relatesToCampaignName = substr($this->relatesToCampaignName, 0, 68) . "...";
                    }
                    echo $this->relatesToCampaignName;
                ?>
            </a>
        </p>
    </div>

    <p style="color: #808080; margin: 10px 0 8px 15px;">This campaign is currently linked to following content(s)</p>
    <?php
    if($this->contents) {
        foreach($this->contents as $content) {
            ?>
            <div class="form_helptext_line"></div>
            <div style="height: 20px;">
                <div style="float: left; width: 420px;">
                    <?php
                    if($content['key_cty'] == 'challenge') {
                        $color = "red";
                    }
                    elseif($content['key_cty'] == 'visions') {
                        $color = "yellow";
                    }
                    elseif($content['key_cty'] == 'ideas') {
                        $color = "green";
                    }
                    ?>
                    <img class="linkedtoimage" src="<?php echo $this->baseUrl."/images/".$color; ?>_vertical_line_small.png" alt="<?php echo $color; ?>" height="15" width="4"/>
                    <?php
                    $linkusr = $this->url(array('controller' => 'account',
                                                'action' => 'view',
                                                'user' => $content['login_name_usr'],
                                                'language' => $this->language),
                                          'lang_default', true);
                    $linkurl = $this->url(array('content_id' => $content['id_cnt'],
                                                'language' => $this->language),
                                          'content_shortview', true);
                    ?>
                    <a href="<?php echo $linkusr; ?>"><?php echo $content['login_name_usr']; ?></a> :
                    <strong><a href="<?php echo $linkurl; ?>"><?php echo $content['title_cnt']; ?></a></strong>
                    <p style="margin: 4px 0 4px 20px;"><?php echo $content['lead_cnt']; ?></p>
                </div>
                <div style="margin-top: 4px;">
                    <?php
                        $linkurl = $this->url(array('contenttype' => $content['key_cty'],
                                                'cmpid'    => $this->relatesToId,
                                                'cntid'    => $content['id_cnt'],
                                                'language' => $this->language),
                                          'removecampaignlinks', true);
                        ?>
                    <a href="<?php echo $linkurl; ?>"><?php echo $this->translate('content-unlink'); ?></a>
                </div>
            </div>
            <div style="clear: both;"></div>
            <?php
        }
        ?> <div class="form_helptext_line"></div> <?php
    }
} else {
    ?>
    <p><?php echo $this->translate('campaign-content-not-exists'); ?></p>
    <?php
}
?>
</div>
<div class="right_side" style="padding: 0px; margin-right: 5px; margin-top: 0px;">
    What is campaign linking?
</div>