<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<div class="linking">
<h3 class="linking_header">Edit campaign content link(s)</h3>
<?php
if($this->campaignexists) {
?>
    <div id="linked_to">
        <div id="linked_to_where">
            <p class="linking_paragraph">Campaign</p>
        </div>
        <div id="linked_to_where_name">
            <p class="linking_paragraph"><a href="<?php echo $this->url(array('cmpid'    => $this->relatesToId,
                                                                              'language' => $this->language),
                                                                        'campaign_view', true); ?>">
                <?php
                    if(strlen($this->relatesToCampaignName) > 68) {
                        $this->relatesToCampaignName = substr($this->relatesToCampaignName, 0, 68) . "...";
                    }
                    echo $this->relatesToCampaignName;
                ?>
            </a></p>
        </div>
    </div>
    <p class="linking_help_text">This campaign is currently linked to following content(s)</p>
    <?php
    if($this->contents) {
        foreach($this->contents as $content) {
            ?>
            <div class="linking_dot_line"></div>
            <div class="linking_from">
                <div class="linking_from_name">
                    <?php
                    $linkusr = $this->url(array('controller' => 'account',
                                                'action' => 'view',
                                                'user' => $content['login_name_usr'],
                                                'language' => $this->language),
                                          'lang_default', true);
                    $linkurl = $this->url(array('content_id' => $content['id_cnt'],
                                                'language' => $this->language),
                                          'content_shortview', true);
                    ?>
                    <div class="linking_from_<?php echo $content['key_cty']; ?>">
                        <a href="<?php echo $linkusr; ?>"><?php echo $content['login_name_usr']; ?></a> :
                        <strong><a href="<?php echo $linkurl; ?>"><?php echo $content['title_cnt']; ?></a></strong>
                        <p class="linking_from_text"><?php echo $content['lead_cnt']; ?></p>
                    </div>
                </div>
                <div class="linking_from_link">
                    <?php
                        $linkurl = $this->url(array('contenttype' => $content['key_cty'],
                                                'cmpid'    => $this->relatesToId,
                                                'cntid'    => $content['id_cnt'],
                                                'language' => $this->language),
                                          'removecampaignlinks', true);
                        ?>
                    <a href="<?php echo $linkurl; ?>">Remove link</a>
                </div>
            </div>
            <div class="clear">&nbsp;</div>
            <?php
        }
        ?> <div class="linking_dot_line"></div> <?php
    }
} else {
    ?>
    <p><?php echo $this->translate('campaign-content-not-exists'); ?></p>
    <?php
}
?>
</div>

<div id="sidebar" style="margin-left:20px; margin-right:0;">
    <div class="box">
        <h4>What is campaign content unlinking?</h4>
        <div class="box-content">
            <p><strong></strong><br />
            </p>

            <p><strong></strong><br />
            </p>

            <div class="clear"></div>
        </div>
    </div>
</div>