<?php $this->headScript()->appendFile($this->baseUrl . '/js/CheckGacForm.js'); ?>

<?php $this->headScript()->captureStart(); ?>
// Definitions for input boxes ([0] = minimum, [1] = maximum, [2] = required (1 true/0 false)
var inputDefinitions = {
    'campaign_name':    [1,  140, 1],
    'campaign_ingress': [1,  320, 1],
    'campaign_desc':    [1,  4000, 1]
};
<?php $this->headScript()->captureEnd(); ?>

<div id="add-content-page" style="float:left; width:500px;">
    <!--<p>Group id: <?php echo $this->grpid; ?></p>-->
    <h2>Create a new campaign</h2>
    <p>Campaign is group’s organized and coordinated effort to promote content
        production to a specified theme.</p>
    <p>Linking content to campaign requires group membership. Group admin can
        also link own campaigns to other campaigns, which help similar campaigns
        to join forces.</p>
    <div id="add_content_form">
        <?php echo $this->form; ?>
    </div>
</div>

<div id="sidebar" style="margin-left:20px; margin-right:0;">
    <div class="box">
        <h4>How to create a campaign?</h4>
        <div class="box-content">
            <p><strong>Name</strong><br />
            Name capture the essence of campaign goals</p>

            <p><strong>Short description</strong><br />
                Shortly explain the purpose of the campaign by answering to what,
                who and whom questions.<p>

            <p>This information is shown on the campaign listing pages and therefore
                is important tool to attract users.<p>

            <p><strong>Full description</strong><br />
                Is elaborating in more detail the campaign and it’s purpose by answer
                following questions:<p>

            <p>1) What is the campaign.<p>

            <p>2) Who is running the campaign and whom should be interested to join in.<p>

            <p>3) Why the campaign is important and valuable.<p>

            <p>4) Where campaign is operating (can be geographical location or circumstances)<p>

            <p>5) When (temporal dimension) the campaign is active. Is this a permanent campaign
                for long-term collaboration or temporary and operating only limited time.<p>
            <div class="clear"></div>
        </div>
    </div>
</div>