<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>

<?php
// some variable initiation
$url_getRecentCampaigns = $this->url(array('controller' => 'ajax',
							 'action' => 'getrecentcampaigns',
							 'language' => $this->language),
							 'lang_default', true);


/* FIXME: Can't create campaing without creating group

$createCampaignUrl = $this->url(array(	'controller' => 'campaign',
					'action'     => 'create',
					'language'   => $this->language),  'lang_default', true);
*/
?>
<?php $this->headScript()->captureStart()?>

// Variables for ajax requests
var url_getrecentcampaigns = '<?php echo $url_getRecentCampaigns; ?>';
var url_ajaxloader = '<?php echo $this->baseUrl('/images/ajax-loader-black.gif'); ?>';

<?php $this->headScript()->captureEnd()?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/recentcampaigns.js')); ?>

<div id="gaccampaignlist">
    <h3 style="float:left;">Recent campaigns</h3>
    
    <div class="clear"></div>
    <div id="campaign-status" class="campaign-status">
        <a href="#" id="active" onclick="return false;">Active</a> |
        <a href="#" id="forthcoming" onclick="return false;">Forthcoming</a> |
        <a href="#" id="ended" onclick="return false;">Ended</a>
    </div>
    
    <div id="campaign-list" class="campaign-list"></div>
    <div id="recent_campaigns_ajax_link" style="text-align: center; margin-top: 10px;">
        <h3>
            <a href="#" onclick="return false;">Show more</a>
        </h3>
    </div>
</div>

<div id="gacsidebar">
    <div class="box">
        <h2>What are campaigns?</h2>
        <div class="box-content">

            <p>To collect multiple insights, group can launch
            a campaign and summarize individual user’s insights
            into one united theme. Basically campaign is group’s
            organized and coordinated effort to promote content
            production to a specified theme.</p>

            <p>Adding content to campaign requires group membership.
            Moreover, users can only link their own already published
            existing contents to a campaign. One content can be linked
            to multiple campaigns.</p>

        </div>
    </div>

    <?php /*
    <div id="groups">
        <h3>Recent groups</h3>
        <ul>
            <?php echo $this->partialLoop('partials/group_row_small.phtml', $this->groups); ?>
        </ul>
    </div>

    <div style="text-align: center; margin-top: 20px;">
        <?php $moreCampaignUrl = $this->url(array('controller' => 'campaign',
                                              'action'     => 'list',
                                              'language'   => $this->language),
                                          'lang_default', true); ?>
        <strong><a href="<?php echo $moreCampaignUrl; ?>">Show more</a></strong>
    </div>
    */ ?>
</div>
