<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>

<?php
// some variable initiation
$url_getRecentCampaigns = $this->url(array('controller' => 'ajax',
							 'action' => 'getrecentcampaigns',
							 'language' => $this->language),
							 'lang_default', true);

$grpUrl = $this->url(array('controller' => 'group',
							'language' => $this->language),
							'lang_default', true);
/* FIXME: Can't create campaing without creating  group

$createCampaignUrl = $this->url(array(	'controller' => 'campaign',
					'action'     => 'create',
					'language'   => $this->language),  'lang_default', true);
*/
?>
<?php $this->headScript()->captureStart()?>

// Variables for ajax requests
var url_getrecentcampaigns = '<?php echo $url_getRecentCampaigns; ?>';
var url_ajaxloader = '<?php echo $this->baseUrl('/images/ajax-loader-black.gif'); ?>';

<?php $this->headScript()->captureEnd()?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/recentcampaigns.js')); ?>


<div id="gaccampaignlist" class="left narrow">
    <h3 class="left">Campaigns</h3>

    
    <?php // There is only tabs style from jquery tabs. Implementation is how it have been. ?>

    <div class="clear"></div>
    <div id="campaign-status" class="ui-tabs">
        <ul >
            <li id="active_tab" ><a href="<?php echo $this->baseUrl ?>/en/ajax/getrecentcampaigns/offset/1/status/active" title="active">Active</a></li>
            <li id="forthcoming_tab" ><a href="<?php echo $this->baseUrl ?>/en/ajax/getrecentcampaigns/offset/1/status/forthcoming" title="forthcoming">Forthcoming</a></li>
            <li id="ended_tab" ><a href="<?php echo $this->baseUrl ?>/en/ajax/getrecentcampaigns/offset/1/status/ended" title="ended">Ended</a></li>
        </ul>
        
        <div id="active" class="nolist">
        
        </div>
        <div id="forthcoming" class="nolist">
        
        </div>
        <div id="ended" class="nolist">
        
        </div>

        
    </div>
    
    <div id="campaign-list" class="campaign-list"></div>
    <div id="recent_campaigns_ajax_link" style="text-align: center; margin-top: 10px;">
        <h3>
            <a href="#" onclick="return false;">Show more</a>
        </h3>
    </div>
</div>
</div>
<div id="sidebar">
    <div class="box">
        <h2>What are campaigns?</h2>
        <div class="box-content">

            <p>To collect multiple insights, <a href="<?php echo $grpUrl; ?>">group</a> can launch 
            a campaign and summarize individual user’s 
            insights into one united theme.</p> 

			<p>Basically campaign is <a href="<?php echo $grpUrl; ?>">group’s</a> organized and
			 coordinated effort	to promote content production 
			 to a specified theme.</p>

			<p>Adding content to campaign requires group 
			membership. To join, go to <a href="<?php echo $grpUrl; ?>">group’s</a> homepage.</p>

			<p>Moreover, users can only link their own already 
			published contents to a campaign. One content can 
			be linked to multiple campaigns.</p>

			<p><a href="<?php echo $grpUrl; ?>">Group</a> admin can also link own campaigns to other 
			campaigns, which help similar campaigns to join 
			forces.</p>
        </div>
    </div>
    <?php /*
    <div id="groups">
        <h3>Recent groups</h3>
        <ul>
            <?php echo $this->partialLoop('partials/group_row_small.phtml', $this->groups); ?>
        </ul>
    </div>

    <div style="text-align: center; margin-top: 20px;">
        <?php $moreCampaignUrl = $this->url(array('controller' => 'campaign',
                                              'action'     => 'list',
                                              'language'   => $this->language),
                                          'lang_default', true); ?>
        <strong><a href="<?php echo $moreCampaignUrl; ?>">Show more</a></strong>
    </div>
    */ ?>
    <!--  Missing a feature? -->
	<h2>
		<?php echo $this->translate('content-list-missing-header'); ?>
	</h2> 
	<p>
		<?php echo $this->translate('index-opensource'); ?>
	</p>
	<!--  End of Missing a feature? -->
    