<div class="linking_content">
<h3 class=\"recent_posts\"><?php echo $this->translate('campaign-link-content-to-campaign'); ?></h3>
<?php
if($this->cmpid != 0 && $this->hasUserContents == true) {
?>
    <div id="linkedto" class="linkedto" style="margin-bottom: 10px;">
        <p class="linkedtotext">
            <?php echo $this->translate('campaign-link-target',
                                                    $this->language);
            ?>
        </p>
        <?php
        // This should be campaign color
        $color = "red";
        ?>
        <img class="linkedtoimage" src="<?php echo $this->baseUrl."/images/".$color; ?>_vertical_line_small.png" alt="<?php echo $color; ?>" />

        <p style="padding-top: 9px;">
            <a href="<?php echo $this->url(array('cmpid' => $this->cmpid,
                                                 'language' => $this->language),
                                           'campaign_view', true); ?>">
                <?php
                    if(strlen($this->cmp['name_cmp']) > 68) {
                        $this->cmp['name_cmp'] = substr($this->cmp['name_cmp'], 0, 68) . "...";
                    }
                    echo $this->cmp['name_cmp'];
                ?>
            </a>
        </p>
    </div>

    <p style="color: #808080; margin: 10px 0 8px 15px;"><?php echo $this->translate('campaign-link-helptext'); ?></p>
    <?php
    if($this->usrcnt) {
        foreach($this->usrcnt as $content) {
            if($content['published_cnt'] != 0) {
                ?>
                <div class="form_helptext_line"></div>
                <div style="height: 20px;">
                    <div style="float: left; width: 445px;">
                        <?php
                        if($content['key_cty'] == "problem") {
                            $linkedColor = "red";
                        }
                        elseif($content['key_cty'] == "finfo") {
                            $linkedColor = "yellow";
                        }
                        elseif($content['key_cty'] == "idea") {
                            $linkedColor = "green";
                        }
                        ?>
                        <img class="linkedtoimage" src="<?php echo $this->baseUrl."/images/".$linkedColor; ?>_vertical_line_small.png" alt="<?php echo $linkedColor; ?>" height="15" width="4"/>
                        <?php
                        $linkurl = $this->url(array('content_id' => $content['id_cnt'],
                                                    'language' => $this->language),
                                              'content_shortview', true);
                        ?>
                        <strong><a href="<?php echo $linkurl; ?>"><?php echo $content['title_cnt']; ?></a></strong>
                        <p style="margin: 4px 0 4px 20px;"><?php echo $content['lead_cnt']; ?></p>
                    </div>
                    <div style="margin-top: 4px;">
                        <?php
                        $linkurl = $this->url(array('cntid'    => $content['id_cnt'],
                                                    'cmpid'    => $this->cmpid,
                                                    'language' => $this->language),
                                              'makecampaignlinks', true);
                        ?>
                        <a href="<?php echo $linkurl; ?>"><?php echo $this->translate('campaign-link'); ?></a>
                    </div>
                </div>
                <div style="clear: both;">&nbsp;</div>
                <?php
            }
        }
        ?> <div class="form_helptext_line"></div> <?php
    }
} else {
    ?>
    <p><?php echo $this->translate('campaign-link-not-content-this-type'); ?></p>
    <?php
}
?>
</div>
<div class="right_side" style="padding: 0px; margin-right: 5px; margin-top: 0px;">
    What is campaign linking?
</div>