<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<div class="linking">
<h3 class="linking_header">Link to campaign</h3>
<?php
if($this->cmpid != 0 && $this->hasUserContents == true) {
?>
    <div id="linked_to">
        <div id="linked_to_where">
            <p class="linking_paragraph">Campaign</p>
        </div>
        <div class="linked_to_where_campaign">
            <p class="linking_paragraph"><a href="<?php echo $this->url(array('cmpid' => $this->cmpid,
                                                 'language' => $this->language),
                                           'campaign_view', true); ?>">
                    <?php
                        if(strlen($this->cmp['name_cmp']) > 68) {
                            $this->cmp['name_cmp'] = substr($this->cmp['name_cmp'], 0, 68) . "...";
                        }
                        echo $this->cmp['name_cmp'];
                    ?>
                </a>
            </p>
        </div>
    </div>
    <?php
    if($this->usrcnt) {
        ?> <p class="linking_help_text"><?php echo $this->translate('campaign-link-helptext'); ?></p> <?php
        foreach($this->usrcnt as $content) {
            if($content['published_cnt'] != 0) {
                ?>
                <div class="linking_dot_line"></div>
                <div class="linking_from">
                    <div class="linking_from_name">
                        <?php
                        $linkurl = $this->url(array('content_id' => $content['id_cnt'],
                                                    'language' => $this->language),
                                              'content_shortview', true);
                        ?>
                        <div class="linking_from_<?php echo $content['key_cty']; ?>">
                            <strong><a href="<?php echo $linkurl; ?>"><?php echo $content['title_cnt']; ?></a></strong>
                            <p class="linking_from_text"><?php echo $content['lead_cnt']; ?></p>
                        </div>
                    </div>
                    <div class="linking_from_link">
                        <?php
                        $linkurl = $this->url(array('cntid'    => $content['id_cnt'],
                                                    'cmpid'    => $this->cmpid,
                                                    'language' => $this->language),
                                              'makecampaignlinks', true);
                        ?>
                        <a href="<?php echo $linkurl; ?>"><?php echo $this->translate('campaign-link'); ?></a>
                    </div>
                </div>
                <div class="clear"></div>
                <?php
            }
        }
        ?> <div class="linking_dot_line"></div> <?php
    } else {
        ?> <p>No campaigns</p> <?php
    }
} else {
    ?>
    <p><?php echo $this->translate('campaign-link-not-content-this-type'); ?></p>
    <?php
}
?>
</div>

<div id="sidebar" style="margin-left:20px; margin-right:0;">
    <div class="box">
        <h4>What is campaign linking?</h4>
        <div class="box-content">
            <div class="clear"></div>
        </div>
    </div>
</div>