<div class="linking">
<h3 class="linking_header">Link to campaign</h3>
<?php
if($this->cmpid != 0 && $this->hasUserCampaigns == true) {
?>
    <div id="linked_to">
        <div id="linked_to_where">
            <p class="linking_paragraph">Campaign</p>
        </div>
        <div class="linked_to_where_campaign">
            <p class="linking_paragraph"><a href="<?php echo $this->url(array('cmpid'    => $this->cmpid,
                                                                              'language' => $this->language),
                                                                        'campaign_view', true); ?>">
                <?php
                    if(strlen($this->cmp['name_cmp']) > 68) {
                        $this->cmp['name_cmp'] = substr($this->cmp['name_cmp'], 0, 68) . "...";
                    }
                    echo $this->cmp['name_cmp'];
                ?>
            </a></p>
        </div>
    </div>
    <p class="linking_help_text">Campaigns available for linking</p>
    <?php
    if($this->usrcmp) {
        foreach($this->usrcmp as $campaign) {
            ?>
            <div class="linking_dot_line"></div>
            <div class="linking_from">
                <div class="linking_from_name">
                    <?php
                    $cmpurl = $this->url(array('cmpid'      => $campaign['id_cmp'],
                                               'language'   => $this->language),
                                         'campaign_view', true);
                    $grpurl = $this->url(array('groupid'    => $campaign['id_grp_cmp'],
                                               'language'   => $this->language),
                                         'group_shortview', true);
                    ?>
                    <p class="campaign_list_paragraph">
                        <strong><a href="<?php echo $cmpurl; ?>"><?php echo $campaign['name_cmp']; ?></a></strong>
                        <?php if ((isset($campaign['group_name_grp']))): ?>
                            <br />by <a href="<?php echo $grpurl; ?>"><?php echo $campaign['group_name_grp']; ?></a> group
                        <?php endif; ?>
                    </p>
                    <p class="linking_from_text"><?php echo $campaign['ingress_cmp']; ?></p>
                </div>
                <div class="linking_from_link">
                    <?php
                    $linkurl = $this->url(array('controller'  => 'campaign',
                                                'action'      => 'makecampaignlink',
                                                'parentcmpid' => $this->cmpid,
                                                'childcmpid'  => $campaign['id_cmp'],
                                                'language'    => $this->language),
                                          'lang_default', true);
                    ?>
                    <a href="<?php echo $linkurl; ?>">Add link</a>
                </div>
            </div>
            <div class="clear"></div>
            <?php
        }
        ?> <div class="linking_dot_line"></div> <?php
    }
} else {
    ?>
    <p>You don't have any campaigns to link.</p>
    <?php
}
?>
</div>

<div id="sidebar" style="margin-left:20px; margin-right:0;">
    <div class="box">
        <h4>What is campaign linking?</h4>
        <div class="box-content">
            <p>Combining different campaigns together boost 
            creativity and helps similar campaigns to join forces.</p>
			<p>By linking you can create logical relationships between different campaigns.</p>
			<p>As a group admin you can link your campaign to other users or to your own campaigns.</p> 
			<p>One campaign can be linked to multiple campaigns.</p>
			<p>If you want, you can remove links later on by clicking 
			“edit campaign links” in the campaigns’s home page.</p>
            <div class="clear"></div>
        </div>
    </div>
</div>