<div class="linking">
<h3 class="linking_header"><?php echo $this->translate('campaign-unlink-content-from-campaign'); ?></h3>
<?php
if($this->contentexists) {
?>
    <div id="linked_to">
        <div id="linked_to_where">
            <p class="linking_paragraph"><?php echo $this->translate('campaign-unlink-target',
                                                                     $this->language);
            ?></p>
        </div>
        <div class="linked_to_where_<?php echo $this->linkingContentType; ?>">
            <p class="linking_paragraph"><a href="<?php echo $this->url(array('content_id' => $this->relatesToId,
                                                                              'language' => $this->language),
                                                                        'content_shortview', true); ?>">
                    <?php
                        if(strlen($this->relatesToContentTitle) > 68) {
                            $this->relatesToContentTitle = substr($this->relatesToContentTitle, 0, 68) . "...";
                        }
                        echo $this->relatesToContentTitle;
                    ?>
                </a>
            </p>
        </div>
    </div>
    <?php
    if($this->campaigns) {
        ?> <p class="linking_help_text"><?php echo $this->translate('campaign-unlink-helptext'); ?></p> <?php
        foreach($this->campaigns as $campaign) {
            ?>
            <div class="linking_dot_line"></div>
            <div class="linking_from">
                <div class="linking_from_name">
                    <?php
                    $groupurl = $this->url(array('groupid' => $campaign['id_grp'],
                                                'language' => $this->language),
                                          'group_shortview', true);
                    $campaignurl = $this->url(array('cmpid' => $campaign['id_cmp'],
                                                'language' => $this->language),
                                          'campaign_view', true);
                    ?>
                    <div class="linking_from_campaign">
                        <a href="<?php echo $groupurl; ?>"><?php echo $campaign['group_name_grp']; ?></a> :
                        <strong><a href="<?php echo $campaignurl; ?>"><?php echo $campaign['name_cmp']; ?></a></strong>
                        <p class="linking_from_text"><?php echo $campaign['ingress_cmp']; ?></p>
                    </div>
                </div>
                <div class="linking_from_link">
                    <?php
                    $linkurl = $this->url(array('contenttype' => $this->linkingContentType,
                                                'cmpid'     => $campaign['id_cmp'],
                                                'cntid'    => $this->relatesToId,
                                                'language' => $this->language),
                                          'removecampaignlinks', true);
                    ?>
                    <a href="<?php echo $linkurl; ?>"><?php echo $this->translate('campaign-unlink'); ?></a>
                </div>
            </div>
            <div class="clear"></div>
            <?php
        }
        ?> <div class="linking_dot_line"></div> <?php
    } else {
        ?> <p>No linked campaigns</p> <?php
    }
} else {
    ?>
    <p><?php echo $this->translate('campaign-content-not-exists'); ?></p>
    <?php
}
?>
</div>

<div id="sidebar" style="margin-left:20px; margin-right:0;">
    <div class="box">
        <h4>What is campaign unlinking?</h4>
        <div class="box-content">
            <p><strong></strong><br />
            </p>

            <p><strong></strong><br />
            </p>

            <div class="clear"></div>
        </div>
    </div>
</div>