<?php

if($this->linkingContentType == "problem") {
    $linkedColor = "red";
}
elseif($this->linkingContentType == "finfo") {
    $linkedColor = "yellow";
}
elseif($this->linkingContentType == "idea") {
    $linkedColor = "green";
}
?>
<div class="linking_content">
<h3 class="recent_posts"><?php echo $this->translate('campaign-unlink-content-from-campaign'); ?></h3>
<?php
if($this->contentexists) {
?>
    <div id="linkedto" class="linkedto" style="margin-bottom: 10px;">
        <p class="linkedtotext">
            <?php echo $this->translate('content-unlink-target',
                                                    $this->language);
            ?>
        </p>
        <img class="linkedtoimage" src="<?php echo $this->baseUrl."/images/".$linkedColor; ?>_vertical_line_small.png" alt="<?php echo $linkedColor; ?>" />

        <p style="padding-top: 9px;">
            <a href="<?php echo $this->url(array('content_id' => $this->relatesToId,
                                                     'language' => $this->language),
                                                     'content_shortview', true); ?>">
                <?php
                    if(strlen($this->relatesToContentTitle) > 68) {
                        $this->relatesToContentTitle = substr($this->relatesToContentTitle, 0, 68) . "...";
                    }
                    echo $this->relatesToContentTitle;
                ?>
            </a>
        </p>
    </div>

    <p style="color: #808080; margin: 10px 0 8px 15px;"><?php echo $this->translate('campaign-unlink-helptext'); ?></p>
    <?php
    if($this->campaigns) {
        foreach($this->campaigns as $campaign) {
            ?>
            <div class="form_helptext_line"></div>
            <div style="height: 20px;">
                <div style="float: left; width: 420px;">
                    <img class="linkedtoimage" src="/images/blue_vertical_line_small.png" alt="<?php echo $color; ?>" height="15" width="4"/>
                    <?php
                    $groupurl = $this->url(array('groupid' => $campaign['id_grp'],
                                                'language' => $this->language),
                                          'group_shortview', true);
                    $campaignurl = $this->url(array('cmpid' => $campaign['id_cmp'],
                                                'language' => $this->language),
                                          'campaign_view', true);
                    ?>
                    <a href="<?php echo $groupurl; ?>"><?php echo $campaign['group_name_grp']; ?></a> :
                    <strong><a href="<?php echo $campaignurl; ?>"><?php echo $campaign['name_cmp']; ?></a></strong>
                    <p style="margin: 4px 0 4px 20px;"><?php echo $campaign['ingress_cmp']; ?></p>
                </div>
                <div style="margin-top: 4px;">
                    <?php
                    $linkurl = $this->url(array('contenttype' => $this->linkingContentType,
                                                'cmpid'     => $campaign['id_cmp'],
                                                'cntid'    => $this->relatesToId,
                                                'language' => $this->language),
                                          'removecampaignlinks', true);
                    ?>
                    <a href="<?php echo $linkurl; ?>"><?php echo $this->translate('campaign-unlink'); ?></a>
                </div>
            </div>
            <div style="clear: both;"></div>
            <?php
        }
        ?> <div class="form_helptext_line"></div> <?php
    }
} else {
    ?>
    <p><?php echo $this->translate('campaign-content-not-exists'); ?></p>
    <?php
}
?>
</div>
<div class="right_side" style="padding: 0px; margin-right: 5px; margin-top: 0px;">
    What is campaign linking?
</div>