<h2>An error occurred</h2>
<hr />
<h2><?php echo $this->message; ?></h2> 
<?php 
	//$this->env = 'development';
?>
<?php if ('development' == $this->env): ?> 
	<div id="errorpage">
	    <h3>Exception information:</h3> 
	    <p> 
	        <b>Message:</b> <?php echo $this->exception->getMessage(); ?> 
	    </p> 
	
	    <h3>Stack trace:</h3> 
	    <div>
		    <pre><?php echo $this->exception->getTraceAsString(); ?></pre> 
		</div>
	    <h3>Request Parameters:</h3> 
	    <div>
		    <pre><?php var_dump($this->request->getParams()); ?></pre> 
	    </div>
    </div>
<?php endif ?>