<h1>An error occurred</h1> 
<h2><?php $this->message; ?></h2> 

<?php if ('development' == $this->env): ?> 
    <h3>Exception information:</h3> 
    <p> 
        <b>Message:</b> <?php $this->exception->getMessage() ?> 
    </p> 

    <h3>Stack trace:</h3> 
    <pre><?php $this->exception->getTraceAsString() ?></pre> 

    <h3>Request Parameters:</h3> 
    <pre><?php var_dump($this->request->getParams()) ?></pre> 
<?php endif ?>