<?php 
/*
THIS FILE IS DEPRECATED. 

The controller now redirects the user to the search results action with a null
search word, thus displaying all results.
*/
?>
			<div>
				<?php
				/*
				// creating tab array
				$tabs = array( array("Tab" => "problems",
									 "Name" => "Problems"
								    ),
							   array("Tab" => "ideas",
								     "Name" => "Ideas"
								    ),
							   array("Tab" => "futureinfo",
							         "Name" => "Future info"
									)
							 );
				$industry = $this->industry;
				$innovation = $this->innovation;
				
				if(strlen($industry) == 0)
				{
					$industry = "%";
				}
				if(strlen($innovation) == 0)
				{
					$innovation = "%";
				}
				
				$url = "?industry=".$industry."&amp;innovation=".$innovation."&amp;search=".$this->searchword."&amp;from=".$this->from;
				// printing tabs
				echo '<ul id="tabs">';
					foreach($tabs as $tab)
					{
						if($tab["Tab"] == $this->tab)
						{
							echo '<li id="active"><a href="'.$url.'&amp;tab='.$tab["Tab"].'">'.$tab["Name"].'</a></li>';
						}
						else
						{
							echo '<li><a href="'.$url.'&amp;tab='.$tab["Tab"].'">'.$tab["Name"].'</a></li>';
						}
					}
				echo "</ul>\n";
				*/
				?>
				<div>
					<p>
						<?php echo $this->translate('search-order_by'); ?>: 
						<a href="<?php echo $this->url(array('order' => 'author'), 'lang_default'); ?>"><?php echo $this->translate('search-author'); ?></a> | 
						<a href="<?php echo $this->url(array('order' => 'header'), 'lang_default'); ?>"><?php echo $this->translate('search-header'); ?></a> | 
						<a href="<?php echo $this->url(array('order' => 'views'), 'lang_default'); ?>"> <?php echo $this->translate('search-views'); ?></a>
					</p>
				</div>
				<div>
					<p>
						<?php
						/*
						// THIS NEEDS SOME CLEANING RIGHT HERE
						// make sure search found something
						if (count($this->objects) > 0)
						{
							if ($resultcount = $this->objects[0]['resultcount'])
							{
								if ($resultcount > 10) 
								{
									echo $this->translate('Page') . ': ';
									
									// If the user is on a page that is not the first page, display arrow pointing left.
									if ($this->from > 9)
									{
										$lastPage = $this->from - 10;
										echo '<a href="?industry='.$this->industry.'&amp;innovation='.$this->innovation
										.'&amp;searchword='.$this->searchword.'&amp;from='.$lastPage .'">&lt;-</a> ';
									}
									
									$pages = $resultcount/10;
									for ($i =0; $pages > 0; $i++)
									{
										$page = $i*10;
										if ($page == $this->from)
										{
											$currentPage = 'class="currentPage"';
										} else
										{
											$currentPage = '';
										}
										echo ' <a href="?industry='.$this->industry.'&amp;innovation='.$this->innovation
											.'&amp;searchword='.$this->searchword.'&amp;from='.$page .' " '.$currentPage.'>' .($i+1) .'</a>';
										$pages--;
									}
									
									// If there are more than 10 results and the user is not viewing the last page, displat arrow pointing right
									if (($this->from+10) < $resultcount)
									{
										$nextPage = $this->from + 10;
										echo ' <a href="?industry='.$this->industry.'&amp;innovation='.$this->innovation
										.'&amp;searchword='.$this->searchword.'&amp;from='.$nextPage .'">-&gt;</a>';
									}
								}
							}
						}
						*/
						?>
						
					</p>
				</div>
				
				<?php
				/*
				// if search found something show the results
				if(count($this->objects) > 0)
				{
					// listing table
					echo '<hr /> ' . 
					'<table cellpadding="0" cellspacing="0" border="2">';
					$i=0;
					foreach ($this->objects as $row)
					{
						$i++;
						if ($i % 2 == 0) {
							$bgcol = "#efe";
						}
						else {
							$bgcol = "#fee";
						}
						echo '
							<tr style="background:'.$bgcol.';">
								<td colspan="2"><p><strong><a href="<?php echo Zend_Controller_Front::getInstance()->getBaseUrl(); ?>/'.$this->tab.'/view/'.$row['id'].'">'.htmlspecialchars($row['title']).'</a></strong></p></td>
							</tr>
						';
						echo '
							<tr style="background:'.$bgcol.';">
								<td><p>'.$row['textlead'].'</p></td>
								<td><p>'
								.$this->translate->_('Author', $this->language).': <a href="">'.$row['username'].'</a><br/>'
								.$this->translate->_('Solutions', $this->language).': <a href="<?php echo Zend_Controller_Front::getInstance()->getBaseUrl(); ?>/'.$this->tab.'/view/'.$row['id'].'#solutions">'.$row['relatedideas'].'</a><br/>'			
								.'
								</p></td>
							</tr>
						';
						echo '
							<tr style="background:'.$bgcol.';">
								<td colspan="2"><p>Avainsanat: <a href="#">'.htmlspecialchars($row['keywords']).'</a> </p><hr /></td>
							</tr>
						';
						echo '';
					}
					echo '</table>';
				}
				else
				{	
					echo $this->translate->_('No search results', $this->language);
				}
				*/
				?>
				
			</div>