			<div id="search_bar">
				<form action="" method="get">
					<p>
					<select name="table" class="search_category">
						<option value=""><?php echo $this->translate->_('Table to search', $this->language); ?></option>
						<option value="oibs_problems">Problem</option>
						<option value="oibs_idea">Idea</option>
						<option value="oibs_future">Future</option>
					</select>
					<select name="industry" class="search_category">
						<option value="%"><?php echo $this->translate->_('Industry', $this->language); ?></option>
						
						<?php
							// set  list of industires to search bar
							foreach ($this->industryArray as $industry)
							{
								echo "<option value='{$industry['id']}'>".$this->translate->_($industry['categoryname'], $this->language)."</option>";
							}
						?>
						
					</select>
					<select name="innovation" class="search_category">
						<option value="%"><?php echo $this->translate->_('Innovation type', $this->language); ?></option>
						
						<?php
							// set  list of innovationtypes to search bar
							foreach ($this->innovationArray as $innovation)
							{
								echo "<option value='{$innovation['id']}'>".$this->translate->_($innovation['categoryname'], $this->language)."</option>";
							}
						?>
						
					</select>
					<input name="search" type="text" size="50" />
					<input type="submit" value="<?php echo $this->translate->_('Search', $this->language); ?>"/>
					</p>
				</form>
			</div>
			<p class="clear_margin"></p>
			<div id="left_1">
				<?php
					$kusivittu = '';
					echo '<div id="category_box">		
					<ul class="category_list">';
					foreach($this->parentList as $row)
					{
						if ($this->listparent == 'industry')
						{
							$searchstring = '?industry=%&innovation=%&search='.$this->searchword;
							$kusivittu = $row['categoryid'];
						} else if ($this->listparent == 'innovation')
						{
							$searchstring = '?industry='.$this->industry.'&innovation=%&search='.$this->searchword;
							$kusivittu = $row['categoryid'];
						} else if ($this->listparent == 'none')
						{
							$searchstring = '?industry='.$row['categoryid'].'&innovation='.$this->innovation.'&search='.$this->searchword;
						} else 
						{
							$searchstring = '?industry='.$row['categoryid'].'&innovation=%&search='.$this->searchword;
							$kusivittu = $row['categoryid'];
						}
						echo '<li> <a href="'.$searchstring.'">'.$this->translate->_($row['categoryname'], $this->language).' (' .$row['amount'] .')</a>
							  </li>';
					}
					echo '</ul>
					
					<ul class="category_list" id="inner">';
					foreach($this->childList as $row)
					{
						if ($this->listparent == 'industry')
						{
							$searchstring = '?industry='.$kusivittu.'&innovation='.$row['categoryid'].'&search='.$this->searchword;
						} else if ($this->listparent == "innovation")
						{
							$searchstring = '?industry='.$row['categoryid'].'&innovation='.$kusivittu.'&search='.$this->searchword;
						} else if ($this->listparent == "none")
						{
							$searchstring = '?industry='.$this->industry.'&innovation='.$row['categoryid'].'&search='.$this->searchword;
						} else 
						{
							$searchstring = '?industry=%&innovation='.$row['categoryid'].'&search='.$this->searchword;
						}

						echo '<li><a href="'.$searchstring.'">'.$this->translate->_($row['categoryname'], $this->language).' (' .$row['amount'] .')</a></li>';
					}
					echo '</ul>';
					echo '</div>';
				?>
				</div>
			<?php /* 
			<div id="right_1">
				<div id="orderby">
					<p class="no_margin">
						<?php echo $this->translate->_('Order by', $this->language); ?>: 
						<a href="?order=username"><?php echo $this->translate->_('Author', $this->language); ?></a> | 
						<a href="?order=title"><?php echo $this->translate->_('Header', $this->language); ?></a> | 
						<a href="?order=views"> <?php echo $this->translate->_('Views', $this->language); ?></a>
					</p>
				</div>
				<div id="paging">
					<p class="no_margin">
					
						<?php
						// make sure search found something
						if (count($this->objects) > 0)
						{
							if ($resultcount = $this->objects[0]['resultcount'])
							{
								if ($resultcount > 10 && $this->from > 9)
								{
									$lastPage = $this->from - 10;
									echo '<a href="?industry='.$this->industry.'&innovation='.$this->innovation
									.'&searchword='.$this->searchword.'&from='.$lastPage .'">&lt;</a> ';
								}
								

								if ($resultcount > 10)
								{
									$pages = $resultcount/10;
									for ($i =0; $pages > 0; $i++)
									{
										$page = $i*10;
										if ($page == $this->from)
										{
											$currentPage = 'class="currentPage"';
										} else
										{
											$currentPage = '';
										}
										echo '<a href="?industry='.$this->industry.'&innovation='.$this->innovation
											.'&searchword='.$this->searchword.'&from='.$page .' " '.$currentPage.'>' .($i+1) .'</a>';
										$pages--;
									}
									
								}
								
								if ($resultcount > 10 && ( ($this->from+10) < $resultcount))
								{
									$nextPage = $this->from + 10;
									echo '<a href="?industry='.$this->industry.'&innovation='.$this->innovation
									.'&searchword='.$this->searchword.'&from='.$nextPage .'">&gt;</a>';
								}
							}
						}
						?>
						
					</p>
				</div>
				<!--<p class="clear"></p>
				 listingtable -->
				
				<?php
				// if search found something show the results
				if(count($this->objects) > 0)
				{
					// listing table
					echo '<table id="listing_table" cellpadding="0" cellspacing="0">';
					foreach ($this->objects as $row)
					{
					echo '<tr><td colspan="2" class="title_row"><p><strong><a href="<?php echo Zend_Controller_Front::getInstance()->getBaseUrl(); ?>/problems/view/'.$row['id'].'">'.$row['title'].'</a></strong></p></td></tr>';
						echo '<tr><td class="textlead_td"><p>'.$row['textlead'].'</p></td>';
						echo '<td class="item_info"><p>'
								.$this->translate->_('Author', $this->language).': <a href="">'.$row['username'].'</a><br/>'
								.$this->translate->_('Views', $this->language).': <a href="<?php echo Zend_Controller_Front::getInstance()->getBaseUrl(); ?>/problems/view/'.$row['id'].'">'.$row['views'].'</a><br/>'									
								.$this->translate->_('Solutions', $this->language).': <a href="<?php echo Zend_Controller_Front::getInstance()->getBaseUrl(); ?>/problems/view/'.$row['id'].'#solutions">'.$row['relatedideas'].'</a><br/>'										
								.$this->translate->_('Comments', $this->language).': <a href="#">9 kpl</a>
							</p></td></tr>';
						echo '<tr><td colspan="2" class="keywords"><p>Avainsanat: <a href="#">'.$row['keywords'].'</a> </p></td></tr>';
					
					}
					echo '</table>';
				}
				else
				{	
					echo $this->translate->_('No search results', $this->language);
				}
				?>
				
			</div> <!-- end of "right_1"  --> */ ?>