



<?php
	/*echo '<div id="custompreviewtext" style="float:right; width:250px; display:block; margin-right:50px; margin-top:10px; margin-bottom:-10px;">
			Aa Bb Cc Dd Ee Ff Gg Hh Ii Jj Kk Ll Mm Nn Oo Pp Qq Rr Ss Tt Uu Vv Ww Xx Yy Zz
		  </div>';*/
	echo $this->customLayoutSettingsForm;
	
	echo '<div id="custompreviewtext" style="width:100px; display:block; margin-top:10px; margin-left:10px; font-size:14px; ">
			Aa Bb Cc Dd Ee
		  </div>';
?>
