		<div class="user_list_top_box">
			<div class="user_list_top_box_left">
				<span class="user_list_top_box_title"><?php echo $this->title; ?></span>
				<img class="user_list_top_box_image" src="<?php echo $this->url(array('controller' => 'account', 
	                                                                      'action' => 'profilethumb', 
	                                                                      'thumb' => true, 
	                                                                      'id' => $this->users[0]['id_usr'], 
	                                                                      'language' => $this->language), 
	                                                                'lang_default', true); ?>" alt="User image" class="profile_image_largesize" />
				<a href="<?php echo $this->url(array('controller' => 'account',
							 'action' => 'view',
							 'user' => $this->users[0]['login_name_usr'],
							 'language' => $this->language), 
							 'lang_default', true); ?>" class="user_list_top_box_user" style="text-decoration: none"><?php echo $this->users[0]['login_name_usr']; ?></a>
				<span class="user_list_top_box_description"><?php echo $this->description; echo $this->users[0]['value'] ?></span>
			</div>
			<div class="user_list_top_box_right">
				<div class="user_list_top_box_runnerups"><span class="user_list_top_box_runnerups_title_rank">#</span><span class="user_list_top_box_runnerups_title_name">Runner-ups</span><span class="user_list_top_box_runnerups_title_points">Points</span></div>
				<div class="user_list_top_box_runnerupsbox">
				<?php $i = 1; foreach($this->users as $user): ?>
					<?php if($i != 1): ?>
					<div class="user_list_top_box_runnerups_line">
						<span class="user_list_top_box_runnerups_rank"><?php echo $i ?>. </span>
						<a href="<?php echo $this->url(array('controller' => 'account',
							 'action' => 'view',
							 'user' => $user['login_name_usr'],
							 'language' => $this->language), 
							 'lang_default', true); ?>" class="user_list_top_box_runnerups_names" style="text-decoration: none;">
							<?php echo $user['login_name_usr']; ?></a>
							<span class="user_list_top_box_runnerups_value"><?php echo $user['value']; ?></span>
					</div>
					<?php endif; ?>
				<?php $i++; endforeach; ?>
				</div>
			</div>
		</div>