<?php 

$url_userFirst = $this->url(array('controller' => 'account',
							 'action' => 'view',
							 'user' => $this->users[0]['login_name_usr'],
							 'language' => $this->language), 
							 'lang_default', true);

$color = "";
$colorFirst = "";
$onlist = false;

if($this->addedUsers[0]['rank'] < 10) {
	if($this->addedUsers[0]['rank'] === 0) $colorFirst =  "color: red;";
	$color = "color: red;";
	$onlist = true;
}

?>

		<div class="user_list_top_box">
			<div class="user_list_top_box_left">
				<p class="user_list_top_box_title"><a href="<?php echo $this->link; ?>" style="text-decoration: none;"><?php echo $this->title; ?></a></p>
				<div class="user_list_top_box_image"><img src="<?php echo $this->url(array('controller' => 'account', 
	                                                                      'action' => 'profilethumb', 
	                                                                      'thumb' => true, 
	                                                                      'id' => $this->users[0]['id_usr'], 
	                                                                      'language' => $this->language), 
	                                                                'lang_default', true); ?>" alt="User image" class="profile_image_largesize" />
				</div>
				<div class="user_list_top_box_bottom">
					<p><a href="<?php echo $url_userFirst; ?>" class="user_list_top_box_user" style="text-decoration: none; <?php echo $colorFirst; ?>"><?php echo $this->users[0]['login_name_usr']; ?></a></p>
					<p><span class="user_list_top_box_description"><?php echo $this->description; echo $this->users[0]['value'] ?></span></p>
					<div class="user_list_top_box_show_more"><a id="user_list_top_box_show_more_link_Users<?php echo $this->name; ?>" href="#" onClick="return false;" style="text-decoration: none;"><img src="<?php echo $this->baseUrl('/images/arrow_down.png'); ?>"/></a></div>
				</div>
			</div>
			<div class="user_list_top_box_right" id="user_list_top_box_right_Users<?php echo $this->name; ?>" style="display:none">
				<div class="user_list_top_box_runnerups"><span class="user_list_top_box_runnerups_title_rank">#</span><span class="user_list_top_box_runnerups_title_name">Runner-ups</span><span class="user_list_top_box_runnerups_title_points">Points</span></div>
				<div class="user_list_top_box_runnerupsbox">
				<?php $i = 1; foreach($this->users as $user): ?>
					<?php if($i != 1): ?>
					<div class="user_list_top_box_runnerups_line">
						<span class="user_list_top_box_runnerups_rank"><?php echo $i ?>. </span>
						<a href="<?php echo $this->url(array('controller' => 'account',
							 'action' => 'view',
							 'user' => $user['login_name_usr'],
							 'language' => $this->language), 
							 'lang_default', true); ?>" class="user_list_top_box_runnerups_names" style="text-decoration: none; <?php if($this->addedUsers[0]['rank'] == $i-1) echo $color; ?>">
							<?php echo $user['login_name_usr']; ?></a>
							<span class="user_list_top_box_runnerups_value"><?php echo $user['value']; ?></span>
					</div>
					<?php endif; ?>
				<?php $i++; endforeach; ?>
					<?php if(!$onlist): ?>
						<div class="user_list_top_box_runnerups_line">
							<span class="user_list_top_box_runnerups_rank"><?php echo $this->addedUsers[0]['rank']+1; ?>. </span>
							 <a href="<?php echo $this->url(array('controller' => 'account',
								 'action' => 'view',
								 'user' => $this->addedUsers[0]['login_name_usr'],
								 'language' => $this->language), 
								 'lang_default', true); ?>" class="user_list_top_box_runnerups_names" style="text-decoration: none; color: red;">
								<?php echo $this->addedUsers[0]['login_name_usr']; ?></a>
								<span class="user_list_top_box_runnerups_value"><?php echo $this->addedUsers[0]['value']; ?></span>
						</div>
					<?php endif; ?>
				</div>
			</div>
		</div>