<?php 

//print_r($this);die;

if(!empty($this->cities)) $usersFound = true;
else $usersFound = false;

$url_userFirst = "";

$url_defaultImage = $this->url(array('controller' => 'account', 
          'action' => 'profilethumb', 
          'thumb' => true, 
          'id' => "0", 
          'language' => $this->language), 
          'lang_default', true);

$url_firstImage = $url_defaultImage;
$onlist = true;
?>


		<div class="user_list_top_box">
			<div class="user_list_top_box_left">
				<p class="user_list_top_box_title"><a href="<?php echo $this->link; ?>" style="text-decoration: none;"><?php echo $this->title; ?></a></p>
				<div class="user_list_top_box_image"><img src="<?php echo $url_firstImage; ?>" alt="User image" class="profile_image_largesize" />
				</div>
				
				<div class="user_list_top_box_bottom">
				<?php if($usersFound): ?>
					<p><a href="<?php echo $url_userFirst; ?>" class="user_list_top_box_user" style="text-decoration: none; <?php //echo $colorFirst; ?>"><?php echo $this->cities[0]['name']; ?></a></p>
					<p><span class="user_list_top_box_description"><?php echo $this->description; echo $this->cities[0]['value'] ?></span></p>
					<div class="user_list_top_box_show_more"><a id="user_list_top_box_show_more_link_Cities<?php echo $this->name; ?>" href="#" onClick="return false;" style="text-decoration: none;"><img src="<?php echo $this->baseUrl('/images/arrow_down.png'); ?>"/></a></div>
				<?php else: ?>
				<p>No users!</p>
				<?php endif; ?>
				</div>
			</div>
			<?php if($usersFound): ?>
			<div class="user_list_top_box_right" id="user_list_top_box_right_Cities<?php echo $this->name; ?>" style="display:none">
				<div class="user_list_top_box_runnerups"><span class="user_list_top_box_runnerups_title_rank">#</span><span class="user_list_top_box_runnerups_title_name">Runner-ups</span><span class="user_list_top_box_runnerups_title_points">Points</span></div>
				<div class="user_list_top_box_runnerupsbox">
				<?php $i = 1; foreach($this->cities as $city): ?>
					<?php if($i != 1): ?>
					<div class="user_list_top_box_runnerups_line">
						<span class="user_list_top_box_runnerups_rank"><?php echo $i ?>. </span>
						<a href="<?php // ?>" class="user_list_top_box_runnerups_names" style="text-decoration: none; <?php //if($this->addedUsers[0]['rank'] == $i-1) echo $color; ?>">
							<?php echo $city['name']; ?></a>
							<span class="user_list_top_box_runnerups_value"><?php echo $city['value']; ?></span>
					</div>
					<?php endif; ?>
				<?php $i++; endforeach; ?>
					<?php if(!$onlist): ?>
						<div class="user_list_top_box_runnerups_line">
							<span class="user_list_top_box_runnerups_rank"><?php echo $this->addedUsers[0]['rank']+1; ?>. </span>
							 <a href="<?php echo $this->url(array('controller' => 'account',
								 'action' => 'view',
								 'user' => $this->addedUsers[0]['login_name_usr'],
								 'language' => $this->language), 
								 'lang_default', true); ?>" class="user_list_top_box_runnerups_names" style="text-decoration: none; color: red;">
								<?php echo $this->addedUsers[0]['login_name_usr']; ?></a>
								<span class="user_list_top_box_runnerups_value"><?php echo $this->addedUsers[0]['value']; ?></span>
						</div>
					<?php endif; ?>
				</div>
			</div>
			<?php endif; ?>
		</div>