                <?php if (!empty($this->authorContents )): ?>
                <ul>
                    <?php foreach($this->authorContents as $content): ?>
                    <?php if($this->type === "saved" && $this->user_edit) {
                              if($content['published_cnt'] != 0)
                                  { continue; }
                          } else {
                              if( ($this->type !== 0 && $this->type !== 'all') && $content['key_cty'] !== $this->type)
                                  { continue; 
                                  }
                          }
                    ?>
                    <?php
                    $contentclass = '';

                    if ($content['key_cty'] === "idea") {
                        $contentclass = "ideas";
                    } elseif ($content['key_cty'] === "problem") {
                        $contentclass = "challenges";
                    } elseif ($content['key_cty'] === "finfo") {
                        $contentclass = "visions";
                    }
                    ?>
                    <li class="<?php echo $contentclass; ?> all 
                    <?php if($content['published_cnt'] == 0) echo 'saved';?> ">
                        <div>
                            <p>
                                <a href="<?php echo $this->url(array('content_id' => $content['id_cnt'],
                                                                     'language' => $this->language),
                                                               'content_shortview', true); ?>">
                                    <?php echo $content['title_cnt']; ?>
                                </a>
                            </p>
                            <p>
                                <?php echo $content['lead_cnt']; ?>
                            </p>
                            <p><strong>Posted</strong>
                               <?php echo date("d.m.Y", strtotime($content['created_cnt'])); ?>
                                <!-- |  <strong>Rating</strong> -->
                               | <strong>Views</strong> <?php echo $content['views']; ?>
                            </p>
                            <?php if ($this->user_edit == true): ?>
                            <p>
                                <b>
                                    <a href="<?php echo $this->url(array('content_id' => $content['id_cnt'],
                                                                         'language' => $this->language),
                                                                   'content_edit', true); ?>">
                                        Edit
                                    </a>
                                </b>
                                <?php if ($this->user_edit == true && $content['published_cnt'] == 0): ?>
                                | <b>
                                    <a href="#" onclick="publishconfirmation('<?php
                                                    echo $this->url(array('language' => $this->language,
                                                                          'content_id' => $content['id_cnt']),
                                                                    'content_publish', true); ?>')">
                                        Publish
                                    </a>
                                </b> |
                                <?php endif; ?>
                                | <b>
                                    <a href="#" onclick="deleteconfirmation('<?php
                                                    echo $this->url(array('language' => $this->language,
                                                                          'content_id' => $content['id_cnt']),
                                                                    'content_remove', true); ?>')">
                                        Delete
                                    </a>
                                </b>
                                <?php if (isset($content['cntHasCntCountParent']) && ($content['cntHasCntCountParent'] > 0 || $content['cntHasCntCountChild'] > 0)): ?>
                                | <b>
                                    <a href="<?php echo $this->url(array('relatestoid' => $content['id_cnt'],
                                                                         'language' => $this->language),
                                                                   'unlinkcontent', true); ?>">
                                        Edit content links (<?php echo ($content['cntHasCntCountParent'] + $content['cntHasCntCountChild']); ?>)
                                    </a>
                                </b>
                                <?php endif; ?>
                                <?php if (isset($content['cmpHasCntCount']) && $content['cmpHasCntCount'] > 0): ?>
                                | <b>
                                    <a href="<?php echo $this->url(array('relatestoid' => $content['id_cnt'],
                                                                 'language' => $this->language),
                                                                 'unlinkcampaign', true); ?>">
                                        Edit campaign links (<?php echo $content['cmpHasCntCount']; ?>)
                                    </a>
                                </b>
                                <?php endif; ?>
                            </p>
                            <?php endif; ?>
                        </div>
                    </li>
                    <li id="popup_publish_content_<?php echo $content['id_cnt']; ?>"
                            class="popup" style="display:none;">
                        <!-- Tämä pitää tehdä vielä paremmin -->
                            <?php echo $this->translate('content-publish-confirm'); ?>

                            <br />
                            <br />

                            <a href="<?php echo $this->url(array('language' => $this->language,
                                                                 'content_id' => $content['id_cnt']),
                                                           'content_publish', true); ?>" class="button">
                                <?php echo $this->translate('content-publish'); ?>
                            </a>

                            <a href="#" style="text-decoration: none;" class="button"
                                onclick="popup_close()">
                                <?php echo $this->translate('content-cancel'); ?>
                            </a>
                    </li>
                    <li id="popup_delete_content_<?php echo $content['id_cnt']; ?>"
                            class="popup" style="display:none;">
                            <?php echo $this->translate('content-delete-confirm'); ?>

                            <br />
                            <br />

                            <a href="<?php echo $this->url(array('language' => $this->language,
                                                                 'content_id' => $content['id_cnt']),
                                                           'content_remove', true); ?>" class="button">
                                <?php echo $this->translate('content-delete'); ?>
                            </a>
                            <a href="#" style="text-decoration: none;" class="button"
                                onclick="popup_close()">
                                <?php echo $this->translate('content-cancel'); ?>
                            </a>
                        <!-- Loppuu tähän -->

                    </li>
                    <?php endforeach; ?>
                </ul>
                <?php endif; ?>
