
	<div id="user_list_tabs">
		<ul>
		<?php foreach($this->topListBoxes as $name => $box): ?>
			<li><a href="#tab_<?php echo $name; ?>"> <?php echo $name; ?> </a></li>
		<?php endforeach; ?>
		</ul>
		<?php foreach($this->topListBoxes as $name => $box): ?>
		<div id="tab_<?php echo $name; ?>"> 
		
			<div>
				<div class="user_list_top_list_title">
					<span>Top <?php echo strtolower($name); ?> list </span>
					<a id="user_list_top_list_expand_all_<?php echo $name; ?>" href="#" onClick="return false;"><img src="<?php echo $this->baseUrl('/images/icon_plus_tiny.png'); ?>" /></a>
				</div>
			<div class="user_list_top_column">
			<?php $i = 0;
				$columnCount = ceil(sizeof($box)/3);
				
				foreach($box as $key => $top) { 
					if($i % $columnCount == 0 && $i != 0) { ?>
						</div> 
						<div class="user_list_top_column">
						<?php 
					} 
						
					echo $this->partial("partials/account_userlist_toplist_box_".strtolower($name).".phtml", $top); 

					$i++;
				}
				
			?>
				</div>
			</div>
		</div>
		<?php endforeach; ?>
	</div>