<?php
$language = Zend_Layout::getMvcInstance()->getView()->language;
$cmpurl = $this->url(array('cmpid' => $this->id_cmp,
                           'language' => $language),
                     'campaign_view', true);

if ($this->end_time_cmp == '0000-00-00 00:00:00') {
    $date = 'Never';
} else {
    $date = new Zend_Date($this->end_time_cmp, Zend_Date::ISO_8601);
    $date = $date->toString('dd MMM, yyyy');
}
// TODO: muokkailua :D
?>
<li class="ideas">
    <div>
        <p>
            <a href="<?php echo $cmpurl; ?>"><?php echo $this->name_cmp; ?></a>
        </p>
        <p>
            <?php echo $this->ingress_cmp; ?>
        </p>
        <span class="left">
            <strong>Ending:</strong>
            <?php echo $date;?>
        </span>
        <span class="right">
            <strong>Posts:</strong>
            1,000,000
            <!-- Tähän kampanjaan liittyvien sisältöjen määrä -->
        </span>
        <div class="clear"></div>
    </div>
</li>