<?php
$language = Zend_Layout::getMvcInstance()->getView()->language;
$cmpurl = $this->url(array('cmpid' => $this->id_cmp,
                           'language' => $language),
                     'campaign_view', true);
$grpurl = $this->url(array('groupid' => $this->id_grp_cmp,
                           'language' => $language),
                       'group_shortview', true);

if ($this->end_time_cmp == '0000-00-00') {
    $date = 'Never';
} else {
    $date = new Zend_Date($this->end_time_cmp, Zend_Date::ISO_8601);
    $date = $date->toString('dd MMM, yyyy');
}
?>
<li>
    <span>
        <strong><a href="<?php echo $cmpurl; ?>"><?php echo $this->name_cmp; ?></a></strong><!--
        <?php if ((isset($this->group_name_grp)) && (isset($this->id_grp_cmp))): ?>
            by <a href="<?php echo $grpurl; ?>"><?php echo $this->group_name_grp; ?></a>
        <?php endif; ?>-->
    </span>
    <div class="clear"></div>
</li>