<?php
$language = Zend_Layout::getMvcInstance()->getView()->language;
$cmpurl = $this->url(array('cmpid' => $this->id_cmp,
                           'language' => $language),
                     'campaign_view', true);
$grpurl = $this->url(array('groupid' => $this->id_grp_cmp,
                           'language' => $language),
                       'group_shortview', true);

$thisDate = date("Y-m-d", time());
$thisDate = new Zend_Date($thisDate, Zend_Date::ISO_8601);
$startDate = new Zend_Date($this->start_time_cmp, Zend_Date::ISO_8601);
$cmpStartEndText = "";
$date = "";
if ($thisDate->compare($startDate) == -1) {
    // Campaign has not started yet
    $date = $startDate->toString('dd MMM, yyyy');
    $cmpStartEndText = "Starting";
} else {
    if ($this->end_time_cmp == '0000-00-00') {
        $date = 'Never';
        $cmpStartEndText = "Ending";
    } else {
        $endDate = new Zend_Date($this->end_time_cmp, Zend_Date::ISO_8601);
        $date = $endDate->toString('dd MMM, yyyy');
        if ($thisDate->compare($endDate) == 1) {
            $cmpStartEndText = "Ended";
        } else {
            $cmpStartEndText = "Ending";
        }
    }
}
?>
<li>
    <div>
        <p class="campaign_list_paragraph">
            <strong><a href="<?php echo $cmpurl; ?>"><?php echo $this->name_cmp; ?></a></strong>
            <?php if ((isset($this->group_name_grp)) && (isset($this->id_grp_cmp))): ?>
                <br />by <a href="<?php echo $grpurl; ?>"><?php echo $this->group_name_grp; ?></a> group
            <?php endif; ?>
        </p>
        <p>
            <?php echo $this->ingress_cmp; ?>
        </p>
        <span class="left">
            <strong><?php echo $cmpStartEndText; ?>:</strong>
            <?php echo $date; ?>
        </span>
        <span class="right">
            <!--
            <strong>Posts:</strong>
            1,000,000
            -->
            <!-- Tähän kampanjaan liittyvien sisältöjen määrä -->
        </span>
        <div class="clear"></div>
    </div>
</li>