<div class="view_content_comments">
	<div class="clear"></div>
	<div id="content_view_comment_form_container">
	<?php if($this->comments->userCanComment()): ?>
		<h3 class="left"><?php echo $this->translate('content-view-comment-add'); ?></h3>		

		<div class="clear"></div>
		<div class="dot-line-500"></div>

		
		<div>
			<p id="replying_to" style="display: none;">Replying to [username]</p>
			<p id="reply_body"></p>
			<a href="#" id="cancel_reply_link" style="display: none;" onclick="javascript:cancelReply();return false;">
				<?php echo $this->translate('content-view-comment-cancel'); ?>
			</a>
		</div>
		
		<p><textarea id="commentTextarea" name="Comments"></textarea></p>
		<input type="button" value="Post comment" id="commentPostButton"></input>
		<input type="hidden" id="comment_parent" value="0"></input>
		<?php //echo $this->comments->getForm(); ?>
	<?php else: ?>
            <p style="margin: 0px; padding: 0px;">Would you like to comment?</p>
            <p style="margin: 0px; padding: 0px;">
            <a id="login_link" href="#">Log in</a> or <a href="<?php echo $this->comments->signupUrl; ?>">Sign up</a>
            </p>
            <?php endif;?>
	</div>
	<div id="content_view_comments">
		<div id="content_view_comments_header" 
                <?php if($this->comments->getCommentCount() == 0):?> style="display: none;"<?php endif; ?>> 
                    <h3><?php echo $this->translate('content-view-comments'); ?></h3>
                </div>
        <?php if ($this->comments->getCommentCount() > 0): ?>
            <?php foreach($this->comments->getComments() as $comment): ?>
            	<?php	$comment['userUrl'] = $this->comments->getUserUrl($comment['login_name_usr']); 
            			$comment['userRating'] = $this->comments->getUserRating($comment['login_name_usr'], 'ContentCount'); 
            	?>
				<?php echo $this->partial('partials/comment_row.phtml', $comment); ?>
			<?php endforeach; ?>
		<?php if (false && $this->comments > $this->count): ?>
             <div id="content_view_comment_pagination">
                <?php echo $this->commentPaginator->render('pagination/slidingPaginationControl.phtml'); ?>
                </div>
		<?php endif;?>
	<?php endif; ?>
	</div>
</div>
     
