<?php 

//some pre-generation stuff..
$authenticated = $this->authenticated;

$pi = 0;    // keeps track of problem cells
$fi = 0;    // keeps track of finfo cells
$ii = 0;    // keeps track of idea cells

// roll children_siblings to separate arrays
if (isset($this->children_siblings[0])) {
    foreach ($this->children_siblings as $children_sibling) {
        if ($children_sibling['name_cty'] == 'Problems') {
            $linked_problems[$pi] = $children_sibling;
            $pi++;
        } else if ($children_sibling['name_cty'] == 'Ideas') {
            $linked_ideas[$ii] = $children_sibling;
            $ii++;
        } else if ($children_sibling['name_cty'] == 'Future info') {
            $linked_futures[$fi] = $children_sibling;
            $fi++;
        }
    }
}


// roll parent_siblings to separate arrays
if (isset($this->parent_siblings[0])) {
    foreach ($this->parent_siblings as $parent_sibling) {
        if ($parent_sibling['name_cty'] == 'Problems') {
            $linked_problems[$pi] = $parent_sibling;
            $pi++;
        } else if ($parent_sibling['name_cty'] == 'Ideas') {
            $linked_ideas[$ii] = $parent_sibling;
            $ii++;
        } else if ($parent_sibling['name_cty'] == 'Future info') {
            $linked_futures[$fi] = $parent_sibling;
            $fi++;
        }
    }
}
?>
<script type="text/javascript">
$(document).ready(function() {
	$("#content-view-viewers-list > a").click(function(event) {
		event.preventDefault();
	});
	$("#content-view-viewers-list").mouseover(function () {
		$(this).css('cursor', 'pointer');
	});
	$("#content-view-viewers-list").qtip(
		{
			content: $("#content-view-viewers-list-content").html().replace(/%7E/g, '~'),
			show: 'click',
			hide: 'click',
			style: { width: { min: 250, max: 500 }} 
		}
	);
});
</script>
<div id="content-page" class="narrow left">
	<div id="viewtop">
		<div class="left">
			<div class="date left"><?php echo $this->translate('content-view-added') . date("d.m.Y H:i", strtotime($this->contentData['created_cnt'])); ?></div>
		<!-- AddThis Button BEGIN -->
		<div id="view_content_left_header_top_add_this" class="left" style="padding-left: 10px">
			<a class="addthis_button_expanded" href="http://www.addthis.com/bookmark.php?v=250&amp;pub=xa-4b12c6f671039279">
				<img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" 
					width="125" height="16" alt="Bookmark and Share" style="border:0"/>
			</a>
			<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pub=xa-4b12c6f671039279"></script>
		</div>
		<!-- AddThis Button END -->
		</div>
               
		<?php if ($this->user_can_rate): // also used to enable/disable flagging ?>
			<div class="right">
				<a href="#" id="flagContentLink" onclick="javascript:flagContent(); return false;">
					<?php echo $this->translate('content-view-flagcontent'); ?>
				</a>
			</div>
		<?php endif; ?>
		<div class="clear"></div>
            <div id="linked">
	            <div id="linked-challenges">
                    <div class="left">
                        <strong><?php echo $this->translate('content-linked-challenges'); if(isset($linked_problems)) echo "(".sizeof($linked_problems).")"; ?></strong>
                        <?php if(isset($linked_problems) && sizeof($linked_problems) > 3): ?><img alt="" src="/~jari/images/icon_plus_tiny.png" id="content_view_linked_content_challenges_more" /><?php endif; ?>
                        <br />
                    	<?php if (isset($linked_problems)): ?>
                        <?php $i = 0; foreach ($linked_problems as $problem): $i++; ?>
                        	<?php if($i == 4): ?> <div id="content_view_linked_content_challenges_extra" class="content_view_linked_content_extra"> <?php endif; ?>
                        	    <strong><a href="<?php echo $this->url(array('controller' => 'account',
	                                                         'action' => 'view',
	                                						 'user' => $problem['login_name_usr'],
	                                                         'language' => $this->language),
	                                                         'lang_default', true); ?>"><?php echo $problem['login_name_usr'] . ': '; ?></a></strong>
	                            <a href="<?php echo $this->url(array('content_id' => $problem['id_cnt'], 
	                                                                 'language' => $this->language), 
	                                                                 'content_shortview', true); ?>">
	                                <?php echo $problem['title_cnt']; ?>
	                            </a>
	                            <br />
                        <?php endforeach; ?>
                        <?php if($i > 3): ?> </div> <?php endif; ?> 
	                    <?php else: ?>
	                        <?php echo $this->translate('content-box-no-linked-challenges'); ?>
	                    <?php endif; ?>
               		</div>

                    <?php if ($authenticated): ?>
                    <div class="right">
                            <?php echo $this->translate('content-box-add'); ?>
                            <a href="<?php echo $this->url(array('language' => $this->language,
                                                                 'contenttype' => 'problem',
                                                                 'relatestoid' => $this->contentData['id_cnt']),
                                                                 'addcnttype', true); ?>">
                                <?php echo $this->translate('content-box-add-new'); ?>
                            </a>
                             | 
                            <a href="<?php echo $this->url(array('language' => $this->language,
                                                                 'contenttype' => 'problem',
                                                                 'relatestoid' => $this->contentData['id_cnt']),
                                                                 'linkcontent', true); ?>">
                                <?php echo $this->translate('content-box-link-existing'); ?>
                            </a>
                    </div>
                    <?php endif; ?>

                <div class="clear"></div>                	
            </div>
            <div id="linked-visions">
                <div class="left">
					<strong><?php echo $this->translate('content-linked-visions'); if(isset($linked_futures)) echo "(".sizeof($linked_futures).")";?></strong>
					<br />
                    	<?php if(isset($linked_futures) && sizeof($linked_futures) > 3): ?><img alt="" src="/~jari/images/icon_plus_tiny.png" id="content_view_linked_content_visions_more" /><?php endif; ?>
                    	
                   	<?php if (isset($linked_futures)): ?>
	                <?php $i= 0; foreach ($linked_futures as $future): $i++; ?>
                        <?php if($i == 4): ?> <div id="content_view_linked_content_visions_extra" class="content_view_linked_content_extra"> <?php endif; ?>
                            <a href="<?php echo $this->url(array('controller' => 'account',
                                                         'action' => 'view',
                                						 'user' => $future['login_name_usr'],
                                                         'language' => $this->language),
                                                         'lang_default', true); ?>"><?php echo $future['login_name_usr'] . ': '; ?></a>
                            <a href="<?php echo $this->url(array('content_id' => $future['id_cnt'], 
                                                                 'language' => $this->language), 
                                                           'content_shortview', true); ?>">
                                <?php echo $future['title_cnt']; ?></a>
                        <?php endforeach; ?>
                        <?php if($i > 3): ?>  </div> <?php endif; ?> 
                    <?php else: ?>
                        <?php echo $this->translate('content-box-no-linked-visions'); ?>
                    <?php endif; ?>
                    	
                </div>

                <?php if ($authenticated): ?>
                    	<div class="right">
                            <?php echo $this->translate('content-box-add'); ?>
                            <a href="<?php echo $this->url(array('language' => $this->language,
                                                                 'contenttype' => 'finfo',
                                                                 'relatestoid' => $this->contentData['id_cnt']),
                                                                 'addcnttype', true); ?>">
                                <?php echo $this->translate('content-box-add-new'); ?>
                            </a>
                             | 
                            <a href="<?php echo $this->url(array('language' => $this->language,
                                                                 'contenttype' => 'finfo',
                                                                 'relatestoid' => $this->contentData['id_cnt']),
                                                                 'linkcontent', true); ?>">
                                <?php echo $this->translate('content-box-link-existing'); ?>
                            </a>
                    	</div>
                    	
                    <?php endif; ?>
	                <div class="clear"></div>             
                </div>
            </div>
            <div id="misc">
               	<div id="content_view_content_info_container" class="left"></div>
                <div id="content-view-viewers-list" class="right"><a href="#"><?php printf($this->translate('content-view-view_times'), $this->views); ?></a></div>
                <div id="content-view-viewers-list-content" style="display: none"><?php echo $this->partial('partials/account_view_user_box_contents_my-reads.phtml', array('myReaders' => $this->viewers)); ?></div>          <?php if ($this->contentData['id_usr'] != $this->userid): ?>
                <div class="clear"></div>
	            <div id="content_view_favourite"></div>

	     <?php endif; ?>
	     <div class="clear"></div>
                <div class="left">
	                <?php if($this->contentData['language_cnt'] != $this->gtranslateLangPair['to']): ?>
	                	<?php if($this->isTranslated): ?>
		                	<?php echo $this->translate('content-view-translated-from') . "<strong>" .$this->languageName . "</strong>. "; ?>
		                	<?php $notranslate = $this->url(array('notranslate' => '1')); ?>
		                	[<a href="<?php echo $notranslate; ?>"><?php echo $this->translate('content-view-not-translated-show-original'); ?></a>]
		                <?php elseif(!$this->isTranslated): ?>
		                	<?php echo $this->translate('content-view-not-translated') . "(<strong>" .$this->languageName . "</strong>). "; ?>
		                	<?php $notranslate = $this->url(array('content_id' => $this->contentData['id_cnt'], 
																  'language' => $this->language), 
																  'content_shortview', true); ?>
		                	[<a href="<?php echo $notranslate; ?>"><?php echo $this->translate('content-view-translated-show-translated'); ?></a>]
		                <?php endif; ?>
	                <?php endif;?>
	                		<?php if ($this->contentData['id_cnt'] != "preview" && $this->contentData['id_usr'] == $this->userid): ?>
	         </div>
        	<div class="user_content_edit right">
        		<a href="#" onClick="return false;">Manage content</a>
        		<ul style="display: none">
        			<li>
	        			<img src="<?php echo $this->baseUrl("/images/icon_arrow_right.png");?>" />
	        			<a href="<?php echo $this->url(array('controller' => 'content',
	                                                         'action' => 'edit',
	        												 'content_id' => $this->contentData['id_cnt'],
	                                                         'language' => $this->language),
	                                                         'content_edit', true); ?>">Edit Content</a>
                    </li>
                    <li>
                    <img src="<?php echo $this->baseUrl("/images/icon_arrow_right.png");?>" />
	                    <a href="<?php echo $this->url(array('controller' => 'content',
	                                                         'action' => 'unlink',
	        												 'relatestoid' => $this->contentData['id_cnt'],
	                                                         'language' => $this->language),
	                                                         'unlinkcontent', true); ?>">Manage linked content</a>
                    </li>
                                                         
        		</ul>
		<?php endif; ?>
                </div>
            </div>        
            </div>
        <div id="content-page-head">
            <h3><?php echo stripslashes($this->contentData['title_cnt']); ?></h3>
            <p><em><?php echo stripslashes($this->contentData['lead_cnt']); ?></em></p>
        </div>
        <div id="content-page-context">
            <div id="content_view_campaigns" style="padding-top:7px;">
                <span class="content_view_bold">
                	<a href="<?php echo $this->url(array('controller' => 'campaign',
                                                         'action' => 'list',
                                                         'language' => $this->language),
                                                         'lang_default', true); ?>">
                		<?php echo $this->translate('content-view-campaigns'); ?>
                	</a>
                </span>
                <?php if (count($this->campaigns) == 0) : ?>
                    <?php echo $this->translate('content-view-has-no-campaigns'); ?>
                <?php else : ?>
                    <?php $i = count($this->campaigns) - 1; ?>
                    <?php foreach($this->campaigns as $campaign): ?>
                        <a href="<?php echo $this->url(array('cmpid' => $campaign['id_cmp'],
                                                             'language' => $this->language),
                                                       'campaign_view', true); ?>">
                            <?php echo stripslashes($campaign['name_cmp']); ?>
                        </a>
                        <?php echo $i-- > 0 ? ', ' : ''; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <div id="content_view_tags" style="padding-top:7px; padding-bottom:7px;">
                <span class="content_view_bold">
                	<a href="<?php echo $this->url(array('controller' => 'tag',
                                                         'action' => 'index',
                                                         'language' => $this->language), 
                                                         'lang_default', true); ?>">
                		<?php echo $this->translate('content-view-tags'); ?>
                	</a>
                </span>
                <?php $i = count($this->tags) - 1; ?>
                <?php if(count($this->tags)): ?>
	                <?php foreach($this->tags as $tag): ?>
	                    <a href="<?php if (isset($tag['id_tag'])) echo $this->url(array('controller' => 'tag', 
	                                                         'action' => 'view', 
	                                                         'id' => $tag['id_tag'], 
	                                                         'language' => $this->language), 
	                                                   		 'lang_default', true); ?>">
	                        <?php echo stripslashes($tag['name_tag']); ?></a><?php echo $i-- > 0 ? ', ' : ''; ?>
	                <?php endforeach; ?>
				<?php endif; ?>
            </div>
            <?php if (!empty($this->contentData['body_cnt'])): ?>
            <p><?php echo stripslashes(nl2br($this->contentData['body_cnt'])); ?></p>
            <?php endif;?>
            <?php if ($this->modified) : ?>
            	<div class="content_view_content_modified">
            		<p><?php echo $this->translate('content-modified')." ".$this->modified; ?></p>
            	</div>
            <?php endif; ?>
            
        </div>
        
        <?php if(!empty($this->contentData['references_cnt'])) : ?>
        <div id="content-page-classification">
        	<?php // Translation missing ?>
        	<span>References: </span>
        	<p><?php echo $this->contentData['references_cnt']; ?></p>
        </div>
        <?php endif;?>
  
	        <?php if(!empty($this->files)) : ?>
	        <div id="content-page-classification">
	        	<div class="content_view_file_list">
        		<span><?php echo $this->translate('content-files').':'; ?></span>
	        		<?php $filecount = count($this->files); ?>
	        		<?php $file_i = 0; ?>
       				<?php foreach ($this->files as $id_fil => $filename): ?>
       					<?php $file_i++; ?>
	        			<a href="<?php echo $this->baseUrl('/en/file/view/'.$id_fil); ?>">
	        				<?php echo $filename; ?></a><?php if($file_i < $filecount) echo ', '; ?>
        			<?php endforeach;?>
	        	</div>
		    </div>
            <?php endif;?>
        <div id="content-page-classification">
            <?php if ($this->contentType == "problem"): ?>
                <p>
                	<span><?php echo $this->translate('content-add-research') . ':'?></span>
                	<?php echo stripslashes($this->contentData['research_question_cnt']); ?>
                </p>
            <?php elseif($this->contentType == "idea"): ?>
                <p>
                	<span><?php echo $this->translate('content-add-solution') . ':'?></span>
                	<?php echo stripslashes($this->contentData['solution_cnt']); ?>
                </p>
            <?php elseif($this->contentType == "finfo"): ?>
                <p>
                	<span><?php echo $this->translate('content-add-opportunity') . ':'?></span>
                	<?php echo stripslashes($this->contentData['opportunity_cnt']); ?>
                </p>
                <p>
                	<span><?php echo $this->translate('content-add-threat') . ':'?></span>
                	<?php echo stripslashes($this->contentData['threat_cnt']); ?>
				</p>
			<?php endif; ?>
		</div> 
        <div id="content-page-classification">
			<p style="font-weight: bold; font-size:80%;">
				<?php echo $this->translate('content-view-solve-'.$this->contentType);?>
            	<a href="<?php echo $this->url(array('language' => $this->language,
                                     				 'contenttype' => 'idea',
                                     				 'relatestoid' => $this->contentData['id_cnt']),
                               						 'linkcontent', true); ?>">
					<img style="vertical-align:middle;" src="<?php echo $this->baseUrl('/images/button_add_existing_idea_'.$this->language); ?>.png" alt="" title="add new idea" />
            	</a>
            	<?php echo $this->translate('or');?>
            	<a href="<?php echo $this->url(array('language' => $this->language,
                                     				 'contenttype' => 'idea',
                                     				 'relatestoid' => $this->contentData['id_cnt']),
                               						 'addcnttype', true); ?>">
					<img style="vertical-align:middle;" src="<?php echo $this->baseUrl('/images/button_add_new_idea_'.$this->language); ?>.png" alt="" title="add new idea" />
				</a>
			</p>
		</div>
        
        <?php if (isset($this->children[0])): ?>
        <div class="solutions_for_this_content">
			<div class="box_468_medium">
            	<span style="font-weight:bold;">
            		<?php echo $this->translate('content-view-solutions-for'); ?>
            	</span>
            </div>
            <div class="box_468_light">
                <div class="child_row" style="clear:both; overflow: hidden;">
                    <?php foreach ($this->children as $child): ?>
                        <div style="clear:both;"></div>
                        <div style="float:left">
				            <img src="<?php echo $this->url(array('controller' => 'account',
				                                                  'action' => 'profilethumb',
				                                                  'id' => $child['id_usr'],
				                                                  'language' => $this->language,
				                                                  'thumb' => 'true'),
				                                            	  'lang_default', true); ?>" 
				                 alt="User image" class="profile_image_smallsize" />
                        </div>
                        <div class="solutions_child_row_content" style="float:left; padding-left: 10px;">
                            <a href="#"><?php echo $child['login_name_usr'];?></a>
                            <span style="font-weight:bold;">
                            	<a href="<?php echo $this->url(array('content_id' => $child['id_cnt'], 
                                                                 	 'language' => $this->language), 
                                                           			 'content_shortview', true); ?>">
                                	<?php echo $child['title_cnt']; ?>
                            	</a>
                            </span>
                            <br />
                            <span><?php echo $child['lead_cnt']; ?></span>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <?php if (isset($this->parents[0])) : ?>
		<div class="success">
			<h3><?php echo $this->translate('content-view-solution-to'); ?></h3>
			<ul>
				<?php foreach ($this->parents as $parent): ?>
					<li>
						<a href="<?php echo $this->url(array('content_id' => $parent['id_cnt'], 
                                                                 'language' => $this->language), 
                                                                 'content_shortview', true); ?>">
							<?php echo $parent['title_cnt']; ?>
						</a>
						<br />
					</li>
				<?php endforeach; ?>
				</ul>
			</div>
		<?php endif; ?>
		<?php if(isset($this->comments)): ?>
		        <?php echo $this->partial('partials/comments.phtml', array('comments' => $this->comments)); ?>
		<?php endif; ?>
	</div>
