<?php
// dirty fix to use language variable from view
$language = Zend_Layout::getMvcInstance()->getView()->language;
//$url_tag_cloud = Zend_Layout::getMvcInstance()->getView()->url_tag_cloud;
$url_tag_cloud = $this->url(array('controller' => 'tag',
                             	 'action' => 'index',
                             	 'language' => $language),
                             	 'lang_default', true);
$url_post = $this->url(array('content_id' => $this->id_cnt,
                             'language' => $language ),
                             'content_shortview', true);

$url_user = $this->url(array('controller' => 'account',
                             'action' => 'view',
                             'user' => $this->login_name_usr,
                             'language' => $language),
                             'lang_default', true);
$url_img = $this->url(array('controller' => 'account',
                            'action' => 'profilethumb',
                            'id' => $this->id_usr,
                            'language' => $language,
                            'thumb' => 'true'),
                            'lang_default', true);
?>
<li class="<?php echo $this->key_cty ?>">
    <div>
        <div class="photo <?php echo $this->key_cty; ?>">
            <a href="#"><img src="<?php echo $url_img; ?>" alt="" /></a>
        </div>
        <div>
            <p>
                <a href="<?php echo $url_user; ?>" class="username">
                    <?php echo $this->login_name_usr; ?>
                    <?php echo "(".$this->count.")"; ?>
                </a>
                <strong>
                    <a href="<?php echo $url_post;?>">
                        <?php echo $this->title_cnt;?>
                    </a>
                </strong>
            </p>
            <p>
                <?php echo $this->lead_cnt; ?>
            </p>
            <p class="tags">
                <a href="<?php echo $url_tag_cloud; ?>">
                    Tags
                </a>:
                <?php echo $this->partialLoop('partials/tag.phtml', $this->tags);?>
            </p>
        </div>
    </div>
    <div class="clear"></div>
</li>