<?php 

$url_register = $this->url(array('controller' => 'account',
                                 'action' => 'register',
                                 'language' => $this->language),
                                 'lang_default', true);

$url_login = $this->url(array('controller' => 'account',
                                 'action' => 'login',
                                 'language' => $this->language),
                                 'lang_default', true); 

// dirty fix to use language variable from view
//$this->language = Zend_Layout::getMvcInstance()->getView()->language;
?>
<div class="user_content_row" style="float: left;">
    <div style="padding: 10px;">
        <div class="view_content_left_header">
            <div class="view_content_left_header_top">
                <div style="float:left; "><?php echo $this->translate('content-view-added') . date("d.m.Y H:i", strtotime($this->contentData['created_cnt'])); ?>
                </div>
                
                <!-- AddThis Button BEGIN -->
                <div id="view_content_left_header_top_add_this">
                    <a class="addthis_button_expanded" href="http://www.addthis.com/bookmark.php?v=250&amp;pub=xa-4b12c6f671039279">
                        <img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" 
                            width="125" height="16" alt="Bookmark and Share" style="border:0"/>
                    </a>
                    <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pub=xa-4b12c6f671039279"></script>
                </div>
                <!-- AddThis Button END -->
               
				<?php if ($this->user_can_rate) { // also used to enable/disable flagging ?>
				<div style="float:right;"><a href="#" id="flagContentLink" onclick="javascript:flagContent(); return false;"><?php echo $this->translate('content-view-flagcontent'); ?></a></div>
				<?php } ?>
            </div>
            <div style="clear:both;"></div>
            <div class="box_468_light">
                <div style="width:150px; float:left; color:#d21034; font-weight: bold; overflow:hidden;">
                    <?php echo $this->translate('content-linked-challenges'); ?>
                    <?php if ($authenticated) { ?>
                    <br />
                    <span style="font-size: 80%; color: black;"><?php echo $this->translate('content-box-add'); ?> </span>
                        <span style="font-size: 80%">
                            <a href="<?php echo $this->url(array('language' => $this->language,
                                                                 'contenttype' => 'problem',
                                                                 'relatestoid' => $this->contentData['id_cnt']),
                                                                 'addcnttype', true); ?>">
                                <?php echo $this->translate('content-box-add-new'); ?>
                            </a>
                             | 
                            <a href="<?php echo $this->url(array('language' => $this->language,
                                                                 'contenttype' => 'problem',
                                                                 'relatestoid' => $this->contentData['id_cnt']),
                                                                 'linkcontent', true); ?>">
                                <?php echo $this->translate('content-box-link-existing'); ?>
                            </a>
                        </span>
                    <?php } ?>
                </div>
                <div style="width:300px; float:left; ">
                    <?php if (isset($linked_problems)) { ?>
                        <?php foreach ($linked_problems as $problem): ?>
                            <a href="<?php echo $this->url(array('content_id' => $problem['id_cnt'], 
                                                                 'language' => $this->language), 
                                                           'content_shortview', true); ?>">
                                <?php echo $problem['title_cnt']; ?>
                            </a>
                            <br />
                        <?php endforeach; ?>
                    <?php } else { ?>
                        <span><?php echo $this->translate('content-box-no-linked-challenges'); ?></span>
                    <?php } ?>
                </div>
            </div>
            <div class="box_468_light" style="border-top: 0;">
                <div style="width:150px; float:left; color:#ffc726; font-weight: bold; overflow:hidden;">
                    <?php echo $this->translate('content-linked-visions'); ?>
                    <?php if ($authenticated) { ?>
                    <br />
                    <span style="font-size: 80%; color: black;"><?php echo $this->translate('content-box-add'); ?> </span>
                        <span style="font-size: 80%">
                            <a href="<?php echo $this->url(array('language' => $this->language,
                                                                 'contenttype' => 'finfo',
                                                                 'relatestoid' => $this->contentData['id_cnt']),
                                                                 'addcnttype', true); ?>">
                                <?php echo $this->translate('content-box-add-new'); ?>
                            </a>
                             | 
                            <a href="<?php echo $this->url(array('language' => $this->language,
                                                                 'contenttype' => 'finfo',
                                                                 'relatestoid' => $this->contentData['id_cnt']),
                                                                 'linkcontent', true); ?>">
                                <?php echo $this->translate('content-box-link-existing'); ?>
                            </a>
                        </span>
                    <?php } ?>
                </div>
                <div style="width:300px; float:left; ">
                    <?php if (isset($linked_futures)) { ?>
                        <?php foreach ($linked_futures as $future): ?>
                            <a href="<?php echo $this->url(array('content_id' => $future['id_cnt'], 
                                                                 'language' => $this->language), 
                                                           'content_shortview', true); ?>">
                                <?php echo $future['title_cnt']; ?>
                            </a>
                            <br />
                        <?php endforeach; ?>
                    <?php } else { ?>
                        <span><?php echo $this->translate('content-box-no-linked-visions'); ?></span>
                    <?php } ?>
                </div>
            </div>
            <div class="view_content_left_header_btm">
                <div style="float:left;">
                	<div id="content_view_content_info_container"></div>
                </div>  
                <!--  <div style="float:left; padding:5px;">
                	<div id="content_view_favourite"></div>
                </div>  -->                
                <div style="float:right; padding:5px;"><?php printf($this->translate('content-view-view_times'), $this->views); ?></div>
            </div>
        </div>
        
        <div class="view_content_left_main" id="view_content_left_main" style="clear:both; padding-top: 10px;">
            <h3 style="padding: 0px; margin: 0px; font-weight: bold;"><?php echo stripslashes($this->contentData['title_cnt']); ?></h3>
            <p style="font-style:italic; padding: 0px; margin: 0px;"><?php echo stripslashes($this->contentData['lead_cnt']); ?></p>
            <div id="content_view_tags" style="padding-top:7px;">
                <span class="content_view_bold"><a href="<?php echo $this->url(array('controller' => 'tag',
                                                                                     'action' => 'index',
                                                                                     'language' => $this->language), 
                                                                                     'lang_default', true); ?>"><?php echo $this->translate('content-view-tags'); ?></a></span>
                <?php 
                    $i = count($this->tags) - 1;
                    //Zend_Debug::dump($this);
                    foreach($this->tags as $tag):
                ?>
                    <a href="<?php echo $this->url(array('controller' => 'tag', 
                                                         'action' => 'view', 
                                                         'id' => $tag['id_tag'], 
                                                         'language' => $this->language), 
                                                   		 'lang_default', true); ?>">
                        <?php echo stripslashes($tag['name_tag']) . "</a>";
                        echo $i-- > 0 ? ', ' : ''; ?>
                <?php endforeach; ?>	
            </div>
            <p><?php echo stripslashes(nl2br($this->contentData['body_cnt'])); ?></p>
            
            <?php if ($this->modified) : ?>
            <div class="content_view_content_modified"><p><?php echo $this->translate('content-modified')." ".$this->modified; ?></p></div>
            <?php endif; ?>
            
        </div>
        
        <?php if(!empty($this->contentData['references_cnt'])) : ?>
        <div class="user_content_spacer"><img src="<?php echo $this->baseUrl('/images/gray_dot_line_500.png');?>" alt="Massidea.org" /></div>
        <div class="content_view_references">
        <span>References: </span>
        <p><?php echo $this->contentData['references_cnt']; ?></p>
        </div>
        <?php endif;?>
  
          <div class="content_view_files">
	        <?php if(!empty($this->files)) : ?>
	        	<div class="user_content_spacer"><img src="<?php echo $this->baseUrl('/images/gray_dot_line_500.png');?>" alt="Massidea.org" /></div>
	        	 <?php 
	        		echo "<p><span>".$this->translate('content-files').":</span>"; 	
	       			foreach ($this->files as $id_fil => $filename) {
	        			echo "<div class='content_view_file_link'><a href='".$this->baseUrl."/en/file/view/".$id_fil."'>".$filename."</a></div>";
	        		}
	        		echo "</p>";
	        	?>
	        <?php endif;?>
        </div>
        
		<!-- From now on, also ideas are allowed to link to ideas (check was removed) -->
        <div class="user_content_spacer"><img src="<?php echo $this->baseUrl('/images/gray_dot_line_500.png');?>" alt="Massidea.org" /></div>
  
        <div class="content_view_core_content">
            <?php
            if ($this->contentType == "problem") { ?>
                <p><span><?php echo $this->translate('content-add-research') .":</span> "
                . stripslashes($this->contentData['research_question_cnt']); ?></p>
            <?php } elseif($this->contentType == "idea") { ?>
                <p><span><?php echo $this->translate('content-add-solution') .":</span> "
                . stripslashes($this->contentData['solution_cnt']); ?></p>
            <?php } elseif($this->contentType == "finfo") { ?>
                <p><span><?php echo $this->translate('content-add-opportunity') .":</span> "
                . stripslashes($this->contentData['opportunity_cnt']); ?></p>
                <p><span><?php echo $this->translate('content-add-threat') .":</span> "
                . stripslashes($this->contentData['threat_cnt']); ?></p>
            <?php } ?>
         </div> 
         <div class="view_content_left_contentlinks">
            <p style="font-weight: bold; font-size:80%;"><?php echo $this->translate('content-view-solve-'.$this->contentType);?>
            <a href="<?php echo $this->url(array('language' => $this->language,
                                     'contenttype' => 'idea',
                                     'relatestoid' => $this->contentData['id_cnt']),
                               'linkcontent', true); ?>">
            <img style="vertical-align:middle;" src="<?php echo $this->baseUrl('/images/button_add_existing_idea_'.$this->language); ?>.png" alt="" title="add new idea" />
            </a>
            <?php echo $this->translate('or');?>
            <a href="<?php echo $this->url(array('language' => $this->language,
                                     'contenttype' => 'idea',
                                     'relatestoid' => $this->contentData['id_cnt']),
                               'addcnttype', true); ?>">
            <img style="vertical-align:middle;" src="<?php echo $this->baseUrl('/images/button_add_new_idea_'.$this->language); ?>.png" alt="" title="add new idea" />
            </a>
            </p>
        </div>
        
        <?php if (isset($this->children[0])) { ?>
        <div class="solutions_for_this_content">
            <div class="box_468_medium">
            <span style="font-weight:bold;"><?php echo $this->translate('content-view-solutions-for'); ?></span>
            </div>
            <div class="box_468_light" style="margin-top: ">
                <div class="child_row" style="clear:both; overflow: hidden;">
                    <?php foreach ($this->children as $child): ?>
                        <div style="clear:both;"></div>
                        <div style="float:left">
                        
				            <img src="<?php echo $this->url(array('controller' => 'account',
				                                                  'action' => 'profilethumb',
				                                                  'id' => $child['id_usr'],
				                                                  'language' => $this->language,
				                                                  'thumb' => 'true'),
				                                            'lang_default', true); ?>" 
				                alt="User image" class="profile_image_smallsize" />
            
                        </div>
                        <div class="solutions_child_row_content" style="float:left; padding-left: 10px;">
                            <a href="#"><?php echo $child['login_name_usr'];?></a>
                            <span style="font-weight:bold;"><a href="<?php echo $this->url(array('content_id' => $child['id_cnt'], 
                                                                 'language' => $this->language), 
                                                           'content_shortview', true); ?>">
                                <?php echo $child['title_cnt']; ?>
                            </a></span><br />
                            <span><?php echo $child['lead_cnt']; ?></span>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <?php } ?>

        
        <div class="user_content_spacer"><img src="<?php echo $this->baseUrl('/images/gray_dot_line_500.png');?>" alt="Massidea.org" /></div>
        
        <?php if ($this->comments > 0) { ?>
        <div class="view_content_comments">
            <div id="content_view_comments">
                <div id="content_view_comments_header">
                    
                    <?php /* if ($this->comments == 1): ?>
                        <h3><?php printf($this->translate('content-view-comment'), $this->comments); ?></h3>
                    <?php elseif ($this->comments > 1): ?>
                        <h3><?php printf($this->translate('content-view-comments'), $this->comments); ?></h3>
                    <?php endif; */?>
                    
                    <h3><?php echo $this->translate('content-view-comments'); ?></h3>
                </div>
            <?php foreach($this->commentData as $comment): ?>		
            <div class="clear"></div>
			<div id="content_view_comment_<?php echo $comment['id_cmt']; ?>_container" 
                class="content_view_comment_container_<?php echo $comment['level']; ?>">
				<div id="content_view_comment_<?php echo $comment['id_cmt']; ?>_header" class="content_view_comment_header">
                    <?php // <img src="/images/no_profile_img_placeholder.gif" alt="No Profile Image" width="48" height="48" /> ?>
					<div id="content_view_comment_<?php echo $comment['id_cmt']; ?>_username" class="content_view_comment_username">
                            <?php echo $comment['login_name_usr']; ?>
                    </div>
                    <div id="content_view_comment_<?php echo $comment['id_cmt']; ?>_date" class="content_view_comment_date">
                        <?php echo date('(d M Y)', strtotime($comment['created_cmt'])); ?>
                    </div>
                    <div id="content_view_comment_<?php echo $comment['id_cmt']; ?>_reply" class="content_view_comment_reply">
                    	<a id="flagSpamLink_<?php echo $comment['id_cmt']; ?>" href="#" onclick="javascript:flagAsSpam('<?php echo $comment['id_cmt']; ?>');return false;">Spam</a> / 
                        <a href="#" onclick="javascript:replyTo('<?php echo $comment['id_cmt']; ?>', 
                                            '<?php echo $comment['login_name_usr']; ?>');return false;">
                            <?php echo $this->translate('content-view-comment-reply'); ?>
                        </a>
                    </div>
                    <?php /*?>
                    <div id="content_view_comment_<?php echo $comment['id_cmt']; ?>_flag" class="content_view_comment_flag">
                        <a href="#">
                            <img src="/images/icon_flag_spam_32x32.png" alt="Flag as spam" width="20" height="20" />
                        </a>
                    </div>
                    <?php */?>
                </div>
				<div id="content_view_comment_<?php echo $comment['id_cmt']; ?>" class="content_view_comment">
                    <?php /*
					<div id="content_view_comment_<?php echo $comment['id_cmt']; ?>_title" class="content_view_comment_title content_view_bold">
						<?php echo $comment['title_cmt']; ?>
					</div>
                    */ ?>
                    
					<div id="content_view_comment_<?php echo $comment['id_cmt']; ?>_textbody" 
                        class="content_view_comment_textbody">
                        <?php echo $this->BBCode->parse(stripslashes($comment['body_cmt'])); ?>
                    </div>
                    
                    <div id="unmodified_<?php echo $comment['id_cmt']; ?>" style="display:none;">
                        <?php echo $comment['body_cmt']; ?>
                    </div>
				</div>
            </div>
			<?php endforeach; ?>
				<?php
                    if (false && $this->comments > $this->count) {
                        echo '<div id="content_view_comment_pagination">';
                        // echo $this->paginationControl($this->commentPaginator, 'Sliding', 'pagination/paginationControl.phtml');
                        echo $this->commentPaginator->render('pagination/slidingPaginationControl.phtml');
                        echo '</div>';
                   }
                ?>
		</div>        
		<?php } if($this->user_can_comment) { ?>
        <div style="clear:both;"></div>
		<div id="content_view_comment_form_container">
			<h3 style="float: left;"><?php echo $this->translate('content-view-comment-add'); ?></h3>
			<a href="#" id="cancel_reply_link" style="float: right; padding: 3px 0px 0px 0px; display: none;" onclick="javascript:cancelReply();return false;"><?php echo $this->translate('content-view-comment-cancel'); ?></a>
			<p id="replying_to" style="float: right; padding: 3px 20px 0px 0px; display: none;">Replying to [username]</p>
			<?php echo $this->comment_form; ?>
		</div>
		<?php } ?>
        <?php if ($this->comments > 0) { echo'</div>'; } ?>
        <?php if (!$this->user_can_comment) { ?>

            <p style="margin: 0px; padding: 0px;">Would you like to comment?</p>
            <p style="margin: 0px; padding: 0px;"><a href="<?php echo $url_login; ?>">Log in</a> or <a href="<?php echo $url_register; ?>">Sign up</a></p>
        <?php } ?>        
                <?php if (isset($this->parents[0])) : ?>
                <div class="success">
                    <h3><?php echo $this->translate('content-view-solution-to'); ?></h3>
                    <ul>
                        <?php foreach ($this->parents as $parent): ?>
                        <li>
                            <a href="<?php echo $this->url(array('content_id' => $parent['id_cnt'], 
                                                                 'language' => $this->language), 
                                                                 'content_shortview', true); ?>">
                                <?php echo $parent['title_cnt']; ?>
                            </a>
                            <br />
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <?php endif; ?>
                <?php
                if($this->contentType == "idea") {
                /*
                ?>
                <div class="success">
                    <h3><?php echo $this->translate('content-view-rivals-for'); ?></h3>
                    <ul>
                        <?php foreach ($this->rivals as $rival): ?>
                        <li>
                            <a href="<?php echo $this->url(array('content_id' => $rival['id_cnt'], 
                                                                 'language' => $this->language), 
                                                           'content_shortview', true); ?>">
                                <?php echo $rival['title_cnt']; ?>
                            </a>
                            <br />
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <?php
                */
                }
                ?>
                <?php /*if($this->user_can_comment): ?>
                <div class="message">
                    <h3><?php //echo $this->translate('content-box-add-headerz'); ?></h3>
                    <ul>
                        <?php
                        if($this->contentType != "idea") {
                        /*
                        } else {
                        ?>
                            <?php if (isset($parent)) : ?>
                            <li>
                                <a href="<?php echo $this->url(array('language' => $this->language,
                                                                     'contenttype' => 'idea',
                                                                     'relatestoid' => $parent['id_cnt']),
                                                               'addcnttype', true); ?>">
                                    <?php echo $this->translate('content-box-add-rival-idea'); ?>
                                </a>
                            </li>
                            <?php endif; ?>
                        <?php
                        
                        }
                        if($this->contentType == "problem") {
                        /*
                        ?>
                        <li>
                            <a href="<?php echo $this->url(array('language' => $this->language,
                                                                 'contenttype' => 'finfo',
                                                                 'relatestoid' => $this->contentData['id_cnt']),
                                                           'addcnttype', true); ?>">
                                <?php echo $this->translate('content-box-add-new-related-futureinfo'); ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('language' => $this->language,
                                                                 'contenttype' => 'finfo',
                                                                 'relatestoid' => $this->contentData['id_cnt']),
                                                           'linkcontent', true); ?>">
                                <?php echo $this->translate('content-box-link-existing-futureinfo'); ?>
                            </a>
                        </li>
                        <?php
                        
                        } elseif($this->contentType == "finfo") { /*
                        ?>
                        <li>
                            <a href="<?php echo $this->url(array('language' => $this->language,
                                                                 'contenttype' => 'problem',
                                                                 'relatestoid' => $this->contentData['id_cnt']),
                                                           'addcnttype', true); ?>">
                                <?php echo $this->translate('content-box-add-new-related-problem'); ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('language' => $this->language,
                                                                 'contenttype' => 'problem',
                                                                 'relatestoid' => $this->contentData['id_cnt']),
                                                           'linkcontent', true); ?>">
                                <?php echo $this->translate('content-box-link-existing-problem'); ?>
                            </a>
                        </li>
                        <?php
                        }
                        ?>
                    </ul>
                </div>
                <?php endif; */?>
                <?php //endif; ?>
    	</div>
</div>