<?php
// dirty fix to use language variable from view
$language = Zend_Layout::getMvcInstance()->getView()->language;
//$url_tag_cloud = Zend_Layout::getMvcInstance()->getView()->url_tag_cloud;
$url_tag_cloud = $this->url(array('controller' => 'tag',
                             	 'action' => 'index',
                             	 'language' => $language),
                             	 'lang_default', true);
$url_post = $this->url(array('content_id' => $this->id_cnt,
                             'language' => $language ),
                             'content_shortview', true);

$url_user = $this->url(array('controller' => 'account',
                             'action' => 'view',
                             'user' => $this->login_name_usr,
                             'language' => $language),
                             'lang_default', true);
$url_img = $this->url(array('controller' => 'account',
                            'action' => 'profilethumb',
                            'id' => $this->id_usr,
                            'language' => $language,
                            'thumb' => 'true'),
                            'lang_default', true)
?>
<div class="user_content_row user_content_row_new" id="postid_<?php echo $this->id_cnt; ?>">
    <div class="user_image_list">
        <img src="<?php echo $url_img; ?>"
        alt="User image" class="profile_image_smallsize smallsize_<?php echo $this->key_cty;?>_border" />
    </div>

    <div class="user_summary_list_without_stats">
        <span class="summary_topic">
            <a href="<?php echo $url_user; ?>">
                <?php echo $this->login_name_usr; ?>
            </a>
            :
            <b>
                <a href="<?php echo $url_post;?>">
                    <?php echo $this->title_cnt;?>
                </a>
            </b>
        </span>

        <br />

        <span class="summary_leadtext">
            <?php echo $this->lead_cnt; ?>
        </span>

        <br />

        <span class="summary_tags">
            <b>
                <a href="<?php echo $url_tag_cloud; ?>">
                    Tags
                </a>:
            </b>
            <?php echo $this->partialLoop('partials/tag.phtml', $this->tags);?>
       </span>
    </div>

    <div class="clear"></div>

</div>