<?php
$language = Zend_Layout::getMvcInstance()->getView()->language;

$homeUrl = $this->url(array('groupid'    => $this->id_grp,
                            'language' => $language),
                      'group_shortview', true);

$campaignsUrl = $this->url(array('groupid'      => $this->id_grp,
                                 'language'   => $language),
                           'group_campaigns_shortview', true);

$infoUrl = $this->url(array('groupid'      => $this->id_grp,
                            'language'   => $language),
                      'group_info_shortview', true);

$membersUrl = $this->url(array('groupid'      => $this->id_grp,
                               'language'   => $language),
                         'group_members_shortview', true);

$feedsUrl = $this->url(array('groupid'      => $this->id_grp,
                             'language'   => $language),
                       'group_feeds_shortview', true);

$discussionUrl = $this->url(array('groupid'      => $this->id_grp,
                                  'language'   => $language),
                            'group_discussion_shortview', true);

$linkedgroupsUrl = $this->url(array('groupid'      => $this->id_grp,
                                    'language'   => $language),
                              'group_linkedgroups_shortview', true);
?>

<div id="profile-meta">
    <ul id="group-menu">
        <!--<li>Picture</li>-->
        <li id="<?php if ($this->grp_action === 'home') echo 'active'; ?>">
            <a href="<?php echo $homeUrl; ?>">Home</a>
        </li>
        <li id="<?php if ($this->grp_action === 'campaigns') echo 'active'; ?>">
            <a href="<?php echo $campaignsUrl; ?>">Campaigns</a>
        </li>
        <li id="<?php if ($this->grp_action === 'info') echo 'active'; ?>">
            <a href="<?php echo $infoUrl; ?>">Info</a>
        </li>
        <li id="<?php if ($this->grp_action === 'members') echo 'active'; ?>">
            <a href="<?php echo $membersUrl; ?>">Members</a>
        </li>
        <li id="<?php if ($this->grp_action === 'feeds') echo 'active'; ?>">
            <a href="<?php echo $feedsUrl; ?>">Feeds</a>
        </li>
        <li id="<?php if ($this->grp_action === 'discussion') echo 'active'; ?>">
            <a href="<?php echo $discussionUrl; ?>">Discussion</a>
        </li>
        <li id="<?php if ($this->grp_action === 'linkedgroups') echo 'active'; ?>">
            <a href="<?php echo $linkedgroupsUrl; ?>">Linked groups</a>
        </li>
    </ul>
</div>