<?php
$language = Zend_Layout::getMvcInstance()->getView()->language;
$grpurl = $this->url(array('groupid' => $this->id_grp,
                           'language' => $language),
                       'group_shortview', true);

$usrurl = $this->url(array('controller' => 'account',
                           'action' => 'view',
                           'user' => $this->login_name_admin,
                           'language' => $language),
                     'lang_default', true);
?>
<li>
    <div>
        <p>
            <strong><a href="<?php echo $grpurl; ?>"><?php echo $this->group_name_grp; ?></a></strong>
        </p>
        <p>
            <?php echo $this->description_grp; ?>
        </p>
        <?php if (isset($this->campaign_count) && isset($this->member_count)) : ?>
        <div class="light-gray">
            <strong>Campaigns:</strong> <?php echo $this->campaign_count; ?>,
            <strong>Members:</strong> <?php echo $this->member_count; ?>
        </div>
        <?php endif; ?>
        <div class="clear"></div>
    </div>
</li>