<?php
$language = Zend_Layout::getMvcInstance()->getView()->language;
$grpurl = $this->url(array('groupid' => $this->id_grp,
                           'language' => $language),
                     'group_shortview', true);
$usrurl = $this->url(array('controller' => 'account',
                           'action' => 'view',
                           'user' => $this->login_name_admin,
                           'language' => $language),
                     'lang_default', true);
?>

<li class="cmpgrp">
    <span>
        <strong><a href="<?php echo $grpurl; ?>"><?php echo $this->escape($this->group_name_grp); ?></a></strong>
    </span>
    <div class="clear"></div>
</li>