<?php
$language = Zend_Layout::getMvcInstance()->getView()->language;

$homeUrl = $this->url(array('groupid'    => $this->id_grp,
                            'language' => $language),
                      'group_shortview', true);

$campaignsUrl = $this->url(array('groupid'      => $this->id_grp,
                                 'language'   => $language),
                           'group_campaigns_shortview', true);

$infoUrl = $this->url(array('groupid'      => $this->id_grp,
                            'language'   => $language),
                      'group_info_shortview', true);

$membersUrl = $this->url(array('controller' => 'account',
                               'action'     => 'userlist',
                               'order'      => 'username',
                               'list'       => 'asc',
                               'country'    => 0,
                               'group'      => $this->group_name_grp,
                               'exactq'     => 1,
                               'language'   => $language),
                         'lang_default', true);

$feedsUrl = $this->url(array('groupid'      => $this->id_grp,
                             'language'   => $language),
                       'group_feeds_shortview', true);

$commentsUrl = $this->url(array('groupid'      => $this->id_grp,
                                  'language'   => $language),
                            'group_comments_shortview', true);

$linkedgroupsUrl = $this->url(array('groupid'      => $this->id_grp,
                                    'language'   => $language),
                              'group_linkedgroups_shortview', true);
?>

<div id="profile-meta">
    <ul id="group-menu">
        <!--<li><img class="avatar" alt="Group profile picture" src="/en/account/profilethumb/id/1/thumb/true" /></li>-->
        <li id="<?php if ($this->grp_action === 'home') echo 'active'; ?>">
            <a href="<?php echo $homeUrl; ?>">Home</a>
        </li>
        <li id="<?php if ($this->grp_action === 'info') echo 'active'; ?>">
            <a href="<?php echo $infoUrl; ?>">Info</a>
        </li>
        <li id="<?php if ($this->grp_action === 'members') echo 'active'; ?>">
            <a href="<?php echo $membersUrl; ?>">Members</a>
        </li>
        <li id="<?php if ($this->grp_action === 'campaigns') echo 'active'; ?>">
            <a href="<?php echo $campaignsUrl; ?>">Campaigns</a>
        </li>
        <li id="<?php if ($this->grp_action === 'comments') echo 'active'; ?>">
            <a href="<?php echo $commentsUrl; ?>">Comments</a>
        </li>
        <li id="<?php if ($this->grp_action === 'linkedgroups') echo 'active'; ?>">
            <a href="<?php echo $linkedgroupsUrl; ?>">Linked groups</a>
        </li>
        <li id="<?php if ($this->grp_action === 'feeds') echo 'active'; ?>">
            <a href="<?php echo $feedsUrl; ?>">Feeds</a>
        </li>
    </ul>
    <div id="group-admins">
        <?php $grpAdminsCount = count($this->grp_admins); ?>
        <ul class="light-gray">
            <li>Group admin<?php if ($grpAdminsCount > 1) echo 's'; ?>:</li>
        <?php foreach ($this->grp_admins as $admin): ?>
            <?php $usrUrl = $this->url(array('controller' => 'account',
                                             'action' => 'view',
                                             'user' => $admin['login_name_usr'],
                                             'language' =>  $this->language),
                                       'lang_default', true); ?>
            <li><a href="<?php echo $usrUrl; ?>"><?php echo $admin['login_name_usr']; ?>
                (<?php echo $admin['count']; ?>)</a></li>
        <?php endforeach; ?>
        </ul>
    </div>
</div>