<?php
$language = Zend_Layout::getMvcInstance()->getView()->language;
$grpurl = $this->url(array('groupid' => $this->id_grp,
                           'language' => $language),
                       'group_shortview', true);
$usrurl = $this->url(array('controller' => 'account',
                           'action' => 'view',
                           'user' => $this->login_name_admin,
                           'language' => $language),
                     'lang_default', true);
?>
<li>
    <div>
        <p>
            <a href="<?php echo $grpurl; ?>"><?php echo $this->login_name_admin; ?></a>:
            <strong><a href="<?php echo $grpurl; ?>"><?php echo $this->group_name_grp; ?></a></strong>
        </p>
        <p>
            <?php echo $this->description_grp; ?>
        </p>
        <div class="clear"></div>
    </div>
</li>