
			
			<!-- For some mystical reason, paragraphs seem to need an empty style-attribute in order to extend a CSS -class -->
			<h4 style="margin-top: 8px; margin-bottom: 6px;"><?php echo $this->translate('index-what-is'); ?></h4>
				<div class="top_right_box">
                    <?php echo $this->translate('index-what-is-long'); ?>
                    <?php // <span class="top_right_box_links"><a href="#"> echo $this->translate('index-learn-more'); </a></span> ?>
                </div>
			<p id="sign_up_now" style="" class="top_right_box_links"><b><a href="<?php echo $url_sign_up; ?>"><?php echo $this->translate('index-sigup')?></a></b></p>
			<h3 style="margin-top: 5px; margin-bottom: 0; padding: 0;"><?php echo $this->translate('index-most-popular')?> <a href="<?php echo $url_tag_cloud; ?>"><?php echo $this->translate('index-tags')?></a></h3>
			<img src="/images/gray_dot_line_200.png" alt="Massidea.org" />
			<div class="tag_cloud">
                <?php
                // tag cloud tags
                //Zend_Debug::dump($this, $label=null, $echo=true); die;
                //$view = $this->_helper->layout->getLayoutInstance;
                $bla = $this->_helper;
                foreach ($this->poptags as $tag) {
                    $url = $this->url(array('controller' => 'tag',
                    'action' => 'view',
                    'id' => $tag['id_tag'],
                    'language' => $this->language),
                    'lang_default', true);
                    echo ' <a href="'.$url.'" style="font-size:'.$tag['tag_size'].'%">'.stripslashes($tag['name_tag']).'</a>';
                }
                ?>
                <p id="show_all_tags" style="padding: 0px;" class="top_right_box_links"><a href="<?php echo $url_tag_cloud; ?>"><?php echo $this->translate('index-show-all')?></a></p>
			</div>
			<img src="/images/gray_dot_line_200.png" alt="Massidea.org" />
			
			<p id="most_active_users" style="padding: 0px;" class="top_right_box_links"><?php echo $this->translate('index-most-active')?> <a href="#"><?php echo $this->translate('index-users')?></a></p>
			<img src="/images/gray_dot_line_200.png" alt="Massidea.org" />
			<div class="top_right_box_links_users">
            <?php
                foreach ($this->activeusers as $user) {
                    $url = $this->url(array('controller' => 'account',
                                            'action' => 'view', 
                                            'user' => $user['login_name_usr'],
                                            'language' => $this->language),
                                            'lang_default', true);
                    echo '<a href="'.$url.'">'.$user['login_name_usr'].'</a> ('.$user['count'].')<br />';
                
                }
            ?>
			</div>
			<div class="top_right_box_links_show_all_users"><a href="#"><?php echo $this->translate('index-show-all')?> <?php echo $this->translate('index-users')?></a></div>
			<img src="/images/gray_dot_line_200.png" alt="Massidea.org" />
			
			<div class="massidea_dev_info"><?php echo $this->translate('index-opensource')?></div>