<?php
// dirty fix to use language variable from view
$language = Zend_Layout::getMvcInstance()->getView()->language;


$url_post = $this->url(array('content_id' => $this->id_cnt,
                             'language' => $language ),
                             'content_shortview', true);

$url_user = $this->url(array('controller' => 'account',
                             'action' => 'view',
                             'user' => $this->login_name_usr,
                             'language' => $language),
                             'lang_default', true);
$type = Zend_Layout::getMvcInstance()->getView()->type;
?>

<div class="mini_content_row">
    <div class="mini_content_row_stats smallsize_<?php echo $type;?>_border">
        <span class="summary_topic">
                <a href="<?php echo $url_post;?>">
                    <?php echo $this->title_cnt;?>
                </a>
        </span>
        <br />
        <?php echo $this->translate('content-list-order-by-views').': '?> <?php echo $this->viewCount; ?>
    </div>

    <div style="clear: both;"></div>

</div>