<?php if($this->admin): ?>
<p><a href="<?php echo $this->link; ?>" style="float: right">Edit feeds</a></p>
<?php endif;?>
<?php if($this->data !== false): ?>
<p><strong>Feed:</strong><br /></p>
<div class='rss-reader clear'><div class='rss-channel'></div><ul>
<?php foreach($this->data['items'] as $item): ?>
	<li style="display:block;"><div class='rss-item'><a href="<?php echo $item['link']; ?>"><?php echo $item['title']; ?></a><br />
	<div class="rss-item-desc" style="display:none"><h2 style="border-bottom:1px dotted #CCC;"><?php echo $item['cTitle']; ?></h2><?php echo $item['desc']; ?></div>
	</div></li>
<?php endforeach; ?>
</ul></div>
<?php endif; ?>