<?php if($this->data !== false): ?>
<div class='rss-reader clear'><div class='rss-channel'><h1><?php echo $this->data['title'];?></h1></div><ul>
<?php foreach($this->data['items'] as $item): ?>
	<li style="display:block;"><div class='rss-item'><a href="<?php echo $item['link']; ?>"><?php echo $item['title']; ?></a><br />
	<?php echo $item['desc']?>
	</div></li>
<?php endforeach; ?>
</ul></div>
<?php endif; ?>