<?php
$language = Zend_Layout::getMvcInstance()->getView()->language;
$url = $this->url(array('controller' => 'account',
                        'action' => 'view',
                        'user' => $this->login_name_usr,
                        'language' => $language),
                        'lang_default', true);
?>
<a href="<?php echo $url ?>">
    <?php echo $this->login_name_usr; ?>
</a>
(<?php echo $this->count; ?>)
<br />