<?php
$language = Zend_Layout::getMvcInstance()->getView()->language;
$url = $this->url(array('controller' => 'account',
                        'action' => 'view',
                        'user' => $this->login_name_usr,
                        'language' => $language),
                        'lang_default',
                        true);
                        
$cityUrl = $this->url(array('controller' => 'account',
                        'action' => 'userlist',
                        'city' => $this->city,
                        'language' => $language),
                        'lang_default',
                        true);
?>
<li><a href="<?php echo $url ?>"><?php echo $this->login_name_usr; ?></a>
<?php
if(isset($this->count)) {
    echo "($this->count)";
}
if (isset($this->city) && !empty($this->city)) {
   echo " | "; ?> <a href="<?php echo $cityUrl; ?>"><?php echo $this->city; ?></a><?php
}
?>
</li>
<?php unset($language, $url); ?>