<?php
$language = Zend_Layout::getMvcInstance()->getView()->language;
$url = $this->url(array('controller' => 'account',
                        'action' => 'view',
                        'user' => $this->login_name_usr,
                        'language' => $language),
                        'lang_default',
                        true);
                        
$cityUrl = $this->url(array('controller' => 'account',
                        'action' => 'userlist',
                        'city' => $this->city,
                        'language' => $language),
                        'lang_default',
                        true);
?>
<li <?php //class="hover-link" onclick="makeLink(this);"?>><a id="user-link" href="<?php echo $url ?>"><?php echo $this->login_name_usr; ?></a>
<?php if(isset($this->count)): ?>
	<?php echo "($this->count)";?>
<?php endif; ?>
<?php if (isset($this->city) && !empty($this->city)): ?>
   | <a href="<?php echo $cityUrl; ?>"><?php echo $this->city; ?></a>
<?php endif; ?>
</li>
<?php unset($language, $url); ?>