<style type="text/css">
#cacheidlist
{
	width: 100%;
	height: 300px;
	border: 1px solid gray;
	padding: 2px;
	overflow: auto;
}

#cacheidlist .cacheidentry
{
	padding: 2px;
}
</style>

<h1><?php echo $this->translate('admin-cachemanager-title'); ?></h1>
<h3><?php echo $this->translate('admin-cachemanager-status'); ?></h3>
<div>
	<p><?php echo $this->translate('admin-cachemanager-filling-percentage'); ?><i><?php echo $this->fillingPercentage; ?>%</i></p>
	<p><?php echo $this->translate('admin-cachemanager-number-of-files'); ?><i><?php echo $this->fileCount; ?></i></p>
	<p><?php echo $this->translate('admin-cachemanager-total-size'); ?><i><?php echo round($this->totalSize,2); ?> kB</i></p>
</div>
<div>
	<a href="<?php echo $this->cleanLink; ?>">Clean all</a> <br />
</div>
<br />
<div id="cacheidlist">
<?php if(!empty($this->flushResponse)): ?>
	<?php foreach ($this->flushResponse as $key => $value): ?>
		<div class="cacheidentry">
			Delete: <?php echo $key; ?> ... <?php echo $value; ?>
		</div>
	<?php endforeach; ?>
<?php else: ?>
	<?php foreach($this->cacheFiles as $cacheFile): ?>
		<div class="cacheidentry">
			<?php echo $cacheFile; ?>
		</div>
	<?php endforeach; ?>
<?php endif; ?>
</div>
<br />
<br />