<?php $this->headScript()->captureStart() ?>
var commentBody = new Array();

$(document).ready(function(){
	var previewChars = 35;
	$(".commentrow").each(function(key, value){
		commentBody[key] = $(value).children().html();
		var commentlength = $(value).children().html().length;
		if(commentlength >= previewChars) {
			var commentshort = commentBody[key].substring(0,previewChars);
			var expandLink = '<a href="#" onclick="javascript:expandText('+key+');return false;">... more</a>';
			$(value).children().html(commentshort + expandLink);
		};
	});
	
	$('#checkallrows').click(function(){
		$("INPUT[type='checkbox']").attr('checked', $('#checkallrows').is(':checked'));   
	});
});

function expandText(key)
{
	$(".commentrow:eq("+key+")").html("<span>"+ commentBody[key] +"</span>");
}

<?php $this->headScript()->captureEnd() ?>

<h2><?php echo $this->translate('admin-comment-flags-title'); ?></h2>
<?php $comments = $this->comments; ?>
<?php if(count($comments)==0): ?> 
	<?php echo $this->translate('admin-comment-flags-no-flags'); ?>
<?php else: // any ways to make this as a zend form? ?>
<form method="post">
<table id="admin_comment_flags_table">
<tr id="desc_tr">
	<td class="desc_td_checkbox"><input type="checkbox" name="selectall" id="checkallrows" /></td>
	<td><?php echo $this->translate('admin-comment-flags-content-title'); ?></td>
	<td style="max-width: 400px;"><?php echo $this->translate('admin-comment-flags-comment-body'); ?></td>
	<td><?php echo $this->translate('admin-comment-flags-flag-count'); ?></td>
</tr>
<?php
$comments = $this->comments;
$count = 0;
?>
<?php foreach($comments as $comment): ?>
	<tr class="item_tr">
	<td><input type="checkbox" name="<?php echo $comment['cmt_id']; ?>" class="chkbx_row" /></td>
	<td><a href="<?php echo $comment['cnt_url']; ?>"><?php echo $comment['cnt_title']; ?></a></td>
	<td class="commentrow"><span><?php echo $comment['cmt_body']; ?></span></td>
	<td><?php echo $comment['cmt_count'];?></td>
	</tr>
	<?php $count++; ?>
<?php endforeach; ?>
</table>
<br />
<p><?php echo $this->translate('admin-comment-flags-items-count') . " " . $count; ?></p>
<fieldset>
	<legend><?php echo $this->translate('admin-comment-flags-control-legend'); ?></legend>
	<input type="radio" id="r_cmt" name="rm" value="comment" />
		<label for="r_cmt">
			<?php echo $this->translate('admin-comment-flags-remove-comment'); ?>
		</label>
	<br />
	<input type="radio" id="r_flg" name="rm" value="flag" />
		<label for="r_flg">
			<?php echo $this->translate('admin-comment-flags-remove-flag'); ?>
		</label>
	<br />
</fieldset>
<br />
<input type="submit" value="<?php echo $this->translate('admin-comment-flags-submit'); ?>" />
</form>
<br />
<?php endif; ?>
<br />
<br />