<?php $this->headScript()->captureStart() ?>
var commentBody = new Array();

$(document).ready(function(){
	var previewChars = 35;
	$(".commentrow").each(function(key, value){
		commentBody[key] = $(value).children().html();
		var commentlength = $(value).children().html().length;
		if(commentlength >= previewChars) {
			var commentshort = commentBody[key].substring(0,previewChars);
			var expandLink = '<a href="#" onclick="javascript:expandText('+key+');return false;">... more</a>';
			$(value).children().html(commentshort + expandLink);
		};
	});
	
	$('#checkallrows').click(function(){
		$("INPUT[type='checkbox']").attr('checked', $('#checkallrows').is(':checked'));   
	});
});

function expandText(key)
{
	$(".commentrow:eq("+key+")").html("<span>"+ commentBody[key] +"</span>");
}

<?php $this->headScript()->captureEnd() ?>

<h1><?php echo $this->translate('admin-comment-flags-title'); ?></h1>
<?php
$comments = $this->comments;
if(count($comments)==0)
{
	echo $this->translate('admin-comment-flags-no-flags');
}
else // any ways to make this as a zend form?
{
?>
<form method="post">
<table id="admin_comment_flags_table">
<tr id="desc_tr">
	<td class="desc_td_checkbox"><input type="checkbox" name="selectall" id="checkallrows" /></td>
	<td><?php echo $this->translate('admin-comment-flags-content-title'); ?></td>
	<td style="max-width: 400px;"><?php echo $this->translate('admin-comment-flags-comment-body'); ?></td>
	<td><?php echo $this->translate('admin-comment-flags-flag-count'); ?></td>
</tr>
<?php 
$comments = $this->comments;
$count = 0;

foreach($comments as $comment)
{
	echo '<tr class="item_tr">'."\n";
	echo "\t<td>" . '<input type="checkbox" name="' . $comment['cmt_id'] . '" class="chkbx_row" />' . "</td>\n";
	echo "\t" . '<td><a href="' . $comment['cnt_url'] . '">' . $comment['cnt_title'] . "</a></td>\n";
	echo "\t" . '<td class="commentrow"><span>' . $comment['cmt_body'] . "</span></td>\n";
	echo "\t<td>" . $comment['cmt_count'] . "</td>\n";
	echo "</tr>\n";
	$count++;
}
?>
</table>
<br />
<p><?php echo $this->translate('admin-comment-flags-items-count') . " " . $count; ?></p>
<fieldset>
	<legend><?php echo $this->translate('admin-comment-flags-control-legend'); ?></legend>
	<input type="radio" id="r_cmt" name="rm" value="comment" />
		<label for="r_cmt">
			<?php echo $this->translate('admin-comment-flags-remove-comment'); ?>
		</label>
	<br />
	<input type="radio" id="r_flg" name="rm" value="flag" />
		<label for="r_flg">
			<?php echo $this->translate('admin-comment-flags-remove-flag'); ?>
		</label>
	<br />
</fieldset>
<br />
<input type="submit" value="<?php echo $this->translate('admin-comment-flags-submit'); ?>" />
</form>
<br />
<?php
}
?>
<br />
<br />