<?php $this->headScript()->captureStart() ?>
$(document).ready(function(){
	$('#checkallrows').click(function(){
		$("INPUT[type='checkbox']").attr('checked', $('#checkallrows').is(':checked'));   
	});
});
<?php $this->headScript()->captureEnd() ?>

<h1><?php echo $this->translate('admin-content-flags-title'); ?></h1>
<?php
$contents = $this->contents;
if(count($contents)==0)
{
	echo $this->translate('admin-content-flags-no-flags');
}
else // any ways to make this as a zend form?
{
?>
<form method="post">
<table id="admin_comment_flags_table">
<tr id="desc_tr">
	<td class="desc_td_checkbox"><input type="checkbox" name="selectall" id="checkallrows" /></td>
	<td><?php echo $this->translate('admin-content-flags-content-title'); ?></td>
	<td style="max-width: 400px;"><?php echo $this->translate('admin-content-flags-content-body'); ?></td>
	<td><?php echo $this->translate('admin-content-flags-flag-count'); ?></td>
</tr>
<?php 
$contents = $this->contents;
$count = 0;

foreach($contents as $content)
{
	echo '<tr class="item_tr">'."\n";
	echo "\t<td>" . '<input type="checkbox" name="' . $content['id'] . '" class="chkbx_row" />' . "</td>\n";
	echo "\t" . '<td><a href="' . $content['url'] . '">' . $content['title'] . "</a></td>\n";
	echo "\t" . '<td class="contentrow"><span>' . $content['lead'] . "</span></td>\n";
	echo "\t<td>" . $content['count'] . "</td>\n";
	echo "</tr>\n";
	$count++;
}
?>
</table>
<br />
<p><?php echo $this->translate('admin-content-flags-items-count') . " " . $count; ?></p>
<fieldset>
	<legend><?php echo $this->translate('admin-content-flags-control-legend'); ?></legend>
	<input type="radio" id="r_cmt" name="rm" value="content" />
		<label for="r_cmt">
			<?php echo $this->translate('admin-content-flags-remove-content'); ?>
		</label>
	<br />
	<input type="radio" id="r_cmt" name="rm" value="pubflag" />
		<label for="r_cmt">
			<?php echo $this->translate('admin-content-flags-remove-pubflag'); ?>
		</label>
	<br />
	<input type="radio" id="r_flg" name="rm" value="flag" />
		<label for="r_flg">
			<?php echo $this->translate('admin-content-flags-remove-flag'); ?>
		</label>
	<br />
</fieldset>
<br />
<input type="submit" value="<?php echo $this->translate('admin-content-flags-submit'); ?>" />
</form>
<br />
<?php
}
?>
<br />
<br />