<?php Zend_Layout::getMvcInstance()->setLayout('layout_new'); ?>
<?php $this->headScript()->captureStart() ?>
$(document).ready(function(){
	$('#checkallrows').click(function(){
		$("INPUT[type='checkbox']").attr('checked', $('#checkallrows').is(':checked'));   
	});
});
<?php $this->headScript()->captureEnd() ?>

<h2><?php echo $this->translate('admin-content-flags-title'); ?></h2>
<?php $contents = $this->contents; ?>
<?php if(count($contents)==0): ?>
	<?php echo $this->translate('admin-content-flags-no-flags'); ?>
<?php else: // any ways to make this as a zend form? ?>
<form method="post">
<table id="admin_comment_flags_table">
<tr id="desc_tr">
	<td class="desc_td_checkbox"><input type="checkbox" name="selectall" id="checkallrows" /></td>
	<td><?php echo $this->translate('admin-content-flags-content-title'); ?></td>
	<td style="max-width: 400px;"><?php echo $this->translate('admin-content-flags-content-body'); ?></td>
	<td><?php echo $this->translate('admin-content-flags-flag-count'); ?></td>
</tr>
<?php 
$contents = $this->contents;
$count = 0;
?>

<?php foreach($contents as $content): ?>

	<tr class="item_tr">
		<td><input type="checkbox" name="<?php echo $content['id']; ?>" class="chkbx_row" /></td>
		<td><a href="<?php echo $content['url']; ?>"><?php $content['title']; ?></a></td>
		<td class="contentrow"><span><?php echo $content['lead'];?></span></td>
		<td><?php echo $content['count'];?></td>
	</tr>
	<?php $count++; ?>
	<?php endforeach; ?>
</table>
<br />
<p><?php echo $this->translate('admin-content-flags-items-count') . " " . $count; ?></p>
<fieldset>
	<legend><?php echo $this->translate('admin-content-flags-control-legend'); ?></legend>
	<input type="radio" id="r_cmt" name="rm" value="content" />
		<label for="r_cmt">
			<?php echo $this->translate('admin-content-flags-remove-content'); ?>
		</label>
	<br />
	<input type="radio" id="r_cmt" name="rm" value="pubflag" />
		<label for="r_cmt">
			<?php echo $this->translate('admin-content-flags-remove-pubflag'); ?>
		</label>
	<br />
	<input type="radio" id="r_flg" name="rm" value="flag" />
		<label for="r_flg">
			<?php echo $this->translate('admin-content-flags-remove-flag'); ?>
		</label>
	<br />
</fieldset>
<br />
<input type="submit" value="<?php echo $this->translate('admin-content-flags-submit'); ?>" />
</form>
<br />
<?php endif; ?>
<br />
<br />