<h1><?php echo $this->translate('admin-edit-user-roles-title') . " " . $this->editrole_username; ?></h1>

<p>
<b><?php echo $this->translate('admin-edit-user-roles-current-roles'); ?></b> <br /><br />

<?php

if(!empty($this->user_roles))
{
    foreach($this->user_roles as $role)
    {
        if($role == "user")
        {
            echo $role . " (".$this->translate('admin-edit-user-roles-cant-remove').")<br />";
        }
        else
        {
            if(isset($_GET['confirm']))
            {
                if($_GET['confirm'] == $role)
                {
                    echo $role . " <b>".$this->translate('admin-edit-user-roles-confirm')."</b> <a href=\"/".$this->language."/admin/removerole/".$this->editrole_username."/".$role."\">".$this->translate('admin-edit-user-roles-confirm-yes')."</a> / ";
                    echo "<a href=\"/".$this->language."/admin/editroles/".$this->editrole_username."\" />".$this->translate('admin-edit-user-roles-confirm-no')."</a><br />";
                }
                else
                {
                    echo $role . " <a href=\"/".$this->language."/admin/editroles/".$this->editrole_username."?confirm=".$role."\" />".$this->translate('admin-edit-user-roles-remove')."</a><br />";
                }
            }
            else
            {
                echo $role . " <a href=\"/".$this->language."/admin/editroles/".$this->editrole_username."?confirm=".$role."\" />".$this->translate('admin-edit-user-roles-remove')."</a><br />";
            }
        }
    }
}
else
{
    echo $this->translate('admin-edit-user-roles-user-no-roles');
}

?>

</p><br />

<p>
<b><?php echo $this->translate('admin-edit-user-roles-add-new-roles'); ?></b> <br /><br />
<?php

foreach($this->roles as $role)
{
    if(!in_array($role, $this->user_roles))
    {
        if(isset($_GET['confirm']))
        {
            if($_GET['confirm'] == $role)
            {
                echo $role . " <b>".$this->translate('admin-edit-user-roles-confirm')."</b> <a href=\"/".$this->language."/admin/addrole/".$this->editrole_username."/".$role."\" />".$this->translate('admin-edit-user-roles-confirm-yes')."</a> / ";
                echo "<a href=\"/".$this->language."/admin/editroles/".$this->editrole_username."\" />".$this->translate('admin-edit-user-roles-confirm-no')."</a><br />";
            }
            else
            {
                echo $role . " <a href=\"/".$this->language."/admin/editroles/".$this->editrole_username."?confirm=".$role."\" />".$this->translate('admin-edit-user-roles-add')."</a><br />";
            }
        }
        else
        {
            echo $role . " <a href=\"/".$this->language."/admin/editroles/".$this->editrole_username."?confirm=".$role."\" />".$this->translate('admin-edit-user-roles-add')."</a><br />";
        }
    }
}

?>
</p>