<?php 
/*
 * Add action links into this array.
 */
$actionList = array(
	array('admin-manage-roles-task-title', 'manageroles'),
	array('admin-content-flags-task-title', 'contentflags'),
	array('admin-comment-flags-task-title', 'commentflags'),
	array('admin-cachemanager-title', 'cachemanager')
);

?>

<h1><?php echo $this->translate('admin-title'); ?></h1>
<h3><?php echo $this->translate('admin-tasks'); ?></h3>
<ul>
<?php foreach($actionList as $action): ?>
	<li><a href="<?php echo $this->url(array('action' => $action[1])); ?>"><?php echo $this->translate($action[0]); ?></a></li>
<?php endforeach; ?>
</ul>