<?php
if($this->managerolesaction == "")
{
    ?>
    <h2><?php echo $this->translate('admin-manage-roles-title'); ?></h2>
    <p>
        <a href="<?php echo $this->baseUrl."/".$this->language; ?>/admin/manageroles/add">
            <?php echo $this->translate('admin-manage-roles-add'); ?>
        </a><br />
        <a href="<?php echo $this->baseUrl."/".$this->language; ?>/admin/manageroles/edit">
            <?php echo $this->translate('admin-manage-roles-edit'); ?>
        </a><br />
        <a href="<?php echo $this->baseUrl."/".$this->language; ?>/admin/manageroles/remove">
            <?php echo $this->translate('admin-manage-roles-remove'); ?>
        </a><br />
    </p>
    <?php
}
elseif($this->managerolesaction == "add")
{
    echo "<h2>".$this->translate('admin-manage-roles-add-title')."</h2>";
}
elseif($this->managerolesaction == "edit")
{
    echo "<h2>".$this->translate('admin-manage-roles-edit-title')."</h2>";
}
elseif($this->managerolesaction == "remove")
{
    echo "<h2>".$this->translate('admin-manage-roles-remove-title')."</h2>";
}

?>