-- Deleting old language database and replace it with google language code languages.

USE `oibs`;

alter table contents_cnt modify language_cnt varchar(5) NOT NULL;

delete from languages_lng;
alter table languages_lng modify iso6391_lng varchar(5) NOT NULL;

INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (1, 'af', 'Afrikaans', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (2, 'sq', 'Albanian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (3, 'am', 'Amharic', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (4, 'ar', 'Arabic', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (5, 'hy', 'Armenian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (6, 'az', 'Azerbaijani', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (7, 'eu', 'Basque', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (8, 'be', 'Belarusian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (9, 'bn', 'Bengali', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (10, 'bh', 'Bihari', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (11, 'bg', 'Bulgarian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (12, 'my', 'Burmese', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (13, 'ca', 'Catalan', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (14, 'chr', 'Cherokee', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (15, 'zh', 'Chinese', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (16, 'zh-CN', 'Chinese_simplified', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (17, 'zh-TW', 'Chinese_traditional', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (18, 'hr', 'Croatian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (19, 'cs', 'Czech', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (20, 'da', 'Danish', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (21, 'dv', 'Dhivehi', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (22, 'nl', 'Dutch', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (23, 'en', 'English', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (24, 'eo', 'Esperanto', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (25, 'et', 'Estonian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (26, 'tl', 'Filipino', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (27, 'fi', 'Finnish', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (28, 'fr', 'French', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (29, 'gl', 'Galician', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (30, 'ka', 'Georgian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (31, 'de', 'German', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (32, 'el', 'Greek', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (33, 'gn', 'Guarani', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (34, 'gu', 'Gujarati', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (35, 'iw', 'Hebrew', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (36, 'hi', 'Hindi', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (37, 'hu', 'Hungarian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (38, 'is', 'Icelandic', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (39, 'id', 'Indonesian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (40, 'iu', 'Inuktitut', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (41, 'ga', 'Irish', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (42, 'it', 'Italian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (43, 'ja', 'Japanese', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (44, 'kn', 'Kannada', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (45, 'kk', 'Kazakh', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (46, 'km', 'Khmer', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (47, 'ko', 'Korean', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (48, 'ku', 'Kurdish', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (49, 'ky', 'Kyrgyz', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (50, 'lo', 'Laothian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (51, 'lv', 'Latvian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (52, 'lt', 'Lithuanian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (53, 'mk', 'Macedonian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (54, 'ms', 'Malay', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (55, 'ml', 'Malayalam', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (56, 'mt', 'Maltese', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (57, 'mr', 'Marathi', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (58, 'mn', 'Mongolian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (59, 'ne', 'Nepali', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (60, 'no', 'Norwegian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (61, 'or', 'Oriya', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (62, 'ps', 'Pashto', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (63, 'fa', 'Persian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (64, 'pl', 'Polish', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (65, 'pt-PT', 'Portuguese', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (66, 'pa', 'Punjabi', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (67, 'ro', 'Romanian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (68, 'ru', 'Russian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (69, 'sa', 'Sanskrit', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (70, 'sr', 'Serbian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (71, 'sd', 'Sindhi', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (72, 'si', 'Sinhalese', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (73, 'sk', 'Slovak', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (74, 'sl', 'Slovenian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (75, 'es', 'Spanish', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (76, 'sw', 'Swahili', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (77, 'sv', 'Swedish', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (78, 'tg', 'Tajik', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (79, 'ta', 'Tamil', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (80, 'tl', 'Tagalog', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (81, 'te', 'Telugu', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (82, 'th', 'Thai', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (83, 'bo', 'Tibetan', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (84, 'tr', 'Turkish', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (85, 'uk', 'Ukrainian', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (86, 'ur', 'Urdu', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (87, 'uz', 'Uzbek', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (88, 'ug', 'Uighur', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (89, 'vi', 'Vietnamese', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (90, 'cy', 'Welsh', NOW(), NOW());
INSERT INTO languages_lng (id_lng, iso6391_lng, name_lng, created_lng, modified_lng) VALUES (91, 'yi', 'Yiddish', NOW(), NOW());

UPDATE contents_cnt SET language_cnt = 'en' WHERE language_cnt NOT IN (SELECT iso6391_lng from languages_lng);

