# iso_country_list.sql
#
# This will create and then populate a MySQL table with a list of the names and
# ISO 3166 codes for countries in existence as of the date below.
#
# Usage:
# mysql -u username -ppassword database_name < ./iso_country_list.sql
#
# For updates to this file, see http://27.org/isocountrylist/
# For more about ISO 3166, see http://www.iso.ch/iso/en/prods-services/iso3166ma/02iso-3166-code-lists/list-en1.html
#
# Created by getisocountrylist.pl on Sun Nov 2 14:59:20 2003.
# Wm. Rhodes <iso_country_list@27.org>
#
  
USE OIBS;

DROP TABLE IF EXISTS countries_ctr;
  
CREATE TABLE countries_ctr (
    iso_ctr CHAR(2) NOT NULL PRIMARY KEY,
    name_ctr VARCHAR(80) NOT NULL,
    printable_name_ctr VARCHAR(80) NOT NULL,
    iso3_ctr CHAR(3),
    numcode_ctr SMALLINT
);

INSERT INTO countries_ctr VALUES ('AF','AFGHANISTAN','Afghanistan','AFG','004');
INSERT INTO countries_ctr VALUES ('AL','ALBANIA','Albania','ALB','008');
INSERT INTO countries_ctr VALUES ('DZ','ALGERIA','Algeria','DZA','012');
INSERT INTO countries_ctr VALUES ('AS','AMERICAN SAMOA','American Samoa','ASM','016');
INSERT INTO countries_ctr VALUES ('AD','ANDORRA','Andorra','AND','020');
INSERT INTO countries_ctr VALUES ('AO','ANGOLA','Angola','AGO','024');
INSERT INTO countries_ctr VALUES ('AI','ANGUILLA','Anguilla','AIA','660');
INSERT INTO countries_ctr VALUES ('AQ','ANTARCTICA','Antarctica',NULL,NULL);
INSERT INTO countries_ctr VALUES ('AG','ANTIGUA AND BARBUDA','Antigua and Barbuda','ATG','028');
INSERT INTO countries_ctr VALUES ('AR','ARGENTINA','Argentina','ARG','032');
INSERT INTO countries_ctr VALUES ('AM','ARMENIA','Armenia','ARM','051');
INSERT INTO countries_ctr VALUES ('AW','ARUBA','Aruba','ABW','533');
INSERT INTO countries_ctr VALUES ('AU','AUSTRALIA','Australia','AUS','036');
INSERT INTO countries_ctr VALUES ('AT','AUSTRIA','Austria','AUT','040');
INSERT INTO countries_ctr VALUES ('AZ','AZERBAIJAN','Azerbaijan','AZE','031');
INSERT INTO countries_ctr VALUES ('BS','BAHAMAS','Bahamas','BHS','044');
INSERT INTO countries_ctr VALUES ('BH','BAHRAIN','Bahrain','BHR','048');
INSERT INTO countries_ctr VALUES ('BD','BANGLADESH','Bangladesh','BGD','050');
INSERT INTO countries_ctr VALUES ('BB','BARBADOS','Barbados','BRB','052');
INSERT INTO countries_ctr VALUES ('BY','BELARUS','Belarus','BLR','112');
INSERT INTO countries_ctr VALUES ('BE','BELGIUM','Belgium','BEL','056');
INSERT INTO countries_ctr VALUES ('BZ','BELIZE','Belize','BLZ','084');
INSERT INTO countries_ctr VALUES ('BJ','BENIN','Benin','BEN','204');
INSERT INTO countries_ctr VALUES ('BM','BERMUDA','Bermuda','BMU','060');
INSERT INTO countries_ctr VALUES ('BT','BHUTAN','Bhutan','BTN','064');
INSERT INTO countries_ctr VALUES ('BO','BOLIVIA','Bolivia','BOL','068');
INSERT INTO countries_ctr VALUES ('BA','BOSNIA AND HERZEGOVINA','Bosnia and Herzegovina','BIH','070');
INSERT INTO countries_ctr VALUES ('BW','BOTSWANA','Botswana','BWA','072');
INSERT INTO countries_ctr VALUES ('BV','BOUVET ISLAND','Bouvet Island',NULL,NULL);
INSERT INTO countries_ctr VALUES ('BR','BRAZIL','Brazil','BRA','076');
INSERT INTO countries_ctr VALUES ('IO','BRITISH INDIAN OCEAN TERRITORY','British Indian Ocean Territory',NULL,NULL);
INSERT INTO countries_ctr VALUES ('BN','BRUNEI DARUSSALAM','Brunei Darussalam','BRN','096');
INSERT INTO countries_ctr VALUES ('BG','BULGARIA','Bulgaria','BGR','100');
INSERT INTO countries_ctr VALUES ('BF','BURKINA FASO','Burkina Faso','BFA','854');
INSERT INTO countries_ctr VALUES ('BI','BURUNDI','Burundi','BDI','108');
INSERT INTO countries_ctr VALUES ('KH','CAMBODIA','Cambodia','KHM','116');
INSERT INTO countries_ctr VALUES ('CM','CAMEROON','Cameroon','CMR','120');
INSERT INTO countries_ctr VALUES ('CA','CANADA','Canada','CAN','124');
INSERT INTO countries_ctr VALUES ('CV','CAPE VERDE','Cape Verde','CPV','132');
INSERT INTO countries_ctr VALUES ('KY','CAYMAN ISLANDS','Cayman Islands','CYM','136');
INSERT INTO countries_ctr VALUES ('CF','CENTRAL AFRICAN REPUBLIC','Central African Republic','CAF','140');
INSERT INTO countries_ctr VALUES ('TD','CHAD','Chad','TCD','148');
INSERT INTO countries_ctr VALUES ('CL','CHILE','Chile','CHL','152');
INSERT INTO countries_ctr VALUES ('CN','CHINA','China','CHN','156');
INSERT INTO countries_ctr VALUES ('CX','CHRISTMAS ISLAND','Christmas Island',NULL,NULL);
INSERT INTO countries_ctr VALUES ('CC','COCOS (KEELING) ISLANDS','Cocos (Keeling) Islands',NULL,NULL);
INSERT INTO countries_ctr VALUES ('CO','COLOMBIA','Colombia','COL','170');
INSERT INTO countries_ctr VALUES ('KM','COMOROS','Comoros','COM','174');
INSERT INTO countries_ctr VALUES ('CG','CONGO','Congo','COG','178');
INSERT INTO countries_ctr VALUES ('CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE','Congo, the Democratic Republic of the','COD','180');
INSERT INTO countries_ctr VALUES ('CK','COOK ISLANDS','Cook Islands','COK','184');
INSERT INTO countries_ctr VALUES ('CR','COSTA RICA','Costa Rica','CRI','188');
INSERT INTO countries_ctr VALUES ('CI','COTE D\'IVOIRE','Cote D\'Ivoire','CIV','384');
INSERT INTO countries_ctr VALUES ('HR','CROATIA','Croatia','HRV','191');
INSERT INTO countries_ctr VALUES ('CU','CUBA','Cuba','CUB','192');
INSERT INTO countries_ctr VALUES ('CY','CYPRUS','Cyprus','CYP','196');
INSERT INTO countries_ctr VALUES ('CZ','CZECH REPUBLIC','Czech Republic','CZE','203');
INSERT INTO countries_ctr VALUES ('DK','DENMARK','Denmark','DNK','208');
INSERT INTO countries_ctr VALUES ('DJ','DJIBOUTI','Djibouti','DJI','262');
INSERT INTO countries_ctr VALUES ('DM','DOMINICA','Dominica','DMA','212');
INSERT INTO countries_ctr VALUES ('DO','DOMINICAN REPUBLIC','Dominican Republic','DOM','214');
INSERT INTO countries_ctr VALUES ('EC','ECUADOR','Ecuador','ECU','218');
INSERT INTO countries_ctr VALUES ('EG','EGYPT','Egypt','EGY','818');
INSERT INTO countries_ctr VALUES ('SV','EL SALVADOR','El Salvador','SLV','222');
INSERT INTO countries_ctr VALUES ('GQ','EQUATORIAL GUINEA','Equatorial Guinea','GNQ','226');
INSERT INTO countries_ctr VALUES ('ER','ERITREA','Eritrea','ERI','232');
INSERT INTO countries_ctr VALUES ('EE','ESTONIA','Estonia','EST','233');
INSERT INTO countries_ctr VALUES ('ET','ETHIOPIA','Ethiopia','ETH','231');
INSERT INTO countries_ctr VALUES ('FK','FALKLAND ISLANDS (MALVINAS)','Falkland Islands (Malvinas)','FLK','238');
INSERT INTO countries_ctr VALUES ('FO','FAROE ISLANDS','Faroe Islands','FRO','234');
INSERT INTO countries_ctr VALUES ('FJ','FIJI','Fiji','FJI','242');
INSERT INTO countries_ctr VALUES ('FI','FINLAND','Finland','FIN','246');
INSERT INTO countries_ctr VALUES ('FR','FRANCE','France','FRA','250');
INSERT INTO countries_ctr VALUES ('GF','FRENCH GUIANA','French Guiana','GUF','254');
INSERT INTO countries_ctr VALUES ('PF','FRENCH POLYNESIA','French Polynesia','PYF','258');
INSERT INTO countries_ctr VALUES ('TF','FRENCH SOUTHERN TERRITORIES','French Southern Territories',NULL,NULL);
INSERT INTO countries_ctr VALUES ('GA','GABON','Gabon','GAB','266');
INSERT INTO countries_ctr VALUES ('GM','GAMBIA','Gambia','GMB','270');
INSERT INTO countries_ctr VALUES ('GE','GEORGIA','Georgia','GEO','268');
INSERT INTO countries_ctr VALUES ('DE','GERMANY','Germany','DEU','276');
INSERT INTO countries_ctr VALUES ('GH','GHANA','Ghana','GHA','288');
INSERT INTO countries_ctr VALUES ('GI','GIBRALTAR','Gibraltar','GIB','292');
INSERT INTO countries_ctr VALUES ('GR','GREECE','Greece','GRC','300');
INSERT INTO countries_ctr VALUES ('GL','GREENLAND','Greenland','GRL','304');
INSERT INTO countries_ctr VALUES ('GD','GRENADA','Grenada','GRD','308');
INSERT INTO countries_ctr VALUES ('GP','GUADELOUPE','Guadeloupe','GLP','312');
INSERT INTO countries_ctr VALUES ('GU','GUAM','Guam','GUM','316');
INSERT INTO countries_ctr VALUES ('GT','GUATEMALA','Guatemala','GTM','320');
INSERT INTO countries_ctr VALUES ('GN','GUINEA','Guinea','GIN','324');
INSERT INTO countries_ctr VALUES ('GW','GUINEA-BISSAU','Guinea-Bissau','GNB','624');
INSERT INTO countries_ctr VALUES ('GY','GUYANA','Guyana','GUY','328');
INSERT INTO countries_ctr VALUES ('HT','HAITI','Haiti','HTI','332');
INSERT INTO countries_ctr VALUES ('HM','HEARD ISLAND AND MCDONALD ISLANDS','Heard Island and Mcdonald Islands',NULL,NULL);
INSERT INTO countries_ctr VALUES ('VA','HOLY SEE (VATICAN CITY STATE)','Holy See (Vatican City State)','VAT','336');
INSERT INTO countries_ctr VALUES ('HN','HONDURAS','Honduras','HND','340');
INSERT INTO countries_ctr VALUES ('HK','HONG KONG','Hong Kong','HKG','344');
INSERT INTO countries_ctr VALUES ('HU','HUNGARY','Hungary','HUN','348');
INSERT INTO countries_ctr VALUES ('IS','ICELAND','Iceland','ISL','352');
INSERT INTO countries_ctr VALUES ('IN','INDIA','India','IND','356');
INSERT INTO countries_ctr VALUES ('ID','INDONESIA','Indonesia','IDN','360');
INSERT INTO countries_ctr VALUES ('IR','IRAN, ISLAMIC REPUBLIC OF','Iran, Islamic Republic of','IRN','364');
INSERT INTO countries_ctr VALUES ('IQ','IRAQ','Iraq','IRQ','368');
INSERT INTO countries_ctr VALUES ('IE','IRELAND','Ireland','IRL','372');
INSERT INTO countries_ctr VALUES ('IL','ISRAEL','Israel','ISR','376');
INSERT INTO countries_ctr VALUES ('IT','ITALY','Italy','ITA','380');
INSERT INTO countries_ctr VALUES ('JM','JAMAICA','Jamaica','JAM','388');
INSERT INTO countries_ctr VALUES ('JP','JAPAN','Japan','JPN','392');
INSERT INTO countries_ctr VALUES ('JO','JORDAN','Jordan','JOR','400');
INSERT INTO countries_ctr VALUES ('KZ','KAZAKHSTAN','Kazakhstan','KAZ','398');
INSERT INTO countries_ctr VALUES ('KE','KENYA','Kenya','KEN','404');
INSERT INTO countries_ctr VALUES ('KI','KIRIBATI','Kiribati','KIR','296');
INSERT INTO countries_ctr VALUES ('KP','KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF','Korea, Democratic People\'s Republic of','PRK','408');
INSERT INTO countries_ctr VALUES ('KR','KOREA, REPUBLIC OF','Korea, Republic of','KOR','410');
INSERT INTO countries_ctr VALUES ('KW','KUWAIT','Kuwait','KWT','414');
INSERT INTO countries_ctr VALUES ('KG','KYRGYZSTAN','Kyrgyzstan','KGZ','417');
INSERT INTO countries_ctr VALUES ('LA','LAO PEOPLE\'S DEMOCRATIC REPUBLIC','Lao People\'s Democratic Republic','LAO','418');
INSERT INTO countries_ctr VALUES ('LV','LATVIA','Latvia','LVA','428');
INSERT INTO countries_ctr VALUES ('LB','LEBANON','Lebanon','LBN','422');
INSERT INTO countries_ctr VALUES ('LS','LESOTHO','Lesotho','LSO','426');
INSERT INTO countries_ctr VALUES ('LR','LIBERIA','Liberia','LBR','430');
INSERT INTO countries_ctr VALUES ('LY','LIBYAN ARAB JAMAHIRIYA','Libyan Arab Jamahiriya','LBY','434');
INSERT INTO countries_ctr VALUES ('LI','LIECHTENSTEIN','Liechtenstein','LIE','438');
INSERT INTO countries_ctr VALUES ('LT','LITHUANIA','Lithuania','LTU','440');
INSERT INTO countries_ctr VALUES ('LU','LUXEMBOURG','Luxembourg','LUX','442');
INSERT INTO countries_ctr VALUES ('MO','MACAO','Macao','MAC','446');
INSERT INTO countries_ctr VALUES ('MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','Macedonia, the Former Yugoslav Republic of','MKD','807');
INSERT INTO countries_ctr VALUES ('MG','MADAGASCAR','Madagascar','MDG','450');
INSERT INTO countries_ctr VALUES ('MW','MALAWI','Malawi','MWI','454');
INSERT INTO countries_ctr VALUES ('MY','MALAYSIA','Malaysia','MYS','458');
INSERT INTO countries_ctr VALUES ('MV','MALDIVES','Maldives','MDV','462');
INSERT INTO countries_ctr VALUES ('ML','MALI','Mali','MLI','466');
INSERT INTO countries_ctr VALUES ('MT','MALTA','Malta','MLT','470');
INSERT INTO countries_ctr VALUES ('MH','MARSHALL ISLANDS','Marshall Islands','MHL','584');
INSERT INTO countries_ctr VALUES ('MQ','MARTINIQUE','Martinique','MTQ','474');
INSERT INTO countries_ctr VALUES ('MR','MAURITANIA','Mauritania','MRT','478');
INSERT INTO countries_ctr VALUES ('MU','MAURITIUS','Mauritius','MUS','480');
INSERT INTO countries_ctr VALUES ('YT','MAYOTTE','Mayotte',NULL,NULL);
INSERT INTO countries_ctr VALUES ('MX','MEXICO','Mexico','MEX','484');
INSERT INTO countries_ctr VALUES ('FM','MICRONESIA, FEDERATED STATES OF','Micronesia, Federated States of','FSM','583');
INSERT INTO countries_ctr VALUES ('MD','MOLDOVA, REPUBLIC OF','Moldova, Republic of','MDA','498');
INSERT INTO countries_ctr VALUES ('MC','MONACO','Monaco','MCO','492');
INSERT INTO countries_ctr VALUES ('MN','MONGOLIA','Mongolia','MNG','496');
INSERT INTO countries_ctr VALUES ('MS','MONTSERRAT','Montserrat','MSR','500');
INSERT INTO countries_ctr VALUES ('MA','MOROCCO','Morocco','MAR','504');
INSERT INTO countries_ctr VALUES ('MZ','MOZAMBIQUE','Mozambique','MOZ','508');
INSERT INTO countries_ctr VALUES ('MM','MYANMAR','Myanmar','MMR','104');
INSERT INTO countries_ctr VALUES ('NA','NAMIBIA','Namibia','NAM','516');
INSERT INTO countries_ctr VALUES ('NR','NAURU','Nauru','NRU','520');
INSERT INTO countries_ctr VALUES ('NP','NEPAL','Nepal','NPL','524');
INSERT INTO countries_ctr VALUES ('NL','NETHERLANDS','Netherlands','NLD','528');
INSERT INTO countries_ctr VALUES ('AN','NETHERLANDS ANTILLES','Netherlands Antilles','ANT','530');
INSERT INTO countries_ctr VALUES ('NC','NEW CALEDONIA','New Caledonia','NCL','540');
INSERT INTO countries_ctr VALUES ('NZ','NEW ZEALAND','New Zealand','NZL','554');
INSERT INTO countries_ctr VALUES ('NI','NICARAGUA','Nicaragua','NIC','558');
INSERT INTO countries_ctr VALUES ('NE','NIGER','Niger','NER','562');
INSERT INTO countries_ctr VALUES ('NG','NIGERIA','Nigeria','NGA','566');
INSERT INTO countries_ctr VALUES ('NU','NIUE','Niue','NIU','570');
INSERT INTO countries_ctr VALUES ('NF','NORFOLK ISLAND','Norfolk Island','NFK','574');
INSERT INTO countries_ctr VALUES ('MP','NORTHERN MARIANA ISLANDS','Northern Mariana Islands','MNP','580');
INSERT INTO countries_ctr VALUES ('NO','NORWAY','Norway','NOR','578');
INSERT INTO countries_ctr VALUES ('OM','OMAN','Oman','OMN','512');
INSERT INTO countries_ctr VALUES ('PK','PAKISTAN','Pakistan','PAK','586');
INSERT INTO countries_ctr VALUES ('PW','PALAU','Palau','PLW','585');
INSERT INTO countries_ctr VALUES ('PS','PALESTINIAN TERRITORY, OCCUPIED','Palestinian Territory, Occupied',NULL,NULL);
INSERT INTO countries_ctr VALUES ('PA','PANAMA','Panama','PAN','591');
INSERT INTO countries_ctr VALUES ('PG','PAPUA NEW GUINEA','Papua New Guinea','PNG','598');
INSERT INTO countries_ctr VALUES ('PY','PARAGUAY','Paraguay','PRY','600');
INSERT INTO countries_ctr VALUES ('PE','PERU','Peru','PER','604');
INSERT INTO countries_ctr VALUES ('PH','PHILIPPINES','Philippines','PHL','608');
INSERT INTO countries_ctr VALUES ('PN','PITCAIRN','Pitcairn','PCN','612');
INSERT INTO countries_ctr VALUES ('PL','POLAND','Poland','POL','616');
INSERT INTO countries_ctr VALUES ('PT','PORTUGAL','Portugal','PRT','620');
INSERT INTO countries_ctr VALUES ('PR','PUERTO RICO','Puerto Rico','PRI','630');
INSERT INTO countries_ctr VALUES ('QA','QATAR','Qatar','QAT','634');
INSERT INTO countries_ctr VALUES ('RE','REUNION','Reunion','REU','638');
INSERT INTO countries_ctr VALUES ('RO','ROMANIA','Romania','ROM','642');
INSERT INTO countries_ctr VALUES ('RU','RUSSIAN FEDERATION','Russian Federation','RUS','643');
INSERT INTO countries_ctr VALUES ('RW','RWANDA','Rwanda','RWA','646');
INSERT INTO countries_ctr VALUES ('SH','SAINT HELENA','Saint Helena','SHN','654');
INSERT INTO countries_ctr VALUES ('KN','SAINT KITTS AND NEVIS','Saint Kitts and Nevis','KNA','659');
INSERT INTO countries_ctr VALUES ('LC','SAINT LUCIA','Saint Lucia','LCA','662');
INSERT INTO countries_ctr VALUES ('PM','SAINT PIERRE AND MIQUELON','Saint Pierre and Miquelon','SPM','666');
INSERT INTO countries_ctr VALUES ('VC','SAINT VINCENT AND THE GRENADINES','Saint Vincent and the Grenadines','VCT','670');
INSERT INTO countries_ctr VALUES ('WS','SAMOA','Samoa','WSM','882');
INSERT INTO countries_ctr VALUES ('SM','SAN MARINO','San Marino','SMR','674');
INSERT INTO countries_ctr VALUES ('ST','SAO TOME AND PRINCIPE','Sao Tome and Principe','STP','678');
INSERT INTO countries_ctr VALUES ('SA','SAUDI ARABIA','Saudi Arabia','SAU','682');
INSERT INTO countries_ctr VALUES ('SN','SENEGAL','Senegal','SEN','686');
INSERT INTO countries_ctr VALUES ('CS','SERBIA AND MONTENEGRO','Serbia and Montenegro',NULL,NULL);
INSERT INTO countries_ctr VALUES ('SC','SEYCHELLES','Seychelles','SYC','690');
INSERT INTO countries_ctr VALUES ('SL','SIERRA LEONE','Sierra Leone','SLE','694');
INSERT INTO countries_ctr VALUES ('SG','SINGAPORE','Singapore','SGP','702');
INSERT INTO countries_ctr VALUES ('SK','SLOVAKIA','Slovakia','SVK','703');
INSERT INTO countries_ctr VALUES ('SI','SLOVENIA','Slovenia','SVN','705');
INSERT INTO countries_ctr VALUES ('SB','SOLOMON ISLANDS','Solomon Islands','SLB','090');
INSERT INTO countries_ctr VALUES ('SO','SOMALIA','Somalia','SOM','706');
INSERT INTO countries_ctr VALUES ('ZA','SOUTH AFRICA','South Africa','ZAF','710');
INSERT INTO countries_ctr VALUES ('GS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','South Georgia and the South Sandwich Islands',NULL,NULL);
INSERT INTO countries_ctr VALUES ('ES','SPAIN','Spain','ESP','724');
INSERT INTO countries_ctr VALUES ('LK','SRI LANKA','Sri Lanka','LKA','144');
INSERT INTO countries_ctr VALUES ('SD','SUDAN','Sudan','SDN','736');
INSERT INTO countries_ctr VALUES ('SR','SURINAME','Suriname','SUR','740');
INSERT INTO countries_ctr VALUES ('SJ','SVALBARD AND JAN MAYEN','Svalbard and Jan Mayen','SJM','744');
INSERT INTO countries_ctr VALUES ('SZ','SWAZILAND','Swaziland','SWZ','748');
INSERT INTO countries_ctr VALUES ('SE','SWEDEN','Sweden','SWE','752');
INSERT INTO countries_ctr VALUES ('CH','SWITZERLAND','Switzerland','CHE','756');
INSERT INTO countries_ctr VALUES ('SY','SYRIAN ARAB REPUBLIC','Syrian Arab Republic','SYR','760');
INSERT INTO countries_ctr VALUES ('TW','TAIWAN, PROVINCE OF CHINA','Taiwan, Province of China','TWN','158');
INSERT INTO countries_ctr VALUES ('TJ','TAJIKISTAN','Tajikistan','TJK','762');
INSERT INTO countries_ctr VALUES ('TZ','TANZANIA, UNITED REPUBLIC OF','Tanzania, United Republic of','TZA','834');
INSERT INTO countries_ctr VALUES ('TH','THAILAND','Thailand','THA','764');
INSERT INTO countries_ctr VALUES ('TL','TIMOR-LESTE','Timor-Leste',NULL,NULL);
INSERT INTO countries_ctr VALUES ('TG','TOGO','Togo','TGO','768');
INSERT INTO countries_ctr VALUES ('TK','TOKELAU','Tokelau','TKL','772');
INSERT INTO countries_ctr VALUES ('TO','TONGA','Tonga','TON','776');
INSERT INTO countries_ctr VALUES ('TT','TRINIDAD AND TOBAGO','Trinidad and Tobago','TTO','780');
INSERT INTO countries_ctr VALUES ('TN','TUNISIA','Tunisia','TUN','788');
INSERT INTO countries_ctr VALUES ('TR','TURKEY','Turkey','TUR','792');
INSERT INTO countries_ctr VALUES ('TM','TURKMENISTAN','Turkmenistan','TKM','795');
INSERT INTO countries_ctr VALUES ('TC','TURKS AND CAICOS ISLANDS','Turks and Caicos Islands','TCA','796');
INSERT INTO countries_ctr VALUES ('TV','TUVALU','Tuvalu','TUV','798');
INSERT INTO countries_ctr VALUES ('UG','UGANDA','Uganda','UGA','800');
INSERT INTO countries_ctr VALUES ('UA','UKRAINE','Ukraine','UKR','804');
INSERT INTO countries_ctr VALUES ('AE','UNITED ARAB EMIRATES','United Arab Emirates','ARE','784');
INSERT INTO countries_ctr VALUES ('GB','UNITED KINGDOM','United Kingdom','GBR','826');
INSERT INTO countries_ctr VALUES ('US','UNITED STATES','United States','USA','840');
INSERT INTO countries_ctr VALUES ('UM','UNITED STATES MINOR OUTLYING ISLANDS','United States Minor Outlying Islands',NULL,NULL);
INSERT INTO countries_ctr VALUES ('UY','URUGUAY','Uruguay','URY','858');
INSERT INTO countries_ctr VALUES ('UZ','UZBEKISTAN','Uzbekistan','UZB','860');
INSERT INTO countries_ctr VALUES ('VU','VANUATU','Vanuatu','VUT','548');
INSERT INTO countries_ctr VALUES ('VE','VENEZUELA','Venezuela','VEN','862');
INSERT INTO countries_ctr VALUES ('VN','VIET NAM','Viet Nam','VNM','704');
INSERT INTO countries_ctr VALUES ('VG','VIRGIN ISLANDS, BRITISH','Virgin Islands, British','VGB','092');
INSERT INTO countries_ctr VALUES ('VI','VIRGIN ISLANDS, U.S.','Virgin Islands, U.s.','VIR','850');
INSERT INTO countries_ctr VALUES ('WF','WALLIS AND FUTUNA','Wallis and Futuna','WLF','876');
INSERT INTO countries_ctr VALUES ('EH','WESTERN SAHARA','Western Sahara','ESH','732');
INSERT INTO countries_ctr VALUES ('YE','YEMEN','Yemen','YEM','887');
INSERT INTO countries_ctr VALUES ('ZM','ZAMBIA','Zambia','ZMB','894');
INSERT INTO countries_ctr VALUES ('ZW','ZIMBABWE','Zimbabwe','ZWE','716');